<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        Trang chủ
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/payment') ?>">
                        Phương thức thanh toán
                    </a>
                </li>
                <li class="active">Thêm mới</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Phương thức thanh toán :: Thêm mới
            </h1>
        </div>
    </div>
</section>

<section class="content" >
    <div class="clearfix">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/payment', array('action' => 'add')));
        $form->setAttribute('id', 'form-payment');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('payment_id'));
        ?>
        <div class="row" >
            <div class="col-sm-6 col-xs-6" >
                <div class="form-group">
                    <label for="payment_name" >
                        Tên phương thức
                    </label>
                    <?php echo $this->formRow($form->get('payment_name')); ?>
                </div>

                <div class="form-group payment_code" >
                    <label for="code" >
                        Kiểu phương thức
                    </label>
                    <?php echo $this->formRow($form->get('code')); ?>
                </div>

                <div class="form-group payment_atm payment_paypal" style="display:none" >
                    <label for="sale_account">Tài khoản nhận tiền</label>
                    <?php echo $this->formRow($form->get('sale_account')); ?>
                </div>

                <div class="clearfix payment_paypal" style="display:none" >
                    <div class="row" >
                        <div class="col-sm-4" >
                            <div class="form-group" >
                                <label for="username">API Username</label>
                                <?php echo $this->formRow($form->get('api_username')); ?>
                            </div>
                        </div>
                        <div class="col-sm-4" >
                            <div class="form-group" >
                                <label for="password">API Password</label>
                                <?php echo $this->formRow($form->get('api_password')); ?>
                            </div>
                        </div>
                        <div class="col-sm-4" >
                            <div class="form-group" >
                                <label for="signature">API Signature</label>
                                <?php echo $this->formRow($form->get('api_signature')); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix payment_onepay" style="display:none" >
                    <div class="row" >
                        <div class="col-sm-3" >
                            <div class="form-group" >
                                <label for="vpc_merchant">Merchant</label>
                                <?php echo $this->formRow($form->get('vpc_merchant')); ?>
                            </div>
                        </div>
                        <div class="col-sm-3" >
                            <div class="form-group" >
                                <label for="vpc_accesscode">AccessCode</label>
                                <?php echo $this->formRow($form->get('vpc_accesscode')); ?>
                            </div>
                        </div>
                        <div class="col-sm-6" >
                            <div class="form-group" >
                                <label for="vpc_hashcode">HashCode</label>
                                <?php echo $this->formRow($form->get('vpc_hashcode')); ?>
                            </div>
                        </div>
                        <div class="col-sm-12" >
                            <div class="form-group" >
                                <label for="is_local">
                                    <?php echo $this->formRow($form->get('is_local')); ?>
                                    Thanh toán nội địa
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix payment_vnpay" style="display:none" >
                    <div class="row" >
                        <div class="col-sm-3" >
                            <div class="form-group" >
                                <label for="vnp_merchant">Merchant</label>
                                <?php echo $this->formRow($form->get('vnp_merchant')); ?>
                            </div>
                        </div>
                        <div class="col-sm-3" >
                            <div class="form-group" >
                                <label for="vnp_tmncode">TmnCode</label>
                                <?php echo $this->formRow($form->get('vnp_tmncode')); ?>
                            </div>
                        </div>
                        <div class="col-sm-6" >
                            <div class="form-group" >
                                <label for="vnp_hashsecret">HashSecret</label>
                                <?php echo $this->formRow($form->get('vnp_hashsecret')); ?>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group" >
            <div class="result-list-img clearfix" >
                <div class="list-img-upload clearfix" >
                    <?php if(!empty($payment->image)){ ?>
                    <div class="img-prevew-upload" data-place="prevewImage" >
                        <a href="javascript:void(0)" class="action-upload" data-btn="removePrevewImage" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </a>
                        <img src="<?php echo $payment->image; ?>" class="img-responsive" >
                    </div>
                    <?php } ?>
                </div>
                <div class="img-prevew-upload btn-upload btn-upload-image-payment" >
                    <a href="javascript:void(0)" class="action-upload" >
                        <i class="fa fa-plus" aria-hidden="true"></i>
                    </a>
                    <a href="javascript:void(0)" class="img-responsive"  >
                        <i class="fa fa-picture-o" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>

        <div class="form-group" >
            <label for="payment_description">Mô tả</label>
            <?php echo $this->formRow($form->get('payment_description')); ?>
        </div>

        <div class="form-group" >
            <label for="is_sandbox">
                <?php echo $this->formRow($form->get('is_sandbox')); ?>
                Chế độ test
            </label>
            <label for="is_published">
                <?php echo $this->formRow($form->get('is_published')); ?>
                Kích hoạt
            </label>
        </div>

        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                Thêm mới phương thức thanh toán
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                Quay lại
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>