<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/payment') ?>">
                        <?php echo $this->translate('txt_phuong_thuc_thanh_toan'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_them_moi'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_phuong_thuc_thanh_toan'); ?> :: 
                <?php echo $this->translate('txt_them_moi'); ?>
            </h1>
        </div>
    </div>
</section>

<section class="content" >
    <div class="clearfix">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/payment', array('action' => 'add')));
        $form->setAttribute('id', 'form-payment');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('payment_id'));
        ?>
        <div class="row" >
            <div class="col-sm-6 col-xs-6" >
                <div class="form-group">
                    <label for="payment_name" >
                        <?php echo $this->translate('txt_ten_phuong_thuc_pay'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('payment_name')); ?>
                </div>

                <div class="form-group payment_code" >
                    <label for="code" >
                        <?php echo $this->translate('txt_kieu_phuong_thuc_pay'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('code')); ?>
                </div>

                <div class="form-group payment_atm payment_paypal paypal_web" style="display:none" >
                    <label for="sale_account">
                        <?php echo $this->translate('txt_tai_khoan_nhan_tien'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('sale_account')); ?>
                </div>

                <div class="clearfix payment_paypal paypal_api" style="display:none" >
                    <div class="row" >
                        <div class="col-sm-4" >
                            <div class="form-group" >
                                <label for="username">
                                    <?php echo $this->translate('txt_api_usernam_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('api_username')); ?>
                            </div>
                        </div>
                        <div class="col-sm-4" >
                            <div class="form-group" >
                                <label for="password">
                                    <?php echo $this->translate('txt_api_password_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('api_password')); ?>
                            </div>
                        </div>
                        <div class="col-sm-4" >
                            <div class="form-group" >
                                <label for="signature">
                                    <?php echo $this->translate('txt_api_signature_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('api_signature')); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix payment_onepay" style="display:none" >
                    <div class="row" >
                        <div class="col-sm-3" >
                            <div class="form-group" >
                                <label for="vpc_merchant">
                                    <?php echo $this->translate('txt_merchant_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('vpc_merchant')); ?>
                            </div>
                        </div>
                        <div class="col-sm-3" >
                            <div class="form-group" >
                                <label for="vpc_accesscode">
                                    <?php echo $this->translate('txt_accesscode_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('vpc_accesscode')); ?>
                            </div>
                        </div>
                        <div class="col-sm-6" >
                            <div class="form-group" >
                                <label for="vpc_hashcode">
                                    <?php echo $this->translate('txt_hashcode_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('vpc_hashcode')); ?>
                            </div>
                        </div>
                        <div class="col-sm-12" >
                            <div class="form-group" >
                                <label for="is_local">
                                    <?php echo $this->formRow($form->get('is_local')); ?>
                                    <?php echo $this->translate('txt_thanh_toan_noi_dia_pay'); ?>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clearfix payment_vnpay" style="display:none" >
                    <div class="row" >
                        <div class="col-sm-3" >
                            <div class="form-group" >
                                <label for="vnp_merchant">
                                    <?php echo $this->translate('txt_merchant_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('vnp_merchant')); ?>
                            </div>
                        </div>
                        <div class="col-sm-3" >
                            <div class="form-group" >
                                <label for="vnp_tmncode">
                                    <?php echo $this->translate('txt_tmncode_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('vnp_tmncode')); ?>
                            </div>
                        </div>
                        <div class="col-sm-6" >
                            <div class="form-group" >
                                <label for="vnp_hashsecret">
                                    <?php echo $this->translate('txt_hashsecret_pay'); ?>
                                </label>
                                <?php echo $this->formRow($form->get('vnp_hashsecret')); ?>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group" >
            <div class="result-list-img clearfix" >
                <div class="list-img-upload clearfix" ></div>
                <div class="img-prevew-upload btn-upload btn-upload-image-payment" >
                    <a href="javascript:void(0)" class="action-upload" >
                        <i class="fa fa-plus" aria-hidden="true"></i>
                    </a>
                    <a href="javascript:void(0)" class="img-responsive"  >
                        <i class="fa fa-picture-o" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>

        <div class="form-group" >
            <label for="payment_description">
                <?php echo $this->translate('txt_mo_ta_pay'); ?>
            </label>
            <?php echo $this->formRow($form->get('payment_description')); ?>
        </div>

        <div class="form-group" >
            <label for="is_sandbox">
                <?php echo $this->formRow($form->get('is_sandbox')); ?>
                <?php echo $this->translate('txt_che_do_test_pay'); ?>
            </label>
            <label for="is_published">
                <?php echo $this->formRow($form->get('is_published')); ?>
                <?php echo $this->translate('txt_kich_hoat'); ?>
            </label>
        </div>

        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                <?php echo $this->translate('txt_them_phuong_thuc_thanh_toan'); ?>
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                <?php echo $this->translate('txt_quay_lai'); ?>
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>