<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        Trang chủ
                    </a>
                </li>
                <li class="active">Phương thức thanh toán</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Phương thức thanh toán :: Quản lý
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/payment') ?>" method="get">
                <div class="coz-search-bar clearfix" data-form="searchAjax" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="Search..." value="<?php echo $q ?>" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo tên
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/payment') ?>" method="post" class="clearfix" id="form-list-payment" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/payment', array('action' => 'add')) ?>"
                   class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm phương thức thanh toán" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($payments) ){ ?>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/payment', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="Hiện phương thức thanh toán" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/payment', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="Ẩn phương thức thanh toán" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/payment', array('action' => 'autoOrder')) ?>')" data-toggle="tooltip" data-placement="top" title="Cập nhật thứ tự" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/payment', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="Xoá phương thức thanh toán" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="error-box" id="error-box" ></div>
        
        <?php if( !empty($payments) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" ></th>
                        <th class="text-center col-lim" >Id</th>
                        <th >Tên</th>
                        <th class="col-lim"  >Kiểu</th>
                        <th class="col-lim" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody id="container-payment-sort" >
                    <?php foreach ($payments as $row) { ?>
                    <tr>
                        <td class="text-center col-lim drag-handle" >
                            <i class="fa fa-arrows"></i>
                        </td>
                        <td class="text-center col-lim" >
                            <?php echo $row['payment_id'] ?>
                            <input name="ordering[<?php echo $row['payment_id'] ?>]" class="ordering" type="hidden" value="<?php echo $row['ordering'] ?>" >
                        </td>
                        <td >
                            <a href="<?php echo $this->url('cms/payment', array('action' => 'edit', 'id' => $row['payment_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa phương thức thanh toán" >
                                <?php echo $row['payment_name'] ?>
                            </a>
                        </td>

                        <td class="col-lim" >
                            <?php echo $row['code'] ?>
                        </td>

                        <td class="col-lim text-right html-ordering" >
                            <?php echo $row['ordering'] ?>
                        </td>

                        <td class="col-lim text-right" >
                            <?php if( empty($row['is_sandbox']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Chế độ thật" >
                                    <i class="fa fa-plane" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Chế độ test" >
                                    <i class="fa fa-fighter-jet" aria-hidden="true"></i>
                                </span>
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>

                        <td class="text-right col-lim" >
                            <a href="<?php echo $this->url('cms/payment', array('action' => 'edit', 'id' => $row['payment_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa phương thức thanh toán" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/payment', array('action' => 'delete', 'id' => $row['payment_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá phương thức thanh toán"  data-confirm="Bạn có muốn xoá ?" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <?php if( empty($row['is_sandbox']) ){ ?>
                            <a href="<?php echo $this->url('cms/payment', array('action' => 'sandbox', 'id' => $row['payment_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Bật chế độ test" >
                                <i class="fa fa-plane" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/payment', array('action' => 'unsandbox', 'id' => $row['payment_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Bật chế độ thật" >
                                <i class="fa fa-fighter-jet" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                            <a href="<?php echo $this->url('cms/payment', array('action' => 'unpublish', 'id' => $row['payment_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn phương thức thanh toán" >
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/payment', array('action' => 'publish', 'id' => $row['payment_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện phương thức thanh toán" >
                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['payment_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có phương thức thanh toán
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>