<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
          <?php echo $this->translate("add_new");?> 
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> <?php echo $this->translate("home");?> </a></li>
        <li><a href="<?php echo $this->url('cms/category') ?>"><?php echo $this->translate("list_themes");?></a></li>
        <li class="active"><?php echo $this->translate("add_new");?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/themes', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('enctype', 'multipart/form-data');
        $form->setAttribute('id', 'form-themes');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('template_id'));
        echo $this->formHidden($form->get('template_dir'));
        echo $this->formHidden($form->get('template_folder'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="categories_template_id"><?php echo $this->translate("root_cat");?></label>
                        <?php echo $this->formRow($form->get('categories_template_id')); ?>
                    </div>
                    <div class="form-group">
                        <label for="template_name"><?php echo $this->translate("name");?></label>
                        <?php echo $this->formRow($form->get('template_name')); ?>
                    </div>
                    <div class="form-group">
                        <label for="template_name"><?php echo $this->translate("templet_alias");?></label>
                        <?php echo $this->formRow($form->get('template_alias')); ?>
                    </div>

                    <div class="form-group" >
                        <div class="result-thumb-website-img row" >
                            <?php if(!empty($template->template_thumb)){ ?>
                            <div class="col-sm-4" >
                                <div class="holder-img" >
                                    <img src="<?php echo $template->template_thumb; ?>" class="img-responsive" />
                                </div>
                            </div>
                            <?php } ?>
                        </div>
                        <button type="button" class="btn btn-link btn-upload-thumb-templete" >
                            Thumb website(png,jpg)
                        </button>
                    </div>

                    <div class="form-group" >
                        <div class="result-thumb-mobile-img row" >
                            <?php if(!empty($template->template_thumb_mobile)){ ?>
                            <div class="col-sm-4" >
                                <div class="holder-img" >
                                    <img src="<?php echo $template->template_thumb_mobile; ?>" class="img-responsive" />
                                </div>
                            </div>
                            <?php } ?>
                        </div>
                        <button type="button" class="btn btn-link btn-upload-thumb-mobile-templete" >
                            Thumb mobile(png,jpg)
                        </button>
                    </div>

                    <div class="form-group">
                        <label for="source" >source</label>
                        <input type="file" name="source" id="source" class="form-control" accept=".zip" />
                    </div>

                    <div class="form-group">
                        <label for="template_description">
                            <?php echo $this->translate("txt_template_description");?>
                        </label>
                        <?php echo $this->formRow($form->get('template_description')); ?>
                    </div>

                    <div class="form-group">
                        <label for="templete_price"><?php echo $this->translate("templete_price");?></label>
                        <?php echo $this->formRow($form->get('templete_price')); ?>
                    </div>

                    <div class="form-group">
                        <label for="categories_alias">
                            <?php echo $this->translate("txt_template_status");?>
                        </label>
                        <?php echo $this->formRow($form->get('template_status')); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <button class="btn btn-primary"> Submit </button>
            <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Cancel</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>
