<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Themes
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/feature') ?>">Đặc tính</a></li>
        <li class="active">Thêm mới đặc tính</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-sm-12" >
        </div>

        <div class="col-sm-12" >
            <div class="list-themes clearfix" >
                <div class="row">
                    <?php foreach ($themes as $key => $ittheme) { ?>
                        <div class="col-sm-3" >
                            <div class="it-themes" >
                                <div class="inner-it-themes" >
                                    <div class="img-themes" >
                                        <img src="<?php echo  $this->Images()->getUrlImage($ittheme['template_thumb'], 230, 128); ?>" />
                                    </div>
                                    <div class="info-themes" >
                                        <a href="javascript:void(0);" class="name-thame" ><?php echo  $ittheme['template_name']; ?></a>
                                    </div>
                                    <div class="ds-button-themes" >
                                        <?php if($ittheme['template_id'] == $website['template_id']){ ?>
                                        <button type="button" class="btn btn-success  btn-sm">Đang dùng</button>
                                        <?php }else{ ?>
                                        <button type="button" data-id="<?php echo  $ittheme['template_id']; ?>" class="btn btn-primary btn-sm btn-block btn-by-thame">
                                        Sử dụng theme này
                                        </button>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>

        </div>

    </div>
</section>