<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/coupons') ?>">
                        <?php echo $this->translate('txt_khuyen_mai'); ?>
                    </a>
                </li>
                <li class="active"> 
                    <?php echo $this->translate('txt_them_moi'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_khuyen_mai'); ?> :: 
                <?php echo $this->translate('txt_them_moi'); ?>
            </h1>
        </div>
    </div>
</section>

<section class="content" >
    <div class="clearfix">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/coupons', array('action' => 'add')));
        $form->setAttribute('id', 'form-coupons');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('coupons_id'));
        echo $this->formHidden($form->get('coupon_percent'));
        ?>
        <div class="row" >
            <div class="col-sm-6 col-xs-6" >
                <div class="form-group">
                    <label for="coupons_code" >
                        <?php echo $this->translate('txt_ma_khuyen_mai'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('coupons_code')); ?>
                </div>

                <div class="form-group">
                    <label for="coupon_price">
                        <?php echo $this->translate('txt_gia_tri'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('coupon_price')); ?>
                </div>

                <div class="row" >
                    <div class="col-xs-6" >
                        <div class="form-group">
                            <label for="start_date">
                                <?php echo $this->translate('txt_ngay_bat_dau'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('start_date')); ?>
                        </div>
                    </div>

                    <div class="col-xs-6" >
                        <div class="form-group">
                            <label for="expire_date">
                                <?php echo $this->translate('txt_ngay_ket_thuc'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('expire_date')); ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="min_price_use">
                        <?php echo $this->translate('txt_dk_su_dung_coupon'); ?>
                    </label>
                    <div class="row" >
                        <div class="col-xs-6" >
                            <?php echo $this->formRow($form->get('min_price_use')); ?>
                        </div>
                        <div class="col-xs-6" >
                            <?php echo $this->formRow($form->get('max_price_use')); ?>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group" >
            <label for="coupons_type">
                <?php echo $this->formRow($form->get('coupons_type')); ?>
                <?php echo $this->translate('txt_dung_nhieu_lan'); ?>
            </label>
            <label for="ordering" id="wrap-coupons-max-use" style="margin-left: 20px"  >
                <?php echo $this->translate('txt_so_lan_dung_max'); ?>
                <?php echo $this->formRow($form->get('coupons_max_use')); ?>
            </label>
        </div>

        <div class="form-group" >
            <label for="is_published">
                <?php echo $this->formRow($form->get('is_published')); ?>
                <?php echo $this->translate('txt_kich_hoat'); ?>
            </label>
        </div>

        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                <?php echo $this->translate('txt_them_moi_ma_km'); ?>
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                <?php echo $this->translate('txt_quay_lai'); ?>
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>