<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        Trang chủ
                    </a>
                </li>
                <li class="active">Danh sách khuyến mãi</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Khuyến mãi :: Quản lý
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/coupons') ?>" method="get">
                <div class="coz-search-bar clearfix" data-form="searchAjax" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="Search..." value="<?php echo $q ?>" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo mã
                                    </option>
                                    <option value="1" <?php echo $type == 1 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo price
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/coupons') ?>" method="post" class="clearfix" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/coupons', array('action' => 'add')) ?>"
                   class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm khuyến mại" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($coupons) ){ ?>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/coupons', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="Hiện khuyến mại" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/coupons', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="Ẩn khuyến mại" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/coupons', array('action' => 'order')) ?>')" data-toggle="tooltip" data-placement="top" title="Cập nhật thứ tự" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/coupons', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="Xoá khuyến mại" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
        
        <?php if( !empty($coupons) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" >Id</th>
                        <th>Mã</th>
                        <th class="col-lim" >Loại mã</th>
                        <th class="col-lim text-right"  >Giá trị</th>
                        <th class="col-lim" >Ngày bắt đầu</th>
                        <th class="col-lim" >Ngày kết thúc</th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($coupons as $coupon) { ?>
                    <tr>
                        <td class="text-center col-lim" >
                            <?php echo $coupon['coupons_id'] ?>
                        </td>

                        <td >
                            <?php echo $coupon['coupons_code'] ?>
                        </td>

                        <td class="col-lim" >
                            <?php if( empty($coupon['coupons_type']) ){ ?>
                                Dùng 1 lần
                            <?php }else{ ?>
                                Dùng nhiều lần
                            <?php } ?>
                        </td>

                        <td class="col-lim text-right" >
                            <?php if( !empty($coupon['coupon_percent']) ){ ?>
                                <?php echo $coupon['coupon_percent'] ?>%
                            <?php }else{ ?>
                                <?php echo number_format($coupon['coupon_price']) ?>
                            <?php } ?>
                        </td>

                        <td class="col-lim" >
                            <?php echo $coupon['start_date'] ?>
                        </td>

                        <td class="col-lim" >    
                            <?php echo $coupon['expire_date'] ?>
                        </td>

                        <td class="col-lim text-right" >    
                            Đã sử dụng <?php echo $coupon['total'] ?>/<?php echo max($coupon['coupons_max_use'], 1) ?> lần
                            <?php if( !empty($coupon['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="text-right col-lim" >
                            <a href="<?php echo $this->url('cms/coupons', array('action' => 'edit', 'id' => $coupon['coupons_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa khuyến mại" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/coupons', array('action' => 'show-logs', 'id' => $coupon['coupons_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xem logs" >
                                <i class="fa fa-history" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/coupons', array('action' => 'delete', 'id' => $coupon['coupons_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá khuyến mại"  data-confirm="Bạn có muốn xoá ?" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/coupons', array('action' => 'auto-add')) ?>" data-toggle="tooltip" data-placement="top" title="Tự động thêm mã"  data-confirm="Bạn có muốn thêm mã tự động ?" >
                                <i class="fa fa-random" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($coupon['is_published']) ){ ?>
                            <a href="<?php echo $this->url('cms/coupons', array('action' => 'unpublish', 'id' => $coupon['coupons_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn khuyến mại" >
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/coupons', array('action' => 'publish', 'id' => $coupon['coupons_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện khuyến mại" >
                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $coupon['coupons_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có khuyến mại
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>