<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Api :: Thêm mới
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/api') ?>">Api</a></li>
        <li class="active">Thêm mới</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/api', array('action' => 'add')));
        $form->setAttribute('id', 'form-api');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('api_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <button class="btn btn-primary">Lưu lại</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="api_module">api module</label>
                        <?php echo $this->formRow($form->get('api_module')); ?>
                    </div>
                    <div class="form-group">
                        <label for="api_class">api class</label>
                        <?php echo $this->formRow($form->get('api_class')); ?>
                    </div>
                    <div class="form-group">
                        <label for="api_function">api function</label>
                        <?php echo $this->formRow($form->get('api_function')); ?>
                    </div>
                    <div class="form-group">
                        <label for="is_published">
                            <?php echo $this->formRow($form->get('is_published')); ?>
                            Hiển thị
                        </label>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <button class="btn btn-primary">Lưu lại</button>
                <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    </div>
</section>