<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_country'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_country'); ?> :: 
                <?php echo $this->translate('txt_quan_ly'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/country', array('action' => 'filter')) ?>" method="post" class="filter_form" role="form" data-form="searchAjax" >
                <div class="coz-search-bar clearfix" >
                    <div class="input-group">
                        <input type="text" name="categories_title" class="form-control" placeholder="<?php echo $this->translate('txt_holder_search'); ?>">
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/country') ?>" method="post" class="clearfix" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-6" ></div>
                <div class="col-sm-6" >
                    <div class="text-right" >
                        <?php if( !empty($countries) ){ ?>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/country', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="Hiện bài viết" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/country', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="Ẩn bài viết" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <?php if( !empty($countries) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" >ID</th>
                        <th class="col-lim" >Code</th>
                        <th>Tên</th>
                        <th class="col-lim" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($countries as $key=>$row ) { ?>
                    <tr>
                        <td class="text-center col-lim" >
                            <?php echo $row['id'] ?>
                        </td>
                        <td class="col-lim" >
                            <a href="<?php echo $this->url('cms/country', array('action' => 'edit', 'id' => $row['id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa country" >
                                <?php echo $row['code'] ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cms/country', array('action' => 'edit', 'id' => $row['id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa country" >
                                <?php echo $row['title'] ?>
                            </a>
                        </td>
                        <td class="col-lim" >
                            <?php echo $row['ordering'] ?>
                        </td>
                        <td class="col-lim" >
                            Thuộc loại <?php echo $row['country_type'] ?>,
                            Loại hiển thị <?php echo $row['level_view'] ?>,

                            <?php if( !empty($row['is_default']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Mặc định" >
                                    <i class="fa fa-fire" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Không mặc định" >
                                    <i class="fa fa-fire" aria-hidden="true"></i>
                                </span>
                            <?php } ?>

                            <?php if( !empty($row['status']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="text-right col-lim" >

                            <a href="<?php echo $this->url('cms/country', array('action' => 'edit', 'id' => $row['id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá country" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($row['is_default']) ){ ?>
                            <a href="<?php echo $this->url('cms/country', array('action' => 'unhot', 'id' => $row['id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Bài viết hot" >
                                <i class="fa fa-fire" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/country', array('action' => 'hot', 'id' => $row['id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Bài viết không hot" >
                                <i class="fa fa-fire" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                            <a href="<?php echo $this->url('cms/country', array('action' => 'unpublish', 'id' => $row['id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn country" >
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/country', array('action' => 'publish', 'id' => $row['id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện country" >
                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                            </a>
                            <?php } ?>
                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có country
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>