<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ngôn ngữ :: Cập nhật từ khóa
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/languagescms') ?>">Ngôn ngữ</a></li>
        <li class="active">Cập nhật từ khóa</li>
    </ol>
</section>
<?php
$keyword = $keyword->toArray();
$word = $keyword[0];
?>
<!-- Main content -->
<section class="content">
    <div class="row">
        <?php if(isset($_SESSION['error'])) : ?>
            <?php $error = $_SESSION['error']; ?>
            <?php unset($_SESSION['error']) ?>);
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <ul>
                            <?php foreach($error as $e) : ?>
                            <li><strong style="color:red"><?php echo $e ?></strong></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
            <?php unset($_SESSION['error']); ?>
        <?php endif; ?>
        <form action="<?php echo $this->url('cms/languagescms', array('action' => 'edit-keyword')) ?>?word=<?php echo $keyword[0]['keyword'] ?>" method="post">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="keyword">Từ khóa</label>
                            <input type="text" name="keyword" value="<?php echo $word['keyword'] ?>" class="form-control" />
                        </div>
                        <?php foreach($languages as $lang) : ?>
                        <?php $translate = '' ?>
                        <?php
                            foreach($keyword as $word){
                                if($word['languages_id'] == $lang['languages_id']){
                                    $translate = $word['translate'];
                                    break;
                                }
                            }
                        ?>
                            <div class="form-group">
                                <label for="language_trangslate_<?php echo $lang['languages_id'] ?>"><?php echo $lang['languages_name'] ?></label>
                                <textarea name="translate[<?php echo $lang['languages_id'] ?>]" id="language_trangslate_<?php echo $lang['languages_id'] ?>" rows="3" class="form-control"><?php echo $translate ?></textarea>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <button class="btn btn-primary">Lưu lại</button>
                <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
            </div>
            <?php echo $this->form()->closeTag(); ?>
    </div>
</section>