<?php
$languages = $languages->toArray();
$keywords = $keywords->toArray();
$data = array();
foreach($keywords as $key => $row){
    $data[$key]['keyword'] = $row['keyword'];
    $tmp = $row['translate'];
    $tmp1 = explode('__AND__', $tmp);//Tách các ngôn ngữ ra
    foreach($tmp1 as $r){
        $tmp2 = explode('_transto_', $r);
        $data[$key][$tmp2[0]] = $tmp2[1];
    }
}
?>
<?php foreach($data as $word) : ?>
    <tr>
        <td><a href="<?php echo $this->url('cms/language', array('action' => 'edit-keyword')) ?>?word=<?php echo $word['keyword'] ?>"><?php echo $word['keyword'] ?></a></td>
        <?php foreach($languages as $lang) : ?>
            <td><?php echo isset($word[$lang['languages_id']]) ? $word[$lang['languages_id']] : '' ?></td>
        <?php endforeach; ?>
        <td><input type="checkbox" name="cid[]" value="<?php echo $word['keyword'] ?>"/></td>
    </tr>
<?php endforeach; ?>