<?php 
    $branches = $this->Branches()->getAllBranches();
    $bran = $this->Branches()->getMainBranches();
?>
<script type="text/javascript" >
    var latitude = <?php echo $this->Branches()->getLatitude($bran); ?>;
    var longitude = <?php echo $this->Branches()->getLongitude($bran); ?>;
</script>

<div class="wrap-breadcrumbs clearfix" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <span itemprop="item name" >
                            <?php echo $this->translate('txt_lien_he') ?>
                        </span>
                        <meta itemprop="position" content="2" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">                
        <div class="col-sm-12">
            <h1 class="title-contact" >
                <?php echo $this->translate('txt_lien_he') ?>
            </h1>
            <div id="google_map_div_0">
                <div class="clearfix map-canvas" >
                    <div id="map_canvas" class="text-center" data-neo="mapContact" data-latitude="<?php echo $this->Branches()->getLatitude($bran); ?>" data-longitude="<?php echo $this->Branches()->getLongitude($bran); ?>" ></div>
                </div>
            </div>

            <div class="info-contact" >
                <div class="row" >

                    <div class="col-md-3" >
                        <div class="item-info-contact" >
                            <div class="iinner-info-contact" >
                                <img src="<?php echo $this->Images()->getUrlImage($this->Websites()->getLogo(), '', 43); ?>" alt="<?php echo $this->translate('title_site') ?>" title="<?php echo $this->translate('title_site') ?>" class="img-fluid" >
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3" >
                        <div class="item-info-contact" >
                            <div class="iinner-info-contact" >
                                <?php echo $this->translate('txt_dia_chi_contact') ?>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3" >
                        <div class="item-info-contact" >
                            <div class="iinner-info-contact" >
                                <div>
                                    <?php echo $this->translate('txt_email_contact') ?>
                                </div>
                                <div>
                                    <?php echo $this->translate('txt_hotline_contact') ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3" >
                        <div class="item-info-contact" >
                            <div class="iinner-info-contact" >
                                <div>
                                    <?php echo $this->translate('txt_worktime_contact') ?>
                                </div>
                                <div>
                                    <?php echo $this->translate('txt_worktime_speacial_contact') ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>       

            <form accept-charset='UTF-8' action='/contact' id='contact' method='post' class="form-horizontal form-contact-page" data-form="contact" >
                <h3 class="title-form-contact" >
                    <?php echo $this->translate('txt_thong_tin_cua_ban') ?>
                </h3>
                <div class="form-group required">
                    <div class="row" >
                        <label class="col-md-2  col-sm-3 control-label" for="fullname">
                            <?php echo $this->translate('txt_ho_va_ten') ?>
                        </label>
                        <div class="col-md-10 col-sm-9">
                            <input type="text" name="fullname" value="" id="ifullname" class="form-control fullname" data-input="fullname" />
                        </div>
                    </div>
                </div>

                <div class="form-group required">
                    <div class="row" >
                        <label class="col-md-2  col-sm-3 control-label" for="email">
                            <?php echo $this->translate('txt_dia_chi_email') ?>
                        </label>
                        <div class="col-md-10 col-sm-9">
                            <input type="text" name="email" value="" id="email" class="form-control email" data-input="email" />
                        </div>
                    </div>
                </div>

                <div class="form-group required">
                    <div class="row" >
                        <label class="col-md-2  col-sm-3 control-label" for="title">
                            <?php echo $this->translate('txt_tieu_de') ?>
                        </label>
                        <div class="col-md-10 col-sm-9">
                            <input type="text" name="title" value="" id="title" class="form-control title" data-input="title" />
                        </div>
                    </div>
                </div>

                <div class="form-group required">
                    <div class="row" >
                        <label class="col-md-2  col-sm-3 control-label" for="content">
                            <?php echo $this->translate('txt_noi_dung') ?>
                        </label>
                        <div class="col-md-10 col-sm-9">
                            <textarea name="description" rows="10" id="content" class="form-control content" data-input="content" ></textarea>
                        </div>
                    </div>
                </div>

                <div class="form-group clearfix" >
                    <div class="pull-right">
                        <input class="btn btn-style" type="submit" value="<?php echo $this->translate('gui_tin_nhan'); ?>" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>