<?php 
    $branches = $this->Branches()->getAllBranches();
    $bran = $this->Branches()->getMainBranches();
    $sliders = $this->Banners()->getBannerWithPositionAlias('CONTACT');
?>
<script type="text/javascript" >
    var latitude = <?php echo $this->Branches()->getLatitude($bran); ?>;
    var longitude = <?php echo $this->Branches()->getLongitude($bran); ?>;
</script>
<section class="bread-crumb">
    <div class="container">
        <div class="bg-breadcrumbs" >
            <div class="row">
                <div class="col-xs-12">
                    <ul class="breadcrumbs">
                        <li class="home">
                            <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>"  data-pjax="true" data-container="Main" ><?php echo $this->translate('txt_trang_chu') ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/contact"  data-pjax="true" data-container="Main" >
                                <?php echo $this->translate('txt_lien_he') ?>
                            </a>
                        </li>
                        <li>
                            <span>
                                <?php echo $this->translate('txt_thanks')?>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<?php if( !empty($sliders) ){ ?>
<div class="banner-contact clearfix thanks" >
    <?php echo $this->partial('app/slider', array('sliders' => $sliders) ); ?>
    <h2 class="title-contact" >
        <?php echo $this->translate('txt_lien_he') ?>
    </h2>
</div>
<?php } ?>

<div class="container">
    <div class="row">                
        <div class="col-sm-10 col-sm-offset-1" >
            <div class="row" >
                <div class="col-md-4" >
                    <div class="info-contact" >
                        <h2 class="name-global-company" >
                            <?php echo $this->translate('txt_name_company_global') ?>
                        </h2>
                        <div class="inner-info-contact" >

                            <div class="item-info-contact" >
                                <span class="ico-info-contact" >
                                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                                </span>
                                <span class="iinner-info-contact" >
                                    <div class="name-com-contact" >
                                        <?php echo $this->translate('txt_name_com_contact') ?>
                                    </div>
                                    <div class="address-com-contact" >
                                        <?php echo $this->translate('txt_dia_chi_contact') ?>
                                    </div>
                                </span>
                            </div>

                            <div class="item-info-contact" >
                                <span class="ico-info-contact" >
                                    <i class="fa fa-envelope" aria-hidden="true"></i>
                                </span>
                                <span class="iinner-info-contact" >
                                    <div class="email-contact" >
                                        <?php echo $this->translate('txt_email_contact') ?>
                                    </div>
                                </span>
                            </div>

                            <div class="item-info-contact" >
                                <span class="ico-info-contact" >
                                    <i class="fa fa-calendar-o" aria-hidden="true"></i>
                                </span>
                                <span class="iinner-info-contact" >
                                    <div>
                                        <?php echo $this->translate('txt_worktime_open') ?>
                                    </div>
                                    <div>
                                        <?php echo $this->translate('txt_worktime_close') ?>
                                    </div>
                                </span>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="col-md-8" >
                    <div class="form-contact-thanks" >
                        <h1 class="title-contact-thanks" >
                            <?php echo $this->translate('txt_contact_thanks');?>
                        </h1>
                        <div class="des-contact-thanks" >
                            <?php echo $this->translate('txt_des_contact_thanks');?>
                        </div>
                        <div class="text-xs-center" >
                            <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/contact"  data-pjax="true" data-container="Main" class="link-send-again" >
                                <?php echo $this->translate('txt_send_other_messager');?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-12" >
            <div id="google_map_div_0">
                <div class="clearfix map-canvas" >
                    <div id="map_canvas" class="text-center" data-neo="mapContact" data-latitude="<?php echo $this->Branches()->getLatitude($bran); ?>" data-longitude="<?php echo $this->Branches()->getLongitude($bran); ?>" ></div>
                </div>
            </div>
        </div>

    </div>
</div>