<section class="bread-crumb">
    <div class="container">
        <div class="bg-breadcrumbs" >
            <div class="row">
                <div class="col-xs-12">
                    <ul class="breadcrumbs">
                        <li class="home">
                            <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>"  data-pjax="true" data-container="Main" ><?php echo $this->translate('txt_trang_chu') ?></a>
                        </li>
                        <li class="home">
                            <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/contact"  data-pjax="true" data-container="Main" ><?php echo $this->translate('ttl_lien_he') ?></a>
                        </li>
                        <li><?php echo $this->translate('ttl_thanks')?></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="coz-wrap-sucess" >
    <div class="container" >
        <div class="row" >
            <div class="col-sm-12" >
                <div class="wrap-thanks" >
                    <h1 class="coz-title-sucess" >
                        <?php echo $this->translate('ttl_thanks');?>
                    </h1>
                    <div class="coz-content-sucess">
                        <div class="coz-inner-title-sucess" >
                            <p>
                                <?php echo $this->translate('txt_thanks_for_contact'); ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>