<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li><a href="<?php echo $this->url('cms/merchant') ?>">Danh sách đại lý</a></li>
                <li class="active">Cập nhật đại lý</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Đại lý :: Cập nhật
            </h1>
        </div>
    </div>
</section>

<script type="text/javascript" >
    var merchan = <?php echo json_encode($merchant); ?>;
</script>

<section class="content" >
    <div class="clearfix">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/merchant', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('id', 'form-merchan');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('merchant_id'));
        echo $this->formHidden($form->get('merchant_alias'));
        ?>
        <div class="row" >
            <div class="col-sm-6 col-xs-6" >
                <div class="form-group">
                    <label for="merchant_type">Loại đại lý</label>
                    <?php echo $this->formRow($form->get('merchant_type')); ?>
                </div>

                <div class="form-group">
                    <label for="merchant_name">Tên đại lý</label>
                    <?php echo $this->formRow($form->get('merchant_name')); ?>
                </div>

                <div class="form-group">
                    <label for="merchant_phone">Số DT</label>
                    <?php echo $this->formRow($form->get('merchant_phone')); ?>
                </div>

                <div class="form-group">
                    <label for="merchant_email">Email</label>
                    <?php echo $this->formRow($form->get('merchant_email')); ?>
                </div>

                <div class="form-group">
                    <label for="merchant_fax">Fax</label>
                    <?php echo $this->formRow($form->get('merchant_fax')); ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="merchant_note">Thông tin thêm</label>
            <?php echo $this->formRow($form->get('merchant_note')); ?>
        </div>
        
        <?php $countries = $this->Contries()->getContryForWebsite(); ?>
        <div class="row address-merchant" >
            <div class="col-sm-12" >
                <div class="form-group" >
                    <h3>Thông tin vị trí</h3>
                </div>
            </div>
            <div class="col-sm-6" >
                <?php if( !empty($countries) ){ ?>
                <div class="form-group" >
                    <label for="country_id">Đất nước</label>
                    <select name="country_id" class="form-control input-sm" id="country_id" >
                        <option value="" >
                            <?php echo $this->translate('chon_country');?>
                        </option>
                        <?php foreach ($countries as $country){ ?>
                        <option value="<?php echo $country['id'] ?>" <?php echo $merchant->country_id == $country['id'] ? 'selected="selected"' : '' ?> >
                            <?php echo $country['title'] ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
                <?php } ?>
                <div class="warp-address-payment" neo-place="addressPayment" ></div>
            </div>
            <div class="col-sm-6" >
                <div class="form-group" >
                    <div id="profile_map_canvas" data-neo="profileMap" data-latitude="<?php echo $merchant->latitude; ?>" data-longitude="<?php echo $merchant->longitude; ?>" ></div>
                    <input type="hidden" value="<?php echo $merchant->longitude; ?>" name="longitude"  >
                    <input type="hidden" value="<?php echo $merchant->latitude; ?>" name="latitude" >
                </div>
            </div>
        </div>

        <div class="form-group" >
            <label for="is_published">
                <?php echo $this->formRow($form->get('is_published')); ?>
                Kích hoạt
            </label>
        </div>

        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                Cập nhật đại lý
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                Quay lại
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>