<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li class="active">Danh sách Đại lý</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Đại lý :: Quản lý
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/merchant') ?>" method="post">
                <div class="coz-search-bar clearfix" data-form="searchAjax" >
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/merchant') ?>" method="post" class="clearfix" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/merchant', array('action' => 'add')) ?>"
                   class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm đại lý" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/merchant', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="Hiện đại lý" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/merchant', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="Ẩn đại lý" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/merchant', array('action' => 'order')) ?>')" data-toggle="tooltip" data-placement="top" title="Cập nhật thứ tự đại lý" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/merchant', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="Xoá đại lý" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" >Loại đại lý</th>
                        <th>Tên đại lý</th>
                        <th>Địa chỉ</th>
                        <th class="col-lim" >Sdt</th>
                        <th class="col-lim" >Fax</th>
                        <th class="col-lim" >Email</th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($merchans as $merchan) { ?>
                    <tr>
                        <td class="text-center col-lim" >
                            <?php if( $merchan['merchant_type'] == 0 ){ ?>
                            Đại lý cấp 3
                            <?php }else if($merchan['merchant_type'] == 1){ ?>
                            Đại lý cấp 1
                            <?php }else{ ?>
                            Đại lý cấp 2
                            <?php } ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cms/merchant', array('action' => 'edit', 'id' => $merchan['merchant_id'])) ?>">
                                <?php echo $merchan['merchant_name'] ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $merchan['address'] ?>
                        </td>
                        <td class="col-lim" >    
                            <?php echo $merchan['merchant_phone'] ?>
                        </td>
                        <td class="col-lim" >    
                            <?php echo $merchan['merchant_fax'] ?>
                        </td>
                        <td class="col-lim" >    
                            <?php echo $merchan['merchant_email'] ?>
                        </td>
                        <td class="col-lim text-right" >    
                            <?php if( !empty($merchan['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="text-right col-lim" >
                            <a href="<?php echo $this->url('cms/merchant', array('action' => 'edit', 'id' => $merchan['merchant_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa đại lý" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/merchant', array('action' => 'delete', 'id' => $merchan['merchant_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá đại lý"  data-confirm="Bạn có muốn xoá ?" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/merchant', array('action' => 'users', 'id' => $merchan['merchant_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xem user" >
                                <i class="fa fa-users" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/merchant', array('action' => 'commission', 'id' => $merchan['merchant_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xem commission" >
                                <i class="fa fa-percent" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($merchan['is_published']) ){ ?>
                                <a href="<?php echo $this->url('cms/merchant', array('action' => 'unpublish', 'id' => $merchan['merchant_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn đại lý" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <a href="<?php echo $this->url('cms/merchant', array('action' => 'publish', 'id' => $merchan['merchant_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện đại lý" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $merchan['merchant_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </form>
</section>