<?php
// module/Album/view/album/album/index.phtml:

$title = 'Blog Management';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('cms/blog', array('action' => 'add')); ?>">Add new blog</a>
</p>
<div class="table-responsive">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Created</th>
            <th>Last Updated</th>
            <th><input type="checkbox" id="checkall"/></th>
            <th>Action</th>
        </tr>
        <?php foreach ($blogs as $blog) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($blog->id); ?></td>
                <td><?php echo $this->escapeHtml($blog->title); ?></td>
                <td><?php echo $blog->created; ?></td>
                <td>
                    <?php echo $blog->updated; ?>
                </td>
                <td>
                    <input type="checkbox" name="cid[]" value="<?php echo $blog->id ?>"/>
                </td>
                <td>
                    <a href="<?php echo $this->url('cms/blog',
                        array('action' => 'edit', 'id' => $blog->id));?>">Edit</a>
                    <a href="<?php echo $this->url('cms/blog',
                        array('action' => 'delete', 'id' => $blog->id));?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>