<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li class="active">Menus</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Menus :: Quản lý
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/menus') ?>" method="post">
                <div class="coz-search-bar clearfix" data-form="searchAjax" >
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/menus') ?>" method="post" class="clearfix" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/menus', array('action' => 'add')) ?>"
                   class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm menus" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <?php if( !empty($menus) ){ ?>
        <div class="row">
            <div class="col-sm-12">
                <h4>Danh sách menu</h4>
                <p class="text-muted">
                    Danh sách menu sẽ giup khách hàng duyệt web của bạn dễ dàng hơn.
                </p>
            </div>
            <div class="col-sm-12" >
                <?php foreach ($menus[0] as $key => $menu) { ?> 
                <div class="row-menu" >
                    <div class="table-responsive" >
                        <table class="table table-data-bind table-no-border" >
                            <thead>
                                <tr>
                                    <th class="text-center col-lim" >id</th>
                                    <th colspan="2" >Tên</th>
                                    <th class="col-lim text-right" >
                                        <i class="fa fa-sort" aria-hidden="true"></i>
                                    </th>
                                    <th class="col-lim text-right" >Trạng thái</th>
                                    <th class="col-lim" ></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-center col-lim" >
                                        <?php echo $menu['menus_id']; ?>
                                    </td>
                                    <td colspan="2" >
                                        <?php echo $this->translate($menu['menus_name']); ?>
                                    </td>
                                    <th class="col-lim text-right" ></th>
                                    <td class="text-right col-lim" >
                                        <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="là menu gốc" >
                                            <i class="fa fa-home" aria-hidden="true"></i>
                                        </span>
                                        <?php if( !empty($menu['is_root']) ){ ?>
                                            <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Menu của hệ thống" >
                                                <i class="fa fa-lock" aria-hidden="true"></i>
                                            </span>
                                        <?php }else{ ?>
                                            <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Menu của custommer" >
                                                <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                                            </span>
                                        <?php } ?>

                                        <?php if( !empty($menu['is_published']) ){ ?>
                                            <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                            </span>
                                        <?php }else{ ?>
                                            <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                            </span>
                                        <?php } ?>
                                    </td>
                                    <td class="text-right col-lim" >
                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'add', 'id' => $menu['menus_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Sửa menu" >
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>

                                        <?php if( !empty($menu['is_root']) ){ ?>
                                        <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Không xoá được vì menu của hệ thống" >
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </span>
                                        <?php }else{ ?>
                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'delete', 'id' => $menu['menus_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Xoá menu"  data-confirm="Bạn có muốn xoá ?" >
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </a>
                                        <?php } ?>

                                        <?php if( !empty($menu['is_published']) ){ ?>
                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'unpublish', 'id' => $menu['menus_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn bài viết" >
                                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                        </a>
                                        <?php }else{ ?>
                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'publish', 'id' => $menu['menus_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện bài viết" >
                                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                        </a>
                                        <?php } ?>
                                    </td>
                                </tr>

                                <?php if(isset($menus[$menu['menus_id']]) && !empty($menus[$menu['menus_id']])){
                                    foreach ($menus[$menu['menus_id']] as $lv1 => $menulv1) {
                                ?>
                                <tr>
                                    <td class="text-center col-lim" >
                                        <?php echo $menulv1['menus_id']; ?>
                                    </td>
                                    <td class="col-lim text-right" >
                                        <span class="el-level-right" >
                                            <i class="fa fa-level-up" aria-hidden="true"></i>
                                        </span>
                                    </td>
                                    <td >
                                        <?php echo $this->translate($menulv1['menus_name']); ?>
                                    </td>
                                    <th class="col-lim text-right" >
                                        <?php echo $menulv1['ordering']; ?>
                                    </th>
                                    <td class="text-right col-lim" >
                                        <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="là menu con" >
                                            <i class="fa fa-home" aria-hidden="true"></i>
                                        </span>

                                        <?php if( !empty($menulv1['number_childrens']) ){ ?>
                                            <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Có <?php echo $menulv1['number_childrens']; ?> menu con" >
                                                <i class="fa fa-share-alt" aria-hidden="true"></i>
                                            </span>
                                        <?php }else{ ?>
                                            <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Không có menu con" >
                                                <i class="fa fa-share-alt" aria-hidden="true"></i>
                                            </span>
                                        <?php } ?>

                                        <?php if( !empty($menulv1['is_published']) ){ ?>
                                            <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                            </span>
                                        <?php }else{ ?>
                                            <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                            </span>
                                        <?php } ?>
                                    </td>
                                    <td class="text-right col-lim" >

                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'add', 'id' => $menulv1['menus_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Sửa menu" >
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>

                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'delete', 'id' => $menulv1['menus_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Xoá menu"  data-confirm="Bạn có muốn xoá ?" >
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </a>

                                        <?php if( !empty($menulv1['is_published']) ){ ?>
                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'unpublish', 'id' => $menulv1['menus_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn bài viết" >
                                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                        </a>
                                        <?php }else{ ?>
                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'publish', 'id' => $menulv1['menus_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện bài viết" >
                                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                        </a>
                                        <?php } ?>
                                    </td>
                                </tr>
                                <?php 
                                    }
                                }else{ ?>
                                <tr>
                                    <td colspan="4" class="text-center" >
                                        Chưa có menu con <br />
                                        Thêm menu con 
                                        <a href="<?php echo $this->url('cms/menus', array('action' => 'add', 'id' => $menu['menus_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Thêm menu" >
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                    </td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có menus
        </p>
        <?php } ?>
    </form>
</section>