<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/shipping') ?>" >
                        <?php echo $this->translate('txt_shipping'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_them_moi'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_shipping'); ?> :: 
                <?php echo $this->translate('txt_them_moi'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-6 pull-rigth" >
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('cms/shipping', array('action' => 'add')));
    $form->setAttribute('id', 'shipping');
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('shipping_id'));
    ?>
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <div class="form-group">
                <label for="group_regions_id" >
                    <?php echo $this->translate('txt_khu_vuc_shipping'); ?>
                </label>
                <?php echo $this->formRow($form->get('group_regions_id')); ?>
            </div>

            <div class="form-group">
                <label for="shipping_title">
                    <?php echo $this->translate('txt_tieu_de_shipping'); ?>
                </label>
                <?php echo $this->formRow($form->get('shipping_title')); ?>
            </div>

            <div class="form-group">
                <label for="shipping_type">
                    <?php echo $this->translate('txt_kieu_vc_shipping'); ?>
                </label>
                <?php echo $this->formRow($form->get('shipping_type')); ?>
            </div>

            <div class="form-group">
                <div class="row" >
                    <div class="col-xs-6" >
                        <label for="shipping_from">
                            <?php echo $this->translate('txt_tu_shipping'); ?>
                        </label>
                        <?php echo $this->formRow($form->get('shipping_from')); ?>
                    </div>
                    <div class="col-xs-6" >
                        <label for="shipping_to">
                            <?php echo $this->translate('txt_den_shipping'); ?>
                        </label>
                        <?php echo $this->formRow($form->get('shipping_to')); ?>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row" >
                    <div class="col-xs-4" >
                        <label for="shipping_value">
                            <?php echo $this->translate('txt_phi_vc_thuong_shipping'); ?>
                        </label>
                        <?php echo $this->formRow($form->get('shipping_value')); ?>
                    </div>
                    <div class="col-xs-4" >
                        <label for="shipping_fast_value">
                            <?php echo $this->translate('txt_phi_vc_nhanh_shipping'); ?>
                        </label>
                        <?php echo $this->formRow($form->get('shipping_fast_value')); ?>
                    </div>
                    <div class="col-xs-4" >
                        <label for="shipping_time">
                            <?php echo $this->translate('txt_thoi_gan_giao_shipping'); ?>
                        </label>
                        <?php echo $this->formRow($form->get('shipping_time')); ?>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="col-sm-6 col-xs-12" >
            <p>
                <?php echo $this->translate('txt_quy_tac_lap_phi_voi_khu_vuc_shipping'); ?>
            </p>
        </div>
    </div>

    <div class="form-group" id="fg-shipping-districts" style="display:none" >
        <label for="shipping_time">
            <?php echo $this->translate('txt_thong_tin_chi_tiet_shipping'); ?>
        </label>
        <div class="row" >
            <div class="col-sm-12" >
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-data-bind">
                        <thead>
                            <tr>
                                <th width="50" style="text-align: center;vertical-align: middle;" rowspan="2" >
                                    <?php echo $this->translate('txt_stt'); ?>
                                </th>
                                <th width="100" rowspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_quan_huyen'); ?>
                                </th>
                                <th width="200"  colspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_van_chuyen_thuong'); ?>
                                    <a href="#" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate("txt_tooltip_van_chuyen_thuong"); ?>" >
                                        <i class="fa fa-question-circle" aria-hidden="true"></i>
                                    </a>
                                </th>
                                <th width="200"  colspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_van_chuyen_nhanh'); ?>
                                    <a href="#" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate("txt_tooltip_van_chuyen_nhanh"); ?>" >
                                        <i class="fa fa-question-circle" aria-hidden="true"></i>
                                    </a>
                                </th>
                                <th width="200"  colspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_thoi_gian_giao_hang'); ?>
                                    <a href="#" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate("txt_tooltip_thoi_gan_giao_hang"); ?>" >
                                        <i class="fa fa-question-circle" aria-hidden="true"></i>
                                    </a>
                                </th>
                                <th width="10" rowspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_giao_hang'); ?>
                                </th>
                            </tr>
                            <tr>
                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_tuy_chinh'); ?>
                                </th>
                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_phi'); ?>
                                </th>

                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_tuy_chinh'); ?>
                                </th>
                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_phi'); ?>
                                </th>

                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_tuy_chinh'); ?>
                                </th>
                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_phi'); ?>
                                </th>
                            </tr>
                        </thead>
                        <tbody id="data-districts" >
                            <tr>
                                <td colspan="9" >
                                    <?php echo $this->translate('txt_khong_co_du_lieu'); ?>
                                </td>
                            </tr>
                        </tbody>
                        <tfoot>

                            <tr>
                                <th width="50" style="text-align: center;vertical-align: middle;" rowspan="2" >
                                    <?php echo $this->translate('txt_stt'); ?>
                                </th>
                                <th width="100" rowspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_quan_huyen'); ?>
                                </th>
                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_tuy_chinh'); ?>
                                </th>
                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_phi'); ?>
                                </th>

                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_tuy_chinh'); ?>
                                </th>
                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_phi'); ?>
                                </th>

                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_tuy_chinh'); ?>
                                </th>
                                <th width="100" style="text-align: center;vertical-align: middle;">
                                    <?php echo $this->translate('txt_phi'); ?>
                                </th>
                                <th width="10" rowspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_giao_hang'); ?>
                                </th>
                            </tr>
                            <tr>
                                <th width="200"  colspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_van_chuyen_thuong'); ?>
                                    <a href="#" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate("txt_tooltip_van_chuyen_thuong"); ?>" >
                                        <i class="fa fa-question-circle" aria-hidden="true"></i>
                                    </a>
                                </th>
                                <th width="200"  colspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_van_chuyen_nhanh'); ?>
                                    <a href="#" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate("txt_tooltip_van_chuyen_nhanh"); ?>" >
                                        <i class="fa fa-question-circle" aria-hidden="true"></i>
                                    </a>
                                </th>
                                <th width="200"  colspan="2" style="text-align: center;vertical-align: middle;" >
                                    <?php echo $this->translate('txt_thoi_gian_giao_hang'); ?>
                                    <a href="#" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate("txt_tooltip_thoi_gan_giao_hang"); ?>" >
                                        <i class="fa fa-question-circle" aria-hidden="true"></i>
                                    </a>
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <button class="btn btn-primary btn-sm" >
            <?php echo $this->translate('txt_them_moi_shipping'); ?>
        </button>
        <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
            <?php echo $this->translate('txt_quay_lai'); ?>
        </button>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</section>