<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Cấu hình
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms') ?>">Cấu hình hệ thống</a></li>
        <li><?php echo $config->description ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-6">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title"><?php echo $config->description ?></h3>
                </div>
                <div class="box-body">
                    <form action="" method="post">
                        <table class="table">
                            <tr>
                                <th valign="middle">Bài viết</th>
                                <td><input type="text" name="value" value="<?php echo $config->value ?>" id="value" class="form-control" readonly /></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><button class="btn btn-primary">Lưu cấu hình</button></td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">
                        Tra cứu bài viết
                    </h3>
                </div>
                <div class="box-body">
                    <input type="text" class="form-control article_autocomplete_config"
                           placeholder="Nhập vào mã sản phẩm hoặc tên sản phẩm"/>
                </div>
            </div>
        </div>
    </div>
</section>