<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Cấu hình :: Footer
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/setting') ?>">Cấu hình hệ thống</a></li>
        <li class="active">Footer</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
<form action="<?php echo $this->url('cms/setting', array('action' => 'footer-list')) ?>" method="post">
    <div class="row">
		<div class="col-xs-12">
			<div class="box box-primary">
				<div class="box-body">
					<button class="btn btn-primary">Lưu</button>
					<button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
				</div>
			</div>
		</div>
        <div class="col-xs-12">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title">Footer::Hỗ trợ khách hàng</h3>
				</div>
				<div class="box-body">
					<textarea name="config[support_customer]" id="support_customer" class="form-control ckeditor" rows="3"><?php echo isset($configs['support_customer']) ? html_entity_decode($configs['support_customer'], ENT_QUOTES, 'UTF-8') : '' ?></textarea>
				</div>
			</div>
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title">Footer::Giới thiệu</h3>
				</div>
				<div class="box-body">
					<textarea name="config[aboutus]" id="aboutus" class="form-control ckeditor" rows="3"><?php echo isset($configs['aboutus']) ? html_entity_decode($configs['aboutus'], ENT_QUOTES, 'UTF-8') : '' ?></textarea>
				</div>
			</div>
        </div>
		<div class="col-xs-12">
			<div class="box box-primary">
				<div class="box-body">
					<button class="btn btn-primary">Lưu</button>
					<button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
				</div>
			</div>
		</div>
    </div>
</form>
</section>