<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Cấu hình :: Quản lý liên kết
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Quản lý kết nối mạng xã hội</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/setting', array('action' => 'add-network')) ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/setting', array('action' => 'add-network')) ?>"
                               class="btn btn-primary">Thêm mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/setting', array('action' => 'publish-network')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/setting', array('action' => 'unpublish-network')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/setting', array('action' => 'delete-network')) ?>')">
                                Xóa
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php //echo $paging ?>
                            </ul>
                        </div>
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Icon</th>
                                <th>Tiêu đề</th>
                                <th>Link</th>
                                <th>Hiển thị</th>
                                <th width="10"><input type="checkbox" class="checkall" /></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($rows as $row) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $row['id'] ?></td>
                                    <td>
                                        <img src="<?php echo FOLDERWEB.$row['icon'] ?>" width="50" height="50" />
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/setting',array('action' => 'edit-network', 'id' => $row['id'])) ?>"><?php echo $row['title'] ?></a>
                                    </td>
									<td>
										<a href="<?php echo $row['link'] ?>" target="__blank"><?php echo $row['link'] ?></a>
									</td>
									<td>
										<?php if($row['is_published'] == 1) : ?>
                                            <?php $href = $this->url('cms/setting', array('action' => 'unpublish-network', 'id' => $row['id'])) ?>
                                        <?php else: ?>
                                            <?php $href = $this->url('cms/setting', array('action' => 'publish-network', 'id' => $row['id'])) ?>
                                        <?php endif; ?>
                                        <?php echo $row['is_published'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Đang hiển thị' data-original-title='Đang hiển thị'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Bị ẩn'><i class='fa fa-circle-o'></i></a>" ?>
									</td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $row['id'] ?>"/>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Icon</th>
                                <th>Tiêu đề</th>
                                <th>Link</th>
                                <th>Hiển thị</th>
                                <th width="10"><input type="checkbox" class="checkall" /></th>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php //echo $paging ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/setting', array('action' => 'add-network')) ?>"
                               class="btn btn-primary">Thêm mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/setting', array('action' => 'publish-network')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/setting', array('action' => 'unpublish-network')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/setting', array('action' => 'delete-network')) ?>')">
                                Xóa
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->