<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_san_pham'); ?> 
                    <?php echo !empty($category) ? $this->translate('txt_trong_danh_muc').'<i>'.$category->categories_title.'</i>' : '' ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_san_pham'); ?> 
                <?php echo !empty($category) ? $this->translate('txt_trong_danh_muc').'<i>'.$category->categories_title.'</i>' : '' ?> :: 
                <?php echo $this->translate('txt_quan_ly'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/product', array('action' => 'index')) ?>" method="get" role="form" data-form="searchAjax" >
                <div class="coz-search-bar clearfix" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="<?php echo $this->translate('txt_holder_search'); ?>" value="<?php echo $q ?>" data-input="q" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" data-input="type" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        <?php echo $this->translate('txt_kieu_tim_kiem'); ?> : 
                                        <?php echo $this->translate('txt_theo_ten'); ?>
                                    </option>
                                    <option value="1" <?php echo $type == 1 ? 'selected="selected"' : '' ?> >
                                        <?php echo $this->translate('txt_kieu_tim_kiem'); ?> : 
                                        <?php echo $this->translate('txt_theo_model'); ?>
                                    </option>
                                    <option value="2" <?php echo $type == 2 ? 'selected="selected"' : '' ?> >
                                        <?php echo $this->translate('txt_kieu_tim_kiem'); ?> : 
                                        <?php echo $this->translate('txt_theo_gia'); ?>
                                    </option>
                                    <option value="3" <?php echo $type == 3 ? 'selected="selected"' : '' ?> >
                                        <?php echo $this->translate('txt_kieu_tim_kiem'); ?> : 
                                        <?php echo $this->translate('txt_theo_so_luong'); ?>
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <span class="tip-search" >
                                <?php echo $this->translate('txt_nhan_vao_day_de_search'); ?>
                            </span>
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>

                    <div class="dropdown-menu coz-dropdown-search" >
                        <div class="dropdown-label clearfix" >
                            <?php echo $this->translate('txt_chon_tieu_chi_search'); ?>
                            <a href="<?php echo $this->url('cms/product') ?>" class="pull-right" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xoa_bo_loc'); ?>" data-btn="clearSearch" data-confirm="<?php echo $this->translate('txt_ban_muon_xoa_search'); ?>" >
                                <i class="fa fa-refresh" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="dropdown-item" >
                            <div class="clearfix" >
                                <div class="row" >  
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_published" value="1" <?php echo $is_published == 1 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_hien_thi'); ?>
                                        </label>
                                    </div>
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_published" value="0" <?php echo $is_published == 0 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_ko_hien_thi'); ?>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="dropdown-item" >
                            <div class="clearfix" >
                                <div class="row" >  
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_new" value="1" <?php echo $is_new == 1 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_la_san_pham_moi'); ?>
                                        </label>
                                    </div>
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_new" value="0" <?php echo $is_new == 0 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_ko_la_san_pham_moi'); ?>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="dropdown-item" >
                            <div class="clearfix" >
                                <div class="row" >  
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_hot" value="1" <?php echo $is_hot == 1 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_la_san_pham_hot'); ?>
                                        </label>
                                    </div>
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_hot" value="0" <?php echo $is_hot == 0 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_ko_la_san_pham_hot'); ?>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="dropdown-item" >
                            <div class="clearfix" >
                                <div class="row" >  
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_goingon" value="1" <?php echo $is_goingon == 1 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_la_san_pham_sap_ve'); ?>
                                        </label>
                                    </div>
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_goingon" value="0" <?php echo $is_goingon == 0 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_ko_la_san_pham_sap_ve'); ?>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="dropdown-item" >
                            <div class="clearfix" >
                                <div class="row" >  
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_available" value="1" <?php echo $is_available == 1 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_san_pham_co_quan_ly_kho'); ?>
                                        </label>
                                    </div>
                                    <div class="col-sm-6" >
                                        <label class="clearfix">
                                            <input type="radio" name="is_available" value="0" <?php echo $is_available == 0 ? 'checked="checked"' : '' ?> > 
                                            <?php echo $this->translate('txt_san_pham_ko_co_quan_ly_kho'); ?>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
px                  </div>
                </div>
            </form>
        </div>
    </div>
</section>

<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/product') ?>" method="post" class="clearfix" id="form-list-product" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-6" ></div>
                <div class="col-sm-6" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/product', array('action' => 'add')) ?>" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_them_san_pham'); ?>" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($products) ){ ?>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/product', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_hien_san_pham'); ?>" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/product', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_an_san_pham'); ?>" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/product', array('action' => 'updateorder')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_cap_nhat_thu_tu'); ?>" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/product', array('action' => 'autoOrder')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_tu_dong_cap_nhat_thu_tu_san_pham'); ?>" >
                            <i class="fa fa-sort-amount-asc" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/product', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xoa_san_pham'); ?>" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="error-box" id="error-box" ></div>

        <?php if( !empty($products) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" ></th>
                        <th class="text-center col-lim" >
                            <?php echo $this->translate('txt_id'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_hinh'); ?>
                        </th>
                        <th>
                            <?php echo $this->translate('txt_ten'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_model'); ?>
                        </th>
                        <th class="col-lim text-right" >
                            <?php echo $this->translate('txt_sale_price_san_pham'); ?>
                        </th>
                        <th class="col-lim text-right" >
                            <?php echo $this->translate('txt_so_luong'); ?>
                        </th>
                        <th class="col-lim" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </th>
                        <th class="col-lim text-right" >
                            <?php echo $this->translate('txt_trang_thai'); ?>
                        </th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody id="container-product-sort" >
                    <?php foreach ($products as $key=>$row ) { ?>
                    <tr>
                        <td class="text-center col-lim drag-handle" >
                            <i class="fa fa-arrows"></i>
                        </td>
                        <td class="text-center col-lim" >
                            <?php echo $row['products_id'] ?>
                            <input name="ordering[<?php echo $row['products_id'] ?>]" class="ordering" type="hidden" value="<?php echo $row['ordering'] ?>" >
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cms/product', array('action' => 'edit', 'id' => $row['products_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_sua_san_pham'); ?>" >
                                <img src="<?php echo $this->Images()->getUrlImage($this->Products()->getImage($row),100); ?>" class="img-reponsive" width="100" >
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cms/product', array('action' => 'edit', 'id' => $row['products_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_sua_san_pham'); ?>" >
                                <?php 
                                    if( !empty($row['has_language']) )
                                        echo $this->Products()->getName($row);
                                    else
                                        echo '<i class="coz-color-disable" >'.$this->Products()->getName($row).'</i><i class="coz-color-important" data-toggle="tooltip" data-placement="top" title="'.$this->translate('txt_ban_cap_nhat_san_pham_no_dang_trong_cho_lng').'" > Warning ,Empty !</a>';
                                ?>
                            </a>
                        </td>
                        <td class="col-lim" >
                            <?php echo $row['products_code'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Products()->getPriceSale($row) ?>/<?php echo $this->Products()->getPrice($row) ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Products()->getQuantity($row) ?>
                        </td>
                        <td class="col-lim text-right html-ordering" >
                            <?php echo $row['ordering'] ?>
                        </td>
                        <td class="col-lim" >
                            <?php if ($this->Products()->getToBuy($row)){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_san_pham_co_the_mua_online'); ?>" >
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-important" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_san_pham_khong_the_mua_online'); ?>" >
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                </span>
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_dang_hien_thi'); ?>" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_dang_an'); ?>" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="text-right col-lim" >
                            <?php if( empty($languages) ){ ?>
                            <a href="<?php echo $this->url('cms/product', array('action' => 'edit', 'id' => $row['products_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_sua_san_pham'); ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <span class="inline-box" >
                                <a href="<?php echo $this->url('cms/product', array('action' => 'edit', 'id' => $row['products_id'])) ?>" title="<?php echo $this->translate('txt_sua_san_pham'); ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </a>
                                <span class="dropdown-menu dropdown-langs" >
                                <?php foreach( $languages as $lang ){ ?>
                                    <span class="dropdown-item" >
                                         <a href='<?php echo $this->url('cms/product', array('action' => 'edit', 'id' => $row['products_id'])) ?>?language=<?php echo $lang["languages_id"] ?>' >
                                            <span>
                                                <?php echo $lang["languages_name"] ?>
                                            </span>
                                        </a>
                                    </span>
                                <?php } ?>
                                </span>
                            </span>
                            <?php } ?>

                            <a href="<?php echo $this->url('cms/product', array('action' => 'copy', 'id' => $row['products_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_copy_san_pham'); ?>"  data-confirm="<?php echo $this->translate('txt_ban_co_muon_nhan_doi_san_pham'); ?>" >
                                <i class="fa fa-files-o" aria-hidden="true"></i>
                            </a>

                            <a href="javascript:void(0);" data-btn="postToFacebook" data-id="<?php echo $row['products_id']; ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_post_san_pham_len_face'); ?>" >
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>

                            <div class="box-verticle clearfix" >
                                <?php if( $key > 0){ ?>
                                <a href="javascript:void(0);" class="item-box-verticle" data-id="<?php echo $row['products_id'] ?>" data-btn="upOrder" data-idup="<?php echo $products[$key-1]['products_id'] ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_len_tren_mot_san_pham'); ?>" >
                                    <i class="fa fa-angle-up" aria-hidden="true"></i>
                                </a>
                                <?php }else{ ?>
                                <a href="javascript:void(0);" class="item-box-verticle" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_len_tren_mot_san_pham'); ?>" >
                                    <i class="fa fa-angle-up" aria-hidden="true"></i>
                                </a>
                                <?php } ?>

                                <?php if( $key < count($products)-1){ ?>
                                <a href="javascript:void(0);" class="item-box-verticle" data-id="<?php echo $row['products_id'] ?>" data-btn="downOrder" data-iddown="<?php echo $products[$key+1]['products_id'] ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xuong_duoi_mot_san_pham'); ?>" >
                                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                                </a>
                                <?php }else{ ?>
                                <a href="javascript:void(0);" class="item-box-verticle" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xuong_duoi_mot_san_pham'); ?>" >
                                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                                </a>
                                <?php } ?>
                            </div>

                            <a href="<?php echo $this->url('cms/product', array('action' => 'delete', 'id' => $row['products_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xoa_san_pham'); ?>"  data-confirm="<?php echo $this->translate('txt_ban_muon_xoa'); ?>" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($row['is_published']) ){ ?>
                            <a href="<?php echo $this->url('cms/product', array('action' => 'unpublish', 'id' => $row['products_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_an_san_pham'); ?>" >
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/product', array('action' => 'unpublish', 'id' => $row['products_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_hien_san_pham'); ?>" >
                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                            </a>
                            <?php } ?>
                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['products_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            <?php echo $this->translate('txt_chua_co_san_pham'); ?>
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>