<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/category') ?>" >
                        <?php echo $this->translate('txt_danh_muc_san_pham'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_cap_nhat_danh_muc'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_danh_muc_san_pham'); ?> ::
                <?php echo $this->translate('txt_cap_nhat_danh_muc'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-6 pull-rigth" >
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('cms/category', array('action' => 'edit', 'id' => $id)));
    $form->setAttribute('enctype', 'multipart/form-data');
    $form->setAttribute('id', 'form-category');
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('categories_id'));
    ?>
    <div class="clearfix" >
        <ul class="nav nav-inline coz-tab clearfix" role="tablist">
            <li class="nav-item active" >
                <a class="nav-link" data-toggle="tab" href="#tab_common" role="tab" rel="nofollow">
                    <?php echo $this->translate('txt_thong_tin_chung'); ?>                            
                </a>
            </li>
            <li class="nav-item" >
                <a class="nav-link" data-toggle="tab" href="#tab_seo" role="tab" rel="nofollow">
                    <?php echo $this->translate('txt_seo'); ?>                                    
                </a>
            </li>
        </ul>
    </div>
    <div class="tab-content clearfix" >
        <div class="tab-pane fade in clearfix active" id="tab_common" role="tabpanel" >
            <div class="coz-tab-content clearfix" >
                <div class="row" >
                    <div class="col-sm-6 col-xs-6" >
                        <div class="form-group">
                            <label for="languageoption">
                                <?php echo $this->translate('txt_ngon_ngu'); ?>
                            </label>
                            <input type="hidden" name="language" value="<?php echo $this->langselected;?>" />
                            <select name="languageoption" id="languageoption" class="form-control input-sm" disabled >
                            <?php
                            if(!empty($this->language_list)){
                                foreach($this->language_list as $listlanguage){
                                    $selected="";
                                    if(!empty($this->langselected) && $this->langselected==$listlanguage["languages_id"]){
                                        $selected="selected";
                                    }
                                    echo "<option value='".$listlanguage["languages_id"]."' $selected>".$listlanguage["languages_name"]."</option>";
                                }
                            }
                            ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="parent_id">
                                <?php echo $this->translate('txt_danh_muc_cha'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('parent_id')); ?>
                        </div>
                        <div class="form-group">
                            <label for="categories_title">
                                <?php echo $this->translate('txt_ten_danh_muc'); ?>
                                <?php if( empty($category->categories_title) ){ ?>
                                <div class="coz-color-disable" >
                                    <?php echo $this->translate('txt_goi_y_ten_tren_nn_khac'); ?> 
                                    (<i><?php echo $category->categories_title_root ?></i>)
                                </div>
                                <?php } ?>
                            </label>
                            <?php echo $this->formRow($form->get('categories_title')); ?>
                        </div>
                        <div class="form-group">
                            <label for="categories_alias" >
                                <?php echo $this->translate('txt_duong_dan'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('categories_alias')); ?>
                        </div>

                        <div class="form-group">
                            <label for="cat_recommend">
                                <?php echo $this->translate('txt_danh_muc_lien_quan'); ?>
                            </label>
                            <select name="cat[]" id="cat_recommend" class="multichoice form-control input-sm" multiple>
                                <?php foreach($cats as $cat) : ?>
                                    <option value="<?php echo $cat['categories_id'] ?>" <?php echo in_array($cat['categories_id'], $cats_recommend) ? 'selected' : '' ?>><?php echo $cat['treename'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                    </div>
                </div>

                <div class="form-group" >
                    <div class="result-list-img clearfix" >
                        <div class="list-img-upload clearfix" >
                            <?php if(!empty($category->icon)){ ?>
                            <div class="img-prevew-upload" data-place="prevewImage" >
                                <a href="javascript:void(0)" class="action-upload" data-btn="removePrevewImage" >
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                                <img src="<?php echo $category->icon; ?>" class="img-responsive" >
                            </div>
                            <?php } ?>
                        </div>
                        <div class="img-prevew-upload btn-upload btn-upload-icon-category" >
                            <a href="javascript:void(0)" class="action-upload" >
                                <i class="fa fa-plus" aria-hidden="true"></i>
                            </a>
                            <a href="javascript:void(0)" class="img-responsive"  >
                                <i class="fa fa-picture-o" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="categories_description">
                        <?php echo $this->translate('txt_mo_ta'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('categories_description')); ?>
                </div>

                <div class="form-group" >
                    <label for="ordering">
                        <?php echo $this->translate('txt_vi_tri'); ?>
                        <?php echo $this->formRow($form->get('ordering')); ?>
                    </label>
                    <label for="is_static">
                        <?php echo $this->formRow($form->get('is_static')); ?>
                        <?php echo $this->translate('txt_danh_muc_tinh'); ?>
                    </label>
                    <label for="is_published">
                        <?php echo $this->formRow($form->get('is_published')); ?>
                        <?php echo $this->translate('txt_hien_thi'); ?>
                    </label>
                </div>

            </div>
        </div>
        <div class="tab-pane fade in clearfix" id="tab_seo" role="tabpanel" >
            <div class="coz-tab-content clearfix" >
                <div class="form-group">
                    <label for="seo_title" >
                        <?php echo $this->translate('txt_seo_title'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('seo_title')); ?>
                </div>
                <div class="form-group">
                    <label for="seo_keywords" >
                        <?php echo $this->translate('txt_seo_keywords'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('seo_keywords')); ?>
                </div>
                <div class="form-group">
                    <label for="seo_description">
                        <?php echo $this->translate('txt_seo_description'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('seo_description')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <button class="btn btn-primary btn-sm" >
            <?php echo $this->translate('txt_cap_nhat_danh_muc'); ?>
        </button>
        <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
            <?php echo $this->translate('txt_quay_lai'); ?>
        </button>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</section>