<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>" >
                        <i class="fa fa-dashboard"></i> 
                        Trang chủ
                    </a>
                </li>
                <li class="active">
                    Danh mục <i><?php echo !empty($category) ? $category->categories_title : '' ?></i>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Danh mục :: Quản lý 
                <i><?php echo !empty($category) ? $category->categories_title : '' ?></i>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/category', array('action' => 'index')) ?>" method="get" role="form" data-form="searchAjax" >
                <div class="coz-search-bar clearfix" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="Search..." value="<?php echo $q ?>" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo tên
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/category') ?>" method="post" class="clearfix" id="form-list-category" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-6" >
                    <?php if( !empty($category) ){ ?>
                    <a href="<?php echo $this->url('cms/category', array('action' => 'index', 'id' => $category->parent_id)) ?>" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Quay về danh mục trước" >
                        <i class="fa fa-caret-left" aria-hidden="true"></i>
                        Quay về danh mục trước
                    </a>
                    <?php } ?>
                </div>
                <div class="col-sm-6" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/category', array('action' => 'add', 'id' => $id)) ?>" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm danh mục" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($categories) ){ ?>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/category', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="Hiện danh mục" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/category', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="Ẩn danh mục" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/category', array('action' => 'autoOrder')) ?>')" data-toggle="tooltip" data-placement="top" title="Cập nhật thứ tự" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/category', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="Xoá danh mục" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="error-box" id="error-box" ></div>

        <?php if( !empty($categories) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" ></th>
                        <th class="text-center col-lim" >ID</th>
                        <th>Tên</th>
                        <th class="col-lim" >Vị trí</th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody id="container-category-sort" >
                    <?php foreach ($categories as $row ) { ?>
                    <tr>
                        <td class="text-center col-lim drag-handle" >
                            <i class="fa fa-arrows"></i>
                        </td>
                        <td class="text-center col-lim" >
                            <?php echo $row['categories_id'] ?>
                            <input name="ordering[<?php echo $row['categories_id'] ?>]" class="ordering" type="hidden" value="<?php echo $row['ordering'] ?>" >
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cms/category', array('action' => 'index', 'id' => $row['categories_id'])) ?>" >
                                <?php 
                                    if( !empty($row['has_language']) )
                                        echo $row['categories_title'];
                                    else
                                        echo '<i class="coz-color-disable" >'.$row['categories_title'].'</i><i class="coz-color-important" data-toggle="tooltip" data-placement="top" title="Bạn vui lòng cập nhật danh mục này, nó đang trống cho ngôn ngữ hiện tại" > Warning ,Empty !</a>';
                                ?>
                            </a>
                        </td>
                        <td class="col-lim text-right html-ordering" >
                            <?php echo $row['ordering'] ?>
                        </td>
                        <td class="col-lim" > 
                            <?php if( !empty($row['total_childrens_active']) ){ ?>   
                                <?php echo $row['number_childrens_active'] ?>/
                                <?php echo $row['total_childrens_active'] ?> active
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="text-right col-lim" >
                            <?php if( empty($languages) ){ ?>
                            <a href="<?php echo $this->url('cms/category', array('action' => 'edit', 'id' => $row['categories_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa danh mục" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <span class="inline-box" >
                                <a href="<?php echo $this->url('cms/category', array('action' => 'edit', 'id' => $row['categories_id'])) ?>" title="Sửa danh mục" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </a>
                                <span class="dropdown-menu dropdown-langs" >
                                <?php foreach( $languages as $lang ){ ?>
                                    <span class="dropdown-item" >
                                         <a href='<?php echo $this->url('cms/category', array('action' => 'edit', 'id' => $row['categories_id'])) ?>?language=<?php echo $lang["languages_id"] ?>' >
                                            <span>
                                                <?php echo $lang["languages_name"] ?>
                                            </span>
                                        </a>
                                    </span>
                                <?php } ?>
                                </span>
                            </span>
                            <?php } ?>

                            
                            <a href="<?php echo $this->url('cms/product', array('action' => 'index', 'id' => $row['categories_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xem sản phẩm" >
                                <i class="fa fa-newspaper-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/category', array('action' => 'delete', 'id' => $row['categories_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá danh mục"  data-confirm="Bạn có muốn xoá ?" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/category', array('action' => 'update-feature', 'id' => $row['categories_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Cập nhật thuộc tính" >
                                <i class="fa fa-list-alt" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($row['is_published']) ){ ?>
                            <a href="<?php echo $this->url('cms/category', array('action' => 'unpublish', 'id' => $row['categories_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn danh mục" >
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/category', array('action' => 'publish', 'id' => $row['categories_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện danh mục" >
                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                            </a>
                            <?php } ?>
                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['categories_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có danh mục
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>