<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Đặc tính :: Thêm mới
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/feature') ?>">Đặc tính</a></li>
        <li class="active">Thêm mới đặc tính</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/website', array('action' => 'add')));
        $form->setAttribute('id', 'form-website');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('feature_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="parent_id">Đặc tính cha</label>
                        <?php echo $this->formRow($form->get('parent_id')); ?>
                    </div>
                    <div class="form-group">
                        <label for="parent_id">Tên đặc tính</label>
                        <?php echo $this->formRow($form->get('feature_title')); ?>
                    </div>
                    <div class="form-group">
                        <label for="parent_id">Đường dẫn</label>
                        <?php echo $this->formRow($form->get('feature_alias')); ?>
                    </div>
                    <div class="form-group">
                        <label for="ordering">Thứ tự
                            <?php echo $this->formRow($form->get('ordering')); ?>
                        </label>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_published">
                                <?php echo $this->formRow($form->get('is_published')); ?>
                                Kích hoạt
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_value">
                                <?php echo $this->formRow($form->get('is_value')); ?>
                                Tự điền giá trị
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <button class="btn btn-primary">Lưu lại</button>
            <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>