<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_websites'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-12 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_websites'); ?> :: 
                <?php echo $this->translate('txt_quan_ly'); ?>
            </h1>
        </div>
    </div>
</section>

<section class="content clearfix" >
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('cms/website', array('action' => 'index')));
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <div class="clearfix" >
        <ul class="nav nav-inline coz-tab clearfix" role="tablist">
            <li class="nav-item active" >
                <a class="nav-link" data-toggle="tab" href="#tab_common" role="tab" rel="nofollow">
                    <?php echo $this->translate('txt_thong_tin_chung'); ?>                                    
                </a>
            </li>
            <li class="nav-item" >
                <a class="nav-link" data-toggle="tab" href="#tab_order" role="tab" rel="nofollow">
                    <?php echo $this->translate('txt_order_website'); ?>                                    
                </a>
            </li>
            <li class="nav-item" >
                <a class="nav-link" data-toggle="tab" href="#tab_coding" role="tab" rel="nofollow">
                    <?php echo $this->translate('txt_coding_website'); ?>                                    
                </a>
            </li>
            <li class="nav-item" >
                <a class="nav-link" data-toggle="tab" href="#tab_analytics" role="tab" rel="nofollow">
                    <?php echo $this->translate('txt_analytics_and_social_website'); ?>
                </a>
            </li>
            <li class="nav-item" >
                <a class="nav-link" data-toggle="tab" href="#tab_seo" role="tab" rel="nofollow">
                    <?php echo $this->translate('txt_seo_website'); ?>
                </a>
            </li>
            <li class="nav-item" >
                <a class="nav-link" data-toggle="tab" href="#tab_orther" role="tab" rel="nofollow">
                    <?php echo $this->translate('txt_thong_tin_khac_website'); ?>
                </a>
            </li>
        </ul>
    </div>
    <div class="tab-content clearfix" >
        <div class="tab-pane fade in clearfix active" id="tab_common" role="tabpanel" >
            <div class="coz-tab-content clearfix" >
                <div class="row" >
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label class="control-label" for="website_name" >
                                <?php echo $this->translate('txt_ten_website'); ?>
                            </label>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('website_name')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="website_name_business">
                                <?php echo $this->translate('txt_ten_kinh_doanh_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('website_name_business')); ?>
                        </div>

                        <div class="form-group" >
                            <label class="control-label" for="website_email_admin" >
                                <?php echo $this->translate('txt_email_quan_tri_website'); ?>
                            </label>
                            <p class="text-muted">
                                <?php echo $this->translate('txt_email_dc_su_dung_de_lien_lac_website'); ?>
                            </p>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('website_email_admin')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="website_email_customer">
                                <?php echo $this->translate('txt_email_gui_thong_bao_website'); ?>
                            </label>
                            <p class="text-muted">
                                <?php echo $this->translate('txt_giai_thich_email_gui_thong_bao_website'); ?>
                            </p>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('website_email_customer')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="website_phone">
                                <?php echo $this->translate('txt_dien_thoai_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('website_phone')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="website_address">
                                <?php echo $this->translate('txt_dia_chi_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('website_address')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="website_contries">
                                <?php echo $this->translate('txt_quoc_gia_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('website_contries')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="is_local">
                                <?php echo $this->translate('txt_chi_ban_trong_nuoc_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('is_local')); ?>
                        </div>

                        <div class="form-group" >
                            <div class="result-list-img clearfix" >
                                <div class="list-img-upload clearfix" >
                                    <?php if(!empty($website->logo)){ ?>
                                    <div class="img-prevew-upload" data-place="prevewImage" >
                                        <a href="javascript:void(0)" class="action-upload" data-btn="removePrevewImage" >
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </a>
                                        <img src="<?php echo $website->logo; ?>" class="img-responsive" >
                                    </div>
                                    <?php } ?>
                                </div>
                                <div class="img-prevew-upload btn-upload btn-upload-logo-website" >
                                    <a href="javascript:void(0)" class="action-upload" >
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                    </a>
                                    <a href="javascript:void(0)" class="img-responsive"  >
                                        <i class="fa fa-picture-o" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label" for="website_domain_refer" >
                        <?php echo $this->translate('txt_tro_do_main_website'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('website_domain_refer')); ?>
                </div>

                <h5>
                    <?php echo $this->translate('txt_tich_hop_login_website'); ?>
                </h5>
                <div class="form-group">
                    <label for="has_login_facebook" >
                        <?php echo $this->formRow($form->get('has_login_facebook')); ?>
                        <?php echo $this->translate('txt_login_facebook_website'); ?>
                    </label>
                    <label for="has_login_google" >
                        <?php echo $this->formRow($form->get('has_login_google')); ?>
                        <?php echo $this->translate('txt_login_google_website'); ?>
                    </label>
                    <label for="has_login_twister" >
                        <?php echo $this->formRow($form->get('has_login_twister')); ?>
                        <?php echo $this->translate('txt_login_twister_website'); ?>
                    </label>
                </div>

            </div>
        </div>

        <div class="tab-pane fade in clearfix" id="tab_order" role="tabpanel" >
            <div class="coz-tab-content clearfix" >
                <div class="row" >
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label class="control-label" for="website_timezone" >
                                <?php echo $this->translate('txt_tien_te_website'); ?>
                            </label>
                            <a href="javascript:void(0)" class="btn-format-currency" >
                                <?php echo $this->translate('txt_thay_doi_dinh_dang_tien_te_website'); ?>
                            </a>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('website_currency')); ?>
                            </div>
                        </div>
                        <div class="box-format-currency" style="display:none" >
                            <div class="form-group">
                                <h5>
                                    <?php echo $this->translate('txt_cau_hinh_hien_thi_tien_website'); ?>
                                </h5>
                                <div class="row" >
                                    <div class="col-xs-4">
                                        <label class="control-label" for="website_currency_decimals">
                                            <?php echo $this->translate('txt_decimals_tien_website'); ?>
                                        </label>
                                        <?php echo $this->formRow($form->get('website_currency_decimals')); ?>
                                    </div>
                                    <div class="col-xs-4">
                                        <label class="control-label" for="website_currency_decimalpoint">
                                            <?php echo $this->translate('txt_decimalpoint_tien_website'); ?>
                                        </label>
                                        <?php echo $this->formRow($form->get('website_currency_decimalpoint')); ?>
                                    </div>
                                    <div class="col-xs-4">
                                        <label class="control-label" for="website_currency_separator">
                                            <?php echo $this->translate('txt_separator_tien_website'); ?>
                                        </label>
                                        <?php echo $this->formRow($form->get('website_currency_separator')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label">
                                <?php echo $this->translate('txt_dinh_dang_ma_hoa_don_website'); ?>
                            </label> <br>
                            <span class="text-muted">
                                <?php echo $this->translate('txt_giai_thich_dinh_dang_ma_hoa_don_website'); ?>
                            </span>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-xs-6">
                                    <label class="control-label" for="website_order_code_prefix">
                                        <?php echo $this->translate('txt_tien_to_ma_hoa_don_website'); ?>
                                    </label>
                                    <?php echo $this->formRow($form->get('website_order_code_prefix')); ?>
                                </div>
                                <div class="col-xs-6">
                                    <label class="control-label" for="website_order_code_suffix">
                                        <?php echo $this->translate('txt_hau_to_ma_hoa_don_website'); ?>
                                    </label>
                                    <?php echo $this->formRow($form->get('website_order_code_suffix')); ?>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="text-muted">
                                <?php echo $this->translate('txt_ma_hoa_don_ap_dung_la_website'); ?> 
                            </span>
                            <span class="example-order-code">#1001, #1002</span>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade in clearfix" id="tab_coding" role="tabpanel" >
            <div class="coz-tab-content clearfix" >
                <div class="row" >
                    <div class="col-sm-10" >
                        <div class="form-group">
                            <label class="control-label" for="javascript">
                                <?php echo $this->translate('txt_javascript_website'); ?>
                            </label>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('javascript')); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="css">
                                <?php echo $this->translate('txt_css_website'); ?>
                            </label>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('css')); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade in clearfix" id="tab_analytics" role="tabpanel" >
            <div class="coz-tab-content clearfix" >
                <div class="row" >
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label class="control-label" for="website_ga_code">
                                <?php echo $this->translate('txt_ga_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('website_ga_code')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="facebook_id">
                                <?php echo $this->translate('txt_app_facebook_id_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('facebook_id')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="google_client_id">
                                <?php echo $this->translate('txt_google_client_id_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('google_client_id')); ?>
                        </div>

                        <?php if($this->CMSCommon()->hasPermission('cms','facebook', 'index')){ ?>
                        <div class="row" >

                            <div class="col-sm-12 text-center"  id="not-oauth-fbapp" >
                                <p>
                                    <?php echo $this->translate('txt_ban_chua_auth_facebook_website'); ?>
                                </p>
                                <a href="/cms/facebook" >
                                    <?php echo $this->translate('txt_auth_facebook_website'); ?>
                                </a>
                            </div>

                            <div class="col-sm-12 config-websites-fbapp" id="oauth-fbapp"  style="display: none"  >
                                <div class="row" >
                                    <div class="col-sm-6" >
                                        <div class="form-group" >
                                            <label class="control-label strong" for="fb_page_id">
                                                <?php echo $this->translate('txt_fanpage_website'); ?>
                                            </label>
                                            <div class="controls">
                                                <select name="fb_page_id" id="fb_page_id" class="form-control fb_page_id" id="fb_page_id" ></select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6" id="wrap-fb_page_tab" style="display: none;" >
                                        <div class="form-group">
                                            <label class="control-label strong" for="fb_page_tab">
                                                <?php echo $this->translate('txt_tab_page_website'); ?>
                                            </label>
                                            <div class="controls">
                                                <select name="fb_page_tab" id="fb_page_tab" class="form-control fb_page_tab" >
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-12 text-center"  id="not-oauth-fbapp" >
                                        <p>
                                            <?php echo $this->translate('txt_ban_da_auth_facebook_website'); ?>
                                        </p>
                                        <a href="javascript:void(0);" data-btn="reOauthFacebookApp" >
                                            <?php echo $this->translate('txt_auth_facebook_website'); ?>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php } ?>

                        <div class="form-group">
                            <label class="control-label" for="url_twister">
                                <?php echo $this->translate('txt_url_twister_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('url_twister')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="url_google_plus">
                                <?php echo $this->translate('txt_url_googleplus_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('url_google_plus')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="url_facebook">
                                <?php echo $this->translate('txt_url_facebook_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('url_facebook')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="url_pinterest">
                                <?php echo $this->translate('txt_url_pinterest_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('url_pinterest')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="url_houzz">
                                <?php echo $this->translate('txt_url_houzz_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('url_houzz')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="url_instagram">
                                <?php echo $this->translate('txt_url_instagram_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('url_instagram')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="url_rss">
                                <?php echo $this->translate('txt_url_rss_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('url_rss')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="url_youtube">
                                <?php echo $this->translate('txt_url_youtube_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('url_youtube')); ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade in clearfix" id="tab_seo" role="tabpanel" >
            <div class="coz-tab-content clearfix" >
                <div class="row" >
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label class="control-label" for="seo_title">
                                <?php echo $this->translate('txt_seo_title_website'); ?>
                            </label>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('seo_title')); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row" >
                    <div class="col-sm-10" >
                        <div class="form-group">
                            <label class="control-label" for="seo_keywords">
                                <?php echo $this->translate('txt_seo_keywords_website'); ?>
                            </label>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('seo_keywords')); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="seo_description">
                                <?php echo $this->translate('txt_seo_description_website'); ?>
                            </label>
                            <div class="controls">
                                <?php echo $this->formRow($form->get('seo_description')); ?>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="tab-pane fade in clearfix" id="tab_orther" role="tabpanel" >
            <div class="coz-tab-content clearfix" >
                <div class="row" >
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label class="control-label" for="version_cart">
                                <?php echo $this->translate('txt_version_cart_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('version_cart')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="type_crop_image">
                                <?php echo $this->translate('txt_kieu_cat_hinh_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('type_crop_image')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="confirm_location">
                                <?php echo $this->translate('txt_hien_poup_hoi_vi_tri_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('confirm_location')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="type_buy">
                                <?php echo $this->translate('txt_giao_hang_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('type_buy')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="ship" >
                                <?php echo $this->translate('txt_gia_tri_don_hang_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('ship')); ?>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="website_timezone" >
                                <?php echo $this->translate('txt_mui_gio_website'); ?>
                            </label>
                            <?php echo $this->formRow($form->get('website_timezone')); ?>
                        </div>

                        <h5>
                            <?php echo $this->translate('txt_loc_san_pham_theo_gia_website'); ?>
                        </h4>
                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-6" >
                                    <label class="control-label" for="website_min_value_slider">
                                        <?php echo $this->translate('txt_gia_tu_website'); ?>
                                    </label>
                                    <?php echo $this->formRow($form->get('website_min_value_slider')); ?>
                                </div>
                                <div class="col-xs-6" >
                                    <label class="control-label" for="website_max_value_slider">
                                        <?php echo $this->translate('txt_gia_den_website'); ?>
                                    </label>
                                    <?php echo $this->formRow($form->get('website_max_value_slider')); ?>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="form-group">
        <button class="btn btn-primary btn-sm" >
            <?php echo $this->translate('txt_cap_nhat_thong_tin_website'); ?>
        </button>
        <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
            <?php echo $this->translate('txt_quay_lai'); ?>
        </button>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</section>