<?php foreach ($articles as $row) : ?>
	<tr>
		<td style="text-align: center"><?php echo $row['articles_id'] ?></td>
		<td>
			<a href="<?php echo $this->url('cms/articles', array('action' => 'edit', 'id' => $row['articles_id'])) ?>"><?php echo $row['articles_title'] ?></a>
		</td>
		<td style="text-align: center">
			<input type="text" style="width: 50px;text-align: center"
				   name="order[<?php echo $row['articles_id'] ?>]"
				   value="<?php echo $row['ordering'] ?>" class="numberInput"/>
		</td>
		<td><?php echo date('d/m/Y', strtotime($row['date_create'])) ?></td>
		<td style="text-align: center">

			<?php if($row['is_published'] == 1) : ?>
				<?php $href = $this->url('cms/articles', array('action' => 'singleunpublish', 'id' => $row['articles_id'])) ?>
			<?php else: ?>
				<?php $href = $this->url('cms/articles', array('action' => 'singlepublish', 'id' => $row['articles_id'])) ?>
			<?php endif; ?>
			<?php echo $row['is_published'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Đang hiển thị' data-original-title='Đang hiển thị'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Bị ẩn'><i class='fa fa-circle-o'></i></a>" ?>
			<!--                                        --><?php //echo $row['is_published'] == 1 ? 'Hiển thị' : '-' ?>
		</td>
		<td style="text-align: center">
			<?php echo $row['is_delete'] == 1 ? 'Đã xóa' : '-' ?>
		</td>
		<td>
			<input type="checkbox" name="cid[]"
				   value="<?php echo $row['articles_id'] ?>" />
		</td>
	</tr>
<?php endforeach; ?>