<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_bai_viet'); ?> 
                    <?php echo !empty($category) ? $this->translate('txt_trong_danh_muc').'<i>'.$category->categories_articles_title.'</i>' : '' ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_bai_viet'); ?> 
                <?php echo !empty($category) ? $this->translate('txt_trong_danh_muc').'<i>'.$category->categories_articles_title.'</i>' : '' ?> ::
                <?php echo $this->translate('txt_quan_ly'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/articles', array('action' => 'index')) ?>" method="get" role="form" data-form="searchAjax" >
                <div class="coz-search-bar clearfix" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="Search..." value="<?php echo $q ?>" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        <?php echo $this->translate('txt_kieu_tim_kiem'); ?> : 
                                        <?php echo $this->translate('txt_theo_ten'); ?>
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/articles') ?>" method="post" class="clearfix" id="form-list-article" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-6" ></div>
                <div class="col-sm-6" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/articles', array('action' => 'add')) ?>" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_them_bai_viet'); ?>" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($articles) ){ ?>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/articles', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_hien_bai_viet'); ?>" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/articles', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_an_bai_viet'); ?>" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/articles', array('action' => 'autoOrder')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_cap_nhat_thu_tu'); ?>" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/articles', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xoa_bai_viet'); ?>" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="error-box" id="error-box" ></div>

        <?php if( !empty($articles) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" ></th>
                        <th class="text-center col-lim" >
                            <?php echo $this->translate('txt_id'); ?>
                        </th>
                        <th class="text-center col-lim" >
                            <?php echo $this->translate('txt_hinh'); ?>
                        </th>
                        <th>
                            <?php echo $this->translate('txt_ten'); ?>
                        </th>
                        <th class="col-lim" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </th>
                        <th class="col-lim text-right" >
                            <?php echo $this->translate('txt_trang_thai'); ?>
                        </th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody id="container-article-sort" >
                    <?php foreach ($articles as $key=>$row ) { ?>
                    <tr>
                        <td class="text-center col-lim drag-handle" >
                            <i class="fa fa-arrows"></i>
                        </td>
                        <td class="text-center col-lim" >
                            <?php echo $row['articles_id'] ?>
                            <input name="ordering[<?php echo $row['articles_id'] ?>]" class="ordering" type="hidden" value="<?php echo $row['ordering'] ?>" >
                        </td>
                        <td class="text-center col-lim" >
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'edit', 'id' => $row['articles_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_sua_bai_viet'); ?>" >
                                <img src="<?php echo $this->Images()->getUrlImage($this->Articles()->getImage($row),100); ?>" class="img-reponsive" width="100" >
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'edit', 'id' => $row['articles_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_sua_bai_viet'); ?>" >
                                <?php 
                                    if( !empty($row['has_language']) )
                                        echo $row['articles_title'];
                                    else
                                        echo '<i class="coz-color-disable" >'.$row['articles_title'].'</i><i class="coz-color-important" data-toggle="tooltip" data-placement="top" title="'.$this->translate('txt_warning_empty_present_language').'" > Warning ,Empty !</a>';
                                ?>
                            </a>
                        </td>
                        <td class="col-lim text-right html-ordering" >
                            <?php echo $row['ordering'] ?>
                        </td>
                        <td class="col-lim" >
                            <?php if( !empty($row['is_new']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_la_bai_viet_moi'); ?>" >
                                    <i class="fa fa-file-o" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_khong_la_bai_viet_moi'); ?>" >
                                    <i class="fa fa-file-o" aria-hidden="true"></i>
                                </span>
                            <?php } ?>

                            <?php if( !empty($row['is_hot']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_la_bai_viet_noi_bat'); ?>" >
                                    <i class="fa fa-fire" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_khong_la_bai_viet_noi_bat'); ?>" >
                                    <i class="fa fa-fire" aria-hidden="true"></i>
                                </span>
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_dang_hien_thi'); ?>" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_dang_an'); ?>" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="text-right col-lim" >
                            <?php if( empty($languages) ){ ?>
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'edit', 'id' => $row['articles_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_sua_bai_viet'); ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <span class="inline-box" >
                                <a href="<?php echo $this->url('cms/articles', array('action' => 'edit', 'id' => $row['articles_id'])) ?>" title="<?php echo $this->translate('txt_sua_bai_viet'); ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </a>
                                <span class="dropdown-menu dropdown-langs" >
                                <?php foreach( $languages as $lang ){ ?>
                                    <span class="dropdown-item" >
                                         <a href='<?php echo $this->url('cms/articles', array('action' => 'edit', 'id' => $row['articles_id'])) ?>?language=<?php echo $lang["languages_id"] ?>' >
                                            <span>
                                                <?php echo $lang["languages_name"] ?>
                                            </span>
                                        </a>
                                    </span>
                                <?php } ?>
                                </span>
                            </span>
                            <?php } ?>

                            <a href="<?php echo $this->url('cms/articles', array('action' => 'delete', 'id' => $row['articles_id'])) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xoa_bai_viet'); ?>" data-confirm="<?php echo $this->translate('txt_ban_muon_xoa'); ?>" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($row['is_new']) ){ ?>
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'unnew', 'id' => $row['articles_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_bai_viet_moi'); ?>" >
                                <i class="fa fa-file-o" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'new', 'id' => $row['articles_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_bai_viet_khong_moi'); ?>" >
                                <i class="fa fa-file-o" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                            <?php if( !empty($row['is_hot']) ){ ?>
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'unhot', 'id' => $row['articles_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_bai_viet_hot'); ?>" >
                                <i class="fa fa-fire" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'hot', 'id' => $row['articles_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_bai_viet_khong_hot'); ?>" >
                                <i class="fa fa-fire" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'unpublish', 'id' => $row['articles_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_an_bai_viet'); ?>" >
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/articles', array('action' => 'publish', 'id' => $row['articles_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_hien_bai_viet'); ?>" >
                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                            </a>
                            <?php } ?>
                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['articles_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            <?php echo $this->translate('txt_hien_bai_viet'); ?>
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>