<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Danh mục :: Thêm mới
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/category_theme') ?>">Danh mục theme</a></li>
        <li class="active">Thêm mới danh mục</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/category_theme', array('action' => 'add')));
        $form->setAttribute('id', 'form-category-theme');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('categories_template_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="parent_id">Danh mục cha</label>
                        <?php echo $this->formRow($form->get('parent_id')); ?>
                    </div>
                    
                    <div class="form-group">
                        <label for="categories_title">Tên danh mục</label>
                        <?php echo $this->formRow($form->get('categories_title')); ?>
                    </div>

                    <div class="form-group">
                        <label for="categories_alias">Đường dẫn</label>
                        <?php echo $this->formRow($form->get('categories_alias')); ?>
                    </div>
                    
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_published">
                                <?php echo $this->formRow($form->get('is_published')); ?>
                                Kích hoạt
                            </label>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <button class="btn btn-primary">Lưu lại</button>
            <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>