<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Danh mục theme :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Danh mục theme</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/category_theme') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/category_theme', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm danh mục mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/category_theme', array('action' => 'publish')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/category_theme', array('action' => 'unpublish')) ?>')">
                                Bỏ kích hoạt
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Danh mục</th>
                                <th width="100" style="text-align: center">Hiển thị</th>
                                <th width="10"><input type="checkbox" class="checkall" /></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($cats as $cat) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $cat['categories_template_id'] ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/category_theme', array('action' => 'edit', 'id' => $cat['categories_template_id'])) ?>">
                                            <?php echo $cat['categories_title'] ?>
                                        </a>
                                    </td>
                                    <td style="text-align: center">
                                        <?php if($cat['is_published'] == 1) : ?>
                                            <?php $href = $this->url('cms/category_theme', array('action' => 'singleunpublish', 'id' => $cat['categories_template_id'])) ?>
                                        <?php else: ?>
                                            <?php $href = $this->url('cms/category_theme', array('action' => 'singlepublish', 'id' => $cat['categories_template_id'])) ?>
                                        <?php endif; ?>
                                        <?php echo $cat['is_published'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Đang hiển thị' data-original-title='Đang hiển thị'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Bị ẩn'><i class='fa fa-circle-o'></i></a>" ?>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $cat['categories_template_id'] ?>"/>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Danh mục</th>
                                <th width="100" style="text-align: center">Hiển thị</th>
                                <th width="10"><input type="checkbox" class="checkall" /></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/category_theme', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm danh mục mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/category_theme', array('action' => 'publish')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/category_theme', array('action' => 'unpublish')) ?>')">
                                Bỏ kích hoạt
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->