<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/siri') ?>">
                        <?php echo $this->translate('txt_siri'); ?>
                    </a>
                </li>
                <li class="active" >
                    <?php echo $this->translate('txt_crawl'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_siri'); ?> :: 
                <?php echo $this->translate('txt_crawl'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
        </div>
    </div>
</section>