<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/siri') ?>">
                        <?php echo $this->translate('txt_siri'); ?>
                    </a>
                </li>
                <li class="active" >
                    <?php echo $this->translate('txt_fix_images'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_siri'); ?> :: 
                <?php echo $this->translate('txt_fix_images'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <?php if( !empty($msg) ){ ?>
    <div class="row" >
        <div class="form-group">
            <div class="alert alert-warning" >
                <?php echo $msg ?>
            </div>
        </div>
    </div>
    <?php } ?>
    
    <form action="/cms/siri/fix-image" method="post" role="form" enctype="multipart/form-data" >
        <div class="row" >
            <div class="col-sm-6" >
                <div class="form-group">
                    <label for="url" >
                        <?php echo $this->translate('txt_link_hinh_anh_siri'); ?>
                    </label>
                    <input type="text" name="url" id="url" placeholder="<?php echo $this->translate('txt_link_hinh_anh_siri'); ?>" class="form-control input-sm" value="<?php echo $url ?>" >
                </div>
            </div>
        </div>

        <div class="form-group">
            <button class="btn btn-primary btn-sm" >
                <?php echo $this->translate('txt_fix_hinh_nay_siri'); ?>
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                <?php echo $this->translate('txt_quay_lai'); ?>
            </button>
        </div>
    </form>
</section>