<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li class="active" >
                    <?php echo $this->translate('txt_siri'); ?> :: 
                    <?php echo $this->translate('txt_robot_siri'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_siri'); ?> :: 
                <?php echo $this->translate('txt_robot_siri'); ?>
            </h1>
        </div>
        <div class="col-sm-12 col-xs-12" >
            <p>
                <?php echo $this->translate('txt_about_siri'); ?>
            </p>
            <div class="list-option-siri" >
                <a href="<?php echo $this->url('cms/siri', array('action' => 'fix-image')) ?>" class="btn btn-primary btn-sm" >
                    <?php echo $this->translate('txt_fix_images'); ?>
                </a>
            </div>
        </div>
    </div>
</section>