<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Banner size :: Sửa
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/BannerSize') ?>">Banner size</a></li>
        <li class="active">Sửa</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/BannerSize', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('id', 'form-banner-size');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <button class="btn btn-primary">Lưu lại</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="position_name">size name</label>
                        <?php echo $this->formRow($form->get('size')); ?>
                    </div>
                    <div class="form-group">
                        <label for="position_alias">width</label>
                        <?php echo $this->formRow($form->get('width')); ?>
                    </div>
                    <div class="form-group">
                        <label for="position_alias">height</label>
                        <?php echo $this->formRow($form->get('height')); ?>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <button class="btn btn-primary">Lưu lại</button>
                <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    </div>
</section>
