<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Banner size  :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Banner size</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/BannerSize') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/BannerSize', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm Banner size mới</a>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="50" style="text-align: center">ID</th>
                                <th style="width:200px">size name</th>
                                <th>width</th>
                                <th>height</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($sizes as $size) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $size['id'] ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/BannerSize', array('action' => 'edit', 'id' => $size['id'])) ?>"><?php echo $size['size'] ?></a>
                                    </td>
                                    <td>
                                        <?php echo $size['width'] ?>
                                    </td>
                                    <td>
                                        <?php echo $size['height'] ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="50" style="text-align: center">ID</th>
                                <th style="width:200px">size name</th>
                                <th>width</th>
                                <th>height</th>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/BannerSize', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm Banner size mới</a>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->