<?php
$list_bcum = $this->Categories()->getAllParentsOfCategory($this->Products()->getCategoriesId($product), true);
$productsNew = $this->Products()->getNewProduct(0,9);
$productsHot = $this->Products()->getHotProduct(0,9);
$productsBestseller = $this->Products()->getProductBestseller(0, 8);
$productsSale = $this->Products()->getSaleProduct(0, 9);
$productsBuyMost = $this->Products()->getProductBuyMost(0, 9);
$item_cum = array();
?>
<div class="wrap-breadcrumbs" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/category" title="<?php echo $this->translate('txt_tat_ca_san_pham'); ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_tat_ca_san_pham'); ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="2" />
                    </li>
                    <?php 
					$pbc = 2;
					if(!empty($list_bcum)){ 
                        for($i = count($list_bcum)-1;$i>=0;$i-- ){
                            $item_cum = $list_bcum[$i];
                            $pbc ++;
                    ?>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Categories()->getCategoriesUrl($item_cum); ?>" title="<?php echo $this->Categories()->getTitle($item_cum); ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->Categories()->getTitle($item_cum); ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="<?php echo $pbc ?>" />
                    </li>
                    <?php }
                    } ?>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <span itemprop="item name" >
                            <?php echo $this->Products()->getTitle($product); ?>
                        </span>
                        <meta itemprop="position" content="<?php echo ($pbc+1) ?>" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="clearfix" >
    <div class="detail-product clearfix" data-controller="product" data-id="<?php echo $this->Products()->getProductsId($product) ?>" >
        <div class="top-detail clearfix" >
            <div class="container">
                <div class="row" >
                    <div class="col-sm-10 col-sm-offset-1" >
                        <div class="row" >
                            <?php $images = $this->Images()->getImages($this->Products()->getProductsId($product)); 
                                if ( !empty($images) ){ ?>
                            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                <div class="slider-detail clearfix" >
                                    <div class="main-slider-detail" >
                                        <div class="box-image-featured pd5" >
                                            <img class="product-image-feature" src="<?php echo $this->Images()->getUrlImage($images[0]['images'], 470); ?>" alt="<?php echo $this->Products()->getTitle($product); ?>" >
                                            <div class="lazy-load-ball lazy-product-featured">
                                                <div class="uil-ring-css">
                                                    <div></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="thumb-slider-detail" id="sliderproduct" >
                                        <div class="owl-carousel owl-theme slideshow" data-neo="owlCarousel" data-own-name="owlDetailSlider" data-wow-delay="0.2s" data-dots="true" data-loop="false" data-nav = "true" data-margin = "10" data-autoplayTimeout="1000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-navTextLeft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navTextRight='<i class="fa fa-chevron-right" aria-hidden="true"></i>' data-responsive='{"0":{"items":2}, "678":{"items":2}, "1000":{"items":4}}' >
                                            <?php foreach ($images as $image){ ?>
                                            <div class="img-item-thumb" >
                                                <a href="javascript:void(0);" title="<?php echo $this->Products()->getTitle($product); ?>" data-image="<?php echo $this->Images()->getUrlImage($image['images'], 470); ?>" >
                                                    <img src="<?php echo $this->Images()->getUrlImage($image['images'], 100); ?>" alt="<?php echo $this->Products()->getName($product) ?>" itemprop="image" class="img-fluid" />
                                                </a>
                                            </div>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>
                            
                            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12" >
                                <div class="details-product clearfix" >
                                    <meta itemscope itemprop="mainEntityOfPage" itemType="https://schema.org/WebPage" itemid="<?php echo $this->Products()->getLink($product) ?>" />
                                    <meta itemprop="productID" content="<?php echo $this->Products()->getProductsId($product); ?>" />

                                    <?php if( !empty($this->Products()->getCode($product)) ){ ?>
                                    <div class="product-code" >
                                        <?php echo $this->translate('txt_ma_san_pham'); ?> : 
                                        <?php echo $this->Products()->getCode($product) ?>
                                    </div>
                                    <?php } ?>

                                    <h1 class="product-name" itemprop="name" >
                                        <?php echo $this->Products()->getTitle($product) ?>
                                    </h1>

                                    <div class="rating-product" >
                                        <?php if( $this->Products()->getIsAvailable($product) ){ ?>
                                            <?php echo $this->Products()->getQuantity($product) ?> in stock |
                                        <?php } ?>

                                        <?php $rating = $this->Products()->getRating($product) ?>
                                        <span class="star-product" >
                                            <?php for( $i=0; $i<$rating; $i++){ ?>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <?php } ?>

                                            <?php if( $rating != floor($rating) ){ ?>
                                            <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                            <?php } ?>

                                            <?php for( $i=$rating; $i<5; $i++){ ?>
                                            <i class="fa fa-star-o" aria-hidden="true"></i>
                                            <?php } ?>
                                        </span>
                                        1 <?php echo $this->translate('txt_review'); ?>
                                    </div>

                                    <div class="form-product clearfix">
                                        <form enctype="multipart/form-data" id="add-to-cart-form" action="/cart/addToCart" method="post" class="form-inline" data-form="addToCart" >
                                            <input type="hidden" value="<?php echo $this->Products()->getProductsId($product) ?>" name="products_id" data-input="products_id" >

                                            <div class="types-product clearfix" >
                                                <div class="row" >
                                                    <?php
                                                    $promotion = $this->Products()->getPromotion($product); 
                                                    if( $this->Products()->IsAvailablePrice($product) ){
                                                        $price = $this->Products()->getPrice($product);
                                                        $price_sale = $this->Products()->getPriceSale($product);
                                                    ?>
                                                        <?php if( !empty($types) ){ ?>
                                                        <div class="col-sm-7" >
                                                            <?php foreach ($types as $key => $type) { ?>
                                                            <label class="itype-product" >
                                                                <input type="radio" name="product_type" data-input="product_type" data-products_id="<?php echo $this->Products()->getProductsId($product) ?>" data-model="type" value="<?php echo $type['products_type_id'] ?>" <?php echo $type['products_type_id'] == $this->Products()->getProductTypeId($product) ? 'checked' : ''; ?> data-images='[{"image":"<?php echo $this->Images()->getUrlImage($type['thumb_image'], 471); ?>", "thumb":"<?php echo $this->Images()->getUrlImage($type['thumb_image'], 150); ?>"}]' >
                                                                <?php echo $type['type_name'] ?> 
                                                                <?php echo $this->Currency()->fomatCurrency($type['price_sale']) ?>
                                                            </label>
                                                            <?php } ?>
                                                        </div>
                                                        <?php }else{ ?>
                                                        <div class="col-sm-7" >
                                                            <label class="itype-product" >
                                                                <input type="radio" checked="checked" >
                                                                <?php echo $this->Currency()->fomatCurrency($price_sale) ?>
                                                            </label>
                                                        </div>
                                                        <?php } ?>
                                                    <?php }else{ ?>
                                                        <div class="col-sm-7" >
                                                            <label class="itype-product" >
                                                                <span class="neo-value-price-update" itemprop="price" content="<?php echo $this->Products()->stringWhenNotAvailablePrice(); ?>" >
                                                                    <?php echo $this->Products()->stringWhenNotAvailablePrice(); ?>
                                                                </span>
                                                            </label>
                                                        </div>
                                                    <?php } ?>

                                                    <div class="col-sm-5 text-md-right text-xs-center" >
                                                        <?php if ( !empty($promotion) ){ ?>
                                                        <div class="sale-flash sale-flash-sm">
                                                            <?php echo $promotion ?>
                                                        </div>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </div>

                                            <?php if( !empty($extensions) ){ ?>
                                            <div class="coz-list-extensions" >
                                                <h2 class="title-h2-extensions" >
                                                    <?php echo $this->translate('txt_danh_sach_san_pham_dinh_kem'); ?>
                                                </h2>
                                                <div class="coz-extensions" >
                                                    <div class="owl-carousel owl-theme coz-owl-nav" data-neo="owlCarousel" data-own-name="owlProductThumb" data-dots="false" data-loop="false" data-nav = "true" data-margin = "0" data-autoplayTimeout="5000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"678":{"items":2}}'  data-navtextleft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navtextright='<i class="fa fa-chevron-right" aria-hidden="true"></i>' >
                                                        <?php foreach ($extensions as $index => $extension) { ?>
                                                        <div class="coz-item-ex" >
                                                            <div class="clearfix" >
                                                                <div class="coz-extensions-img" >
                                                                    <img src="<?php echo $this->Images()->getUrlImage($this->Extension()->getImage($extension), 50, 50); ?>" >
                                                                </div>
                                                                <div class="coz-extensions-text">
                                                                    <div class="coz-extensions-title">
                                                                        <?php echo $this->Extension()->getName($extension); ?>
                                                                    </div>
                                                                    <div class="coz-extensions-message">
                                                                        <div class="coz-extensions-price"  >
                                                                            <?php echo $this->Currency()->fomatCurrency($this->Extension()->getPrice($extension)); ?>
                                                                        </div>
                                                                        <?php if($this->Extension()->getIsAlways($extension)){ ?>
                                                                        <div class="coz-extensions-status" >
                                                                            <i class="fa fa-check" aria-hidden="true"></i> <?php echo $this->translate('txt_luon_dinh_kem_san_pham'); ?>
                                                                        </div>
                                                                        <?php }else{ ?>
                                                                        <div class="coz-extensions-status" >
                                                                            <div class="clearfix" data-place="noExtension" data-products_id="<?php echo $this->Products()->getProductsId($product) ?>" data-id="<?php echo $this->Extension()->getId($extension); ?>" >
                                                                                <i class="fa fa-plus" aria-hidden="true"></i>
                                                                                <a href="javascript:void(0);" data-btn="appExtension" data-products_id="<?php echo $this->Products()->getProductsId($product) ?>" data-id="<?php echo $this->Extension()->getId($extension); ?>" rel="nofollow" >
                                                                                    <?php echo $this->translate('txt_dinh_kem_san_pham'); ?>
                                                                                </a>
                                                                            </div>
                                                                            <div class="clearfix" data-place="hasExtension" data-products_id="<?php echo $this->Products()->getProductsId($product) ?>" data-id="<?php echo $this->Extension()->getId($extension); ?>" style="display: none" >
                                                                                <i class="fa fa-minus" aria-hidden="true"></i>
                                                                                <a href="javascript:void(0);" data-btn="cancelExtension" data-products_id="<?php echo $this->Products()->getProductsId($product) ?>" data-id="<?php echo $this->Extension()->getId($extension); ?>" >
                                                                                    <?php echo $this->translate('txt_bo_dinh_kem_san_pham'); ?>
                                                                                </a>
                                                                            </div>
                                                                        </div>
                                                                        <input type="checkbox" style="display: none" data-products_id="<?php echo $this->Products()->getProductsId($product) ?>" data-extention_id = "<?php echo $this->Extension()->getId($extension); ?>" value="<?php echo $this->Extension()->getId($extension); ?>" class="extention-<?php echo $this->Extension()->getId($extension); ?>" name="extention[]" data-input="extention"  data-model="extention" >
                                                                        <?php } ?>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <?php } ?>

                                            <div class="product-description product_description" >
                                                <div class="mini-product-description clearfix" >
                                                    <?php echo $this->Html()->TruncateHTML($this->Products()->getProductsDescription($product))->truncateWords(30); ?>
                                                </div>
                                                <div class="full-product-description clearfix" style="display: none;" itemprop="description" >
                                                    <?php echo $this->Products()->getProductsDescription($product) ?>
                                                </div>
                                                <div class="text-xs-right" >
                                                    <a href="javascript:void(0);" class="btn-toggle-product-description btn-more-product-description" >
                                                        <?php echo $this->translate('txt_xem_them_description') ?>
                                                        <i class="fa fa-angle-down" aria-hidden="true"></i>
                                                    </a>
                                                    <a href="javascript:void(0);" class="btn-toggle-product-description btn-mini-product-description" style="display: none;" >
                                                        <?php echo $this->translate('txt_thu_ngan_description') ?>
                                                        <i class="fa fa-angle-up" aria-hidden="true"></i>
                                                    </a>
                                                </div>
                                            </div>

                                            <?php if ( $this->Products()->getToBuy($product) ){ ?>
                                            <div class="grid-boot-sm" >
                                                <div class="row" >
                                                    <div class="col-sm-3 col-sm-offset-0 col-xs-8 col-xs-offset-2" >
                                                        <div class="plugin-quantity" data-plugin="quantity" >
                                                            <span class="quantity-down" data-btn="downQuantity" >
                                                                <i class="fa fa-minus" aria-hidden="true"></i>
                                                            </span>
                                                            <input type="number" class="input-product-quantity" value="1" maxlength="12" name="quantity" data-role="neojq" data-ntype="quantity" data-input="quantity" data-model="quantity" data-products_id="<?php echo $this->Products()->getProductsId($product) ?>" >
                                                            <span class="quantity-up" data-btn="upQuantity" >
                                                                <i class="fa fa-plus" aria-hidden="true"></i>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-9 col-xs-12" >
                                                        <div class="row" >
                                                            <div class="col-xs-6" >
                                                                <button type="submit" class="btn btn-block btn-add-cart" title="<?php echo $this->translate('txt_mua_ngay') ?>" >
                                                                    <span>
                                                                        <?php echo $this->translate('txt_mua_ngay') ?>
                                                                    </span>
                                                                </button>
                                                            </div>
                                                            <div class="col-xs-6" >
                                                                <a href="<?php echo $this->Products()->getAddToCartProductsUrl($product) ?>" class="btn btn-add-cart btn-block" data-neo="ajax" data-role="form" >
                                                                    <?php echo $this->translate('txt_add_to_cart') ?>
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <?php }else{ ?>
                                            <div class="product-action" >
                                                <a href="<?php echo $this->Products()->getBuyProductsByEmailUrl($product) ?>" class="btn btn-add-cart" data-neo="popup" rel="nofollow" >
                                                    <span>
                                                        <?php echo $this->translate('txt_register_email') ?>
                                                    </span>
                                                </a>
                                            </div>
                                            <?php } ?>

                                            <div class="shipping-rule" >
                                                <h3 class="title-shipping-rule" >
                                                    <?php echo $this->translate('txt_free_shipping_on_all_orders') ?>
                                                </h3>
                                                <div class="list-shipping-rule" >
                                                    <span class="item-shipping-rule" >
                                                        <i class="fa fa-check" aria-hidden="true"></i>
                                                        <?php echo $this->translate('txt_ships_next_business_day') ?>    
                                                    </span>
                                                    <span class="item-shipping-rule" >
                                                        <i class="fa fa-check" aria-hidden="true"></i>
                                                        <?php echo $this->translate('txt_100_satisfaction_guaranteed') ?>
                                                    </span>
                                                    <span class="item-shipping-rule" >
                                                        <i class="fa fa-check" aria-hidden="true"></i>
                                                        <?php echo $this->translate('txt_lifetime_warranty') ?>
                                                    </span>
                                                </div>
                                            </div>

                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix product-arside" >
            <div class="container">
                <div class="row" >
                    <div class="col-sm-10 col-sm-offset-1" >
                        <div class="product-contact-link" >
                            <?php echo $this->translate('txt_have_a_questions_click_here') ?>
                        </div>
                        <div class="product-social-link" >
                            <?php echo $this->translate('txt_share_with_your_friends') ?>
                            <a href="<?php echo $this->Products()->getLinkShareFacebook($product) ?>" title="" rel="nofollow" class="link-social" data-btn="share" data-network="facebook" itemprop="sameAs" target="_blank">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                            <a href="<?php echo $this->Products()->getLinkShareTwitter($product) ?>" title="" rel="nofollow" class="link-social" data-btn="share" data-network="twitter" itemprop="sameAs" target="_blank">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                            <a href="<?php echo $this->Products()->getLinkShareGoogle($product) ?>" title=""  class="link-social" data-btn="share" data-network="google" itemprop='sameAs' target='_blank' >
                                <i class="fa fa-google-plus" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="clearfix" >
            <div class="hidden-sm-down" >
                <div class="container">
                    <div class="row" >
                        <div class="col-sm-10 col-sm-offset-1" >
                            <ul class="nav nav-inline nav-tab-detail clearfix row" role="tablist">
                                <?php 
                                $active = '';
                                $num = 1;
                                if( !empty($this->Products()->getProductsMore($product)) ){
                                    $active = 'products_more';
                                    $num += 1;
                                }
                                if( !empty($this->Products()->getProductsLongdescription($product)) ){
                                    if(empty($active)){
                                        $active = 'products_longdescription';
                                    }
                                    $num += 1;
                                }
                                if( !empty($this->Products()->getYoutubeVideo($product)) ){ 
                                    if(empty($active)){
                                        $active = 'youtube_video';
                                    }
                                    $num += 1;
                                }
                                if( !empty($this->Products()->getProductsMore($product)) ){
                                ?>
                                <li class="nav-item col-sm-<?php echo 12/$num ?>" >
                                    <a class="nav-link active" data-toggle="tab" href="#products_more" role="tab" rel="nofollow" >
                                        <?php echo $this->translate('thong_tin_san_pham') ?>
                                    </a>
                                </li>
                                <?php } ?> 

                                <?php if( !empty($this->Products()->getProductsLongdescription($product)) ){ ?>
                                <li class="nav-item col-sm-<?php echo 12/$num ?>" >
                                    <a class="nav-link <?php echo $active == 'products_longdescription' ? 'active' : '' ?>" data-toggle="tab" href="#products_longdescription" role="tab" rel="nofollow" >
                                        <?php echo $this->translate('cau_hinh_chi_tiet') ?>
                                    </a>
                                </li>
                                <?php } ?>

                                <?php if( !empty($this->Products()->getYoutubeVideo($product)) ){ ?>
                                <li class="nav-item col-sm-<?php echo 12/$num ?>" >
                                    <a class="nav-link <?php echo $active == 'youtube_video' ? 'active' : '' ?>" data-toggle="tab" href="#youtube_video" role="tab" rel="nofollow" >
                                        <?php echo $this->translate('xem_video') ?>
                                    </a>
                                </li>
                                <?php } ?>

                                <li class="nav-item col-sm-<?php echo 12/$num ?>" >
                                    <a class="nav-link <?php echo $active == '' ? 'active' : '' ?>" data-toggle="tab" href="#comment" role="tab" rel="nofollow" >
                                        <?php echo $this->translate('txt_comment_fb') ?>
                                    </a>
                                </li>
                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="tab-content tab-content-detail clearfix" >

                <?php if( !empty($this->Products()->getProductsMore($product)) ){ ?>
                <div class="tab-pane fade in <?php echo $active == 'products_more' ? 'active' : '' ?>" id="products_more" role="tabpanel" itemprop="review" itemscope itemtype="http://schema.org/Review" >
                    <div class="container" itemprop="description" >
                        <div class="hidden-md-up" >
                            <ul class="nav nav-inline nav-tab-detail nav-tab-detail-mm" >
                                <li class="nav-item" >
                                    <a class="nav-link text-xs-center" href="#products_more" >
                                        <?php echo $this->translate('thong_tin_san_pham') ?>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="row" >
                            <div class="col-sm-10 col-sm-offset-1" >
                                <div class="tab-pane-mm clearfix" >
                                    <?php echo $this->Products()->getProductsMore($product) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>

                <?php if(!empty($this->Products()->getProductsLongdescription($product))){ ?>
                <div class="tab-pane fade in <?php echo $active == 'products_longdescription' ? 'active' : '' ?>" id="products_longdescription" role="tabpanel" itemprop="review" itemscope itemtype="http://schema.org/Review" >
                    <div class="container" itemprop="description" >
                        <div class="hidden-md-up" >
                            <ul class="nav nav-inline nav-tab-detail nav-tab-detail-mm" >
                                <li class="nav-item" >
                                    <a class="nav-link text-xs-center" href="#products_longdescription" >
                                        <?php echo $this->translate('cau_hinh_chi_tiet') ?>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="row" >
                            <div class="col-sm-10 col-sm-offset-1" >
                                <div class="tab-pane-mm clearfix" >
                                    <?php echo $this->Products()->getProductsLongdescription($product) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>

                <?php if( !empty($this->Products()->getYoutubeVideo($product)) ){ ?>
                <div class="tab-pane fade in <?php echo $active == 'youtube_video' ? 'active' : '' ?>" id="youtube_video" role="tabpanel" itemprop="review" itemscope itemtype="http://schema.org/Review" >
                    <div class="container" itemprop="video" itemscope itemtype="http://schema.org/VideoObject" >
                        <div class="hidden-md-up" >
                            <ul class="nav nav-inline nav-tab-detail nav-tab-detail-mm" >
                                <li class="nav-item" >
                                    <a class="nav-link text-xs-center" href="#youtube_video" >
                                        <?php echo $this->translate('xem_video') ?>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="row" >
                            <div class="col-sm-10 col-sm-offset-1" >
                                <div class="tab-pane-mm clearfix" >
                                    <link itemprop="url" href="//www.youtube.com/embed/<?php echo $this->Products()->getYoutubeVideo($product) ?>?autoplay=0" >
                                    <iframe class="mfp-iframe iframe-video" src="//www.youtube.com/embed/<?php echo $this->Products()->getYoutubeVideo($product) ?>?autoplay=0" frameborder="0" allowfullscreen ></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>

                <div class="tab-pane fade in <?php echo $active == '' ? 'active' : '' ?>" id="comment" role="tabpanel" >
                    <div class="container" >
                        <div class="hidden-md-up" >
                            <ul class="nav nav-inline nav-tab-detail nav-tab-detail-mm" >
                                <li class="nav-item" >
                                    <a class="nav-link text-xs-center" href="#comment" >
                                        <?php echo $this->translate('txt_comment_fb') ?>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="row" >
                            <div class="col-sm-10 col-sm-offset-1" >
                                <div class="tab-pane-mm clearfix" >
                                    <form class="form-horizontal form-comment" data-form="commentProduct" >
                                        <input type="hidden" name="id" value="<?php echo $this->Products()->getProductsId($product); ?>" >

                                        <div class="form-group" >
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <label>
                                                        <?php echo $this->translate('txt_title_comment'); ?>
                                                    </label>
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text" value="" class="form-control title" name="title" id="title"  placeholder="<?php echo $this->translate('txt_title_comment'); ?>" data-input="title" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group" >
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <label>
                                                        <?php echo $this->translate('txt_email_comment'); ?>
                                                    </label>
                                                </div>
                                                <div class="col-md-6">
                                                    <input type="text" value="" class="form-control title" name="email" id="email"  placeholder="<?php echo $this->translate('txt_email_comment'); ?>" data-input="email" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group" >
                                            <label>
                                                <?php echo $this->translate('txt_noidung_comment'); ?>
                                            </label>
                                            <textarea name="noidung" class="form-control" placeholder="<?php echo $this->translate('txt_noidung_comment'); ?>" data-input="noidung" ></textarea>
                                        </div>

                                        <div class="form-group" >
                                            <button type="button" class="btn btn-style-b" data-btn="commentProduct" >
                                                <?php echo $this->translate('txt_btn_send_comment'); ?>
                                            </button>
                                        </div>

                                    </form>

                                    <?php
                                    $totalFaq = $this->Products()->getTotalFqaProduct($this->Products()->getProductsId($product));
                                    if( !empty($totalFaq) ){
                                        $faqs = $this->Products()->getFqaProduct($this->Products()->getProductsId($product), 0, 5);
                                    ?>
                                    <h3 class="tlt-comment" >
                                        <?php echo $this->translate('txt_list_faq_product') ?>
                                    </h3>
                                    <div class="list-faq clearfix" >
                                        <?php foreach ($faqs as $key => $faq) {
                                            $faqcs = array();
                                            if( !empty($faq['total_child']) ){
                                                $faqcs = $this->Products()->getFqaChild($this->Faq()->getId($faq), 0, 5);
                                            }
                                        ?>
                                        <div class="item-faq clearfix" data-place="listComment" data-id="0" >
                                            <div class="ava-comment" >
                                                <a href="javascript:void(0);" title="" rel="nofollow" >
                                                    <img src="<?php echo $this->Images()->getUrlImage($this->Faq()->getAvatar($faq), 60, 60); ?>" class="img-fluid" >
                                                </a>
                                            </div>
                                            <div class="nava-comment" >
                                                <div class="mana-comment" >
                                                    <div class="tie-comment" >
                                                        <?php echo $this->Faq()->getTitle($faq); ?>
                                                    </div>
                                                    <div class="mcom-comment" >
                                                        <?php echo $this->Faq()->getContent($faq); ?>
                                                    </div>
                                                </div>
                                                <?php if( !empty($faqcs) ){ ?>
                                                <div class="list-faq clearfix" data-place="listComment" data-id="<?php echo $this->Faq()->getId($faq); ?>" >
                                                    <?php foreach ($faqcs as $key => $faqc) { ?>
                                                    <div class="item-faq clearfix" >
                                                        <div class="ava-comment" >
                                                            <a href="" title="" rel="nofollow" >
                                                                <img src="<?php echo $this->Images()->getUrlImage($this->Faq()->getAvatar($faqc), 60, 60); ?>" class="img-fluid" >
                                                            </a>
                                                        </div>
                                                        <div class="nava-comment" >
                                                            <div class="mana-comment" >
                                                                <div class="tie-comment" >
                                                                    <?php echo $this->Faq()->getTitle($faqc); ?>
                                                                </div>
                                                                <div class="mcom-comment" >
                                                                    <?php echo $this->Faq()->getContent($faqc); ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <?php } ?>
                                                </div>

                                                <?php if( $faq['total_child'] > 5 ){ ?>
                                                <div class="text-xs-center" >
                                                    <a href="javascript:void(0);" class="btn-more-comment" data-bnt="moreComment" data-id="<?php echo $this->Faq()->getId($faq); ?>"  data-page="1" data-size="5" >
                                                        <?php echo $this->translate('txt_view_more_comment') ?>
                                                    </a>
                                                </div>
                                                <?php } ?>

                                                <?php } ?>
                                            </div>
                                        </div>
                                        <?php } ?>
                                    </div>

                                    <?php if( $totalFaq > 5 ){ ?>
                                    <div class="text-xs-center" >
                                        <a href="javascript:void(0);" class="btn-more-comment" data-bnt="moreComment" data-id="0" data-page="1" data-size="5" >
                                            <?php echo $this->translate('txt_view_more_comment') ?>
                                        </a>
                                    </div>
                                    <?php } ?>

                                    <?php } ?>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

    <div class="clearfix" >
        <div class="container">
            <div class="row" >
                <div class="col-sm-10 col-sm-offset-1" >
                    <?php 
        			$limit = 8;
        			$price_volatility = 20000000;// gia bien dong trong khoang 20tr
        			$price_min = $product->price_sale - $price_volatility > 0 ? $product->price_sale - $price_volatility : 0;
        			$price_max = $product->price_sale + $price_volatility;
        			$product_near_price = $this->Products()->getProductNearPrice($product->categories_id, $product->products_id, $product->price_sale, $price_min, $price_max, 0, 8);
        			if(!empty($product_near_price)) { ?>
                    <div class="group-product" >
                        <div class="group-heading clearfix" >
                            <h2 itemprop="name" class="title-box  pull-xs-left" >
                                <?php echo $this->translate('txt_near_price_this_product') ?>
                            </h2>
                        </div>
                        <div class="group-body" >
                            <div class="content-sec owl-carousel owl-theme coz-owl-nav" data-neo="owlCarousel" data-own-name="owlProductNearPrice" data-margin="0" data-dots="false" data-loop="false" data-nav = "true" data-margin = "0" data-autoplayTimeout="1000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-navTextLeft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navTextRight='<i class="fa fa-chevron-right" aria-hidden="true"></i>' data-responsive='{"0":{"items":1}, "678":{"items":2}, "992":{"items":3}, "1000":{"items":4}}' >
                            
                                <?php foreach ($product_near_price as $key => $p) { ?>                
                                <div class="item" >
                                    <?php   echo $this->partial('app/item-product', array('product' => $p, 'index' => $key , 'notSchema' => TRUE) ); ?>
                                </div>
                                <?php } ?>

                            </div>
                        </div>
                    </div>
                    <?php } ?>

                    <?php 
        			$product_recommends = $this->Products()->getRecommendProductById($product->products_id, 0, 8);
        			if(!empty($product_recommends)) { ?>
                    <div class="group-product" >
                        <div class="group-heading clearfix" >
                            <h2 itemprop="name" class="title-box  pull-xs-left" >
                                <?php echo $this->translate('txt_product_recommends') ?>
                            </h2>
                        </div>
                        <div class="group-body" >
                            <div class="content-sec owl-carousel owl-theme coz-owl-nav" data-neo="owlCarousel" data-own-name="owlProductRecommends" data-margin="0" data-dots="false" data-loop="false" data-nav = "true" data-margin = "0" data-autoplayTimeout="1000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-navTextLeft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navTextRight='<i class="fa fa-chevron-right" aria-hidden="true"></i>' data-responsive='{"0":{"items":1}, "678":{"items":2}, "992":{"items":3}, "1000":{"items":4}}' >
                            
                                <?php foreach ($product_recommends as $key => $p) { ?>                
                                <div class="item" >
                                    <?php   echo $this->partial('app/item-product', array('product' => $p, 'index' => $key , 'notSchema' => TRUE) ); ?>
                                </div>
                                <?php } ?>

                            </div>
                        </div>
                    </div>
                    <?php } ?>

                    <?php if(!empty($productsHot)) { ?>
                    <div class="group-product" >
                        <div class="group-heading clearfix" >
                            <h2 itemprop="name" class="title-box  pull-xs-left" >
                                <?php echo $this->translate('txt_san_pham_hot') ?>
                            </h2>
                        </div>
                        <div class="group-body" >
                            <div class="content-sec owl-carousel owl-theme coz-owl-nav" data-neo="owlCarousel" data-own-name="owlProductHot" data-margin="0" data-dots="false" data-loop="false" data-nav = "true" data-margin = "0" data-autoplayTimeout="1000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-navTextLeft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navTextRight='<i class="fa fa-chevron-right" aria-hidden="true"></i>' data-responsive='{"0":{"items":1}, "678":{"items":2}, "992":{"items":3}, "1000":{"items":4}}' >
                            
                                <?php foreach ($productsHot as $key => $p) { ?>                
                                <div class="item" >
                                    <?php   echo $this->partial('app/item-product', array('product' => $p, 'index' => $key , 'notSchema' => TRUE) ); ?>
                                </div>
                                <?php } ?>

                            </div>
                        </div>
                    </div>
                    <?php } ?>

                    <?php if(!empty($productsNew)) { ?>
                    <div class="group-product" >
                        <div class="group-heading clearfix" >
                            <h2 itemprop="name" class="title-box  pull-xs-left" >
                                <?php echo $this->translate('txt_san_pham_moi') ?>
                            </h2>
                        </div>
                        <div class="group-body" >
                            <div class="content-sec owl-carousel owl-theme coz-owl-nav" data-neo="owlCarousel" data-own-name="owlProductHot" data-margin="0" data-dots="false" data-loop="false" data-nav = "true" data-margin = "0" data-autoplayTimeout="1000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-navTextLeft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navTextRight='<i class="fa fa-chevron-right" aria-hidden="true"></i>' data-responsive='{"0":{"items":1}, "678":{"items":2}, "992":{"items":3}, "1000":{"items":4}}' >
                            
                                <?php foreach ($productsNew as $key => $p) { ?>                
                                <div class="item" >
                                    <?php   echo $this->partial('app/item-product', array('product' => $p, 'index' => $key , 'notSchema' => TRUE) ); ?>
                                </div>
                                <?php } ?>

                            </div>
                        </div>
                    </div>
                    <?php } ?>

                    <?php if(!empty($productsSale)) { ?>
                    <div class="group-product" >
                        <div class="group-heading clearfix" >
                            <h2 itemprop="name" class="title-box  pull-xs-left" >
                                <?php echo $this->translate('txt_san_pham_giam_gia') ?>
                            </h2>
                        </div>
                        <div class="group-body" >
                            <div class="content-sec owl-carousel owl-theme coz-owl-nav" data-neo="owlCarousel" data-own-name="owlProductSale" data-margin="0" data-dots="false" data-loop="false" data-nav = "true" data-margin = "0" data-autoplayTimeout="1000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-navTextLeft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navTextRight='<i class="fa fa-chevron-right" aria-hidden="true"></i>' data-responsive='{"0":{"items":1}, "678":{"items":2}, "992":{"items":3}, "1000":{"items":4}}' >
                            
                                <?php foreach ($productsSale as $key => $p) { ?>                
                                <div class="item" >
                                    <?php   echo $this->partial('app/item-product', array('product' => $p, 'index' => $key , 'notSchema' => TRUE) ); ?>
                                </div>
                                <?php } ?>

                            </div>
                        </div>
                    </div>
                    <?php } ?>

                    <?php if(!empty($productsBuyMost)) { ?>
                    <div class="group-product" >
                        <div class="group-heading clearfix" >
                            <h2 itemprop="name" class="title-box  pull-xs-left" >
                                <?php echo $this->translate('txt_san_pham_mua_nhieu') ?>
                            </h2>
                        </div>
                        <div class="group-body" >
                            <div class="content-sec owl-carousel owl-theme coz-owl-nav" data-neo="owlCarousel" data-own-name="owlProductBuyMost" data-margin="0" data-dots="false" data-loop="false" data-nav = "true" data-margin = "0" data-autoplayTimeout="1000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-navTextLeft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navTextRight='<i class="fa fa-chevron-right" aria-hidden="true"></i>' data-responsive='{"0":{"items":1}, "678":{"items":2}, "992":{"items":3}, "1000":{"items":4}}' >
                            
                                <?php foreach ($productsBuyMost as $key => $p) { ?>                
                                <div class="item" >
                                    <?php   echo $this->partial('app/item-product', array('product' => $p, 'index' => $key , 'notSchema' => TRUE) ); ?>
                                </div>
                                <?php } ?>

                            </div>
                        </div>
                    </div>
                    <?php } ?>

                    <?php if(!empty($productsBestseller)) { ?>
                    <div class="group-product" >
                        <div class="group-heading clearfix" >
                            <h2 itemprop="name" class="title-box  pull-xs-left" >
                                <?php echo $this->translate('txt_san_pham_ban_chay') ?>
                            </h2>
                        </div>
                        <div class="group-body" >
                            <div class="content-sec owl-carousel owl-theme coz-owl-nav" data-neo="owlCarousel" data-own-name="owlProductBestseller" data-margin="0" data-dots="false" data-loop="false" data-nav = "true" data-margin = "0" data-autoplayTimeout="1000" data-autoPlay="5000" data-autoplayHoverPause = "true" data-navTextLeft='<i class="fa fa-chevron-left" aria-hidden="true"></i>' data-navTextRight='<i class="fa fa-chevron-right" aria-hidden="true"></i>' data-responsive='{"0":{"items":1}, "678":{"items":2}, "992":{"items":3}, "1000":{"items":4}}' >
                            
                                <?php foreach ($productsBestseller as $key => $p) { ?>                
                                <div class="item" >
                                    <?php   echo $this->partial('app/item-product', array('product' => $p, 'index' => $key , 'notSchema' => TRUE) ); ?>
                                </div>
                                <?php } ?>

                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->partial('app/case-upgrate', array() ); ?>

<?php echo $this->partial('app/case-feature', array() ); ?>

<?php echo $this->partial('app/case-supplier', array() ); ?>