<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>" >
                        <i class="fa fa-dashboard"></i> 
                        Trang chủ
                    </a>
                </li>
                <li class="active">
                    Đặc tính <i><?php echo !empty($feature) ? $feature->feature_title : '' ?></i>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Đặc tính :: Quản lý
                <i><?php echo !empty($feature) ? $feature->feature_title : '' ?></i>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/feature', array('action' => 'index')) ?>" method="get" role="form" data-form="searchAjax" >
                <div class="coz-search-bar clearfix" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="Search..." value="<?php echo $q ?>" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo tên
                                    </option>
                                    <option value="1" <?php echo $type == 1 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo màu sắc
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/feature') ?>" method="post" class="clearfix" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-6" >
                    <?php if( !empty($feature) ){ ?>
                    <a href="<?php echo $this->url('cms/feature', array('action' => 'index', 'id' => $feature->parent_id)) ?>" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Quay về đặc tính trước" >
                        <i class="fa fa-caret-left" aria-hidden="true"></i>
                        Quay về đặc tính trước
                    </a>
                    <?php } ?>
                </div>
                <div class="col-sm-6" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/feature', array('action' => 'add', 'id' => $id)) ?>" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm đặc tính" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($features) ){ ?>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/feature', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="Hiện đặc tính" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/feature', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="Ẩn đặc tính" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/feature', array('action' => 'updateorder')) ?>')" data-toggle="tooltip" data-placement="top" title="Cập nhật thứ tự" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button" onclick="doSubmit(this.form, '<?php echo $this->url('cms/feature', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="Xoá đặc tính" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <?php if( !empty($features) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" >ID</th>
                        <th>Tên</th>
                        <th class="text-center col-lim" ></th>
                        <th class="col-lim" >Vị trí</th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($features as $row ) { ?>
                    <tr>
                        <td class="text-center col-lim" >
                            <?php echo $row['feature_id'] ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cms/feature', array('action' => 'index', 'id' => $row['feature_id'])) ?>" >
                                <?php echo $row['feature_title'] ?>
                            </a>
                        </td>
                        <td class="text-center col-lim" >
                            <a href="<?php echo $this->url('cms/feature', array('action' => 'index', 'id' => $row['feature_id'])) ?>">
                                <?php if( $this->Features()->isNormal($row) ){ ?>
                                <span class="ui-name-fearture" >
                                    <?php echo $this->Features()->getName($row) ?>
                                </span>
                                <?php }else if( $this->Features()->isColor($row) ){ ?>
                                <span class="ui-color-fearture" style="background: #<?php echo $this->Features()->getColor($row) ?>" >
                                    <span class="ui-icolor-fearture" >
                                        <?php echo $this->Features()->getColor($row) ?>
                                    </span>
                                </span>
                                <?php }else{ ?>
                                <span class="ui-pattern-fearture" style="background: url(<?php echo $this->Features()->getPattern($row) ?>) no-repeat center center;" >
                                    <span class="ui-ipattern-fearture" >
                                        <img src="<?php echo $this->Features()->getPattern($row) ?>" />
                                    </span>
                                </span>
                                <?php } ?>
                            </a>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $row['ordering'] ?>
                        </td>
                        <td class="col-lim" > 
                            <?php if( !empty($row['total_childrens_active']) ){ ?>   
                                <?php echo $row['number_childrens_active'] ?>/
                                <?php echo $row['total_childrens_active'] ?> active
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="text-right col-lim" >

                            <a href="<?php echo $this->url('cms/feature', array('action' => 'edit', 'id' => $row['feature_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa feature" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/feature', array('action' => 'delete', 'id' => $row['feature_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá feature"  data-confirm="Bạn có muốn xoá ?" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($row['is_published']) ){ ?>
                            <a href="<?php echo $this->url('cms/feature', array('action' => 'unpublish', 'id' => $row['feature_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn feature" >
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/feature', array('action' => 'publish', 'id' => $row['feature_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện feature" >
                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                            </a>
                            <?php } ?>
                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['feature_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có feature
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>