<?php if( !empty($_SESSION['CMSMEMBER']) ){ ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>
            <?php echo $this->translate('txt_administrator'); ?>
        </title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img_/favicon.ico'))
            ->appendStylesheet('//cdn.coz.vn/bootstrap/3.3.6/css/bootstrap.min.css')
            ->appendStylesheet('//cdn.coz.vn/font-awesome/4.7.0/css/font-awesome.min.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/ionicons.min.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/morris/morris.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/jvectormap/jquery-jvectormap-1.2.2.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/fullcalendar/fullcalendar.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/daterangepicker/daterangepicker-bs3.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/colorpicker/bootstrap-colorpicker.min.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/timepicker/bootstrap-timepicker.min.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/AdminLTE.css')
            ->appendStylesheet($this->basePath() . '/admincp/css/site.css')
            ->appendStylesheet($this->basePath() . '/admincp/select2/select2-bootstrap.css')
            ->appendStylesheet($this->basePath() . '/admincp/select2/select2.css')
            ->appendStylesheet($this->basePath() . '/admincp/js/plugins/tags-input/src/jquery.tagsinput.css')
            ->appendStylesheet($this->basePath() . '/admincp/js/plugins/tagEditor/jquery.tag-editor.css')
            ->appendStylesheet($this->basePath() . '/admincp/js/plugins/magnific-popup/dist/magnific-popup.css');
		?>
        <script src="http://maps.google.com/maps/api/js?key=AIzaSyAHa_nwcjR0pfJ6w0S0SGA7MG9jMzNm_K0" ></script>
		<script type="text/javascript">
            var baseUrl = '<?php echo $this->basePath() ?>';
            var cmsUrl = '<?php echo $this->basePath('cms'); ?>';
            var apiUrl = '<?php echo $this->basePath('api'); ?>';
            <?php if( !empty($_SESSION['assign']) ){ ?>
                var assign_ = <?php echo json_encode($_SESSION['assign']); ?>;
            <?php }else{ ?>
                var assign_ = null;
            <?php } ?>
        </script>
        <?php echo $this->headScript()
            ->prependFile('https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/admincp/js/jsmap.js')
            ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js')
            ->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js')
            ->appendFile('//cdn.coz.vn/bootstrap/3.3.6/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/admincp/select2/select2.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/input-mask/jquery.inputmask.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/input-mask/jquery.inputmask.date.extensions.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/input-mask/jquery.inputmask.extensions.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/input-mask/jquery.inputmask.numeric.extensions.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/daterangepicker/moment.min.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/daterangepicker/daterangepicker.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/timepicker/bootstrap-timepicker.min.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/colorpicker/bootstrap-colorpicker.min.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/datatables/jquery.dataTables.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/datatables/dataTables.bootstrap.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/ckeditor/ckeditor.js')
            ->appendFile($this->basePath() . '/admincp/js/accounting.js')
            ->appendFile($this->basePath() . '/admincp/js/AdminLTE/app.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/tags-input/src/jquery.tagsinput.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/tagEditor/jquery.caret.min.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/tagEditor/jquery.tag-editor.min.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/magnific-popup/dist/jquery.magnific-popup.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/jquery-html5-upload/jquery.html5_upload.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/html5-dropfile-upload/assets/js/jquery.filedrop.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/webcamjs/webcam.min.js')
            ->appendFile($this->basePath() . '/admincp/js/jquery.nicescroll.min.js')
            ->appendFile($this->basePath() . '/admincp/js/jquery.modal_upload.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')
            ->appendFile($this->basePath() . '/admincp/js/plugins/morris/morris.min.js')
            ->appendFile('//cdn.coz.vn/jquery-tmpl/jquery.tmpl.min.js')
            ->appendFile('//cdn.coz.vn/gmaps/gmaps.min.js')
            ->appendFile('//cdn.coz.vn/nicEdit/nicEdit.js')
            ->appendFile('//cdn.coz.vn/html5sortable/jquery.sortable.min.js'); ?>
    </head>
    <body class="skin-blue" <?php if(isset($_SERVER['REQUEST_URI']) && ($_SERVER['REQUEST_URI']=='/cms/branches/add' || strpos($_SERVER['REQUEST_URI'], '/cms/branches/edit')!==FALSE)){
		?>onunload="GUnload()"<?php }?> >

        <div class="wrapper row-offcanvas row-offcanvas-left" >
            <aside class="left-side sidebar-offcanvas">
                <section class="sidebar">
                    <?php echo $this->partial('layout/menu',array()) ?>
                </section>
            </aside>
            <aside class="right-side" >
                <?php echo $this->content ?>
            </aside>
        </div>
        <script type="text/javascript" src="/admincp/js/common.js"></script>
    </body>
</html>
<?php }else{ ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>
            <?php echo $this->translate('txt_detect_problem'); ?>
        </title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    </head>
    <body style="padding: 0;margin: 0">
        <script type="text/javascript">
            window.location.href = '<?php echo $this->basePath() ?>';
        </script>
        <div style="position: fixed;top: 0;left: 0;bottom: 0;right: 0;background: #FFF" >
            <div style="display: table;width: 100%;height: 100%;vertical-align: middle;" >
                <div style="display: table-cell;width: 100%;height: 100%;vertical-align: middle;" >
                    <div style="width: 100%;text-align: center;padding: 10px;font-size: 12px;" >
                        Processing...
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
<?php } ?>