<a href="javascript:void(0);" class="navbar-btn sidebar-toggle navbar-btn-mb" data-toggle="offcanvas" role="button">
    <span class="sr-only">
        <?php echo $this->translate('txt_toggle_navigation'); ?>
    </span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<ul class="nav navbar-nav" >
    <li class="dropdown messages-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"></a>
        <ul class="dropdown-menu">
            <li>
                <ul class="menu">
                    <li>
                        <a href="#">
                            <div class="pull-left">
                            </div>
                            <h4>
                                Support Team
                                <small>
                                    <i class="fa fa-clock-o"></i> 5 mins
                                </small>
                            </h4>
                            <p>Why not buy a new awesome theme?</p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="pull-left">
                            </div>
                            <h4>
                                AdminLTE Design Team
                                <small><i class="fa fa-clock-o"></i> 2 hours</small>
                            </h4>
                            <p>Why not buy a new awesome theme?</p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="pull-left">
                            </div>
                            <h4>
                                Developers
                                <small><i class="fa fa-clock-o"></i> Today</small>
                            </h4>
                            <p>Why not buy a new awesome theme?</p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="pull-left">
                            </div>
                            <h4>
                                Sales Department
                                <small><i class="fa fa-clock-o"></i> Yesterday</small>
                            </h4>
                            <p>Why not buy a new awesome theme?</p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="pull-left">
                            </div>
                            <h4>
                                Reviewers
                                <small><i class="fa fa-clock-o"></i> 2 days</small>
                            </h4>
                            <p>Why not buy a new awesome theme?</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
        </ul>
    </li> 

    <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-user"></i>
            <span><?php echo $_SESSION['CMSMEMBER']['full_name'] ?><i class="caret"></i></span>
        </a>
        <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header bg-light-blue">
    <!--            <img src="img/avatar3.png" class="img-circle" alt="User Image" />-->
                <p>
                    <?php echo $_SESSION['CMSMEMBER']['full_name'] ?>
                    <small>Member since <?php //echo $_SESSION['MEMBER']['date_create'] ?></small>
                </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
            
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
                <div class="pull-left">
                    <a href="<?php echo $this->url('cms/user',array('action' => 'profile')) ?>" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                    <a href="<?php echo $this->url('cms/login',array('action' => 'logout')) ?>" class="btn btn-default btn-flat">Sign out</a>
                </div>
            </li>
        </ul>
    </li>
</ul>