<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Giờ vàng khuyến mãi :: Thêm mới
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/goldtimer') ?>">Giờ vàng khuyến mãi</a></li>
        <li class="active">Thêm mới giờ vàng</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/goldtimer', array('action' => 'add')));
        $form->setAttribute('id', 'form-goldtimer');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('gold_timer_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="gold_timer_title">Tiêu đề</label>
                        <?php echo $this->formRow($form->get('gold_timer_title')); ?>
                    </div>
                    <div class="form-group">
                        <label for="date_start">Ngày bắt đầu</label>
                        <?php echo $this->formRow($form->get('date_start')); ?>
                    </div>
                    <div class="form-group">
                        <label for="date_end">Ngày kết thúc</label>
                        <?php echo $this->formRow($form->get('date_end')); ?>
                    </div>
                    <div class="form-group">
                        <label for="time_start">Thời gian bắt đầu</label>
                        <?php echo $this->formRow($form->get('time_start')); ?>
                    </div>
                    <div class="form-group">
                        <label for="time_end">Thời gian kết thúc</label>
                        <?php echo $this->formRow($form->get('time_end')); ?>
                    </div>
                </div>
            </div>

            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Chọn sản phẩm</h3>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <label for="search_product">Tìm sản phẩm</label>
                        <input type="text" class="form-control gold_product_autocomplete"
                               placeholder="Nhập vào mã sản phẩm hoặc tên sản phẩm"/>
                    </div>
                    <div class="form-group">
                        <label>Danh sách sản phẩm</label>
                    </div>
                    <table class="table product_deal_table">
                        <thead>
                        <tr>
                            <th>Mã SP</th>
                            <th>Tên SP</th>
                            <th>Giá bán</th>
                            <th>Giá khuyến mãi</th>
                            <th>Tác vụ</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $list_add = array(); ?>
                        <?php if(isset($_POST['products'])): ?>
                            <?php $products = $_POST['products']; ?>
                            <?php foreach($products as $key => $product): ?>
                                <?php $list_add[] = $key; ?>
                                <tr class="gold_products_item_<?php echo $key ?>">
                                    <td>
                                        <?php echo $product['products_code'] ?>
                                        <input name="products[<?php echo $key ?>][products_code]" type="hidden" value="<?php echo $product['products_code'] ?>"/>
                                    </td>
                                    <td>
                                        <?php echo $product['products_title'] ?>
                                        <input name="products[<?php echo $key ?>][products_title]" type="hidden" value="<?php echo $product['products_title'] ?>"/>
                                    </td>
                                    <td><input type="text" class="moneyInput" name="products[<?php echo $key ?>][price]" value="<?php echo $product['price'] ?>"/></td>
                                    <td><input type="text" class="moneyInput" name="products[<?php echo $key ?>][price_sale]" value="<?php echo $product['price_sale'] ?>"/></td>
                                    <td><a href="javascript:;" onclick="removeDealProduct(this,<?php echo $key ?>)">Xóa</a></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <button class="btn btn-primary">Lưu lại</button>
            <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>
<script type="text/javascript">
    var list_added = [<?php echo implode(',', $list_add) ?>];
</script>