<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Giờ vàng :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Giờ vàng</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/goldtimer') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/goldtimer', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm giờ vàng mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/goldtimer', array('action' => 'publish')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/goldtimer', array('action' => 'unpublish')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/goldtimer', array('action' => 'delete')) ?>')">
                                Xóa giờ vàng
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Tiêu đề</th>
                                <th width="100" style="text-align: center">Ngày bắt đầu</th>
                                <td width="200" style="text-align: center">Ngày kết thúc</td>
                                <th width="100" style="text-align: center">Thời gian bắt đầu</th>
                                <th width="100" style="text-align: center">Thời gian kết thúc</th>
                                <th width="100" style="text-align: center">Hiển thị</th>
                                <th width="10"><input type="checkbox" class="checkall" /></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($gold_timers as $row) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $row['gold_timer_id'] ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/goldtimer',array('action'=> 'edit', 'id' => $row['gold_timer_id'])) ?>"><?php echo $row['gold_timer_title'] ?></a>
                                    </td>
                                    <td style="text-align: center">
                                        <?php echo date('d/m/Y', strtotime($row['date_start'])) ?>
                                    </td>
                                    <td style="text-align: center">
                                        <?php echo date('d/m/Y', strtotime($row['date_end'])) ?>
                                    </td>
                                    <td style="text-align: center">
                                        <?php echo $row['time_start'] ?>
                                    </td>
                                    <td style="text-align: center">
                                        <?php echo $row['time_end'] ?>
                                    </td>
                                    <td style="text-align: center">
										<?php if($row['is_published']) : ?>
										<?php $href = $this->url('cms/goldtimer',array('action' => 'unpublish','id' => $row['gold_timer_id'])) ?>
										<?php else: ?>
										<?php $href = $this->url('cms/goldtimer',array('action' => 'publish','id' => $row['gold_timer_id'])) ?>
										<?php endif; ?>
										<?php echo $row['is_published'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Đang hiển thị' data-original-title='Đang hiển thị'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Bị ẩn'><i class='fa fa-circle-o'></i></a>" ?>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $row['gold_timer_id'] ?>"/>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Tiêu đề</th>
                                <th width="100" style="text-align: center">Ngày bắt đầu</th>
                                <td width="200" style="text-align: center">Ngày kết thúc</td>
                                <th width="100" style="text-align: center">Thời gian bắt đầu</th>
                                <th width="100" style="text-align: center">Thời gian kết thúc</th>
                                <th width="100" style="text-align: center">Hiển thị</th>
                                <th width="10"><input type="checkbox" class="checkall" /></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/goldtimer', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm giờ vàng mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/goldtimer', array('action' => 'publish')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/goldtimer', array('action' => 'unpublish')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/goldtimer', array('action' => 'delete')) ?>')">
                                Xóa giờ vàng
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->