<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Liên hệ :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Liên hệ</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/contact') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/contact', array('action' => 'delete')) ?>')">
                                Xóa
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                                <tr>
                                    <th width="50" style="text-align: center">ID</th>
                                    <th>Người hỏi</th>
                                    <th>Email</th>
                                    <th>Lượt trả lời</th>
                                    <th>Trạng thái</th>
                                    <th>Ngày hỏi</th>
                                    <th width="10"><input type="checkbox" class="checkall"/></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($contacts as $row) { ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $row['id'] ?></td>
                                    <td>
                                        <?php echo $row['fullname'] ?>
                                    </td>
                                    <td>
                                        <?php echo $row['email'] ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/contact', array('action' => 'replay','id' => $row['id'])) ?>"  data-toggle='tooltip' title='Vào trả lời' data-original-title='Vào trả lời'><?php echo empty($row['total_relay']) ? 'Chưa trả lời' : "Có <strong>{$row['total_relay']}</strong> câu trả lời"  ?></a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/contact', array('action' => 'replay','id' => $row['id'])) ?>"  data-toggle='tooltip' title='Vào trả lời' data-original-title='Vào trả lời'>
                                            <?php echo empty($row['readed']) ? 'Chưa đọc' : "Đã đọc"  ?>
                                        </a>
                                    </td>
                                    <td>
                                        <?php echo $row['date_send'] ?>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $row['id'] ?>"/>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th width="50" style="text-align: center">ID</th>
                                    <th>Người hỏi</th>
                                    <th>Email</th>
                                    <th>Lượt trả lời</th>
                                    <th>Trạng thái</th>
                                    <th>Ngày hỏi</th>
                                    <th width="10"><input type="checkbox" class="checkall"/></th>
                                </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/contact', array('action' => 'delete')) ?>')">
                                Xóa
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->