<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Liên hệ :: Trả lời
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/contact') ?>">Liên hệ</a></li>
        <li class="active">Trả lời câu hỏi</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Liên hệ</h3>
                </div>
                <div class="box-body">
                        <p>Email: <strong><?php echo $contact['email'] ?></strong></p>
                        <p>Người hỏi: <strong><?php echo $contact['fullname'] ?></strong></p>
                        <p>Thời gian hỏi: <strong><?php echo date('d-m-Y H:i:s', strtotime($contact['date_create'])) ?></strong></p>
                        <label>Nội dung</label>
                        <div>
                            <strong>
                            <?php echo $contact['description'] ?>
                            </strong>
                        </div>
                </div>
            </div>
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title">Trả lời</h3>
                </div>
                <div class="box-body" >
                    <?php foreach($replays as $replay) { ?>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?php echo $replay['content'] ?>
                        </div>
                    </div>
                    <?php } ?>

                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form action="" method="post">
                                <input name="id" type="hidden" value="<?php echo $contact['id'] ?>"/>
                                <input name="users_id" type="hidden" value="<?php echo $_SESSION['CMSMEMBER']['users_id'] ?>"/>
                                <div class="form-group">
                                    <textarea name="content" id="content" cols="30" rows="5" class="form-control" style="border: none" autofocus></textarea>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary">Trả lời</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>