<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/permission') ?>">
                        <?php echo $this->translate('txt_permission'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_cap_nhat'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_permission'); ?> :: 
                <?php echo $this->translate('txt_cap_nhat'); ?>
            </h1>
        </div>
    </div>
</section>

<section class="content" >
    <div class="clearfix">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/permission', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('id', 'form-permission');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('permissions_id'));
        ?>
        <div class="row" >
            <div class="col-sm-6 col-xs-6" >
                <div class="form-group">
                    <label for="permissions_name" >
                        <?php echo $this->translate('txt_ten_quyen'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('permissions_name')); ?>
                </div>

                <div class="form-group">
                    <label for="module" >
                        <?php echo $this->translate('txt_khu_vuc_quyen'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('module')); ?>
                </div>

                <div class="form-group">
                    <label for="module" >
                        <?php echo $this->translate('txt_chuc_nang_quyen'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('controller')); ?>
                </div>

                <div class="form-group">
                    <label for="module" >
                        <?php echo $this->translate('txt_hanh_dong_quyen'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('action')); ?>
                </div>

            </div>
        </div>

        <div class="form-group">
            <label for="module" >
                <?php echo $this->translate('txt_mo_ta_quyen'); ?>
            </label>
            <?php echo $this->formRow($form->get('description')); ?>
        </div>

        <div class="form-group" >
            <label for="is_published">
                <?php echo $this->formRow($form->get('is_published')); ?>
                <?php echo $this->translate('txt_kich_hoat'); ?>
            </label>
        </div>

        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                <?php echo $this->translate('txt_cap_nhat_quyen'); ?>
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                <?php echo $this->translate('txt_quay_lai'); ?>
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>