<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ngôn ngữ :: Thêm mới
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/language') ?>">Ngôn ngữ</a></li>
        <li class="active">Thêm ngôn ngữ</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/language', array('action' => 'add')));
        $form->setAttribute('id', 'form-language');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('languages_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="languages_name">Tiêu đề</label>
                        <?php echo $this->formRow($form->get('languages_name')); ?>
                    </div>
                    <div class="form-group">
                        <label for="languages_file">Mã vùng ngôn ngữ</label>
                        <p>Ví dụ: en_US, vi_VN...</p>
                        <?php echo $this->formRow($form->get('languages_file')); ?>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_published">
                                <?php echo $this->formRow($form->get('is_published')); ?>
                                Kích hoạt
                            </label>
                        </div>
                    </div>
                </div>
            </div>
<!--            <div class="box box-primary">-->
<!--                <div class="box-header">-->
<!--                    <h3 class="box-title">-->
<!--                        Dịch-->
<!--                    </h3>-->
<!--                    <div class="pull-right box-tools">-->
<!--                        <button type="button" onclick="add_more_trans()" class="btn btn-primary btn-sm"><i class="fa fa-plus-square"></i></button>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="box-body">-->
<!---->
<!--                    <div id="translate">-->
<!--                        --><?php //$index = 0; ?>
<!--                        --><?php //foreach($template as $key => $tran): ?>
<!--                            <div class="form-group">-->
<!--                                <div class="row">-->
<!--                                    <div class="col-xs-3">-->
<!--                                        <input type="text" readonly name="translate[--><?php //echo $index ?><!--][key]" value="--><?php //echo $key ?><!--" class="form-control" />-->
<!--                                    </div>-->
<!--                                    <div class="col-xs-2">-->
<!--                                        <button type="button" class="btn btn-info">&raquo;</button>-->
<!--                                    </div>-->
<!--                                    <div class="col-xs-7">-->
<!--                                        <input type="text" name="translate[--><?php //echo $index ?><!--][tran]" value="--><?php //echo $tran ?><!--" class="form-control" />-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                            --><?php //$index++ ?>
<!--                        --><?php //endforeach; ?>
<!---->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
        </div>

        <div class="col-xs-12">
            <button class="btn btn-primary">Lưu lại</button>
            <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>
<!--<script type="template" id="lang-trans-template">-->
<!--    <div class="form-group">-->
<!--        <div class="row">-->
<!--            <div class="col-xs-3">-->
<!--                <input type="text" name="translate[{INDEX}][key]" value="" class="form-control" />-->
<!--            </div>-->
<!--            <div class="col-xs-2">-->
<!--                <button type="button" class="btn btn-info">&raquo;</button>-->
<!--            </div>-->
<!--            <div class="col-xs-6">-->
<!--                <input type="text" name="translate[{INDEX}][tran]" value="" class="form-control" />-->
<!--            </div>-->
<!--            <div class="col-xs-1">-->
<!--                <button type="button" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></button>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</script>-->