<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ngôn ngữ :: Cập nhật
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/language') ?>">Ngôn ngữ</a></li>
        <li class="active">Cập nhật ngôn ngữ</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/language', array('action' => 'add')));
        $form->setAttribute('id', 'form-language');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('languages_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="languages_name">Tiêu đề</label>
                        <?php echo $this->formRow($form->get('languages_name')); ?>
                    </div>
                    <div class="form-group">
                        <label for="languages_file">Mã vùng ngôn ngữ</label>
                        <p>Ví dụ: en_US, vi_VN...</p>
                        <?php echo $this->formRow($form->get('languages_file')); ?>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_published">
                                <?php echo $this->formRow($form->get('is_published')); ?>
                                Kích hoạt
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-12">
            <button class="btn btn-primary">Lưu lại</button>
            <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>