<div class="popup-edit-keyword" >
    <?php
    $word = $keyword;
    ?>
    <form action="" method="post" id="form-edit-keyword" >
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="keyword">Từ khóa</label>
                        <input type="text" name="keyword_view" value="<?php echo $word['keyword'] ?>" class="form-control" disabled />
                        <input type="hidden" name="keyword" value="<?php echo $word['keyword'] ?>" class="form-control" />
                    </div>
                    <?php foreach($languages as $lang) : ?>
                        <div class="form-group">
                            <label for="language_trangslate_<?php echo $lang['languages_id'] ?>"><?php echo $lang['languages_name'] ?></label>
                            <textarea name="translate[<?php echo $lang['languages_id'] ?>]" id="language_trangslate_<?php echo $lang['languages_id'] ?>" rows="3" class="form-control"><?php echo isset($word[$lang['languages_id']]) ? $word[$lang['languages_id']] : '' ?></textarea>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <a href="javascript:void(0);" class="btn btn-primary btn-save-keyword" >Lưu lại</a>
        </div>
    </form>
</div>