<div class="case-quote" >
    <div class="case-inner-quote" >
        <div class="container" >
            <div class="row" >
                <div class="col-md-10 col-md-offset-1">
                    <div class="row" >
                        <div class="col-md-7 col-sm-12" >
                            <div class="info-quote" >
                                <h2 class="title-quote" >About IP Supply</h2>
                                <div class="description-quote" >
                                    IP Supply is a network hardware reseller founded in 2010 and based in Lidcombe, NSW. Trading in more than 80 countries, we have a strong profile on the markets for new and refurbished
                                    network equipments.
                                </div>

                                <div class="rating-quote" >
                                    <span class="inline-rtq" >
                                        <img src="/styles/dataimages/ebay.png" width="90" >
                                    </span>
                                    <span class="inline-rtq" >
                                        Review: 
                                        <span class="star-rtq" >
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                            <i class="fa fa-star-o" aria-hidden="true"></i>
                                        </span>
                                    </span>
                                    <span class="inline-rtq" >
                                        4.8/5
                                    </span>
                                </div>

                                <div class="more-quote" >
                                    <a class="btn btn-style-a" title="" >
                                        Discover More
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5 col-sm-12" >
                            <div class="form-quote" >
                                <div class="header-from-quote" >
                                    <h2 class="title-from-quote" >
                                        <?php echo $this->translate('txt_get_a_free_quote'); ?>
                                    </h2>
                                    <p class="small-from-quote" >
                                        <?php echo $this->translate('txt_des_get_a_free_quote'); ?>
                                    </p>
                                </div>
                                <div class="clearfix main-form-quote" >
                                    <form class="form-horizontal" data-form="anythingContact" >
                                        <input type="hidden" name="type" value="get_free_quote" >
                                        <div class="form-group" >
                                            <input type="text" name="fullname" class="form-control" placeholder="<?php echo $this->translate('txt_request_quote_name'); ?>"  data-required="true" >
                                        </div>
                                        <div class="form-group" >
                                            <input type="text" name="email" class="form-control" placeholder="<?php echo $this->translate('txt_request_quote_email'); ?>" data-required="true" >
                                        </div>
                                        <div class="form-group" >
                                            <input type="text" name="telephone" class="form-control" placeholder="<?php echo $this->translate('txt_request_quote_phone'); ?>" data-required="true" >
                                        </div>
                                        <div class="form-group" >
                                            <select name="products_id" class="form-control" >
                                                <option value="0" >
                                                    Product Requested
                                                </option>
                                            </select>
                                        </div>
                                        <div class="form-group" >
                                            <textarea name="description" class="form-control" placeholder="Message" ></textarea>
                                        </div>
                                        <div class="form-group text-xs-center" >
                                            <button type="button" class="btn btn-block btn-style-b" data-btn="anythingContact" >
                                                <?php echo $this->translate('txt_btn_request_a_quote'); ?>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>