<div class="case-top-feature" >
    <div class="container" >
        <h2 class="title-feature" >
            Why Buy from <span class="color-blue" >IP Supply</span>
        </h2>
        <div class="list-feature" >
            <div class="row" >
                <div class="col-sm-1" ></div>
                <div class="col-sm-2" >
                    <div class="item-feature old" >
                        <div class="thumb-feature" >
                            <i class="fa fa-usd" aria-hidden="true"></i>
                        </div>
                        <h3 class="name-feature" >
                            100% Wholesale <br />
                            Price
                        </h3>
                    </div>
                </div>
                <div class="col-sm-2" >
                    <div class="item-feature even" >
                        <div class="thumb-feature" >
                            <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                        </div>
                        <h3 class="name-feature" >
                            100% Quality <br />
                            Assurance
                        </h3>
                    </div>
                </div>
                <div class="col-sm-2" >
                    <div class="item-feature old" >
                        <div class="thumb-feature" >
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </div>
                        <h3 class="name-feature" >
                            24X7 Free <br /> Support
                        </h3>
                    </div>
                </div>
                <div class="col-sm-2" >
                    <div class="item-feature even" >
                        <div class="thumb-feature" >
                            <i class="fa fa-refresh" aria-hidden="true"></i>
                        </div>
                        <h3 class="name-feature" >
                            100% Money <br /> Back Guarantee
                        </h3>
                    </div>
                </div>
                <div class="col-sm-2" >
                    <div class="item-feature old" >
                        <div class="thumb-feature" >
                            <i class="fa fa-credit-card" aria-hidden="true"></i>
                        </div>
                        <h3 class="name-feature" >
                            Easy and Flexible <br /> payment
                        </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>