<?php 
$aboutus_id = $this->translate('txt_id_aboutus');
$aboutUs = $this->Articles()->getRow( $aboutus_id ); 
?>
<div class="case-quote" >
    <div class="case-inner-quote" >
        <div class="container" >
            <div class="row" >
                <div class="col-md-10 col-md-offset-1">
                    <div class="row" >
                        <div class="col-md-7 col-sm-12" >
                            <?php if( !empty($aboutUs) ){ ?>
                            <div class="info-quote" >
                                <h2 class="title-quote" >
                                    <?php echo $this->Articles()->getTitle($aboutUs); ?>
                                </h2>
                                <div class="description-quote" >
                                    <?php echo $this->Articles()->getDescription($aboutUs); ?>
                                </div>

                                <div class="rating-quote" >
                                    <span class="inline-rtq" >
                                        <img src="/styles/dataimages/ebay.png" width="90" >
                                    </span>
                                    <span class="inline-rtq" >
                                        <?php echo $this->translate('txt_review'); ?>
                                        <?php $rating = $this->Articles()->getRating($aboutUs) ?>
                                        <span class="star-rtq" >
                                            <?php for( $i=0; $i<$rating; $i++){ ?>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <?php } ?>

                                            <?php if( $rating != floor($rating) ){ ?>
                                            <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                            <?php } ?>

                                            <?php for( $i=$rating; $i<5; $i++){ ?>
                                            <i class="fa fa-star-o" aria-hidden="true"></i>
                                            <?php } ?>
                                        </span>
                                    </span>
                                    <span class="inline-rtq" >
                                        <?php echo $rating; ?>/5
                                    </span>
                                </div>

                                <div class="more-quote" >
                                    <a class="btn btn-style-a" href="<?php echo $this->Articles()->getUrl($aboutUs); ?>" title="<?php echo $this->Articles()->getTitle($aboutUs); ?>" data-pjax="true" data-container="Main" >
                                        <?php echo $this->translate('txt_discover_more'); ?>
                                    </a>
                                </div>
                            </div>
                            <?php } ?>
                        </div>
                        <div class="col-md-5 col-sm-12" >
                            <div class="form-quote" >
                                <div class="header-from-quote" >
                                    <h2 class="title-from-quote" >
                                        <?php echo $this->translate('txt_get_a_free_quote'); ?>
                                    </h2>
                                    <p class="small-from-quote" >
                                        <?php echo $this->translate('txt_des_get_a_free_quote'); ?>
                                    </p>
                                </div>
                                <div class="clearfix main-form-quote" >
                                    <form class="form-horizontal" data-form="anythingContact" >
                                        <input type="hidden" name="type" value="get_free_quote" >
                                        <div class="form-group" >
                                            <input type="text" name="fullname" class="form-control" placeholder="<?php echo $this->translate('txt_request_quote_name'); ?>"  data-required="true" >
                                        </div>
                                        <div class="form-group" >
                                            <input type="text" name="email" class="form-control" placeholder="<?php echo $this->translate('txt_request_quote_email'); ?>" data-required="true" >
                                        </div>
                                        <div class="form-group" >
                                            <input type="text" name="telephone" class="form-control" placeholder="<?php echo $this->translate('txt_request_quote_phone'); ?>" data-required="true" >
                                        </div>
                                        <div class="form-group" >
                                            <textarea type="text" name="product_name" class="form-control product-name" placeholder="<?php echo $this->translate('txt_request_quote_product_name'); ?>" data-required="true" ></textarea>
                                        </div>
                                        <div class="form-group" >
                                            <textarea name="description" class="form-control" placeholder="Message" ></textarea>
                                        </div>
                                        <div class="form-group text-xs-center" >
                                            <button type="button" class="btn btn-block btn-style-b" data-btn="anythingContact" >
                                                <?php echo $this->translate('txt_btn_request_a_quote'); ?>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>