<div class="case-upgrate" >
    <div class="container" >
        <div class="row" >
            <div class="col-sm-10 col-sm-offset-1" >
                <div class="row" >
                    <div class="col-sm-7 text-sm-left text-xs-center" >
                        <h2 class="title-upgrate" >
                            <?php echo $this->translate('txt_save_up_to'); ?>
                        </h2>
                        <div>
                            <?php echo $this->translate('txt_des_save_up_to'); ?>
                        </div>
                    </div>
                    <div class="col-sm-5 text-sm-right text-xs-center" >
                        <a class="btn btn-style-a" title="" >
                            <?php echo $this->translate('txt_shop_s_products'); ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>