<div class="case-upgrate" >
    <div class="container" >
        <div class="row" >
            <div class="col-sm-10 col-sm-offset-1" >
                <div class="row" >
                    <div class="col-sm-7" >
                        <h2 class="title-upgrate" >Save Up to 95% on Cisco</h2>
                        <div>Same day Shipment for most items one year end user warranty</div>
                    </div>
                    <div class="col-sm-5 text-xs-right" >
                        <a class="btn btn-style-a" title="" >
                            Shop Cisco Products
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>