<div class="case-top-feature" >
    <div class="container" >
        <h2 class="title-feature" >
            <?php echo $this->translate('txt_why_buy_from_ip_supply'); ?>
        </h2>
        <div class="list-feature" >
            <div class="row" >
                <div class="col-xs-10 col-xs-offset-1" >
                    <div class="row" >
                        <div class="col-lg-2 col-lg-offset-1 col-md-4 col-sm-6 col-xs-6" >
                            <div class="item-feature old" >
                                <div class="thumb-feature" >
                                    <i class="fa fa-usd" aria-hidden="true"></i>
                                </div>
                                <h3 class="name-feature" >
                                    <?php echo $this->translate('txt_100_wholesale_price'); ?>
                                </h3>
                            </div>
                        </div>

                        <div class="col-lg-2 col-md-4 col-sm-6 col-xs-6" >
                            <div class="item-feature even" >
                                <div class="thumb-feature" >
                                    <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                </div>
                                <h3 class="name-feature" >
                                    <?php echo $this->translate('txt_100_quality_assurance'); ?>
                                </h3>
                            </div>
                        </div>

                        <div class="col-lg-2 col-md-4 col-sm-6 col-xs-6" >
                            <div class="item-feature old" >
                                <div class="thumb-feature" >
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                </div>
                                <h3 class="name-feature" >
                                    <?php echo $this->translate('txt_24_7_free_support'); ?>
                                </h3>
                            </div>
                        </div>

                        <div class="col-lg-2 col-lg-offset-0 col-md-4 col-md-offset-2 col-sm-6 col-xs-6" >
                            <div class="item-feature even" >
                                <div class="thumb-feature" >
                                    <i class="fa fa-refresh" aria-hidden="true"></i>
                                </div>
                                <h3 class="name-feature" >
                                    <?php echo $this->translate('txt_100_money_back_guarantee'); ?>
                                </h3>
                            </div>
                        </div>

                        <div class="col-lg-2 col-lg-offset-0 col-md-4 col-md-offset-0 col-sm-6 col-xs-6 col-xs-offset-3" >
                            <div class="item-feature old" >
                                <div class="thumb-feature" >
                                    <i class="fa fa-credit-card" aria-hidden="true"></i>
                                </div>
                                <h3 class="name-feature" >
                                    <?php echo $this->translate('txt_easy_and_flexible_payment'); ?>
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>