<div class="case-quote" >
    <div class="case-inner-quote" >
        <div class="container" >
            <div class="row" >
                <div class="col-sm-10 col-sm-offset-1">
                    <div class="row" >
                        <div class="col-sm-7" >
                            <div class="info-quote" >
                                <h2 class="title-quote" >About IP Supply</h2>
                                <div class="description-quote" >
                                    IP Supply is a network hardware reseller founded in 2010 and based in Lidcombe, NSW. Trading in more than 80 countries, we have a strong profile on the markets for new and refurbished
                                    network equipments.
                                </div>

                                <div class="rating-quote" >
                                    <span class="inline-rtq" >
                                        <img src="/styles/dataimages/ebay.png" width="90" >
                                    </span>
                                    <span class="inline-rtq" >
                                        Review: 
                                        <span class="star-rtq" >
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star" aria-hidden="true"></i>
                                            <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                            <i class="fa fa-star-o" aria-hidden="true"></i>
                                        </span>
                                    </span>
                                    <span class="inline-rtq" >
                                        4.8/5
                                    </span>
                                </div>

                                <div class="more-quote" >
                                    <a class="btn btn-style-a" title="" >
                                        Discover More
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-5" >
                            <div class="form-quote" >
                                <div class="header-from-quote" >
                                    <h2 class="title-from-quote" >
                                        Get a Free Quote
                                    </h2>
                                    <p class="small-from-quote" >
                                        Complete the form below to get your free quote.
                                    </p>
                                </div>
                                <div class="clearfix main-form-quote" >
                                    <div class="form-group" >
                                        <input type="text" name="" class="form-control" placeholder="Name" >
                                    </div>
                                    <div class="form-group" >
                                        <input type="text" name="" class="form-control" placeholder="Email" >
                                    </div>
                                    <div class="form-group" >
                                        <input type="text" name="" class="form-control" placeholder="Phone" >
                                    </div>
                                    <div class="form-group" >
                                        <select name="type" class="form-control" >
                                            <option value="" >
                                                Product Requested
                                            </option>
                                        </select>
                                    </div>
                                    <div class="form-group" >
                                        <textarea name="" class="form-control" placeholder="Message" ></textarea>
                                    </div>
                                    <div class="form-group text-xs-center" >
                                        <button class="btn btn-block btn-style-b" >
                                            Request A Quote
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>