<div class="case-supplier" >
    <div class="container" >
        <h3 class="title-supplier" >
            Largest Equipment Selection
        </h3>
        <p class="text-xs-center">
            Thousands of popular and hard-to-find equipment in inventory ready to ship
        </p>
        <div class="row" >
            <div class="col-sm-8 col-sm-offset-2" >
                <div class="list-supplier" >
                    <div class="item-supplier" >
                        <a href="" title="" >
                            <img src="/styles/dataimages/cisco.png" class="img-fluid" >
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>