<?php
if( empty($category) 
    ||  (!empty($category) && empty($this->Categories()->getChildrens($categories, $this->Categories()->getId($category)))) ){
    $categoriesRoot = $this->Categories()->getRoot($categories);
}else{
    $categoriesRoot = $this->Categories()->getChildrens($categories, $this->Categories()->getId($category));
}
if( !empty($categoriesRoot) ){ ?>
<ul class="nav-category clearfix" >
    <?php 
    foreach ($categoriesRoot as $key01 => $category01) { 
        $childrens = $this->Categories()->getChildrens($categories, $this->Categories()->getId($category01));
    ?>
    <li class="nav-item" >
        <a href="<?php echo $this->Categories()->getCategoriesUrl($category01); ?>" title="<?php echo $this->Categories()->getTitle($category01); ?>" class="nav-link"  data-pjax="true" data-container="Main"  itemprop="url" >
            <span class="txt-inner" >
                <?php echo $this->Categories()->getTitle($category01); ?>
            </span>
            <span class="number-in" >
                <?php echo $this->Categories()->getNumberProduct($category01); ?>
            </span>
        </a>
        <?php if( !empty($childrens) ){ ?>
        <ul class="dropdown-menu">
            <?php foreach ($childrens as $key02 => $category02){ 
                $childrens02 = $this->Categories()->getChildrens($categories, $this->Categories()->getId($category02));
            ?>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->Categories()->getCategoriesUrl($category02); ?>" title="<?php echo $this->Categories()->getTitle($category02); ?>"  data-pjax="true" data-container="Main"  itemprop="url" >
                    <span class="txt-inner" >
                        <?php echo $this->Categories()->getTitle($category02); ?>
                    </span>
                    <span class="number-in" >
                        <?php echo $this->Categories()->getNumberProduct($category02); ?>
                    </span>
                </a>

                <?php if( !empty($childrens02) ){ ?>
                <ul class="dropdown-menu">
                    <?php foreach ($childrens02 as $key02 => $category03){ ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo $this->Categories()->getCategoriesUrl($category03); ?>" title="<?php echo $this->Categories()->getTitle($category02); ?>"  data-pjax="true" data-container="Main"  itemprop="url" >
                            <span class="txt-inner" >
                                <?php echo $this->Categories()->getTitle($category02); ?>
                            </span>
                            <span class="number-in" >
                                <?php echo $this->Categories()->getNumberProduct($category03); ?>
                            </span>
                        </a>
                    </li>
                    <?php } ?>
                    
                </ul>
                <?php } ?>

            </li>
            <?php } ?>

        </ul>
        <?php } ?>

    </li>
    <?php } ?>
</ul>
<?php } ?>