<div class="general-box" >
    <h2 class="title-general" >
        Can't find the <br />
        Product you want?
    </h2>
    <div class="ds-general clearfix" >
        <div class="sub-general clearfix contact-sm" >
            <h4 class="sub-title-general" >Let us know!</h4>
            <div class="form-group" >
                <input type="text" name="" class="form-control" placeholder="Name" >
            </div>
            <div class="form-group" >
                <input type="text" name="" class="form-control" placeholder="Email" >
            </div>
            <div class="form-group" >
                <input type="text" name="" class="form-control" placeholder="Phone" >
            </div>
            <div class="form-group" >
                <textarea name="" class="form-control" placeholder="Item I'm looking for" ></textarea>
            </div>
            <div class="form-group" >
                <button class="btn btn-style-c btn-style-sm" >
                    Submit
                </button>
            </div>
        </div>
    </div>
</div>