<?php
$languages_id = $datas->languages_id;
$country_code = $datas->country_code;
$country_id = $datas->country_id;
$countries = $datas->countries;
$languages = $datas->languages;
$language = $datas->language;
$categories = $datas->categories;
$menus = $datas->menus;
$menu_one = $this->Menus()->getMenuWithAlias('MENU_FOOTER_01');
$menu_two = $this->Menus()->getMenuWithAlias('MENU_FOOTER_02');
?>
<div class="footer" >
    <div class="container" >
        <div class="row" >
            <div class="col-sm-10 col-sm-offset-1" >
                <div class="top-footer" >
                    <div class="row" >

                        <div class="col-sm-3" >
                            <div class="col-footer" >
                                <h2 class="title-footer" >
                                    Need Help?
                                </h2>
                                <div class="info-footer" >
                                    <div class="sub-col-footer" >
                                        <div class="title-ms-footer" >Call: +61 2 8061 6886</div>
                                        <div>E.: sales@ipsupply.com.au</div>
                                    </div>
                                    <div class="sub-col-footer" >
                                        <div class="title-ms-footer" >IP Supply Pty Ltd</div>
                                        <div>Unit 16 / 4A Bachell Ave
                                        Lidcombe, NSW 2141
                                        Australia</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-3" >
                            <div class="col-footer" >
                                <h2 class="title-footer" >
                                    Shopping
                                </h2>
                                <div class="info-footer" >
                                    <a href="" title="" class="footer-link" >Router</a>
                                    <a href="" title="" class="footer-link" >Switches</a>
                                    <a href="" title="" class="footer-link" >Firewalls Security</a>
                                    <a href="" title="" class="footer-link" >IP Phones VOIP</a>
                                    <a href="" title="" class="footer-link" >Wireless AP</a>
                                    <a href="" title="" class="footer-link" >Modules & Cards</a>
                                    <a href="" title="" class="footer-link" >Accessories</a>
                                    <a href="" title="" class="footer-link" >Memory</a>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-3" >
                            <div class="col-footer" >
                                <h2 class="title-footer" >
                                    Help & Support
                                </h2>
                                <div class="info-footer" >
                                    <a href="" title="" class="footer-link" >About IP Supply</a>
                                    <a href="" title="" class="footer-link" >Contact Us</a>
                                    <a href="" title="" class="footer-link" >Request a Quote</a>
                                    <a href="" title="" class="footer-link" >Sell your Cisco</a>
                                    <a href="" title="" class="footer-link" >About your order</a>
                                    <a href="" title="" class="footer-link" >Wishlist</a>
                                    <a href="" title="" class="footer-link" >Compare list</a>
                                    <a href="" title="" class="footer-link" >Sitemap</a>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-3" >
                            <div class="col-footer" >
                                <h2 class="title-footer" >
                                    Newsletter
                                </h2>
                                <div class="info-footer" >
                                    <div class="sub-col-footer" >
                                        Sign Up our Newslatter to get the latest offer in your inbox.
                                    </div>

                                    <div class="sub-col-footer" >
                                        <div class="letter-form" >
                                            <input type="text" name="" placeholder="Your Email..." >
                                            <button>
                                                <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                    </div>

                                    <div class="sub-col-footer" >
                                        <a href="" class="link-social" >
                                            <i class="fa fa-facebook" aria-hidden="true"></i>
                                        </a>
                                        <a href="" class="link-social" >
                                            <i class="fa fa-twitter" aria-hidden="true"></i>
                                        </a>
                                        <a href="" class="link-social" >
                                            <i class="fa fa-google-plus" aria-hidden="true"></i>
                                        </a>
                                        <a href="" class="link-social" >
                                            <i class="fa fa-instagram" aria-hidden="true"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="bottom-footer" >
                    <div class="row" >
                        <div class="col-sm-9" >
                            <div class="copy-right" >
                                © 2017 IP Supply Pty Ltd. All Rights Reserved.
                            </div>
                        </div>
                        <div class="col-sm-3" >
                            <div class="pay-support" >
                                <img src="/styles/dataimages/pay.png" class="img-fluid" alt="" >
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a href="javascript:void(0);" title="" class="back-to-top" >
    <i class="fa fa-chevron-up" aria-hidden="true"></i>
</a>







