<?php
$languages_id = $datas->languages_id;
$country_code = $datas->country_code;
$country_id = $datas->country_id;
$countries = $datas->countries;
$languages = $datas->languages;
$language = $datas->language;
$categories = $datas->categories;
$menus = $datas->menus;
$menu = $this->Menus()->getMenuWithAlias('MENU_TOP');
$menuRoot = $this->Menus()->getChildrens($menus, $this->Menus()->getId($menu));
$categoryArticles = $this->CategoriesArticles()->getAllCategoryArticleAndSort();
?>
<script id="tmplCartMini" data-place="productCartTemplate" type="text/x-jQuery-tmpl">
    <div>
        <a href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="link-lb-summary" rel="nofollow" >
            <span class="inner-nav-top" >
                <i class="ic i-cart" ></i>
                <?php echo $this->translate('txt_gio_hang') ?>
                <span class="num-cart" >
                    ${carts.getNumberProductInCart()}
                </span>
            </span>
        </a>
        <div class="dropdown-menu" >
            {{if carts.getNumberProductInCart() > 0 }}
            <div class="top-cart-content arrow_box" >
                <div class="dropdown-label" >
                    <?php echo $this->translate('txt_danh_sach_san_pham_in_cart'); ?> 
                    (${carts.getNumberProductInCart()} <?php echo $this->translate('txt_san_pham'); ?>)
                </div>
                <div id="cart-sidebar" class="mini-products-list count_li" >
                    <div class="clearfix" style="padding: 10px"  >
                        {{each products }}
                        <div class="item clearfix" >
                            <a class="product-image" href="${coz.view.product.getLink($value)}" ${coz.view.product.getTypeView($value)} title="${coz.view.product.getTitle($value)}" rel="nofollow" >
                                <img class="anh-img" alt="${coz.view.product.getTitle($value)}" src="${coz.view.product.getImage($value)}" width="80">
                            </a>
                            <div class="detail-item">
                                <div class="product-details">
                                    <a href="${coz.view.product.getUrlDel($value)}" data-neo="ajax" title="<?php echo $this->translate('txt_xoa')?>" class="fa fa-remove" rel="nofollow" >&nbsp;</a>
                                    <p class="product-name"> 
                                        <a href="${coz.view.product.getLink($value)}" ${coz.view.product.getTypeView($value)} title="${coz.view.product.getTitle($value)}" rel="nofollow" >
                                            ${coz.view.product.getName($value)}
                                        </a>
                                    </p>
                                </div>
                                <div class="product-details-bottom"> 
                                    <span class="price">
                                        ${coz.fomatCurrency(coz.view.product.getPriceSale($value))}
                                    </span> 
                                    <span class="title-desc">
                                        <?php echo $this->translate('txt_so_luong')?> :
                                    </span> 
                                    <strong>
                                        ${coz.view.product.getProductsQuantityInCart($value)}
                                    </strong>
                                </div>
                            </div>
                        </div>
                        <div style="height:10px;"></div>
                        {{/each}}
                    </div>

                    <div class="li-fix-2" >
                        <div class="actions clearfix" >
                            <a href="<?php echo $this->Cart()->getUrlPayment(); ?>" class="btn-checkout" >
                                <span>
                                    <?php echo $this->translate('txt_thanh_toan'); ?>
                                </span>
                            </button>

                            <a class="view-cart" href="<?php echo $this->Cart()->getUrlCart(); ?>" >
                                <span>
                                    <?php echo $this->translate('txt_xem_gio_hang'); ?>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {{else}}
            <div class="top-cart-content arrow_box">
                <div id="cart-sidebar" class="mini-products-list">
                    <div class="dropdown-label" >
                        <?php echo $this->translate('txt_chua_co_san_pham'); ?>
                    </div>
                </div>
            </div>
            {{/if}}
        </div>
    </div>
</script>

<div class="header clearfix" >
    <div class="container" >
        <div class="top-header" >
            <div class="clearfix text-xs-right" >
                <div class="end-bar clearfix" >
                    <a href="" title="" class="nav-link nav-link-blue" >
                        Request A Quote
                    </a>
                </div>
                <div class="user-bar clearfix" >
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                    <a href="" title="" class="nav-link" >
                        Login
                    </a>/
                    <a href="" title="" class="nav-link" >
                        Register
                    </a>
                </div>
                <div class="sub-navi clearfix" >
                    <a href="" title="" class="nav-link" >
                        About Us
                    </a>
                    <a href="" title="" class="nav-link" >
                        Your Order
                    </a>
                    <a href="" title="" class="nav-link" >
                        Sell Your Cisco
                    </a>
                    <a href="" title="" class="nav-link" >
                        Contact Us
                    </a>
                </div>
            </div>
        </div>
        <div class="bottom-header clearfix" >
            <div class="row" >
                <div class="col-sm-4" >
                    <a href="" title="" class="logo-navi" >
                        <img src="images/logo.png" alt="" class="img-fluid" >
                    </a>
                </div>
                <div class="col-sm-8" >
                    <div class="wrap-cotrol clearfix text-xs-right" >
                        <div class="search-bar" >
                            <form class="clearfix" >
                                <input type="" name="" class="input-search" >
                                <button class="btn-search" >
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </form>
                        </div>
                        <a href="" title="" class="link-call-me" >
                            Call <i class="icon i-phone" ></i> 02 8061 6886
                        </a>
                        <div class="cart-mini" >
                            <a href="" class="round-cart" >
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                <span>02</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="navi-top" >
        <div class="container" >
            <nav class="nav-main collapse navbar-toggleable-md" id="exCollapsingNavbar2" >
                <ul class="nav navbar-nav clearfix">
                    <li class="nav-item active" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                <i class="fa fa-home" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                Cisco Equipment
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                        <ul class="dropdown-menu" >
                            <li>
                                <a href="" title="Trang chủ" >
                                    <span class="inner-text" >
                                        Cisco Equipment
                                    </span>
                                    <span class="direct-drop" >
                                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="" title="Trang chủ" >
                                    <span class="inner-text" >
                                        Cisco Equipment
                                    </span>
                                    <span class="direct-drop" >
                                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="" title="Trang chủ" >
                                    <span class="inner-text" >
                                        Cisco Equipment
                                    </span>
                                    <span class="direct-drop" >
                                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="" title="Trang chủ" >
                                    <span class="inner-text" >
                                        Cisco Equipment
                                    </span>
                                    <span class="direct-drop" >
                                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="" title="Trang chủ" >
                                    <span class="inner-text" >
                                        Cisco Equipment
                                    </span>
                                    <span class="direct-drop" >
                                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                Cisco Accessories
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                Servers
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>  
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                Ethernet
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                Fiber
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                Racks & Cabinets
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li> 
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                Power
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                Packs & Bundles
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item" >
                        <a href="" class="nav-link" title="Trang chủ" >
                            <span class="inner-text" >
                                CK Outlet
                            </span>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </a>
                    </li>            
                </ul>
            </nav>
        </div>
    </div>
</div>