<?php
$languages_id = $datas->languages_id;
$country_code = $datas->country_code;
$country_id = $datas->country_id;
$countries = $datas->countries;
$languages = $datas->languages;
$language = $datas->language;
$categories = $datas->categories;
$menus = $datas->menus;
$subMenu = $this->Menus()->getMenuWithAlias('SUB_MENU_TOP');
$menu = $this->Menus()->getMenuWithAlias('MENU_TOP');
$subMenuRoot = $this->Menus()->getChildrens($menus, $this->Menus()->getId($subMenu));
$menuRoot = $this->Menus()->getChildrens($menus, $this->Menus()->getId($menu));
$categoryArticles = $this->CategoriesArticles()->getAllCategoryArticleAndSort();
?>
<script id="tmplCartMini" data-place="productCartTemplate" type="text/x-jQuery-tmpl">
    <div>
        <a href="javascript:void(0);" class="round-cart" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" rel="nofollow" >
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <span>${carts.getNumberProductInCart()}</span>
        </a>
        <div class="dropdown-menu coz-dropdown-menu" >
            {{if carts.getNumberProductInCart() > 0 }}
            <div class="top-cart-content arrow_box" >
                <div class="dropdown-label" >
                    <?php echo $this->translate('txt_danh_sach_san_pham_in_cart'); ?> 
                    (${carts.getNumberProductInCart()} <?php echo $this->translate('txt_san_pham'); ?>)
                </div>
                <div id="cart-sidebar" class="mini-products-list count_li" >
                    <div class="clearfix" style="padding: 10px"  >
                        {{each products }}
                        <div class="item clearfix" >
                            <a class="product-image" href="${coz.view.product.getLink($value)}" ${coz.view.product.getTypeView($value)} title="${coz.view.product.getTitle($value)}" rel="nofollow" >
                                <img class="anh-img" alt="${coz.view.product.getTitle($value)}" src="${coz.view.product.getImage($value)}" width="80">
                            </a>
                            <div class="detail-item">
                                <div class="product-details">
                                    <a href="${coz.view.product.getUrlDel($value)}" data-neo="ajax" title="<?php echo $this->translate('txt_xoa')?>" class="fa fa-remove" rel="nofollow" >&nbsp;</a>
                                    <p class="product-name"> 
                                        <a href="${coz.view.product.getLink($value)}" ${coz.view.product.getTypeView($value)} title="${coz.view.product.getTitle($value)}" rel="nofollow" >
                                            ${coz.view.product.getName($value)}
                                        </a>
                                    </p>
                                </div>
                                <div class="product-details-bottom"> 
                                    <span class="price">
                                        ${coz.fomatCurrency(coz.view.product.getPriceSale($value))}
                                    </span> 
                                    <span class="title-desc">
                                        <?php echo $this->translate('txt_so_luong')?> :
                                    </span> 
                                    <strong>
                                        ${coz.view.product.getProductsQuantityInCart($value)}
                                    </strong>
                                </div>
                            </div>
                        </div>
                        <div style="height:10px;"></div>
                        {{/each}}
                    </div>

                    <div class="li-fix-2" >
                        <div class="actions clearfix" >
                            <a href="<?php echo $this->Cart()->getUrlPayment(); ?>" class="btn-checkout" >
                                <span>
                                    <?php echo $this->translate('txt_thanh_toan'); ?>
                                </span>
                            </button>

                            <a class="view-cart" href="<?php echo $this->Cart()->getUrlCart(); ?>" >
                                <span>
                                    <?php echo $this->translate('txt_xem_gio_hang'); ?>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {{else}}
            <div class="top-cart-content arrow_box">
                <div id="cart-sidebar" class="mini-products-list">
                    <div class="dropdown-label" >
                        <?php echo $this->translate('txt_chua_co_san_pham'); ?>
                    </div>
                </div>
            </div>
            {{/if}}
        </div>
    </div>
</script>

<div class="header clearfix" >
    <div class="container" >
        <div class="top-header" >
            <div class="clearfix text-xs-right" >
                <div class="end-bar clearfix" >
                    <a href="" title="" class="nav-link nav-link-blue" >
                        <?php echo $this->translate('txt_request_a_quote') ?>
                    </a>
                </div>
                <div class="user-bar clearfix" >
                    <span class="hidden-sm-down" >
                        <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        <?php if( !$this->User()->hasLogin() ){ ?>
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/sign-in" title="<?php echo $this->translate('txt_login') ?>" class="nav-link" >
                            <?php echo $this->translate('txt_login') ?>
                        </a>/
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/sign-up" title="<?php echo $this->translate('txt_sign_up') ?>" class="nav-link" >
                            <?php echo $this->translate('txt_sign_up') ?>
                        </a>
                        <?php }else{ ?>
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile" title="<?php echo $this->translate('txt_profile') ?>" class="nav-link" >
                            <?php echo $this->translate('txt_xin_chao_ban') ?>
                            <?php echo $this->User()->getFullName() ?>
                        </a>/
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/logout" title="<?php echo $this->translate('txt_logout') ?>" class="nav-link" >
                            <?php echo $this->translate('txt_logout') ?>
                        </a>
                        <?php } ?>
                    </span>
                    <span class="hidden-md-up user-bar-mm" >
                        <a href="javascript:void(0);" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" rel="nofollow" >
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        </a>
                        <div class="dropdown-menu coz-dropdown-menu" >
                            <div class="top-cart-content arrow_box" >
                                <div class="dropdown-label" >
                                    Chao ban
                                </div>
                                <?php if( !$this->User()->hasLogin() ){ ?>
                                <div class="dropdown-item" >
                                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/sign-in" title="<?php echo $this->translate('txt_login') ?>" class="nav-link" >
                                        <?php echo $this->translate('txt_login') ?>
                                    </a>
                                </div>
                                <div class="dropdown-item" >
                                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/sign-up" title="<?php echo $this->translate('txt_sign_up') ?>" class="nav-link" >
                                        <?php echo $this->translate('txt_sign_up') ?>
                                    </a>
                                </div>
                                <?php }else{ ?>
                                <div class="dropdown-item" >
                                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile" title="<?php echo $this->translate('txt_profile') ?>" class="nav-link" >
                                        <?php echo $this->translate('txt_xin_chao_ban') ?>
                                        <?php echo $this->User()->getFullName() ?>
                                    </a>
                                </div>
                                <div class="dropdown-item" >
                                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/logout" title="<?php echo $this->translate('txt_logout') ?>" class="nav-link" >
                                        <?php echo $this->translate('txt_logout') ?>
                                    </a>
                                </div>
                                <?php } ?>
                            </div>
                        </div>
                    </span>
                </div>
                <?php if( !empty($subMenuRoot) ){ ?>
                <div class="sub-navi clearfix hidden-sm-down" >
                    <?php foreach ($subMenuRoot as $key01 => $menu01) { ?>
                    <a href="<?php echo $this->Menus()->getLinkForMenu($menu01); ?>" title="<?php echo $this->Menus()->getName($menu01); ?>" class="nav-link" >
                        <?php echo $this->Menus()->getName($menu01); ?>
                    </a>
                    <?php } ?>
                </div>
                <?php } ?>
            </div>
        </div>
        <div class="bottom-header clearfix" >
            <div class="row" >
                <div class="col-lg-4 col-md-3 col-sm-7 col-xs-7" >
                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('title_site') ?>" class="logo-navi" >
                        <img src="<?php echo $this->Images()->getUrlImage($this->Websites()->getLogo(), 250); ?>" alt="<?php echo $this->translate('title_site') ?>" class="img-fluid" >
                    </a>
                </div>
                <div class="col-lg-8 col-md-9 col-sm-5 col-xs-5" >
                    <div class="wrap-cotrol clearfix text-xs-right" >
                        <div class="search-bar hidden-sm-down" >
                            <form action="<?php echo $this->Websites()->getUrlPrefixLang() ?>/search" class="clearfix" method="GET" >
                                <input type="text" name="keyword" class="input-search" placeholder="<?php echo $this->translate('txt_search_holder') ?>" >
                                <button type="submit" class="btn-search" >
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </form>
                        </div>
                        <a href="" title="" class="link-call-me hidden-sm-down" >
                            <?php echo $this->Html()->mapMacroTranslate('txt_hotline_header', array('{ICON}'=> '<i class="icon i-phone" ></i>') ); ?>
                        </a>
                        <div class="cart-mini" data-place="cartMini" ></div>
                        <a class="btn-togle-mm hidden-md-up" href="javascript:void(0);" data-toggle="collapse" data-target="#main-navigation" rel="nofollow">
                            <span></span>
                            <span></span>
                            <span></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if( !empty($menuRoot) ){ ?>
    <div class="navi-top" >
        <div class="container" >
            <nav class="nav-main collapse navbar-toggleable-md" id="main-navigation" >
                <ul class="nav navbar-nav clearfix">
                    <?php 
                    foreach ($menuRoot as $key01 => $menu01) { 
                        $childrens = $this->Menus()->getChildrens($menus, $this->Menus()->getId($menu01));
                        $categoriesRoot = $this->Categories()->getRoot($categories);
                        $categoriesArticlesRoot = $this->CategoriesArticles()->getRoot($categoryArticles);
                    ?>
                    <li class="nav-item <?php echo $this->Menus()->getClassStatusActive($menu01); ?>" >
                        <a href="<?php echo $this->Menus()->getLinkForMenu($menu01); ?>" class="nav-link" title="<?php echo str_replace('"', '\'', $this->Menus()->getName($menu01)); ?>" data-pjax="true" data-container="Main" itemprop='url' >
                            <span class="inner-text" >
                                <?php echo $this->Menus()->getName($menu01); ?>
                            </span> 
                            <?php 
                            if( $this->Menus()->hasChildrens($menus, $menu01, $categories, $categoryArticles) ){ ?>
                            <span class="direct-drop" >
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                            <?php } ?>
                        </a>
                        <?php 
                        if( !empty($childrens) 
                            && !$this->Menus()->isCollection($menu01)
                            && !$this->Menus()->isBlog($menu01) ){ ?>
                        <ul class="dropdown-menu" >
                            <?php foreach ($childrens as $key02 => $menu02){ ?>
                            <li>
                                <a  href="<?php echo $this->Menus()->getLinkForMenu($menu02); ?>" title="<?php echo str_replace('"', '\'', $this->Menus()->getName($menu02)); ?>" data-pjax="true" data-container="Main" itemprop='url' >
                                    <span class="inner-text" >
                                        <?php echo $this->Menus()->getName($menu02); ?>
                                    </span>                     
                                </a>
                            </li>
                            <?php } ?>
                        </ul>
                        <?php }else if($this->Menus()->isCollection($menu01) 
                            && !empty($categoriesRoot)){ ?>
                        <ul class="dropdown-menu" >
                            <?php 
                            foreach ($categoriesRoot as $key01 => $category01) { 
                                $categoriesChildrens = $this->Categories()->getChildrens($categories, $this->Categories()->getId($category01));
                            ?>
                            <li>
                                <a  href="<?php echo $this->Categories()->getCategoriesUrl($category01); ?>" data-pjax="true" data-container="Main" itemprop='url' >
                                    <span class="inner-text" >
                                        <?php echo $this->Categories()->getTitle($category01); ?> 
                                    </span>
                                    <?php if( !empty($categoriesChildrens) ){ ?>
                                    <span class="direct-drop" >
                                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                    </span> 
                                    <?php } ?>                   
                                </a>
                                <?php if( !empty($categoriesChildrens) ){ ?>
                                <ul class="dropdown-menu" >
                                    <?php 
                                    foreach ($categoriesChildrens as $key02 => $category02){ 
                                        $categoriesChildrens02 = $this->Categories()->getChildrens($categories, $this->Categories()->getId($category02));
                                    ?>
                                    <li>
                                        <a href="<?php echo $this->Categories()->getCategoriesUrl($category02); ?>" title="<?php echo $this->Categories()->getTitle($category02); ?>" data-pjax="true" data-container="Main" itemprop='url' >
                                            <?php echo $this->Categories()->getTitle($category02); ?>
                                            <?php if( !empty($categoriesChildrens02) ){ ?>
                                            <span class="direct-drop" >
                                                <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                            </span> 
                                            <?php } ?> 
                                        </a>
                                        <?php if( !empty($categoriesChildrens02) ){ ?>
                                        <ul class="dropdown-menu">
                                            <?php foreach ($categoriesChildrens02 as $key03 => $category03){ ?>
                                            <li>
                                                <a href="<?php echo $this->Categories()->getCategoriesUrl($category03); ?>" title="<?php echo $this->Categories()->getTitle($category03); ?>" >
                                                    <span class="inner-text" >
                                                        <?php echo $this->Categories()->getTitle($category03); ?>
                                                    </span>
                                                </a>
                                            </li>
                                            <?php } ?>
                                        </ul>
                                        <?php } ?>
                                    </li>
                                    <?php } ?>
                                </ul>
                                <?php } ?>
                            </li>
                            <?php } ?>
                        </ul>
                        <?php }else if( $this->Menus()->isBlog($menu01) 
                            && !empty($categoriesArticlesRoot) ){ ?>
                        <ul class="dropdown-menu" >
                            
                            <?php 
                            foreach ($categoriesArticlesRoot as $key01 => $category01) { 
                                $categoriesArticlesChildrens = $this->CategoriesArticles()->getChildrens($categoryArticles, $this->CategoriesArticles()->getId($category01));
                            ?>
                            <li>
                                <a href="<?php echo $this->CategoriesArticles()->getCategoriesUrl($category01); ?>" title="<?php echo $this->CategoriesArticles()->getTitle($category01); ?>" data-pjax="true" data-container="Main" itemprop='url' >
                                    <span class="inner-text" >
                                        <?php echo $this->CategoriesArticles()->getTitle($category01); ?>
                                    </span>
                                    <?php if( !empty($categoriesArticlesChildrens) ){ ?>
                                    <span class="direct-drop" >
                                        <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                    </span> 
                                    <?php } ?>
                                </a>
                                <?php if( !empty($categoriesArticlesChildrens) ){ ?>
                                <ul class="dropdown-menu" >
                                    <?php 
                                    foreach ($categoriesArticlesChildrens as $key02 => $category02){ 
                                        $categoriesArticlesChildrens02 = $this->CategoriesArticles()->getChildrens($categoryArticles, $this->CategoriesArticles()->getId($category02));
                                    ?>
                                    <li>
                                        <a href="<?php echo $this->CategoriesArticles()->getCategoriesUrl($category02); ?>" title="<?php echo $this->CategoriesArticles()->getTitle($category02); ?>" data-pjax="true" data-container="Main" itemprop='url' >
                                            <span class="inner-text" >
                                                <?php echo $this->CategoriesArticles()->getTitle($category02); ?>
                                            </span>
                                            <?php if( !empty($categoriesArticlesChildrens02) ){ ?>
                                            <span class="direct-drop" >
                                                <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                            </span> 
                                            <?php } ?>
                                        </a>
                                        <?php if( !empty($categoriesArticlesChildrens02) ){ ?>
                                        <ul class="dropdown-menu">
                                            <?php foreach ($categoriesArticlesChildrens02 as $key03 => $category03){ ?>
                                            <li>
                                                <a  href="<?php echo $this->CategoriesArticles()->getCategoriesUrl($category03); ?>" title="<?php echo $this->CategoriesArticles()->getTitle($category03); ?>" data-pjax="true" data-container="Main" itemprop='url' >
                                                    <span class="inner-text" >
                                                        <?php echo $this->CategoriesArticles()->getTitle($category03); ?>
                                                    </span>
                                                </a>
                                            </li>
                                            <?php } ?>
                                        </ul>
                                        <?php } ?>

                                    </li>
                                    <?php } ?>

                                </ul>
                                <?php } ?>

                            </li>
                            <?php } ?>

                        </ul>
                        <?php } ?>
                    </li>
                    <?php } ?>           
                </ul>
            </nav>
        </div>
    </div>
    <?php } ?>
    <div class="hidden-md-up search-bar-mm" >
        <div class="container" >
            <div class="search-bar" >
                <form action="<?php echo $this->Websites()->getUrlPrefixLang() ?>/search" class="clearfix" method="GET" >
                    <input type="text" name="keyword" class="input-search" placeholder="<?php echo $this->translate('txt_search_holder') ?>" >
                    <button type="submit" class="btn-search" >
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>