<?php if( !empty($article) ){ ?>
<div class="item-sm-blog">
    <div class="row" >
        <div class="col-sm-5" >
            <div class="blog-item-image">
                <a href="<?php echo $this->Articles()->getUrl($article); ?>" title="<?php echo $this->Articles()->getTitle($article); ?>" data-pjax="true" data-container="Main" >
                    <img src="<?php echo $this->Images()->getUrlImage($this->Articles()->getImage($article),81); ?>" alt="<?php echo $this->Articles()->getTitle($article); ?>" class="img-fluid" >
                </a>
            </div>
        </div>
        <div class="col-sm-7" >
            <div class="blog-item-title">                               
                <a href="<?php echo $this->Articles()->getUrl($article); ?>" title="<?php echo $this->Articles()->getTitle($article); ?>" data-pjax="true" data-container="Main" >
                    <h2>
                        <?php echo $this->Articles()->getTitle($article); ?>
                    </h2>
                </a>                        
                <p>
                    <?php echo $this->translate('txt_dang') ?>  
                    <?php echo $this->Common()->timeAgo($this->Articles()->getDateCreate($article)); ?>
                </p>                            
            </div>
        </div>
    </div>
</div>
<?php } ?>