<?php  if( !empty($article) ){ ?>
<div class="item-blog">
    <div class="row" >
        <div class="col-sm-4" >
            <div class="blog-item-image">       
                <a href="<?php echo $this->Articles()->getUrl($article); ?>" title="<?php echo $this->Articles()->getTitle($article); ?>" data-pjax="true" data-container="Main" >
                    <img src="<?php echo $this->Images()->getUrlImage($this->Articles()->getImage($article),260, 185); ?>" alt="<?php echo $this->Articles()->getTitle($article); ?>" class="img-fluid" >
                </a>
                    
            </div>
        </div>
        <div class="col-sm-8" >
            <div class="blog-item-title">
                <a href="<?php echo $this->Articles()->getUrl($article); ?>" title="<?php echo $this->Articles()->getTitle($article); ?>" data-pjax="true" data-container="Main" >
                    <h2>
                        <?php echo $this->Articles()->getTitle($article); ?>
                    </h2>
                </a>
                <div class="blog-content-short-description" >
                    <?php echo $this->Articles()->getDescription($article); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php } ?>