<?php 
if( !empty($product) ){
    $price = $this->Products()->getPrice($product);
    $price_sale = $this->Products()->getPriceSale($product);
    $promotion = $this->Products()->getPromotion($product);
?>
<div class="product-sm" >
    <?php if ( !empty($promotion) ){ ?>
    <div class="sale-flash">
        <?php echo $promotion ?>
    </div>
    <?php } ?>
    <div class="thumb-product" >
        <a href="<?php echo $this->Products()->getLink($product) ?>" <?php echo $this->Products()->getTypeView($product) ?> title="<?php echo $this->Products()->getTitle($product); ?>"  data-pjax="true" data-container="Main" >
            <img src="<?php echo $this->Images()->getUrlImage($this->Products()->getImage($product), 290, 250); ?>" alt="<?php echo $this->Products()->getTitle($product); ?>" class="img-fluid" >
        </a>
        <div class="action-sm-product" >
            <form action="<?php echo $this->Websites()->getUrlPrefixLang() ?>/cart/addToCart" data-neo="form" method="post" class="variants pro-action-btn" enctype="multipart/form-data" data-form="addToCart" >
                <input type="hidden" value="<?php echo $this->Products()->getProductsId($product); ?>" name="products_id" data-input="products_id" >
                <?php if ($this->Products()->getToBuy($product)){ ?>
                    <a href="<?php echo $this->Products()->getAddToCartProductsUrl($product) ?>" class="btn-sm-ico" data-neo="ajax" data-role="form" >
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    </a>
                <?php }else{ ?>
                    <a href="<?php echo $this->Products()->getBuyProductsByEmailUrl($product) ?>" class="btn-sm-ico" title="<?php echo $this->translate('txt_register_email') ?>" data-neo="popup" rel="nofollow" >
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    </a>
                <?php } ?>
                <a href="<?php echo $this->Products()->getLink($product) ?>" <?php echo $this->Products()->getTypeView($product) ?> title="<?php echo $this->Products()->getTitle($product); ?>"  data-pjax="true" data-container="Main" class="btn-sm-ico" >
                    <i class="fa fa-eye" aria-hidden="true"></i>
                </a>
                <a href="<?php echo $this->Products()->getHeartProductsUrl($product) ?>" title="<?php echo $this->Products()->getTitle($product); ?>" class="btn-sm-ico" >
                    <i class="fa fa-heart" aria-hidden="true"></i>
                </a>
            </form>
        </div>
    </div>
    <div class="info-product text-xs-center" >
        <?php $rating = $this->Products()->getRating($product) ?>
        <div class="rating-product" >
            <?php for( $i=0; $i<$rating; $i++){ ?>
            <i class="fa fa-star" aria-hidden="true"></i>
            <?php } ?>

            <?php if( $rating != floor($rating) ){ ?>
            <i class="fa fa-star-half-o" aria-hidden="true"></i>
            <?php } ?>

            <?php for( $i=$rating; $i<5; $i++){ ?>
            <i class="fa fa-star-o" aria-hidden="true"></i>
            <?php } ?>
        </div>
        <div class="code-product" >
            <?php echo $this->translate('txt_ma_san_pham'); ?> : 
            <?php echo $this->Products()->getCode($product) ?>
        </div>
        <h2 class="name-product" >
            <a href="<?php echo $this->Products()->getLink($product) ?>" <?php echo $this->Products()->getTypeView($product) ?> title="<?php echo $this->Products()->getTitle($product); ?>"  data-pjax="true" data-container="Main" >
                <?php echo $this->Products()->getTitle($product) ?>
            </a>
        </h2>

        <?php if( $this->Products()->IsAvailablePrice($product) ){ ?>
        <div class="price-product" >
            <span class="price-sale">
                <?php echo $this->Products()->getTypeName($product) ?> 
                <?php echo $this->Currency()->fomatCurrency($price_sale) ?>
            </span>
        </div>
        <?php }else{ ?>
        <div class="price-product" >
            <span class="price-sale">
                <?php echo $this->Products()->stringWhenNotAvailablePrice(); ?>
            </span>
        </div>
        <?php } ?>

        <div class="action-product" >
            <form action="<?php echo $this->Websites()->getUrlPrefixLang() ?>/cart/addToCart" data-neo="form" method="post" class="variants pro-action-btn" enctype="multipart/form-data" data-form="addToCart" >
                <input type="hidden" value="<?php echo $this->Products()->getProductsId($product); ?>" name="products_id" data-input="products_id" >
                <div class="clearfix" >
                    <?php if ($this->Products()->getToBuy($product)){ ?>
                        <a href="<?php echo $this->Products()->getAddToCartProductsUrl($product) ?>" class="btn btn-style" data-neo="ajax" data-role="form" >
                            <?php echo $this->translate('txt_mua_ngay') ?>
                        </a>
                    <?php }else{ ?>
                        <a href="<?php echo $this->Products()->getBuyProductsByEmailUrl($product) ?>" class="btn btn-style" title="<?php echo $this->translate('txt_register_email') ?>" data-neo="popup" rel="nofollow" >
                            <?php echo $this->translate('txt_register_email') ?>
                        </a>
                    <?php } ?>
                </div>
            </form>
        </div>
    </div>
</div>
<?php } ?>