<?php 
    $children = $this->viewModel()->getCurrent()->getChildren();
    $datas = $children[0];
    $favicon = $datas->favicon;
    $has_header = $datas->has_header;
    $has_footer = $datas->has_footer;
?>
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js ie6 oldie" lang="en"><![endif]-->
<!--[if IE 7]><html class="no-js ie7 oldie" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js ie8 oldie" lang="en"><![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en">
    <!--<![endif]-->
    <head>
        <meta name="google-site-verification" content="Jftwx0qdxYqnCbYkt-WwBQ_nRhWokkZrwssOs2haXbQ" />
        <?php   echo $this->headTitle();
                echo $this->headMeta();
                echo $this->Html()
                        ->setContentview( $this )
                        ->setDatas( $datas )
                        ->getMetaHeader();
                echo $this->CSS()
                        ->setContentview( $this )
                        ->setDatas( $datas )
                        ->setHeadLink( array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . $favicon) )
                        ->getStylesheet()
                        ->getHeadLink();
                echo $this->JS()
                        ->setContentview( $this )
                        ->setDatas( $datas )
                        ->getJavascriptHead();
        ?>
    </head>
    <body>
        <div class="page <?php echo $this->CSS()
                                        ->setContentview( $this )
                                        ->setDatas( $datas )
                                        ->getClassConten(); ?>" >
            <?php
                if( $has_header )   
                    echo $this->partial('app/header', array('datas' => $datas) );

                echo '<div class="clearfix" data-pjax-container="Main" role="main" itemprop="mainContentOfPage" >'.$this->content. '</div>';
                
                if( $has_footer )
                    echo $this->partial('app/footer', array('datas' => $datas) );
            ?>
        </div>

        <?php   echo  $this->JS()
                        ->setContentview( $this )
                        ->setDatas( $datas )
                        ->getJavascriptFoot();
                echo  $this->JS()
                        ->setContentview( $this )
                        ->setDatas( $datas )
                        ->getJavascripts()
                        ->getHeadScript();
                echo $this->inlineScript();
        ?>
    </body>
</html>