<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->translate('txt_thong_tin_don_hang') ?></title>
    </head>

    <body>

        <table width="100%" border="0" vspace="0" hspace="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#FFF" style="font-size:14px;font-family: 'Times New Roman', Times, serif;width:100%;margin:0;padding:0;color:#333" >

            <tr >
                <td align="center" valign="top" >
                    <table width="600" border="0" vspace="0" hspace="0" cellspacing="0" cellpadding="0" align="center" >
                        <tr>
                            <td>
                                <p style="display:block;margin:0;padding:10px 0;font-size:12px;" >
                                    <?php echo $this->translate('txt_problem_viewing_this_email') ?> ? 
                                    <i><?php echo $this->translate('txt_view_it_in_browser') ?></i>
                                </p>
                            </td>
                            <td align="right" >
                                <p style="display:block;margin:0;padding:10px 0;text-align:right">
                                    <?php if( !empty($this->Websites()->getUrlFacebook()) ){ ?>
                                    <a href="<?php echo $this->Websites()->getUrlFacebook(); ?>" target="_blank" style="color:#FFF;text-decoration:none" >
                                        facebook
                                    </a>
                                    <?php } ?>

                                    <?php if( !empty($this->Websites()->getUrlTwister()) ){ ?>
                                    <a href="<?php echo $this->Websites()->getUrlTwister(); ?>" target="_blank" style="color:#FFF;text-decoration:none" >
                                        twister
                                    </a>
                                    <?php } ?>

                                    <?php if( !empty($this->Websites()->getUrlGooglePlus()) ){ ?>
                                    <a href="<?php echo $this->Websites()->getUrlGooglePlus(); ?>" target="_blank" style="color:#FFF;text-decoration:none" >
                                        google+
                                    </a>
                                    <?php } ?>

                                    <?php if( !empty($this->Websites()->getUrlRss()) ){ ?>
                                    <a href="<?php echo $this->Websites()->getUrlRss() ?>" target="_blank" style="color:#FFF;text-decoration:none" >
                                        rss
                                    </a>
                                    <?php } ?>

                                    <?php if( !empty($this->Websites()->getUrlYoutube()) ){ ?>
                                    <a href="<?php echo $this->Websites()->getUrlYoutube() ?>" target="_blank" style="color:#FFF;text-decoration:none" >
                                        youtube
                                    </a>
                                    <?php } ?>

                                </p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr bgcolor="#FFF" >
                <td align="center" valign="top" >
                    <table width="600" border="0" vspace="0" hspace="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#FFF" >
                        <tr>
                            <td align="center" >
                                <a href="" style="display:block;padding:20px 0" >
                                    <img src="<?php echo $this->Images()->getUrlImage($this->Websites()->getLogo(), 187, 158); ?>" width="200" alt="" title="" />
                                </a>
                            </td>
                        </tr>
                        
                        <tr>
                            <td valign="top" >
                                <div > 
                                    <?php
                                        $html = $this->translate('welcome_and_thanks_success');
                                        $html = str_replace('{WEBSITE}',$this->Websites()->getDomain(), $html);
                                        $html = str_replace('{FULL_NAME}',$invoice->full_name, $html);
                                        $html = str_replace('{CODE}',$invoice->invoice_title, $html);
                                        $html = str_replace('{DATE}',date('d/m/Y H:i:s', strtotime($invoice->date_create)), $html);
                                        $html = str_replace('{TRANS}',($invoice->delivery == 'no_delivery' ? $this->translate('txt_chua_giao_hang') : ($invoice->delivery == 'delivered' ? $this->translate('txt_da_giao_hang') : $this->translate('txt_dang_giao_hang'))), $html);
                                        $html = str_replace('{PAYMENT}',($invoice->payment == 'paid' ? $this->translate('txt_da_thanh_toan') : $this->translate('txt_chua_thanh_toan')), $html);
                                        echo $html;
                                    ?>
                                </div>
                            </td>
                        </tr>
                        
                        <tr>
                            <td align="right">
                                <p style="margin:0;padding:10px 20px;display:block;color:#333;" >           
                                    <?php echo $this->translate('txt_duoc_dat_luc') ?>: <?php echo date('d/m/Y H:i:s', strtotime($invoice->date_create)) ?>
                                </p>
                            </td>
                        </tr>
                        
                        <tr>
                            <td>
                                <p style="display:block" >
                                    <?php echo $this->translate('txt_tinh_trang_giao_hang') ?>: 
                                    <b style="color:#e10000" ><?php echo $invoice->delivery == 'no_delivery' ? $this->translate('txt_chua_giao_hang') : ($invoice->delivery == 'delivered' ? $this->translate('txt_da_giao_hang') : $this->translate('txt_dang_giao_hang')) ?></b><br  />

                                    <?php echo $this->translate('txt_tinh_trang_thanh_toan') ?>:
                                    <b style="color:#e10000" ><?php echo $invoice->payment == 'paid' ? $this->translate('txt_da_thanh_toan') : $this->translate('txt_chua_thanh_toan') ?></b><br  />

                                    <?php echo $this->translate('txt_ma_so_đon_hang') ?>: <b><?php echo $invoice->invoice_title ?></b>
                                </p>
                            </td>
                        </tr>

                        <tr>
                            <td >
                                <p>
                                    <?php echo $this->translate('danh_sach_san_pham');?>
                                </p>
                                <table style="width: 100%;border-collapse: collapse;border: 1px solid #f5f5f5;" border="1" >
                                    <tr>
                                        <th style="width:10px;padding: 10px;">
                                            #
                                        </th>
                                        <th style="width:10px;padding: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('ma_hang');?>
                                        </th>
                                        <th colspan="6" style="padding: 10px;" >
                                            <?php echo $this->translate('ten_hang'); ?>
                                        </th>
                                        <th style="width:10px;padding: 10px;text-align: right;" colspan="2" >
                                            <?php echo $this->translate('don_gia');?>
                                        </th>
                                        <th style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;" >
                                            <?php echo $this->translate('so_luong');?>
                                        </th>
                                        <th style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;">
                                            <?php echo $this->translate('thanh_tien');?>
                                        </th>
                                        <th style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;">
                                            <?php echo $this->translate('txt_tong_tien');?>
                                        </th>
                                    </tr>
                                    <?php 
                                    $index = 1;
                                    $total_products = 0;
                                    foreach ($cart as $key => $products) {
                                        if($key == 'coupon'  || $key == 'shipping'  ) continue; 
                                        foreach($products['product_type'] as $product_type_id => $row){
                                            $total_products += $row['price_total'];
                                            $extentions = array_merge($row['extensions'], $row['extensions_require']);
                                    ?>
                                    <tr>
                                        <td style="padding: 10px;" <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?>  >
                                            <?php echo $index++ ?>
                                        </td>

                                        <td <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> style="padding: 10px;white-space: nowrap;" >
                                            <?php echo $row['code'] ?>
                                        </td>

                                        <td colspan="6" style="padding: 10px;" >
                                            <a href="/<?php echo $row['alias'] ?>-<?php echo $row['id'] ?>" title="<?php echo $row['title']; ?>">
                                                <?php echo $row['title'] ?>
                                            </a>
                                        </td>

                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" <?php echo empty($row['extensions_require']) ? 'colspan="2"' : '' ?> >
                                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSaleSimple($row)) ?>
                                        </td>

                                        <?php if( !empty($row['extensions_require']) ){ ?>
                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)) ?>
                                        </td>
                                        <?php } ?>

                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                                            <?php echo $this->Cart()->getProductsQuantity($row) ?>
                                        </td>

                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)*$this->Cart()->getProductsQuantity($row)) ?>
                                        </td>

                                        <td <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                            <?php echo $this->Currency()->fomatCurrency($row['price_total']) ?>
                                        </td>

                                    </tr>

                                    <?php
                                    $k_ex = 0; 
                                    if( !empty($row['extensions_require']) ){
                                        foreach ($row['extensions_require'] as $k_ => $ext) {
                                            $quality = $ext['quantity'];
                                    ?>
                                    <tr>
                                        <?php if($k_ex == 0){ ?>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" rowspan="<?php echo count($extentions); ?>" style="padding: 10px" >
                                            <?php echo $this->translate('txt_sp_dinh_kem');?>
                                        </td>
                                        <?php } ?>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo ($k_ex+1); ?>
                                        </td>
                                        <td style="padding: 10px;" colspan="2" >
                                            <?php echo $ext['ext_name'] ?>
                                        </td>
                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                            <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                                        </td>
                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;"><?php echo $quality; ?></td>
                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                            <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                                        </td>
                                    </tr>
                                    <?php $k_ex++; 
                                        }
                                    } ?>

                                    <?php 
                                    if( !empty($row['extensions']) ){
                                        foreach ($row['extensions'] as $k_ => $ext) {
                                            $quality = $ext['quantity'];
                                    ?>
                                    <tr>
                                        <td style="text-align:center;padding: 10px;" >
                                            <?php echo ($k_ex+1); ?>
                                        </td>
                                        <td style="padding: 10px;" colspan="5" >
                                            <?php echo $ext['ext_name'] ?>
                                        </td>
                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                            <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                                        </td>
                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;" ><?php echo $quality; ?></td>
                                        <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                            <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                                        </td>
                                    </tr>
                                    <?php $k_ex++; 
                                        }
                                    } ?>

                                    <?php }
                                    } ?>

                                    <tr>
                                        <td colspan="12" style="text-align:right;padding: 10px;" >
                                            <strong><?php echo $this->translate('txt_tong_phu');?></strong>
                                        </td>
                                        <td style="padding: 10px;text-align: right;color: #e10000;" >
                                            <strong><?php echo $this->Currency()->fomatCurrency($total_orig) ?></strong>
                                        </td>
                                    </tr>

                                    <?php if ( !empty($cart['coupon']) ) { ?>
                                    <tr>
                                        <td colspan="12" style="text-align:right;padding: 10px;" >
                                            <strong><?php echo $this->translate('txt_gia_tri_giam_gia'); ?></strong>
                                        </td>
                                        <td style="padding: 10px;text-align: right;color: #e10000;" >
                                            <strong>
                                                <?php echo $this->Currency()->fomatCurrency($cart['coupon']['coupon_price']) ?>
                                            </strong>
                                        </td>
                                    </tr>
                                    <?php } ?>

                                    <tr>
                                        <td colspan="12" style="text-align:right;padding: 10px;" >
                                            <strong><?php echo $this->translate('txt_phi_van_chuyen'); ?></strong>
                                        </td>
                                        <td style="padding: 10px;text-align: right;color: #e10000;" >
                                            <strong>
                                                <?php echo $this->Currency()->fomatCurrency($fee, 'txt_mien_phi_ship') ?>
                                            </strong>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td colspan="12" style="text-align:right;padding: 10px;" >
                                            <strong><?php echo $this->translate('tong_cong'); ?></strong>
                                        </td>
                                        <td style="padding: 10px;text-align: right;color: #e10000;" >
                                            <strong>
                                                <?php echo $this->Currency()->fomatCurrency($total + $fee) ?>
                                            </strong>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td colspan="12" style="text-align:right;padding: 10px;" >
                                            <strong><?php echo $this->translate('tong_cong_tax'); ?></strong>
                                        </td>
                                        <td style="padding: 10px;text-align: right;color: #e10000;" >
                                            <strong>
                                                <?php echo $this->Currency()->fomatCurrency($total_tax + $fee) ?>
                                            </strong>
                                        </td>
                                    </tr>

                                </table>
                            </td>
                        </tr>
                        
                        <tr>
                            <td style="padding:10px 0px" >
                                <p style="display: block;margin-bottom: 10px" >
                                    <?php echo $this->translate('txt_thong_tin_nguoi_mua'); ?>
                                </p>
                                <table style="width: 100%;border-collapse: collapse;border: 1px solid #f5f5f5;" border="1"  >
                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >    
                                            <?php echo $this->translate('khach_hang');?>
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong><?php echo $invoice->full_name ?></strong>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('so_dien_thoai');?>
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong></strong><?php echo $invoice->phone ?></strong>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('txt_email');?>
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong></strong><?php echo $invoice->email ?></strong>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('txt_dia_chi');?> 
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong>
                                                <?php echo $this->Invoice()->getAddress($invoice); ?>
                                            </strong>
                                        </td>
                                    </tr>

                                </table>
                            </td>
                        </tr>

                        <tr>
                            <td style="padding:10px 0px" >
                                <p style="display: block;margin-bottom: 10px" >
                                    <?php echo $this->translate('txt_thong_tin_van_chuyen'); ?>
                                </p>
                                <table style="width: 100%;border-collapse: collapse;border: 1px solid #f5f5f5;" border="1" >
                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('khach_hang');?>
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong><?php echo $invoice->ships_full_name ?></strong>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('so_dien_thoai');?>
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong></strong><?php echo $invoice->ships_phone ?></strong>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('txt_email');?>
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong><?php echo $invoice->ships_email ?></strong>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('txt_dia_chi');?>
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong>
                                                <?php echo $this->Invoice()->getAddress($invoice, 1); ?>
                                            </strong>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                            <?php echo $this->translate('txt_kieu_van_chuyen');?> 
                                        </td>
                                        <td style="padding: 10px;" >
                                            <strong>
                                                <?php echo ( $transport_type == 0 ? $this->translate('txt_shipping_normal') : $this->translate('txt_shipping_fast')); ?>
                                            </strong>
                                        </td>
                                    </tr>

                                </table>
                            </td>
                        </tr>
                        
                    </table>
                </td>
            </tr>
            
            
        </table>

    </body>
</html>
