<script id="tmplFillterSort" data-place="tmplFillterSort" type="text/x-jQuery-tmpl">
<div>
    <?php echo $this->translate('txt_sap_xep_theo') ?>
    <div class="form-inline form-viewpro" data-form="category" >
        <div class="form-group">
            <select class="form-control sort-by-script neo-trigger-filter" name="sort" data-input="sort" >
                {{each coz.model.fillter.sort.getOptions() }}
                <option value="${coz.model.fillter.sort.getValue($value)}" {{if coz.model.fillter.sort.isSelected($value) }}selected="selected"{{/if}} >
                    ${coz.model.fillter.sort.getText($value)}
                </option>
                {{/each}}
            </select>
        </div>
    </div>
</div>
</script>

<script id="tmplFillterFeature" data-place="tmplFillterFeature" type="text/x-jQuery-tmpl">
<div>
    <div class="bar-fillter clearfix" >
        
        <div class="fillter-item clearfix {{if coz.model.fillter.price.isClose() }}closed{{/if}}" data-place="itemFillter" data-id="price" >
            <div class="header-item-fillter clearfix" data-place="itemHeaderFillter" data-id="price" >
                <a class="fillter-toogle" href="javascript:void(0);" data-btn="toggleFillter" data-id="price" rel="nofollow" >
                    <?php echo $this->translate('txt_loc_theo_gia') ?>
                    <span class="fillter-direct" >
                        {{if coz.model.fillter.price.isClose() }}
                        <i class="fa fa-angle-down" aria-hidden="true"></i>
                        {{else}}
                        <i class="fa fa-angle-up" aria-hidden="true"></i>
                        {{/if}}
                    </span>
                </a>
            </div>
            <div class="body-item-fillter clearfix" data-place="itemBodyFillter" data-id="price" >
                <div class="clearfix wrap-ranger-price" >
                    <input type="text" data-neo="ionRangeSlider"  data-min="${coz.model.fillter.price.getMin()}" data-max="${coz.model.fillter.price.getMax()}" data-grid="true" value="${coz.model.fillter.price.getVal()}" name="price" data-input="price" />
                </div>
                <div class="price-from-to" >
                    ${language.translate('txt_gia_tu')} : 
                    <span class="txt-ranger-from" data-place="valueRangerFrom" >${coz.fomatCurrency(coz.model.fillter.price.getFrom())}</span> - 
                    <span class="txt-ranger-to"  data-place="valueRangerTo" >${coz.fomatCurrency(coz.model.fillter.price.getTo())}</span>
                </div>
            </div>
        </div>

        {{if coz.feature.hasFeature() }}
            {{each coz.feature.getRoot() }}
                {{if coz.feature.hasChild(coz.feature.getID($value)) }}
                <div class="fillter-item clearfix {{if coz.feature.isClose($value) }}closed{{/if}}" data-place="itemFillter" data-id="${coz.feature.getID($value)}" >
                    <div class="header-item-fillter clearfix" data-place="itemHeaderFillter" data-id="${coz.feature.getID($value)}" >
                        <a class="fillter-toogle" href="javascript:void(0);" data-btn="toggleFillter" data-id="${coz.feature.getID($value)}" rel="nofollow" >
                            ${coz.feature.getName($value)}
                            <span class="fillter-direct" >
                                {{if coz.feature.isClose($value) }}
                                <i class="fa fa-angle-down" aria-hidden="true"></i>
                                {{else}}
                                <i class="fa fa-angle-up" aria-hidden="true"></i>
                                {{/if}}
                            </span>
                        </a>
                    </div>
                    <div class="body-item-fillter clearfix" data-place="itemBodyFillter" data-id="${coz.feature.getID($value)}" >
                        <div class="list-fillter-check clearfix" >
                            {{each coz.feature.getChild(coz.feature.getID($value)) }}
                            <div class="coz-item-check {{if coz.feature.isChecked($value) }}checked{{/if}}" data-id="${coz.feature.getID($value)}" >
                                <div class="coz-check-box" >
                                    <span></span>
                                    <input type="checkbox" name="feature[]" value="${coz.feature.getName($value)}" id="filler-${coz.feature.getID($value)}" {{if coz.feature.isChecked($value) }}checked="checked"{{/if}} style="display: none" data-id="${coz.feature.getID($value)}" data-input="feature" >
                                </div>
                                <div class="coz-lable-check" >
                                    <span class="coz-label-check-inner">
                                        ${coz.feature.getName($value)}
                                    </span>
                                    <span class="coz-sum-check" >(${coz.feature.getNum($value)})</span>
                                </div>
                            </div>
                            {{/each}}
                        </div>
                    </div>
                </div>
                {{/if}}
            {{/each}}
        {{/if}}
    </div>
</div>
</script>

<div class="wrap-breadcrumbs clearfix" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <span itemprop="item name" >
                            <?php echo $this->translate('txt_ket_qua_tim_kiem'); ?>
                        </span>
                        (<strong><?php echo $total; ?></strong> <?php echo $this->translate('txt_san_pham_duoc_tim_thay'); ?>)
                        <meta itemprop="position" content="2" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="search-fluid clearfix" >
    <div class="container" >
        <div class="search-advance" >
            <form action="/search" class="clearfix" method="get" >
                <div class="row" >
                    
                    <div class="col-lg-2 col-md-12" >
                        <div class="search-col" >
                            <div class="hidden-md-down" >
                                <div class="img-seach" >
                                    <img src="/styles/dataimages/gift.png" alt="" class="img-fluid" >
                                </div>
                            </div>
                            <div class="hidden-lg-up" >
                                <div class="search-header-mobi text-sm-center" >
                                    <div class="clearfix" >
                                        <i class="ic i-gift" ></i>
                                    </div>
                                    <div class="text-smm" >
                                        <?php echo $this->translate('txt_ban_muon_tang_qua') ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php 
                        $totalCol = 2;
                        $cities = $this->Cities()->loadCitiesByCountry($country_id);
                        $categoriesRoot = $this->Categories()->getRoot($categories);
                        if( !empty($cities) ){
                            $totalCol += 1;
                        }
                        if( !empty($categoriesRoot) ){
                            $totalCol += 1;
                        }
                    ?>
                    
                    <div class="col-lg-7 col-md-12" >
                        <div class="row" >
                            <div class="col-lg-<?php echo (12/$totalCol) ?> col-md-6 col-sm-6" >
                                <div class="search-col" >
                                    <div class="row" >
                                        <div class="col-sm-12" >
                                            <label class="label-search" >
                                                <?php echo $this->translate('txt_khoang_gia') ?>
                                            </label>
                                        </div>
                                        <div class="col-sm-12" >
                                            <div class="input-search has-icon" >
                                                <select class="control-search" name="price" >
                                                    <option value="0;500000" >
                                                        0-<?php echo $this->Currency()->fomatCurrency(500000) ?>
                                                    </option>
                                                    <option value="500000;1000000" >
                                                        <?php echo $this->Currency()->fomatCurrency(500000) ?>-
                                                        <?php echo $this->Currency()->fomatCurrency(1000000) ?>
                                                    </option>
                                                    <option value="1000000;5000000" >
                                                        <?php echo $this->Currency()->fomatCurrency(1000000) ?>-
                                                        <?php echo $this->Currency()->fomatCurrency(5000000) ?>
                                                    </option>
                                                    <option value="5000000;10000000" >
                                                        <?php echo $this->Currency()->fomatCurrency(5000000) ?>-
                                                        <?php echo $this->Currency()->fomatCurrency(10000000) ?>
                                                    </option>
                                                    <option value="10000000;50000000" >
                                                        <?php echo $this->Currency()->fomatCurrency(10000000) ?>-
                                                        <?php echo $this->Currency()->fomatCurrency(50000000) ?>
                                                    </option>
                                                    <option value="50000000;100000000" >
                                                        <?php echo $this->Currency()->fomatCurrency(50000000) ?>-
                                                        <?php echo $this->Currency()->fomatCurrency(100000000) ?>
                                                    </option>
                                                    <option value="100000000" >
                                                        ><?php echo $this->Currency()->fomatCurrency(100000000) ?>
                                                    </option>
                                                </select>
                                                <span class="icon-search" >
                                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <?php if( !empty($cities) ){ ?>
                            <div class="col-lg-<?php echo (12/$totalCol) ?> col-md-6 col-sm-6" >
                                <div class="search-col" >
                                    <div class="row" >
                                        <div class="col-sm-12" >
                                            <label class="label-search" >
                                                <?php echo $this->translate('txt_den_tu_dau') ?>
                                            </label>
                                        </div>
                                        <div class="col-sm-12" >
                                            <div class="input-search has-icon" >
                                                <select class="control-search" name="cities" >
                                                    <?php foreach ($cities as $city){ ?>
                                                    <option value="<?php echo $city['cities_id'] ?>" >
                                                        <?php echo $city['cities_title'] ?>
                                                    </option>
                                                    <?php } ?>
                                                </select>
                                                <span class="icon-search" >
                                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>

                            <?php if( !empty($categoriesRoot) ){ ?>
                            <div class="col-lg-<?php echo (12/$totalCol) ?> col-md-6 col-sm-6" >
                                <div class="search-col" >
                                    <div class="row" >
                                        <div class="col-sm-12" >
                                            <label class="label-search" >
                                                <?php echo $this->translate('txt_tang_hoa_gi') ?>
                                            </label>
                                        </div>
                                        <div class="col-sm-12" >
                                            <div class="input-search has-icon" >
                                                <select class="control-search" name="type" >
                                                    <?php 
                                                    foreach ($categoriesRoot as $key01 => $category01) {
                                                        $childrens = $this->Categories()->getChildrens($categories, $this->Categories()->getId($category01)); 
                                                    ?>
                                                        <?php if( empty($childrens) ){ ?>
                                                        <option value="<?php echo $this->Categories()->getId($category01); ?>" >
                                                            <?php echo $this->Categories()->getTitle($category01); ?>
                                                        </option>
                                                        <?php }else{ ?>
                                                        <optgroup label="<?php echo $this->Categories()->getTitle($category01); ?>" >
                                                            <?php foreach ($childrens as $key02 => $category02){ ?>
                                                            <option value="<?php echo $this->Categories()->getId($category02); ?>" >
                                                                <?php echo $this->Categories()->getTitle($category02); ?>
                                                            </option>
                                                            <?php } ?>
                                                        </optgroup>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </select>
                                                <span class="icon-search" >
                                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>

                            <div class="col-lg-<?php echo (12/$totalCol) ?> col-md-6 col-sm-6" >
                                <div class="search-col" >
                                    <div class="row" >
                                        <div class="col-sm-12" >
                                            <label class="label-search" >
                                                <?php echo $this->translate('txt_thoi_gian') ?>
                                            </label>
                                        </div>
                                        <div class="col-sm-12" >
                                            <div class="input-search has-icon" >
                                                <input type="text" class="control-search datetimepicker" name="time" value="<?php echo date('d-m-Y'); ?>" >
                                                <span class="icon-search" >
                                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-offset-0 col-lg-3 col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8" >
                        <div class="search-col" >
                            <input type="submit" name="" value="<?php echo $this->translate('txt_tang_hoa_ngay') ?>" class="btn btn-search-advance" >
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>

<div class="co-main clearfix" >
    <div class="container">
        <div class="row">

            <section class="col-lg-9 col-lg-push-3" >
                <div class="box-product" >
                    <div class="box-pheading" >
                        <h1 class="title-box" >
                            <?php echo $this->translate('txt_ket_qua_tim_kiem'); ?> : 
                            <b><?php echo $keyword; ?></b>
                        </h1>
                    </div>
                    <div class="box-pbody" id="PjaxProductCategory" data-pjax-container="ProductCategory" >
                        <?php echo $this->partial('application/search/list-product', array('rows' => $rows, 'paging' => $paging, 'total' => $total ) ); ?>
                    </div>
                </div>
            </section>

            <section class="col-lg-3 col-lg-pull-9" >

                <?php echo $this->partial('app/categories-left', array('categories' => $categories) ); ?>

                <div class="fillter-feature clearfix" >
                    <div class="tmpl-fillter-feature clearfix" data-place="fillterFeature" ></div>
                </div>

                <div class="dh-banner" >
                    <div class="inner-dh-banner" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" >
                            <img src="/styles/dataimages/banner.jpg" alt="" class="img-fluid" >
                        </a>
                    </div>
                </div>

            </section>

        </div>
    </div>
</div>