<?php if(!empty($rows)){ ?>
<div class="bar-filter" >
    <div class="row" >
        <div class="col-sm-7" >
            <span class="num-of-result" >
                Showing 1-<?php echo count($rows); ?> of <?php echo $total; ?>
            </span>
        </div>
        <div class="col-sm-5 text-xs-right" >
            <select class="select-filter neo-trigger-filter" name="sort" data-input="sort" >
                <?php echo $this->Html()->getHtmlOptionTagSortFilter(); ?>
            </select>

            <a href="javascript:void(0);" title="" class="switche-view <?php echo empty($view) ? 'active' : ''  ?>" data-btn="switchView" data-value="0" >
                <i class="fa fa-th-large" aria-hidden="true"></i>
                <input type="radio" name="view" value="0" <?php echo empty($view) ? 'checked="checked"' : ''  ?> style="display: none" data-input="view" >
            </a>
            <a href="javascript:void(0);" title="" class="switche-view <?php echo !empty($view) ? 'active' : ''  ?>" data-btn="switchView"  data-value="1" >
                <i class="fa fa-th-list" aria-hidden="true"></i>
                <input type="radio" name="view" value="1" <?php echo !empty($view) ? 'checked="checked"' : ''  ?> style="display: none" data-input="view" >
            </a>
        </div>
    </div>
</div>

<div class="list-product col-padd-empty" >
    <div class="row" >
        <?php foreach ($rows as $key => $p) { ?>
            <div class="col-lg-4 col-md-4 col-sm-6" >
                <?php echo $this->partial('app/item-product', array('product' => $p) ); ?>
            </div>
            <?php if( $key%3 == 0 ){ ?>
            <div class="col-sm-12 hidden-sm-up" >
                <div class="line-grid" ></div>
            </div>
            <?php }else if( $key%3 == 1 ){ ?>
            <div class="col-sm-12 hidden-md-up" >
                <div class="line-grid" ></div>
            </div>
            <?php }else if( $key%3 == 2 ){ ?>
            <div class="col-sm-12 hidden-sm-down" >
                <div class="line-grid" ></div>
            </div>
            <?php } ?>
        <?php } ?>
    </div>
</div>

<div class="bar-filter" >
    <div class="row" >
        <div class="col-sm-7" >
            <span class="num-of-result" >
                Showing 1-<?php echo count($rows); ?> of <?php echo $total; ?>
            </span>
        </div>
        <div class="col-sm-5" >
            <?php if( !empty($paging) ){ ?>
                <div class="co-paging" >
                    <div class="pull-xs-right">
                        <nav class="clearfix">
                            <?php echo $paging; ?>                  
                        </nav>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<?php }else{ ?>
<div class="clearfix" >
    <p class="empty-data" >
        <?php echo $this->translate('txt_dang_cap_nhat') ?>
    </p>
</div>
<?php } ?>