<?php 
if(!empty($rows)){
    foreach ($rows as $key => $p) { ?>
        <div class="col-lg-3 col-md-6 col-sm-6" >
            <?php echo $this->partial('app/item-product', array('product' => $p) ); ?>
        </div>
        <?php if( $key%4 == 1 ){ ?>
        <div class="col-sm-12 hidden-lg-up" >
            <div class="line-grid" ><div class="iline-grid" ></div></div>
        </div>
        <?php }else if( $key%4 == 3 ){ ?>
        <div class="col-sm-12" >
            <div class="line-grid" ><div class="iline-grid" ></div></div>
        </div>
        <?php } ?>
<?php
    }
} ?>