<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        api :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">api</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/api') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/api', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm api mới</a>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="50" style="text-align: center">ID</th>
                                <th style="width:200px">Function</th>
                                <th>Class</th>
                                <th>Module</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($api as $row) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $row['api_id'] ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/api', array('action' => 'edit', 'id' => $row['api_id'])) ?>"><?php echo $row['api_function'] ?></a>
                                    </td>
                                    <td>
                                        <?php echo $row['api_class'] ?>
                                    </td>
                                    <td>
                                        <?php echo $row['api_module'] ?>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $row['api_id'] ?>" />
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="50" style="text-align: center">ID</th>
                                <th style="width:200px">Function</th>
                                <th>Class</th>
                                <th>Module</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/api', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm api mới</a>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->