<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Thành viên :: Danh sách admin
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Danh sách admins</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/user') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/user', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm thành viên mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/user', array('action' => 'publish')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/user', array('action' => 'unpublish')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/user', array('action' => 'delete')) ?>')">
                                Xóa thành viên
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Họ tên</th>
                                <th>Username</th>
                                <th width="150">Ngày đăng ký</th>
                                <th width="100" style="text-align: center">Kích hoạt</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($users as $user) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $user['users_id'] ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/user', array('action' => 'edit', 'id' => $user['users_id'])) ?>"><?php echo $user['full_name'] ?></a>
                                    </td>
                                    <td>
                                        <?php echo $user['user_name'] ?>
                                    </td>
                                    <td><?php echo date('d/m/Y', strtotime($user['date_create'])) ?></td>
                                    <td style="text-align: center">
                                        <?php echo $user['is_published'] == 1 ? 'Hiển thị' : '-' ?>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $user['users_id'] ?>"/>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Họ tên</th>
                                <th>Username</th>
                                <th width="150">Ngày đăng ký</th>
                                <th width="100" style="text-align: center">Kích hoạt</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/user', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm thành viên mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/user', array('action' => 'publish')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/user', array('action' => 'unpublish')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/user', array('action' => 'delete')) ?>')">
                                Xóa thành viên
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->