<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>" >
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li >
                    <a href="<?php echo $this->url('cms/manufacturers') ?>" >
                        <?php echo $this->translate('txt_nha_san_xuat'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_them_moi'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_nha_san_xuat'); ?> :: 
                <?php echo $this->translate('txt_them_moi'); ?>
            </h1>
        </div>
    </div>
</section>

<section class="content" >
    <div class="clearfix">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/manufacturers', array('action' => 'add')));
        $form->setAttribute('enctype', 'multipart/form-data');
        $form->setAttribute('id', 'form-manufacturers');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('manufacturers_id'));
        ?>
        <div class="row" >
            <div class="col-sm-6 col-xs-6" >
                <div class="form-group">
                    <label for="manufacturers_name" >
                        <?php echo $this->translate('txt_ten_nha_xan_xuat'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('manufacturers_name')); ?>
                </div>
            </div>
        </div>

        <div class="form-group" >
            <div class="result-list-img clearfix" >
                <div class="list-img-upload clearfix" ></div>
                <div class="img-prevew-upload btn-upload btn-upload-logo-manufacturers" >
                    <a href="javascript:void(0)" class="action-upload" >
                        <i class="fa fa-plus" aria-hidden="true"></i>
                    </a>
                    <a href="javascript:void(0)" class="img-responsive"  >
                        <i class="fa fa-picture-o" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>

        <div class="form-group" >
            <label for="description">
                <?php echo $this->translate('txt_mo_ta_nha_xan_xuat'); ?>
            </label>
            <?php echo $this->formRow($form->get('description')); ?>
        </div>

        <div class="form-group" >
            <label for="warranty_description">
                <?php echo $this->translate('txt_cho_do_bao_hanh_nha_xan_xuat'); ?>
            </label>
            <?php echo $this->formRow($form->get('warranty_description')); ?>
        </div>

        <div class="form-group" >
            <label for="is_published">
                <?php echo $this->formRow($form->get('is_published')); ?>
                <?php echo $this->translate('txt_kich_hoat'); ?>
            </label>
            <label for="ordering">
                <?php echo $this->translate('txt_thu_tu'); ?>
                <?php echo $this->formRow($form->get('ordering')); ?>
            </label>
        </div>

        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                <?php echo $this->translate('txt_them_moi_nha_san_xuat'); ?>
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                <?php echo $this->translate('txt_quay_lai'); ?>
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>