<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Khuyến mãi :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Khuyến mãi</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/manufacturers') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="
                            <?php echo $this->url('cms/manufacturers', array('action' => 'add-promotion')) ?>"
                                                           class="btn btn-primary">Thêm khuyến mãi mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/manufacturers', array('action' => 'publish-promotion')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/manufacturers', array('action' => 'unpublish-promotion')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/manufacturers', array('action' => 'delete-promotion')) ?>')">
                                Xóa
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Nhà sản xuất</th>
                                <th>Tiêu đề</th>
                                <th width="100" style="text-align: center">Ngày bắt đầu</th>
                                <th width="150">Ngày kết thúc</th>
                                <th width="100" style="text-align: center">Kích hoạt</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($data as $row) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $row['promotions_id'] ?></td>
                                    <td>
                                        <?php echo $row['manufacturers_name'] ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/manufacturers',array('action' => 'edit-promotion', 'id' => $row['promotions_id'])) ?>"><?php echo $row['title'] ?></a>
                                    </td>
                                    <td style="text-align: center">
                                        <?php echo date('d/m/Y', strtotime($row['date_start'])) ?>
                                    </td>

                                    <td><?php echo date('d/m/Y', strtotime($row['date_end'])) ?></td>
                                    <td style="text-align: center">
                                        <?php if($row['is_published'] == 1) : ?>
                                            <?php $href = $this->url('cms/manufacturers', array('action' => 'unpublish-promotion', 'id' => $row['promotions_id'])) ?>
                                        <?php else: ?>
                                            <?php $href = $this->url('cms/manufacturers', array('action' => 'publish-promotion', 'id' => $row['promotions_id'])) ?>
                                        <?php endif; ?>
                                        <?php echo $row['is_published'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Đang hiển thị' data-original-title='Đang hiển thị'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Bị ẩn'><i class='fa fa-circle-o'></i></a>" ?>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $row['promotions_id'] ?>"/>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Nhà sản xuất</th>
                                <th>Tiêu đề</th>
                                <th width="100" style="text-align: center">Ngày bắt đầu</th>
                                <th width="150">Ngày kết thúc</th>
                                <th width="100" style="text-align: center">Kích hoạt</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="
                            <?php echo $this->url('cms/manufacturers', array('action' => 'add-promotion')) ?>"
                               class="btn btn-primary">Thêm khuyến mãi mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/manufacturers', array('action' => 'publish-promotion')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/manufacturers', array('action' => 'unpublish-promotion')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/manufacturers', array('action' => 'delete-promotion')) ?>')">
                                Xóa
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->