<!DOCTYPE html>
<html class="bg-black">
<head>
    <meta charset="UTF-8">
    <title>AdminLTE | Log in</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img_/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/admincp/css/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/admincp/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath() . '/admincp/css/AdminLTE.css')?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="bg-black">

<div class="form-box" id="login-box">
    <div class="header">Sign In</div>
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('cms/login', array('action' => 'authenticate')));
    $form->setAttribute('id', 'form-login');
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <div class="body bg-gray">
        <div class="form-group">
            <?php echo $this->formRow($form->get('username')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('password')); ?>
        </div>
        <div class="form-group">
            <label for="rememberme">
                <?php echo $this->formRow($form->get('rememberme')); ?> Remember me
            </label>
        </div>
    </div>
    <div class="footer">
        <button type="submit" class="btn bg-olive btn-block">Sign me in</button>
        <p><a href="#">I forgot my password</a></p>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
<?php echo $this->headScript()
    ->appendFile($this->basePath() . '/admincp/js/jquery.min.js')
    ->appendFile($this->basePath() . '/admincp/js/bootstrap.min.js')
?>
</body>
</html>