<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        Trang chủ
                    </a>
                </li>
                <li class="active">Chi nhánh</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Chi nhánh :: Quản lý
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/branches') ?>" method="get">
                <div class="coz-search-bar clearfix" data-form="searchAjax" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="Search..." value="<?php echo $q ?>" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo tên
                                    </option>
                                    <option value="1" <?php echo $type == 1 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo địa chỉ
                                    </option>
                                    <option value="2" <?php echo $type == 2 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo số điện thoại
                                    </option>
                                    <option value="3" <?php echo $type == 3 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo email
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/branches') ?>" method="post" class="clearfix" id="form-list-branche"  >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/branches', array('action' => 'add')) ?>"
                   class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm chi nhánh" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($branches) ){ ?>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/branches', array('action' => 'publish')) ?>')" data-toggle="tooltip" data-placement="top" title="Hiện chi nhánh" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/branches', array('action' => 'unpublish')) ?>')" data-toggle="tooltip" data-placement="top" title="Ẩn chi nhánh" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/branches', array('action' => 'autoOrder')) ?>')" data-toggle="tooltip" data-placement="top" title="Cập nhật thứ tự" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/branches', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="Xoá chi nhánh" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="error-box" id="error-box" ></div>
        
        <?php if( !empty($branches) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" ></th>
                        <th class="text-center col-lim" >Id</th>
                        <th class="col-lim" >Tên</th>
                        <th class="col-lim"  >Website</th>
                        <th class="col-lim"  >Email</th>
                        <th class="col-lim text-right"  >Số DT</th>
                        <th >Địa chỉ</th>
                        <th class="col-lim" >
                            <i class="fa fa-sort" aria-hidden="true"></i>
                        </th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody id="container-branches-sort" >
                    <?php foreach ($branches as $row) { ?>
                    <tr>
                        <td class="text-center col-lim drag-handle" >
                            <i class="fa fa-arrows"></i>
                        </td>
                        <td class="text-center col-lim" >
                            <?php echo $row['branches_id'] ?>
                            <input name="ordering[<?php echo $row['branches_id'] ?>]" class="ordering" type="hidden" value="<?php echo $row['ordering'] ?>" >
                        </td>
                        <td class="col-lim"  >
                            <a href="<?php echo $this->url('cms/branches', array('action' => 'edit', 'id' => $row['branches_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa chi nhánh" >
                                <?php echo $row['branches_title'] ?>
                            </a>
                        </td>

                        <td class="col-lim" >
                            <?php echo $row['website'] ?>
                        </td>

                        <td class="col-lim" >
                            <?php echo $row['email'] ?>
                        </td>

                        <td class="col-lim  text-right" >
                            <?php echo $row['phone'] ?>
                        </td>

                        <td >
                            <?php echo $row['address'] ?>
                        </td>
                        <td class="col-lim text-right html-ordering" >
                            <?php echo $row['ordering'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php if( !empty($row['is_default']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Là chi nhánh chính" >
                                    <i class="fa fa-home" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Là chi nhánh thường" >
                                    <i class="fa fa-home" aria-hidden="true"></i>
                                </span>
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>

                        <td class="text-right col-lim" >
                            <a href="<?php echo $this->url('cms/branches', array('action' => 'edit', 'id' => $row['branches_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa chi nhánh" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/branches', array('action' => 'delete', 'id' => $row['branches_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá chi nhánh"  data-confirm="Bạn có muốn xoá ?" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($row['is_default']) ){ ?>
                            <a href="<?php echo $this->url('cms/branches', array('action' => 'undefault', 'id' => $row['branches_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Tắt là chi nhánh chính" >
                                <i class="fa fa-home" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/branches', array('action' => 'default', 'id' => $row['branches_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Bật là chi nhánh chính" >
                                <i class="fa fa-home" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                            <?php if( !empty($row['is_published']) ){ ?>
                            <a href="<?php echo $this->url('cms/branches', array('action' => 'unpublish', 'id' => $row['branches_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn chi nhánh" >
                                <i class="fa fa-toggle-on" aria-hidden="true"></i>
                            </a>
                            <?php }else{ ?>
                            <a href="<?php echo $this->url('cms/branches', array('action' => 'publish', 'id' => $row['branches_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện chi nhánh" >
                                <i class="fa fa-toggle-off" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['branches_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có chi nhánh
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>