<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        goi :: sua
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/pack') ?>">goi</a></li>
        <li class="active">sua</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/pack', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('id', 'form-pack');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('pack_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <button class="btn btn-primary">Lưu lại</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="permissions_name">Tên gói</label>
                        <?php echo $this->formRow($form->get('pack_name')); ?>
                    </div>
                    <div class="form-group">
                        <label for="module">Mô tả</label>
                        <?php echo $this->formRow($form->get('pack_description')); ?>
                    </div>
                    <div class="form-group">
                        <label for="module">price</label>
                        <?php echo $this->formRow($form->get('pack_price')); ?>
                    </div>
                    <div class="form-group">
                        <label for="module">time</label>
                        <?php echo $this->formRow($form->get('time')); ?>
                    </div>
                    <div class="form-group">
                        <label for="module">time bonus</label>
                        <?php echo $this->formRow($form->get('time_bonus')); ?>
                    </div>
                    <div class="form-group">
                        <label for="module">number product</label>
                        <?php echo $this->formRow($form->get('products')); ?>
                    </div>
                    <div class="form-group">
                        <label for="module">bandwidth</label>
                        <?php echo $this->formRow($form->get('bandwidth')); ?>
                    </div>

                    <div class="form-group">
                        <label for="module">storage</label>
                        <?php echo $this->formRow($form->get('storage')); ?>
                    </div>

                    <div class="form-group">
                        <label for="shop">email marketing</label>
                        <?php echo $this->formRow($form->get('email_marketing')); ?>
                    </div>

                    <div class="form-group">
                        <label for="domain">
                            <?php echo $this->formRow($form->get('domain')); ?>
                            domain
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="edit_seo">
                            <?php echo $this->formRow($form->get('edit_seo')); ?>
                            edit seo
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="chat_live">
                            <?php echo $this->formRow($form->get('chat_live')); ?>
                            chat live
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="shop">
                            <?php echo $this->formRow($form->get('shop')); ?>
                            shop online
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="responsive">
                            <?php echo $this->formRow($form->get('responsive')); ?>
                            responsive
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="payment_online">
                            <?php echo $this->formRow($form->get('payment_online')); ?>
                            payment online
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="multi_language">
                            <?php echo $this->formRow($form->get('multi_language')); ?>
                            multi language
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="edit_layout">
                            <?php echo $this->formRow($form->get('edit_layout')); ?>
                            edit layout
                        </label>
                    </div>
                    <div class="form-group">
                        <label for="is_published">
                            <?php echo $this->formRow($form->get('is_published')); ?>
                            hiển thị
                        </label>
                    </div>

                </div>
            </div>

            <?php if(count($modules)>0){ ?>
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Phân quyền theo module</h3>
                </div>
                <div class="box-body">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <ul class="list-group">
                            <?php foreach($modules as $module) : ?>
                                <li class="list-group-item">
                                    <span style="display:inline-block;width:500px;text-overflow: ellipsis;overflow: hidden;white-space: nowrap"><?php echo $module['module_name'] ?></span>
                                    <input type="checkbox" name="modules[]" <?php echo in_array($module['module_id'],$module_access) ? 'checked' : '' ?>  value="<?php echo $module['module_id'] ?>"/>
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <?php } ?>

        </div>
    </div>
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <button class="btn btn-primary">Lưu lại</button>
                <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    </div>
</section>