<div class="coz-wrap-cart-idex clearfix" >
    <div class="container" >
        <div class="row">
        	<div class="clearfix" data-place="hasContainCart" >
	        	<?php 
	            $carts = $this->Cart()->getCart();
	            if( !empty($carts) ){
	            	$caculator = $this->Cart()->sumSubTotalPriceInCart();
	            	$numberProduct = $this->Cart()->getNumberProductInCart();
	            ?>
	            <div class="col-md-9" >
	            	<h1 class="ui-h1-cart-idex" >
	                    <?php echo $this->translate('txt_gio_hang_cua_ban') ?>
	                </h1>
	                <div class="clearfix" >
	                	<div class="title-cart-idex" >
	                		<?php echo str_replace('{NUMBER}', $numberProduct, $this->translate('txt_co_sp_trong_gio_hang')) ?>
	                	</div>
	                	<div class="clearfix" >
	                		<form action="<?php echo $this->url('checkout', array('action' => 'update-cart')) ?>" method="post" data-form="cart" >
	                			<div class="row" >
				                    <div class="col-md-12">
				                        <div class="coz-wrap-cart-form-auth" >
				                            <div class="coz-table-responsive">
				                                <table class="coz-table-cart coz-table-cart-idex" >
				                                    <?php
				                                    $_i = 0; 
			                                        foreach ($carts as $id => $product) {
			                                            foreach ($product['product_type'] as $product_type_id => $p) {
			                                        ?>

			                                        <?php if( !empty($_i) ){ ?>
				                                    <tr class="line-tbl-cart-idex"  data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
				                                    	<td colspan="6" ></td>
				                                    </tr>
				                                    <?php } ?>

				                                    <tr data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
				                                    	<td rowspan="2" >
				                                    		<div class="coz-cart-img" >
				                                    			<a class="img-product-cart" data-place="linkProduct" href="<?php echo $this->Products()->getLink($p) ?>" <?php echo $this->Products()->getTypeView($p) ?> title="<?php echo $this->Products()->getTitle($p) ?>" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
				                                                    <img src="<?php echo $this->Images()->getUrlImage($this->Products()->getImage($p), 84); ?>" alt="<?php echo $this->Products()->getTitle($p) ?>" >
				                                                </a>
				                                    		</div>
				                                    	</td>
				                                    	<td colspan="3" >
			                                    			<a class="coz-cart-product-name" data-place="linkProduct"  href="<?php echo $this->Products()->getLink($p) ?>" <?php echo $this->Products()->getTypeView($p) ?> title="<?php echo $this->Products()->getTitle($p) ?>" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
			                                    				<span data-place="nameProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
		                                                        	<?php echo $this->Products()->getName($p) ?>
		                                                        </span>
		                                                    </a>
				                                    	</td>
				                                    	<td class="coz-text-right" colspan="2" >
				                                    		<div class="clearfix" >
					                                    		<?php 
					                                    			$price = $this->Products()->getPrice($p);
					                                    			$price_sale = $this->Products()->getPriceSale($p);
					                                    			if( $price_sale < $price){
					                                    		?>
					                                    		<div class="coz-cart-price-root"  data-place="priceProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
					                                    			<?php echo $this->Currency()->fomatCurrency($price) ?>
					                                    		</div>
					                                    		<div class="coz-cart-price-sale" >
					                                    			<?php echo $this->translate('txt_giam_con') ?>
					                                    			&nbsp&nbsp
					                                    			<span data-place="priceSaleProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" > 
					                                    				<?php echo $this->Currency()->fomatCurrency($price_sale) ?>
					                                    			</span>
					                                    		</div>
					                                    		<?php }else{ ?>
					                                    		<div class="coz-cart-price-sale" data-place="priceSaleProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" > 
					                                    			<?php echo $this->Currency()->fomatCurrency($price_sale) ?>
					                                    		</div>
					                                    		<?php } ?>
				                                    		</div>
				                                    	</td>
				                                    </tr>
				                                    <tr data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
				                                    	<td >
				                                    		<div class="coz-item-dest-product-cart" >
				                                    			<a href="<?php echo $this->Cart()->getUrlEditProduct($p) ?>" class="coz-btn-edit-item-dest-product-cart" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" data-place="btnEditPropertiesCartProduct" data-pin="[data-type='name'][data-cartid='<?php echo $id.'-'.$product_type_id ?>']" >
				                                    				<i class="fa fa-pencil" aria-hidden="true"></i>
				                                    			</a>
				                                    			<div class="icoz-item-dest-product-cart" >
					                                    			<div class="coz-qual-dest-cart" >
					                                    				<span class="coz-label-des-pro" >
					                                    					<?php echo $this->translate('txt_so_luong'); ?>
					                                    				</span>
					                                    				<span class="coz-label-des-pro" >
					                                    					<span data-place="quantityProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
					                                    						<?php echo $this->Cart()->getProductsQuantity($p) ?>
					                                    					</span>
					                                    					<input type="hidden" value="<?php echo $this->Cart()->getProductsQuantity($p) ?>" name="quantity[<?php echo $this->Products()->getProductsId($p) ?>][<?php echo $this->Products()->getProductTypeId($p) ?>]" data-place="quantityProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
					                                    				</span>
					                                    			</div>
					                                    			<?php $typeName = $this->Products()->getProductTypeName($p);  ?>
					                                    			<div class="coz-qual-dest-cart" data-place="hasTypeName" <?php echo empty($typeName) ? 'style="display:none"' : '' ?> >
					                                    				<span class="coz-label-des-pro" >
					                                    					<?php echo $this->translate('txt_loai_san_pham'); ?>
					                                    				</span>
					                                    				<span class="coz-label-des-pro" data-place="typeNameProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
					                                    					<?php echo $typeName; ?>
					                                    				</span>
					                                    			</div>

					                                    			<?php 
					                                    			$ext = $this->Products()->getExtension($p);
					                                    			$ext_m = $this->Products()->getExtensionRequire($p);
					                                    			$lsExt = array_merge($ext, $ext_m);
					                                    			?>
					                                    			<div class="coz-qual-dest-cart" data-place="hasExtentionProduct" <?php echo empty($lsExt) ? 'style="display:none"' : '' ?> >
					                                    				<span class="coz-label-des-pro" >
					                                    					<?php echo $this->translate('txt_extention_product_on_cart'); ?>
					                                    				</span>
					                                    				<span class="coz-label-des-pro" data-place="extentionProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
					                                    					<?php 
					                                    					foreach ($lsExt as $kex => $itex) {
					                                    						echo (empty($kex) ? '' : ';').$itex['ext_name'];
					                                    					}
					                                    					?>
					                                    				</span>
					                                    			</div>
				                                    			</div>
				                                    		</div>
				                                    	</td>
				                                    	<td colspan="4" class="coz-position-relative" >
				                                    		<span class="coz-cart-product-note" data-place="noteProduct" >
				                                    			<?php echo $this->translate('txt_tong_tien_payment') ?>&nbsp&nbsp
					                                    		<span class="coz-product-price" data-place="priceTotalProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" > 
				                                    				<?php echo $this->Currency()->fomatCurrency($p['price_total']) ?>
				                                    			</span><br />
				                                    			<span class="coz-text-price-not-tax" >
					                                    			<?php echo $this->translate('txt_gia_khong_bao_gom_thue_payment') ?>
					                                    		</span>
				                                    		</span>
				                                    		<a class="coz-btn-cart-remove-product" href="<?php echo $this->Cart()->getUrlDel($p) ?>" data-btn="delCartProduct"  data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" rel="nofollow" >
				                                    			<i class="fa fa-times" aria-hidden="true"></i>
				                                    		</a>
				                                    	</td>
				                                    </tr>

				                                    <?php }
		                                        	} ?>
				                                </table>
				                            </div>
				                        </div>
				                    </div>
				                </div>

				                <div class="col-xs-12 coz-text-center" >
				                    <button class="coz-btn-flat" >
					                    <?php echo $this->translate('txt_cap_nhat_gio_hang') ?>
					                </button>
								</div>
							</form>
	                	</div>
	                </div>
	            </div>

	            <div class="col-md-3" >
	            	<h2 class="ui-h1-cart-idex" >
	                    <?php echo $this->translate('txt_tom_tat_don_hang') ?>
	                </h2>
	            	<?php $coupon = $this->Coupons()->getCoupon(); ?>
			        <div class="box-coupon-cart-idex clearfix coz-coupon-summary-cart-index"  data-place="coupon" >

			            <div class="clearfix" data-place="notHasCoupon" <?php echo (!empty($coupon) ? 'style="display:none"' : '') ?> >
			                <div class="title-coupon-cart-idex" >
			                    <?php echo $this->translate('txt_nhap_ma_giam_gia') ?>
			                </div>
			                <a href="javascript:void(0);" class="btn-js-toggle-coupon" data-btn="hideFormCoupon" rel="nofollow" >
			                    <i class="fa fa-times" aria-hidden="true"></i>
			                </a>
			                <div class="form-coupon-cart-idex" >
			                    <div class="clearfix" >
			                        <div class="formCoupon" data-form="formCoupon" >
			                            <div class="coz-input-group" >
			                                <div class="coz-form-control" >
			                                    <div class="ui-input-payment" >
			                                        <input id="couponCode" name="couponcode" class="input-payment" type="text" placeholder="<?php echo $this->translate('txt_nhap_ma_giam_gia') ?>" value="" data-input="coupon" >
			                                    </div>
			                                </div>
			                                <div class="coz-input-group-addon" >
			                                    <a href="javascript:void(0);" class="coz-btn-flat coz-btn-flat-active coz-btn-flat-block" data-btn="btnAppCounpon" >
			                                       <?php echo $this->translate('txt_app_ma_giam_gia') ?>                        
			                                    </a>
			                                </div>
			                            </div>
			                        </div>
			                    </div>
			                </div>
			            </div>

			            <div class="clearfix" <?php echo (empty($coupon) ? 'style="display:none"' : '') ?> data-place="hasCoupon" >
			                <div class="title-coupon-cart-idex" >
			                    <?php echo $this->translate('txt_ma_giam_gia_hien_tai') ?>
			                </div>
			                <a href="javascript:void(0);" class="btn-js-toggle-coupon" data-btn="hideFormCoupon" rel="nofollow" >
			                    <i class="fa fa-times" aria-hidden="true"></i>
			                </a>
			                <div class="form-coupon-cart-idex" >
			                    <div class="clearfix" >
			                        <div class="row" >
			                            <div class="col-sm-10" >
			                                <label class="ui-lb-payment">
			                                    <?php echo $this->translate('txt_ma_coupon_payment') ?> : 
			                                    <span class="coz-curent-coupon" data-place="valueCouponCode" ><?php echo (empty($coupon) ? '' : $coupon['coupons_code'] ) ?></span>
			                                </label>
			                            </div>
			                            <div class="col-sm-2" >
			                                <a href="javascript:void(0);" title="<?php echo $this->translate('txt_sua_coupon_payment') ?>" data-btn="btnEditCounpon" rel="nofollow" >
			                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
			                                </a>
			                                <a href="javascript:void(0);" title="<?php echo $this->translate('txt_xoa_coupon_payment') ?>" data-btn="btnRemoveCounpon" rel="nofollow" >
			                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
			                                </a>
			                            </div>
			                            <div class="col-sm-12" >
			                                <label class="ui-lb-payment" >
			                                    <?php echo $this->translate('txt_gia_tri_coupon_payment') ?> : 
			                                    <span class="coz-value-coupon" data-place="valueCoupon" >
			                                        <?php echo $this->Coupons()->getPriceWithCurrency() ?>
			                                    </span>
			                                </label>
			                            </div>
			                        </div>
			                    </div>
			                </div>
			            </div>

			        </div>

	            	<table class="table table-bordered total-table">
						<tbody>
							<tr>
								<td class="text-xs-left">
									<?php echo $this->translate('txt_tong_tien') ?>
								</td>
								<td class="text-xs-right">
									<div class="coz-product-price" data-place="priceCartTotalOrig" >
										<?php echo $this->Currency()->fomatCurrency($caculator['price_total_orig']) ?>
									</div>
								</td>
							</tr>

							<tr <?php echo ( empty($coupon) ? 'style="display:none"' : '') ?> id="coz-tr-coupon-payment" data-place="hasCoupon" >
		                        <td class="text-xs-left">
		                            <?php echo $this->translate('txt_giam_gia_payment') ?>
		                        </td>
		                        <td class="text-xs-right">
		                            <div class="coz-product-price" data-place="valueCoupon" >
		                                <?php echo $this->Coupons()->getPriceWithCurrency() ?>
		                            </div>
		                        </td>
		                    </tr>

							<?php if( $caculator['price_total'] < $caculator['price_total_tax'] ){ ?>
							<tr data-place="hasPriceCartTax" >
								<td class="text-xs-left">
									<?php echo $this->translate('txt_tien_thue_payment') ?>
								</td>
								<td class="text-xs-right">
									<div class="coz-product-price" data-place="priceCartTax" >
										<?php echo $this->Currency()->fomatCurrency($caculator['price_total_tax'] - $caculator['price_total']) ?>
									</div>
								</td>
							</tr>
							<?php } ?>

							<tr>
								<td class="text-xs-left">
									<?php echo $this->translate('txt_lb_total_tax_payment') ?>
								</td>
								<td class="text-xs-right">
									<div class="coz-product-price"  data-place="priceCartTotalTax" >
										<?php echo $this->Currency()->fomatCurrency($caculator['price_total_tax']) ?>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<div class="list-action-cart-idex clearfix" >
						<a href="<?php echo $this->url('checkout', array('action' => 'process')) ?>" class="coz-btn-flat coz-btn-flat-active coz-btn-flat-block coz-mgb" title="<?php echo $this->translate('txt_thanh_toan') ?>" rel="nofollow" >
							<span><?php echo $this->translate('txt_thanh_toan') ?></span>
						</a>

						<a href="<?php echo $this->Link()->getCategoryUrl() ?>" class="coz-btn-flat  coz-btn-flat-block" title="<?php echo $this->translate('txt_mua_tiep') ?>" rel="nofollow" >
							<span><?php echo $this->translate('txt_mua_tiep') ?></span>
						</a>
					</div>
	            </div>
	            <?php } ?>
	        </div>

            <div class="col-sm-12" data-place="notContainCart" <?php echo (empty($carts) ? 'style="display:none"' : '') ?> >
            	<h1 class="ui-h1-cart-idex" >
                    <?php echo $this->translate('txt_gio_hang_cua_ban') ?>
                </h1>
                <p class="coz-cart-empty">
                    <?php echo $this->translate('txt_chua_co_san_pham_trong_cart') ?>
                </p>
            </div>
        </div>
    </div>
</div>