<div class="header-cart clearfix" >
	<div class="container" >
        <div class="row" >
            <div class="col-lg-4 col-md-3 col-sm-7 col-xs-7" >
                <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('title_site') ?>" class="logo-navi" >
                    <img src="<?php echo $this->Images()->getUrlImage($this->Websites()->getLogo(), 250); ?>" alt="<?php echo $this->translate('title_site') ?>" class="img-fluid" >
                </a>
            </div>
            <div class="col-lg-8 col-md-9 col-sm-5 col-xs-5" ></div>
        </div>
    </div>
</div>

<div class="coz-wrap-cart-idex clearfix" >
    <div class="container" >
        <div class="row">
        	<div class="clearfix" data-place="hasContainCart" >
	        	<?php 
	            $carts = $this->Cart()->getCart();
	            if( !empty($carts) ){
	            	$caculator = $this->Cart()->sumSubTotalPriceInCart();
	            	$numberProduct = $this->Cart()->getNumberProductInCart();
	            ?>
	            <div class="col-xs-12" >
	            	<h1 class="ui-h1-cart-idex" >
	                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" class="small-link" title="<?php echo $this->translate('txt_mua_tiep') ?>" >
	                    	<i class="fa fa-chevron-left" aria-hidden="true"></i>
	                    	<?php echo $this->translate('txt_mua_tiep') ?>
	                    </a>
	                    <?php echo $this->translate('txt_gio_hang_cua_ban') ?>
	                </h1>
	            </div>
	            <div class="col-md-8" >
	                <div class="clearfix" >
	                	<div class="clearfix" >
	                		<form action="<?php echo $this->url('checkout', array('action' => 'update-cart')) ?>" method="post" data-form="cart" >
	                			<div class="row" >
				                    <div class="col-md-12">
				                        <div class="coz-wrap-cart-form-auth" >
				                            <div class="coz-table-responsive">
				                                <table class="coz-table-cart-idex" >
				                                	<thead>
			                                        	<tr>
			                                        		<th class="lm-ran text-xs-center" >
			                                        			<?php echo $this->translate('txt_san_pham') ?>
			                                        		</th>
			                                        		<th class="text-xs-center" >
			                                        			<?php echo $this->translate('txt_ten') ?>
			                                        		</th>
			                                        		<th class="lm-ran text-xs-center" >
			                                        			<?php echo $this->translate('txt_gia') ?>
			                                        		</th>
			                                        		<th class="lm-ran text-xs-center" >
			                                        			<?php echo $this->translate('txt_so_luong') ?>
			                                        		</th>
			                                        		<th class="lm-ran text-xs-center" ></th>
			                                        	</tr>
			                                        	<tr class="tr-empty">
			                                        		<td colspan="5" ></td>
			                                        	</tr>
			                                        </thead>
			                                        <tbody>
				                                    <?php
				                                    $_i = 0; 
			                                        foreach ($carts as $id => $product) {
			                                            foreach ($product['product_type'] as $product_type_id => $p) {
			                                        ?>
			                                        	<tr data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
			                                        		<td class="lm-ran" >
			                                        			<a class="img-pcart" data-place="linkProduct" href="<?php echo $this->Products()->getLink($p) ?>" <?php echo $this->Products()->getTypeView($p) ?> title="<?php echo $this->Products()->getTitle($p) ?>" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
				                                                    <img src="<?php echo $this->Images()->getUrlImage($this->Products()->getImage($p), 84); ?>" alt="<?php echo $this->Products()->getTitle($p) ?>" >
				                                                </a>
			                                        		</td>

			                                        		<td>
			                                        			<a class="name-pcart" data-place="linkProduct"  href="<?php echo $this->Products()->getLink($p) ?>" <?php echo $this->Products()->getTypeView($p) ?> title="<?php echo $this->Products()->getTitle($p) ?>" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
				                                    				<span data-place="nameProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
			                                                        	<?php echo $this->Products()->getName($p) ?>
			                                                        </span>
			                                                    </a>
			                                                    <?php $typeName = $this->Products()->getProductTypeName($p);  ?>
				                                    			<div class="coz-qual-dest-cart" data-place="hasTypeName" <?php echo empty($typeName) ? 'style="display:none"' : '' ?> >
				                                    				<span class="coz-label-des-pro" >
				                                    					<?php echo $this->translate('txt_loai_san_pham'); ?>
				                                    				</span>
				                                    				<span class="coz-label-des-pro" data-place="typeNameProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
				                                    					<?php echo $typeName; ?>
				                                    				</span>
				                                    			</div>

				                                    			<?php 
				                                    			$ext = $this->Products()->getExtension($p);
				                                    			$ext_m = $this->Products()->getExtensionRequire($p);
				                                    			$lsExt = array_merge($ext, $ext_m);
				                                    			?>
				                                    			<div class="coz-qual-dest-cart" data-place="hasExtentionProduct" <?php echo empty($lsExt) ? 'style="display:none"' : '' ?> >
				                                    				<span class="coz-label-des-pro" >
				                                    					<?php echo $this->translate('txt_extention_product_on_cart'); ?>
				                                    				</span>
				                                    				<span class="coz-label-des-pro" data-place="extentionProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
				                                    					<?php 
				                                    					foreach ($lsExt as $kex => $itex) {
				                                    						echo (empty($kex) ? '' : ';').$itex['ext_name'];
				                                    					}
				                                    					?>
				                                    				</span>
				                                    			</div>
			                                        		</td>

			                                        		<td class="lm-ran" >
			                                        			<?php 
					                                    			$price = $this->Products()->getPrice($p);
					                                    			$price_sale = $this->Products()->getPriceSale($p);
					                                    		?>
				                                    			<div class="price-pcart" data-place="priceSaleProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" > 
					                                    			<?php echo $this->Currency()->fomatCurrency($price_sale) ?>
					                                    		</div>
			                                        			<span class="tax-pcart" >
			                                        				<?php echo $this->translate('txt_gia_khong_bao_gom_thue_payment') ?>
			                                        			</span>
			                                        		</td>

			                                        		<td class="lm-ran" >
			                                        			<div class="plugin-quantity" data-plugin="quantity" data-cart="true" >
		                                                            <span class="quantity-down" data-btn="downQuantity">
		                                                                <i class="fa fa-minus" aria-hidden="true"></i>
		                                                            </span>
		                                                            <input type="text" class="input-product-quantity" value="<?php echo $this->Cart()->getProductsQuantity($p) ?>" name="quantity[<?php echo $this->Products()->getProductsId($p) ?>][<?php echo $this->Products()->getProductTypeId($p) ?>]" data-place="quantityProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" data-input="quantity" >
		                                                            <span class="quantity-up" data-btn="upQuantity">
		                                                                <i class="fa fa-plus" aria-hidden="true"></i>
		                                                            </span>
		                                                        </div>
			                                        		</td>

			                                        		<td class="lm-ran ls-option" >
			                                        			<a class="del-pcart" href="<?php echo $this->Cart()->getUrlDel($p) ?>" data-btn="delCartProduct"  data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" rel="nofollow" >
					                                    			<i class="fa fa-times" aria-hidden="true"></i>
					                                    		</a>
			                                        		</td>
			                                        	</tr>

			                                        	<tr class="tr-empty">
			                                        		<td colspan="5" ></td>
			                                        	</tr>
				                                    <?php }
		                                        	} ?>
		                                        	</tbody>
				                                </table>
				                            </div>
				                        </div>
				                    </div>
				                </div>
							</form>
	                	</div>
	                </div>
	            </div>

	            <div class="col-md-4" >
	            	<h2 class="tsum-cart-idex" >
	                    <?php echo $this->translate('txt_tom_tat_don_hang') ?>
	                </h2>
	            	<?php $coupon = $this->Coupons()->getCoupon(); ?>
			        <div class="box-coupon-cart-idex clearfix coz-coupon-summary-cart-index"  data-place="coupon" >

			            <div class="clearfix" data-place="notHasCoupon" <?php echo (!empty($coupon) ? 'style="display:none"' : '') ?> >
			                <div class="title-coupon-cart-idex" >
			                    <?php echo $this->translate('txt_nhap_ma_giam_gia') ?>
			                </div>
			                <a href="javascript:void(0);" class="btn-js-toggle-coupon" data-btn="hideFormCoupon" rel="nofollow" >
			                    <i class="fa fa-times" aria-hidden="true"></i>
			                </a>
			                <div class="form-coupon-cart-idex" >
			                    <div class="clearfix" >
			                        <div class="formCoupon" data-form="formCoupon" >
			                            <div class="coz-input-group" >
			                                <div class="coz-form-control" >
			                                    <div class="ui-input-payment" >
			                                        <input id="couponCode" name="couponcode" class="input-payment" type="text" placeholder="<?php echo $this->translate('txt_nhap_ma_giam_gia') ?>" value="" data-input="coupon" >
			                                    </div>
			                                </div>
			                                <div class="coz-input-group-addon" >
			                                    <a href="javascript:void(0);" class="coz-btn-flat coz-btn-flat-active coz-btn-flat-block" data-btn="btnAppCounpon" >
			                                       <?php echo $this->translate('txt_app_ma_giam_gia') ?>                        
			                                    </a>
			                                </div>
			                            </div>
			                        </div>
			                    </div>
			                </div>
			            </div>

			            <div class="clearfix" <?php echo (empty($coupon) ? 'style="display:none"' : '') ?> data-place="hasCoupon" >
			                <div class="title-coupon-cart-idex" >
			                    <?php echo $this->translate('txt_ma_giam_gia_hien_tai') ?>
			                </div>
			                <a href="javascript:void(0);" class="btn-js-toggle-coupon" data-btn="hideFormCoupon" rel="nofollow" >
			                    <i class="fa fa-times" aria-hidden="true"></i>
			                </a>
			                <div class="form-coupon-cart-idex" >
			                    <div class="clearfix" >
			                        <div class="row" >
			                            <div class="col-sm-10" >
			                                <label class="ui-lb-payment">
			                                    <?php echo $this->translate('txt_ma_coupon_payment') ?> : 
			                                    <span class="coz-curent-coupon" data-place="valueCouponCode" ><?php echo (empty($coupon) ? '' : $coupon['coupons_code'] ) ?></span>
			                                </label>
			                            </div>
			                            <div class="col-sm-2" >
			                                <a href="javascript:void(0);" title="<?php echo $this->translate('txt_sua_coupon_payment') ?>" data-btn="btnEditCounpon" rel="nofollow" >
			                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
			                                </a>
			                                <a href="javascript:void(0);" title="<?php echo $this->translate('txt_xoa_coupon_payment') ?>" data-btn="btnRemoveCounpon" rel="nofollow" >
			                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
			                                </a>
			                            </div>
			                            <div class="col-sm-12" >
			                                <label class="ui-lb-payment" >
			                                    <?php echo $this->translate('txt_gia_tri_coupon_payment') ?> : 
			                                    <span class="coz-value-coupon" data-place="valueCoupon" >
			                                        <?php echo $this->Coupons()->getPriceWithCurrency() ?>
			                                    </span>
			                                </label>
			                            </div>
			                        </div>
			                    </div>
			                </div>
			            </div>

			        </div>

	            	<table class="table coz-table-summary total-table">
						<tbody>
							<tr>
								<td class="text-xs-left">
									<?php echo $this->translate('txt_tong_tien') ?>
								</td>
								<td class="text-xs-right">
									<div class="p-price" data-place="priceCartTotalOrig" >
										<?php echo $this->Currency()->fomatCurrency($caculator['price_total_orig']) ?>
									</div>
								</td>
							</tr>

							<tr <?php echo ( empty($coupon) ? 'style="display:none"' : '') ?> id="coz-tr-coupon-payment" data-place="hasCoupon" >
		                        <td class="text-xs-left">
		                            <?php echo $this->translate('txt_giam_gia_payment') ?>
		                        </td>
		                        <td class="text-xs-right">
		                            <div class="p-price" data-place="valueCoupon" >
		                                <?php echo $this->Coupons()->getPriceWithCurrency() ?>
		                            </div>
		                        </td>
		                    </tr>

							<?php if( $caculator['price_total'] < $caculator['price_total_tax'] ){ ?>
							<tr data-place="hasPriceCartTax" >
								<td class="text-xs-left">
									<?php echo $this->translate('txt_tien_thue_payment') ?>
								</td>
								<td class="text-xs-right">
									<div class="p-price" data-place="priceCartTax" >
										<?php echo $this->Currency()->fomatCurrency($caculator['price_total_tax'] - $caculator['price_total']) ?>
									</div>
								</td>
							</tr>
							<?php } ?>

							<tr>
								<td class="text-xs-left">
									<?php echo $this->translate('txt_lb_total_tax_payment') ?>
								</td>
								<td class="text-xs-right">
									<div class="p-price" >
										<b data-place="priceCartTotalTax" >
											<?php echo $this->Currency()->fomatCurrency($caculator['price_total_tax']) ?>
										</b>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					<div class="clearfix" >
						<a href="<?php echo $this->url('checkout', array('action' => 'address')) ?>" class="coz-btn-flat coz-btn-flat-active coz-btn-flat-block coz-mgb" title="<?php echo $this->translate('txt_thanh_toan') ?>" rel="nofollow" >
							<span><?php echo $this->translate('txt_thanh_toan') ?></span>
						</a>
					</div>
	            </div>
	            <?php } ?>
	        </div>

            <div class="col-sm-12" data-place="notContainCart" <?php echo (empty($carts) ? 'style="display:none"' : '') ?> >
            	<h1 class="ui-h1-cart-idex" >
                    <?php echo $this->translate('txt_gio_hang_cua_ban') ?>
                </h1>
                <p class="coz-cart-empty">
                    <?php echo $this->translate('txt_chua_co_san_pham_trong_cart') ?>
                </p>
            </div>

            <div class="group-method clearfix" >
		        <div class="row" >
		        	<div class="col-md-9" >
		        		<div class="row" >
				        	<div class="col-md-5" >
				        		<h2 class="tpay-methods" >
				                    <?php echo $this->translate('txt_ds_payment_method') ?>
				                </h2>
				                <div class="pay-methods" >
				                	<div class="row" >
				                		<div class="col-sm-4" >
						                	<div class="ipay-methods" >
						                		<a href="javascript:void(0);" title="<?php echo $this->translate('txt_alt_paypal') ?>" >
						                			<img src="/styles/dataimages/paypal.png" class="img-fluid" alt="<?php echo $this->translate('txt_alt_paypal') ?>" >
						                		</a>
						                	</div>
					                	</div>

					                	<div class="col-sm-4" >
						                	<div class="ipay-methods" >
						                		<a href="javascript:void(0);" title="<?php echo $this->translate('txt_alt_visa') ?>" >
						                			<img src="/styles/dataimages/visa.png" class="img-fluid" alt="<?php echo $this->translate('txt_alt_visa') ?>" >
						                		</a>
						                	</div>
					                	</div>

					                	<div class="col-sm-4" >
						                	<div class="ipay-methods" >
						                		<a href="javascript:void(0);" title="<?php echo $this->translate('txt_alt_mastercard') ?>" >
						                			<img src="/styles/dataimages/mastercard.png" class="img-fluid" alt="<?php echo $this->translate('txt_alt_mastercard') ?>" >
						                		</a>
						                	</div>
					                	</div>
				                	</div>
				                </div>
				        	</div>
				        	<div class="col-md-5 col-md-offset-1" >
				        		<h2 class="tpay-methods" >
				                    <?php echo $this->translate('txt_ds_shipment_method') ?>
				                </h2>
				                <div class="pay-methods" >
				                	<div class="row" >
				                		<div class="col-sm-4" >
						                	<div class="ipay-methods" >
						                		<a href="javascript:void(0);" title="<?php echo $this->translate('txt_alt_couriersplease') ?>" >
						                			<img src="/styles/dataimages/couriersplease.jpg" class="img-fluid" alt="<?php echo $this->translate('txt_alt_couriersplease') ?>" >
						                		</a>
						                	</div>
					                	</div>

					                	<div class="col-sm-4" >
						                	<div class="ipay-methods" >
						                		<a href="javascript:void(0);" title="<?php echo $this->translate('txt_alt_ups') ?>" >
						                			<img src="/styles/dataimages/ups.png" class="img-fluid" alt="<?php echo $this->translate('txt_alt_ups') ?>" >
						                		</a>
						                	</div>
					                	</div>

					                	<div class="col-sm-4" >
						                	<div class="ipay-methods" >
						                		<a href="javascript:void(0);" title="<?php echo $this->translate('txt_alt_australiapost') ?>" >
						                			<img src="/styles/dataimages/australiapost.png" class="img-fluid" alt="<?php echo $this->translate('txt_alt_australiapost') ?>" >
						                		</a>
						                	</div>
					                	</div>
				                	</div>
				                	<div class="row" >
				                		<div class="col-sm-4" >
						                	<div class="ipay-methods" >
						                		<a href="javascript:void(0);" title="<?php echo $this->translate('txt_alt_dhl') ?>" >
						                			<img src="/styles/dataimages/dhl.jpg" class="img-fluid" alt="<?php echo $this->translate('txt_alt_dhl') ?>" >
						                		</a>
						                	</div>
					                	</div>

					                	<div class="col-sm-4" >
						                	<div class="ipay-methods" >
						                		<a href="javascript:void(0);" title="<?php echo $this->translate('txt_alt_tnt') ?>" >
						                			<img src="/styles/dataimages/tnt.png" class="img-fluid" alt="<?php echo $this->translate('txt_alt_tnt') ?>" >
						                		</a>
						                	</div>
					                	</div>
				                	</div>
				                </div>
				        	</div>
			        	</div>
		        	</div>
		        </div>
	        </div>

	        <div class="list-descript-idex-cart clearfix" >
	        	<div class="row" >
	        		
	        		<div class="col-sm-4" >
		        		<div class="item-idex-cart clearfix" >
		        			<h3 class="lb-descript-idex-cart" >
		        				<?php echo $this->translate('txt_tit_descript_cart_idex_01') ?>
		        			</h3>
		        			<div class="nd-descript-idex-cart" >
		        				<?php echo $this->translate('txt_des_descript_cart_idex_01') ?>
		        			</div>
		        		</div>
	        		</div>

	        		<div class="col-sm-4" >
		        		<div class="item-idex-cart clearfix" >
		        			<h3 class="lb-descript-idex-cart" >
		        				<?php echo $this->translate('txt_tit_descript_cart_idex_02') ?>
		        			</h3>
		        			<div class="nd-descript-idex-cart" >
		        				<?php echo $this->translate('txt_des_descript_cart_idex_02') ?>
		        			</div>
		        		</div>
	        		</div>

	        		<div class="col-sm-4" >
		        		<div class="item-idex-cart clearfix" >
		        			<h3 class="lb-descript-idex-cart" >
		        				<?php echo $this->translate('txt_tit_descript_cart_idex_03') ?>
		        			</h3>
		        			<div class="nd-descript-idex-cart" >
		        				<?php echo $this->translate('txt_des_descript_cart_idex_03') ?>
		        			</div>
		        		</div>
	        		</div>

	        	</div>
	        </div>

        </div>
    </div>
</div>