<?php 
$carts = $this->Cart()->getCart();
if( !empty($carts) ){
    $caculator = $this->Cart()->sumSubTotalPriceInCart();
?>
<div class="coz-tab-step  coz-position-relative" >
    <div class="coz-nav-tab-step clearfix coz-tab2">
        <a href="#tab-shipping-payment" class="coz-item-nav-tab-step active" >
            <?php echo $this->translate('txt_tab_van_chuyen_thanh_toan'); ?>
        </a>
        <a href="#tab-cart-02" class="coz-item-nav-tab-step" >
            <?php echo $this->translate('txt_tab_gio_hang'); ?>
        </a>
    </div>

    <div class="coz-mobile-nav-tab-step" data-place="menuMobile" >
        <a href="javascript:void(0);" class="coz-btn-mobile-nav-step" data-btn="togleMenuMobile" >
            <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
        </a>
        <div class="coz-wrap-mobile-nav-step" data-place="contentMenuMobile" >
            <ul class="coz-mm-mobile-nav-step" >
                <li>
                    <a href="#tab-shipping-payment" data-btn="triggerTab" data-target=".coz-item-nav-tab-step[href='#tab-shipping-payment']" >
                        <?php echo $this->translate('txt_tab_van_chuyen_thanh_toan'); ?>
                    </a>
                </li>
                <li>
                    <a href="#tab-cart-02" data-btn="triggerTab" data-target=".coz-item-nav-tab-step[href='#tab-cart-02']" >
                        <?php echo $this->translate('txt_tab_gio_hang'); ?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    
    <div class="coz-conten-tab-step">

        <div class="coz-tab-content-step01 active clearix" id="tab-shipping-payment" >

            <?php $payments = $this->Payments()->getPayments();
            if(!empty($payments)){ ?>
            <form class="clearfix" action="" data-form="shipping" method="post" >
                <div class="row" >
                    <div class="col-sm-12" data-place="hasErrorShipper" >
                        <div class="coz-error" data-place="errorShipper" ></div>
                    </div>
                    <div class="col-sm-offset-3  col-sm-6" >
                        <div class="coz-wrap-shipng" >
                            <h2 class="coz-title-payment" >
                                <?php echo $this->translate('txt_lb_hinh_thuc_van_chuyen_payment'); ?>
                            </h2>
                            <div class="clearfix coz-padd-left" >
                                <div neo-place="Shipping" ></div>
                            </div>
                        </div>

                        <div class="coz-wrap-method-payment" style="margin-bottom:30px" >
                            <h2 class="coz-title-payment" >
                                <?php echo $this->translate('txt_lb_thanh_toan_payment') ?>
                            </h2>
                            <div class="clearfix coz-padd-left" >
                                <p class="coz-note-payment" >
                                    <?php echo $this->translate('txt_des_thanh_toan_payment') ?>
                                </p>
                                <div class="form-element-payment" >
                                    <div class="row" >
                                        <div class="col-sm-12" >
                                            <div class="ui-select-payment" >
                                                <?php $payment_id = (!empty($buyer['payment_id'])) ? $buyer['payment_id'] : 0; ?>
                                                <select class="coz-select-payment" name="trans[payment_id]" data-input="trans[payment_id]" >
                                                    <option value="" selected="selected" >
                                                        <?php echo $this->translate('txt_chon_phuong_thuc_thanh_toan_payment') ?>
                                                    </option>
                                                    <?php foreach ($payments as $index => $pay) { ?>
                                                    <option value="<?php echo $pay['payment_id']; ?>" <?php echo ($payment_id == $pay['payment_id'] ? 'selected' : '') ?> >
                                                        <?php echo $pay['payment_name']; ?>
                                                    </option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="coz-tab-payment" >
                                    <?php foreach ($payments as $index => $pay) { 
                                        if( $pay['code'] != "PAYPAL" ){
                                    ?>
                                    <div class="coz-content-tab-payment" <?php echo ($pay['code'] == "ONEPAY") ? 'data-place="Onepay"' : '' ?> id="<?php echo $pay['payment_id'] ?>" >
                                        <?php 
                                        if( $pay['code'] != "ONEPAY" 
                                            || ($pay['code'] == "ONEPAY" && !empty($pay['is_local'])) ){
                                            echo $pay['payment_description'];
                                        }else if( $pay['code'] == "ONEPAY" && empty($pay['is_local']) ){ ?>
                                        <h2 class="coz-title-payment" >
                                            <?php echo $this->translate('txt_info_billing_address_payment') ?>
                                        </h2>
                                        <div class="clearfix coz-padd-left" >
                                            <p class="coz-note-payment" >
                                                <?php echo $this->translate('txt_des_info_billing_address_payment') ?>
                                            </p>
                                            <div class="clearfix" >
                                                <div class="form-element-payment" >
                                                    <div class="row" >
                                                        <div class="col-sm-12" >
                                                            <label class="ui-lb-payment" >
                                                                <?php echo $this->translate('txt_dat_nuoc_ngan_hang_phat_hanh_payment') ?>
                                                            </label>
                                                        </div>
                                                        <div class="col-sm-12" >
                                                            <select class="coz-select-payment coz-select-country-payment"  name="trans[avs_country]" id="avs_country"  data-input="trans[avs_country]" >
                                                                <option value="" >
                                                                    <?php echo $this->translate('chon_country');?>
                                                                </option>
                                                                <?php foreach ($countries as $country){ ?>
                                                                <option value="<?php echo $country['id'] ?>" >
                                                                    <?php echo $country['title'] ?>
                                                                </option>
                                                                <?php } ?>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row" >
                                                    <div class="col-sm-6" >
                                                        <div class="form-element-payment" >
                                                            <div class="row" >
                                                                <div class="col-sm-12" >
                                                                    <label class="ui-lb-payment" >
                                                                        <?php echo $this->translate('txt_dia_chi_ngan_hang_phat_hanh_payment') ?>
                                                                    </label>
                                                                </div>
                                                                <div class="col-sm-12" >
                                                                    <div class="ui-input-payment" >
                                                                        <input type="text" value="" name="trans[avs_street01]" id="avs_street01" spellcheck="false" class="input-payment avs_street01" aria-invalid="true" data-input="trans[avs_street01]" >
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="col-sm-6" >
                                                        <div class="form-element-payment" >
                                                            <div class="row" >
                                                                <div class="col-sm-12" >
                                                                    <label class="ui-lb-payment" >
                                                                        <?php echo $this->translate('txt_thanh_pho_ngan_hang_phat_hanh_payment') ?>
                                                                    </label>
                                                                </div>
                                                                <div class="col-sm-12" >
                                                                    <div class="ui-input-payment" >
                                                                        <input type="text" value="" name="trans[avs_city]" id="avs_city" spellcheck="false" class="input-payment avs_city" aria-invalid="true" data-input="trans[avs_city]" >
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="row" >
                                                    <div class="col-sm-6" >
                                                        <div class="form-element-payment" >
                                                            <div class="row" >
                                                                <div class="col-sm-12" >
                                                                    <label class="ui-lb-payment" >
                                                                        <?php echo $this->translate('txt_quan_huyen_ngan_hang_phat_hanh_payment') ?>
                                                                    </label>
                                                                </div>
                                                                <div class="col-sm-12" >
                                                                    <div class="ui-input-payment" >
                                                                        <input type="text" value="" name="trans[avs_stateprov]" id="avs_stateprov" spellcheck="false" class="input-payment avs_stateprov" aria-invalid="true" data-input="trans[avs_stateprov]" >
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6" >
                                                        <div class="form-element-payment" >
                                                            <div class="row" >
                                                                <div class="col-sm-12" >
                                                                    <label class="ui-lb-payment" >
                                                                        <?php echo $this->translate('txt_ma_vung_ngan_hang_phat_hanh_payment') ?>
                                                                    </label>
                                                                </div>
                                                                <div class="col-sm-12" >
                                                                    <div class="ui-input-payment" >
                                                                        <input type="text" value="" name="trans[avs_postCode]" id="avs_postCode" spellcheck="false" class="input-payment avs_postCode" aria-invalid="true" data-input="trans[avs_postCode]" >
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <?php } ?>
                                    </div>
                                    <?php }
                                    } ?>
                                </div>
                            </div>
                        </div>

                        <div class="form-element-payment" >
                            <div class="row">
                                <div class="col-md-12" >
                                    <div class="coz-text-right" >
                                        <a href="javascript:void(0);" class="coz-btn-flat coz-btn-flat-active"  data-btn="payShippingPayment" >
                                            <?php echo $this->translate('txt_tiep_tuc_payment')?>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <?php } ?>
        </div>

        <div class="coz-tab-content-step01 clearix" id="tab-cart-02" >
            <div class="coz-table-responsive">
                <table class="coz-table-cart coz-table-cart-idex" >
                    <?php
                    $_i = 0; 
                    foreach ($carts as $id => $product) {
                        foreach ($product['product_type'] as $product_type_id => $p) {
                    ?>

                    <?php if( !empty($_i) ){ ?>
                    <tr class="line-tbl-cart-idex"  data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                        <td colspan="6" ></td>
                    </tr>
                    <?php } ?>

                    <tr data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                        <td rowspan="2" >
                            <div class="coz-cart-img" >
                                <a class="img-product-cart" data-place="linkProduct" href="<?php echo $this->Products()->getLink($p) ?>" <?php echo $this->Products()->getTypeView($p) ?> title="<?php echo $this->Products()->getTitle($p) ?>" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                    <img src="<?php echo $this->Images()->getUrlImage($this->Products()->getImage($p), 84); ?>" alt="<?php echo $this->Products()->getTitle($p) ?>" >
                                </a>
                            </div>
                        </td>
                        <td colspan="3" >
                            <a class="coz-cart-product-name" data-place="linkProduct"  href="<?php echo $this->Products()->getLink($p) ?>" <?php echo $this->Products()->getTypeView($p) ?> title="<?php echo $this->Products()->getTitle($p) ?>" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                <span data-place="nameProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                    <?php echo $this->Products()->getName($p) ?>
                                </span>
                            </a>
                        </td>
                        <td class="coz-text-right" colspan="2" >
                            <div class="clearfix" >
                                <?php 
                                    $price = $this->Products()->getPrice($p);
                                    $price_sale = $this->Products()->getPriceSale($p);
                                    if( $price_sale < $price){
                                ?>
                                <div class="coz-cart-price-root"  data-place="priceProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                    <?php echo $this->Currency()->fomatCurrency($price) ?>
                                </div>
                                <div class="coz-cart-price-sale" >
                                    <?php echo $this->translate('txt_giam_con') ?>&nbsp&nbsp
                                    <span data-place="priceSaleProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" > 
                                        <?php echo $this->Currency()->fomatCurrency($price_sale) ?>
                                    </span>
                                </div>
                                <?php }else{ ?>
                                <div class="coz-cart-price-sale" data-place="priceSaleProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" > 
                                    <?php echo $this->Currency()->fomatCurrency($price_sale) ?>
                                </div>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>
                    <tr data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                        <td >
                            <div class="coz-item-dest-product-cart" >
                                <a href="<?php echo $this->Cart()->getUrlEditProduct($p) ?>" class="coz-btn-edit-item-dest-product-cart" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" data-place="btnEditPropertiesCartProduct" data-pin="[data-type='name'][data-cartid='<?php echo $id.'-'.$product_type_id ?>']" >
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                </a>
                                <div class="icoz-item-dest-product-cart" >
                                    <div class="coz-qual-dest-cart" >
                                        <span class="coz-label-des-pro" >
                                            <?php echo $this->translate('txt_so_luong'); ?>
                                        </span>
                                        <span class="coz-label-des-pro" >
                                            <span data-place="quantityProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                                <?php echo $this->Cart()->getProductsQuantity($p) ?>
                                            </span>
                                            <input type="hidden" value="<?php echo $this->Cart()->getProductsQuantity($p) ?>" name="quantity[<?php echo $this->Products()->getProductsId($p) ?>][<?php echo $this->Products()->getProductTypeId($p) ?>]" data-place="quantityProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                        </span>
                                    </div>
                                    <?php $typeName = $this->Products()->getProductTypeName($p);  ?>
                                    <div class="coz-qual-dest-cart" data-place="hasTypeName" <?php echo empty($typeName) ? 'style="display:none"' : '' ?> >
                                        <span class="coz-label-des-pro" >
                                            <?php echo $this->translate('txt_loai_san_pham'); ?>
                                        </span>
                                        <span class="coz-label-des-pro" data-place="typeNameProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                            <?php echo $typeName; ?>
                                        </span>
                                    </div>

                                    <?php 
                                    $ext = $this->Products()->getExtension($p);
                                    $ext_m = $this->Products()->getExtensionRequire($p);
                                    $lsExt = array_merge($ext, $ext_m);
                                    ?>
                                    <div class="coz-qual-dest-cart" data-place="hasExtentionProduct" <?php echo (empty($ext) && empty($ext_m)) ? 'style="display:none"' : '' ?> >
                                        <span class="coz-label-des-pro" >
                                            <?php echo $this->translate('txt_extention_product_on_cart'); ?>
                                        </span>
                                        <span class="coz-label-des-pro" data-place="extentionProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                            <?php 
                                            foreach ($lsExt as $kex => $itex) {
                                                echo (empty($kex) ? '' : ';').$itex['ext_name'];
                                            }
                                            ?>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td colspan="4" class="coz-position-relative" >
                            <span class="coz-cart-product-note" data-place="noteProduct" >
                                <?php echo $this->translate('txt_tong_tien_payment') ?>&nbsp&nbsp
                                <span class="coz-product-price" data-place="priceTotalProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" > 
                                    <?php echo $this->Currency()->fomatCurrency($p['price_total']) ?>
                                </span><br />
                                <span class="coz-text-price-not-tax" >
                                    <?php echo $this->translate('txt_gia_khong_bao_gom_thue_payment') ?>
                                </span>
                            </span>
                            <a class="coz-btn-cart-remove-product" href="<?php echo $this->Cart()->getUrlDel($p) ?>" data-btn="delCartProduct"  data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                <i class="fa fa-times" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>

                    <?php }
                    } ?>
                </table>
            </div>
            <div class="clearfix" >
                <table class="table table-bordered total-table coz-table-sumary-cart">
                    <tbody>
                        <tr>
                            <td class="text-xs-left">
                                <?php echo $this->translate('txt_tong_tien') ?>
                            </td>
                            <td class="text-xs-right">
                                <div class="coz-product-price" data-place="priceCartTotalOrig" >
                                    <?php echo $this->Currency()->fomatCurrency($caculator['price_total_orig']) ?>
                                </div>
                            </td>
                        </tr>

                        <tr <?php echo ( empty($coupon) ? 'style="display:none"' : '') ?> id="coz-tr-coupon-payment" data-place="hasCoupon" >
                            <td class="text-xs-left">
                                <?php echo $this->translate('txt_giam_gia_payment') ?>
                            </td>
                            <td class="text-xs-right">
                                <div class="coz-product-price" data-place="valueCoupon" >
                                    <?php echo $this->Coupons()->getPriceWithCurrency() ?>
                                </div>
                            </td>
                        </tr>

                        <?php if( $caculator['price_total'] < $caculator['price_total_tax'] ){ ?>
                        <tr data-place="hasPriceCartTax" >
                            <td class="text-xs-left">
                                <?php echo $this->translate('txt_tien_thue_payment') ?>
                            </td>
                            <td class="text-xs-right">
                                <div class="coz-product-price" data-place="priceCartTax" >
                                    <?php echo $this->Currency()->fomatCurrency($caculator['price_total_tax'] - $caculator['price_total']) ?>
                                </div>
                            </td>
                        </tr>
                        <?php } ?>

                        <tr>
                            <td class="text-xs-left">
                                <?php echo $this->translate('txt_lb_total_tax_payment') ?>
                            </td>
                            <td class="text-xs-right">
                                <div class="coz-product-price"  data-place="priceCartTotalTax" >
                                    <?php echo $this->Currency()->fomatCurrency($caculator['price_total_tax']) ?>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
<?php } ?>