<?php
	$countries = $this->Contries()->getContries();
	$country_id = $this->User()->getCountryId();
?>
<div class="coz-wrapper-profile" >
	<div class="container">
	    <div class="row coz-profile">
			<div class="col-md-3">
				<?php echo $this->partial('application/profile/menu', array('active' => 'comments', 'point' => $point) ); ?>
			</div>
			<div class="col-md-9">
	            <div class="coz-profile-content">
				   
	            	<div class="coz-user-info-block" >

		                <div class="coz-user-heading">
		                    <h3><?php echo $this->translate('txt_danh_gia_cua_ban') ?></h3>
		                    <span class="help-block"><?php echo $this->User()->getUserName(); ?></span>
		                </div>
		                <div class="row" >
		                	<?php if( !empty($comments) ){ ?>
		                	<div class="col-sm-12" >
			                	<div class="table-responsive">
	                                <table class="coz-table-cart" >
	                                	<thead>
	                                        <tr>
	                                            <th class="text-center" width="140" >
	                                                <?php echo $this->translate('txt_hinh_anh'); ?>
	                                            </th>
	                                            <th class="text-center" width="200" >
	                                                <?php echo $this->translate('txt_ten_san_pham'); ?>
	                                            </th>
		                                        <th>
		                                        	<?php echo $this->translate('txt_danh_gia')?>
		                                        </th>
	                                        </tr>
	                                    </thead>
	                                    <tbody>
	                                    	<?php foreach($comments as $p){ ?>
	                                        <tr>
	                                        	<th class="text-center" width="140" >
	                                                <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/<?php echo$product['alias'] ?>-<?php echo $product['id'] ?>" title="<?php echo $product['title']; ?>" >
	                                                    <img src="<?php echo $this->Images()->getUrlImage($product['thumb_image'], 75, 100); ?>" alt="<?php echo $product['title']; ?>">
	                                                </a>
	                                            </td>
												<th class="text-center" width="200" >
													<a href="<?php echo $this->Products()->getLink($p) ?>" <?php echo $this->Products()->getTypeView($p) ?> title="<?php echo $p['products_title']; ?>" >
	                                                    <?php echo $this->Products()->getName($p) ?>
	                                                </a>
												</td>
												<td class="text-center" >
	                                                <?php echo $p['comments_content'] ?>
	                                            </td>
											</tr>
	                                        <?php } ?>
	                                    </tbody>
	                                </table>
	                            </div>
                            </div>
                            <div class="col-sm-12" >
                            	<?php if(!empty($paging)){ ?>
		                        <nav >
		                            <ul class="coz-pagination" >
		                                <?php echo $paging; ?>
		                            </ul>
		                        </nav>
				                <?php } ?>
                            </div>
                            <?php }else{ ?>
		                    <div class="col-sm-12" >
		                        <p class="cart-empty">
		                            <?php echo $this->translate('txt_chua_co_danh_gia_nao') ?>
		                        </p>
		                    </div>
		                    <?php } ?>

		                </div>

		            </div>
				   
	            </div>
			</div>
		</div>
	</div>
</div>