<div class="profile-breadcrumbs clearfix" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <span itemprop="item name" >
                            <?php echo $this->translate('txt_your_order'); ?>
                        </span>
                        <meta itemprop="position" content="2" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="wrapper-profile clearfix" >
	<div class="container">
	    <div class="row">
			<div class="col-md-3">
				<?php echo $this->partial('application/profile/menu', array('active' => 'history') ); ?>
			</div>
			<div class="col-md-9">
	            <h1 class="title-profile">
	            	<?php echo $this->translate('txt_thong_tin_invoice'); ?>
	            </h1>

	            <div class="col-sm-12 coz-print-body" data-bodyPrint="true" data-id="<?php echo $invoice->invoice_id; ?>" >
	                <?php echo html_entity_decode($invoice->content, ENT_QUOTES, 'UTF-8'); ?>
            	</div>
	            
			</div>
		</div>
	</div>
</div>