<div class="coz-wrapper-profile" >
	<div class="container">
	    <div class="row coz-profile">
			<div class="col-md-3">
				<?php echo $this->partial('application/profile/menu', array('active' => 'history', 'point' => $point) ); ?>
			</div>
			<div class="col-md-9">
	            <div class="coz-profile-content">
				   
	            	<div class="coz-user-info-block" >

		                <div class="coz-user-heading">
		                    <h3><?php echo $this->translate('txt_detail_invoice') ?></h3>
		                    <span class="help-block"><?php echo $this->User()->getUserName(); ?></span>
		                </div>
		                <div class="row" >
		                	<?php if( !empty($invoice) ){ ?>
		                	<div class="clearfix" >
		                		<div class="col-sm-12" >
			                		<p class="coz-note-payment" >
			                            <?php echo $this->translate('txt_thong_tin_invoice') ?>
			                        </p>
			                	</div>
			                	<div class="col-sm-12 coz-print-body" data-bodyPrint="true" data-id="<?php echo $invoice->invoice_id; ?>" >
					                <?php echo html_entity_decode($invoice->content, ENT_QUOTES, 'UTF-8'); ?>
			                	</div>

			                	<?php if( $this->User()->isMerchant() ){ ?>
			                	<div class="col-sm-12" >
			                		<div class="form-element-payment" >
		                                <div class="row" >
		                                    <div class="col-sm-12" >
		                                        <div class="clearfix coz-text-right" >
		                                        	<span class="help-block">
		                                        		<?php echo $this->translate('txt_ban_muon_action_invoice') ?>
		                                        	</span>

		                                        	<?php if( $invoice->delivery == 'accept' ){ ?>
		                                            <input name="accept" type="button" value="<?php echo $this->translate('txt_accept_invoice') ?>" class="coz-btn" >
		                                            <?php }else{ ?>
		                                            <input name="accept" type="button" value="<?php echo $this->translate('txt_accept_invoice') ?>" class="coz-btn coz-btn-active" data-btn="acceptInvoice" data-id="<?php echo $invoice->invoice_id; ?>" >
		                                            <?php } ?>

		                                            <?php if( $invoice->delivery == 'finish' ){ ?>
		                                            <input name="finish" type="button" value="<?php echo $this->translate('txt_finish_invoice') ?>" class="coz-btn" >
		                                            <?php }else{ ?>
		                                            <input name="finish" type="button" value="<?php echo $this->translate('txt_finish_invoice') ?>" class="coz-btn coz-btn-active" data-btn="finishInvoice" data-id="<?php echo $invoice->invoice_id; ?>" >
		                                            <?php } ?>

		                                            <input name="print" type="button" value="<?php echo $this->translate('txt_print_invoice') ?>" class="coz-btn coz-btn-active" data-btn="printInvoice" data-id="<?php echo $invoice->invoice_id; ?>" >

		                                        </div>
		                                    </div>
		                                </div>
		                            </div>
			                	</div>
			                	<?php } ?>

		                	</div>

                            <?php }else{ ?>
		                    <div class="col-sm-12" >
		                        <p class="cart-empty">
		                            <?php echo $this->translate('txt_assign_khong_thay') ?>
		                        </p>
		                    </div>
		                    <?php } ?>

		                </div>

		            </div>
				   
	            </div>
			</div>
		</div>
	</div>
</div>