<div class="profile-breadcrumbs clearfix" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <span itemprop="item name" >
                            <?php echo $this->translate('txt_account_summary'); ?>
                        </span>
                        <meta itemprop="position" content="2" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="wrapper-profile clearfix" >
	<div class="container">
	    <div class="row">
			<div class="col-md-3">
				<?php echo $this->partial('application/profile/menu', array('active' => 'index') ); ?>
			</div>
			<div class="col-md-9">
	            <h1 class="title-profile">
	            	<?php echo $this->translate('txt_edit_persion_infomation'); ?>
	            </h1>
	            <div class="row" >
	            	<div class="col-md-9" >
			            <form accept-charset='UTF-8' action="/profile/edit" method='post' class="form-edit-profile-use" data-form="editProfile" >
			            	<div class="form-group" >
		                        <div class="row">
		                            <div class="col-md-3 text-xs-right">
		                                <label style="padding: 5px 0 0" >
		                                    <?php echo $this->translate('txt_ten_user'); ?>
		                                </label>
		                            </div>
		                            <div class="col-md-5">
		                                <input type="text" value="<?php echo $this->User()->getFullName(); ?>" name="full_name" spellcheck="false" class="form-control" aria-invalid="true" data-input="full_name" >
		                            </div>
		                        </div>
		                    </div>

		                    <div class="form-group" >
                                <div class="row">
                                    <div class="col-md-3 text-xs-right">
                                        <label>
                                            <?php echo $this->translate('txt_gioi_tinh_user'); ?>
                                        </label>
                                    </div>
                                    <div class="col-md-9">
                                        <label class="radio-gender" >
                                            <input type="radio" name="gender" <?php echo empty($this->User()->getGender()) ? 'checked="checked"' : '' ?> value="0" >
                                            <?php echo $this->translate('txt_gioi_tinh_nam'); ?>
                                        </label>
                                        <label class="radio-gender" >
                                            <input type="radio" name="gender" <?php echo !empty($this->User()->getGender()) ? 'checked="checked"' : '' ?> value="1" >
                                            <?php echo $this->translate('txt_gioi_tinh_nu'); ?>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group" >
                                <div class="row">
                                    <div class="col-md-3 text-xs-right">
                                        <label style="padding: 5px 0 0" >
                                            <?php echo $this->translate('txt_birthday_user_profile'); ?>
                                        </label>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="row" >
                                            <div class="col-md-3 col-sm-4" >
                                                <div class="form-group" >
                                                	<label style="padding: 5px 0" >
			                                            <?php echo $this->translate('txt_bod_dd_fomat'); ?>
			                                        </label>
			                                        <div class="clearfix" >
	                                                    <select name="birthday[day]" class="form-control" >
	                                                        <option value="0" >
	                                                            <?php echo $this->translate('txt_day_birthday_user'); ?>
	                                                        </option>
	                                                        <?php for($i=1; $i<=31;$i++){ ?>
	                                                        <option value="<?php echo $i ?>" <?php echo $this->User()->getDayBirthday() == $i ? 'selected="selected"' : '' ?> >
	                                                            <?php echo $i ?>
	                                                        </option>
	                                                        <?php } ?>
	                                                    </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3 col-sm-4" >
                                                <div class="form-group" >
                                                	<label style="padding: 5px 0" >
			                                            <?php echo $this->translate('txt_bod_mm_fomat'); ?>
			                                        </label>
			                                        <div class="clearfix" >
	                                                    <select name="birthday[month]" class="form-control" >
	                                                        <option value="0" >
	                                                            <?php echo $this->translate('txt_month_birthday_user'); ?>
	                                                        </option>
	                                                        <?php for($i=1; $i<=12;$i++){ ?>
	                                                        <option value="<?php echo $i ?>" <?php echo $this->User()->getMonthBirthday() == $i ? 'selected="selected"' : '' ?> >
	                                                            <?php echo $i ?>
	                                                        </option>
	                                                        <?php } ?>
	                                                    </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3 col-sm-4" >
                                                <div class="form-group" >
                                                	<label style="padding: 5px 0" >
			                                            <?php echo $this->translate('txt_bod_yy_fomat'); ?>
			                                        </label>
			                                        <div class="clearfix" >
	                                                    <select name="birthday[year]" class="form-control" >
	                                                        <option value="0" >
	                                                            <?php echo $this->translate('txt_year_birthday_user'); ?>
	                                                        </option>
	                                                        <?php for($i=date("Y"); $i>=(date("Y")-100);$i--){ ?>
	                                                        <option value="<?php echo $i ?>" <?php echo $this->User()->getYearBirthday() == $i ? 'selected="selected"' : '' ?> >
	                                                            <?php echo $i ?>
	                                                        </option>
	                                                        <?php } ?>
	                                                    </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

		                    <div class="form-group" >
		                        <div class="row">
		                            <div class="col-md-3 text-xs-right">
		                                <label style="padding: 5px 0 0" >
		                                    <?php echo $this->translate('txt_phone_user_profile'); ?>
		                                </label>
		                            </div>
		                            <div class="col-md-5">
		                                <input type="text" name="phone" spellcheck="false" class="form-control" value="<?php echo $this->User()->getPhone(); ?>" data-input="phone" >
		                            </div>
		                        </div>
		                    </div>

		                    <div class="form-group clearfix last" >
                                <div class="row" >
                                    <div class="col-md-5 col-md-offset-3">
                                        <div class="row" >
                                            <div class="col-md-10 col-md-offset-1">
                                                <button class="coz-btn-flat coz-btn-flat-active coz-btn-flat-block" type="submit" >
                                                    <span>
                                                    	<?php echo $this->translate('txt_save_edit_profile') ?>
                                                    </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


				        </form>
			        </div>
		        </div>
			</div>
		</div>
	</div>
</div>