<div class="profile-breadcrumbs clearfix" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <span itemprop="item name" >
                            <?php echo $this->translate('txt_your_order'); ?>
                        </span>
                        <meta itemprop="position" content="2" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="wrapper-profile clearfix" >
	<div class="container">
	    <div class="row">
			<div class="col-md-3">
				<?php echo $this->partial('application/profile/menu', array('active' => 'history') ); ?>
			</div>
			<div class="col-md-9">
	            <h1 class="title-profile">
	            	<?php echo $this->translate('txt_purchase_history'); ?>
	            </h1>

	            <?php if( !empty($invoices) ){ ?>
                <div class="al-summary-invoice" >
                    <span class="it-quist-info-use" >
                        <?php echo $this->translate('txt_puchase'); ?>
                        <b>
                            <?php echo $total ?> order -
                            <?php echo $total_product ?> items
                        </b>
                    </span>
                </div>
            	<div class="clearfix" >
                	<div class="table-responsive">
                        <table class="coz-table-invoice" >
                        	<thead>
                                <tr>
                                    <th>
                                        <?php echo $this->translate('txt_titile_invoice'); ?>
                                    </th>
                                    <th>
                                        <?php echo $this->translate('txt_confirm_invoice'); ?>
                                    </th>
                                    <th>
                                        <?php echo $this->translate('txt_total_invoice'); ?>
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            	<?php foreach($invoices as $row){ ?>
                                <tr>
                                    <td>
                                    	<a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile/deinvoice?id=<?php echo $row['invoice_id']; ?>" title="<?php echo $this->translate('txt_chi_tiet_hoa_don'); ?>" >
                                        	<?php echo $row['invoice_title']; ?>
                                        </a>
                                    </td>
                                    <td width="100" class="col-lm text-xs-center" >
                                        <?php echo $this->translate($row['payment']); ?>
                                    </td>
                                    <td width="100" class="col-lm text-xs-right" >
                                        <span class="price" >
                                            <?php echo $this->Currency()->fomatCurrency($row['total_tax']+$row['shipping_fee']); ?>
                                        </span>
                                    </td>
                                    <td width="100" class="col-lm" >
                                    	<a href="javascript:void(0);" class="coz-btn-link" data-neo="magnificPopup" data-type="inline" data-src='#ivoice_<?php echo $row['invoice_id']; ?>' rel="nofollow" >
                                        	<?php echo $this->translate('txt_xem_nhanh_hd'); ?>
                                        </a>
                                        <div id="ivoice_<?php echo $row['invoice_id']; ?>" style="display:none;" >
                                        	<div class="container" >
	                                        	<div class="coz-wrap-content-invoice-profile" >
	                                        		<?php echo html_entity_decode($row['content'], ENT_QUOTES, 'UTF-8');?>
	                                        	</div>
                                        	</div>
                                        </div>
                                    </td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-sm-12" >
                	<?php if(!empty($paging)){ ?>
                    <nav >
                        <ul class="coz-pagination" >
                            <?php echo $paging; ?>
                        </ul>
                    </nav>
	                <?php } ?>
                </div>
                <?php }else{ ?>
                <div class="col-sm-12" >
                    <p class="cart-empty">
                        <?php echo $this->translate('txt_chua_co_giao_dich_nao') ?>
                    </p>
                </div>
                <?php } ?>
	            
			</div>
		</div>
	</div>
</div>