<?php
	$countries = $this->Contries()->getContries();
	$country_id = $this->User()->getCountryId();
?>
<div class="coz-wrapper-profile" >
	<div class="container">
	    <div class="row coz-profile">
			<div class="col-md-3">
				<?php echo $this->partial('application/profile/menu', array('active' => 'history', 'point' => $point) ); ?>
			</div>
			<div class="col-md-9">
	            <div class="coz-profile-content">
				   
	            	<div class="coz-user-info-block" >

		                <div class="coz-user-heading">
		                    <h3><?php echo $this->translate('txt_lich_su_mua_hang') ?></h3>
		                    <span class="help-block"><?php echo $this->User()->getUserName(); ?></span>
		                </div>
		                <div class="row" >
		                	<?php if( !empty($invoices) ){ ?>
		                	<div class="col-sm-12" >
		                		<div class="coz-wrap-chart-profile-history" >
		                			<canvas id="profileHistoryChart" data-neo="profileHistoryChart" ></canvas>
		                		</div>
		                	</div>
		                	<div class="col-sm-12" >
			                	<div class="table-responsive">
	                                <table class="coz-table-cart" >
	                                	<thead>
	                                        <tr>
	                                            <th class="text-center">
	                                                <?php echo $this->translate('txt_titile_invoice'); ?>
	                                            </th>
	                                            <th class="text-center">
	                                                <?php echo $this->translate('txt_confirm_invoice'); ?>
	                                            </th>
	                                            <th class="text-center">
	                                                <?php echo $this->translate('txt_total_invoice'); ?>
	                                            </th>
	                                            <th class="text-center">
	                                                <?php echo $this->translate('txt_detail_invoice'); ?>
	                                            </th>
	                                        </tr>
	                                    </thead>
	                                    <tbody>
	                                    	<?php foreach($invoices as $row){ ?>
	                                        <tr>
		                                        <td width="120" >
		                                        	<a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile/deinvoice?id=<?php echo $row['invoice_id']; ?>" title="<?php echo $this->translate('txt_chi_tiet_hoa_don'); ?>" >
		                                            	<?php echo $row['invoice_title']; ?>
		                                            </a>
		                                        </td>
		                                        <td width="120" class="sucess" >
		                                            <?php echo $this->translate($row['payment']); ?>
		                                        </td>
		                                        <td width="180" align="right">
		                                            <?php echo $this->Currency()->fomatCurrency($row['total_tax']+$row['shipping_fee']); ?>
		                                        </td>
		                                        <td width="180" >
		                                        	<a href="javascript:void(0);" class="coz-btn-link" data-neo="magnificPopup" data-type="inline" data-src='#ivoice_<?php echo $row['invoice_id']; ?>' rel="nofollow" >
			                                        	<?php echo $this->translate('txt_xem_nhanh_hd'); ?>
			                                        </a>
			                                        <div id="ivoice_<?php echo $row['invoice_id']; ?>" style="display:none;" >
			                                        	<div class="container" >
				                                        	<div class="coz-wrap-content-invoice-profile" >
				                                        		<?php echo html_entity_decode($row['content'], ENT_QUOTES, 'UTF-8');?>
				                                        	</div>
			                                        	</div>
			                                        </div>
		                                        </td>
		                                    </tr>
	                                        <?php } ?>
	                                    </tbody>
	                                </table>
	                            </div>
                            </div>
                            <div class="col-sm-12" >
                            	<?php if(!empty($paging)){ ?>
		                        <nav >
		                            <ul class="coz-pagination" >
		                                <?php echo $paging; ?>
		                            </ul>
		                        </nav>
				                <?php } ?>
                            </div>
                            <?php }else{ ?>
		                    <div class="col-sm-12" >
		                        <p class="cart-empty">
		                            <?php echo $this->translate('txt_chua_co_giao_dich_nao') ?>
		                        </p>
		                    </div>
		                    <?php } ?>

		                </div>

		            </div>
				   
	            </div>
			</div>
		</div>
	</div>
</div>