<div class="profile-breadcrumbs clearfix" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <span itemprop="item name" >
                            <?php echo $this->translate('txt_account_summary'); ?>
                        </span>
                        <meta itemprop="position" content="2" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="wrapper-profile clearfix" >
	<div class="container">
	    <div class="row">
			<div class="col-md-3">
				<?php echo $this->partial('application/profile/menu', array('active' => 'index') ); ?>
			</div>
			<div class="col-md-9">
	            <h1 class="title-profile">
	            	<?php echo $this->translate('txt_account_summary'); ?>
	            </h1>
	            <div class="list-sumad" >
		            <div class="row" >
		            	<div class="col-md-4" >
		            		<div class="item-sumad" >
		            			<h3 class="title-sumad" >
		            				<?php echo $this->translate('txt_persion_info'); ?>
		            			</h3>
		            			<div class="tb-info-profile" >
		            				<table class="tb-iprofile">
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_name_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo $this->User()->getFullName(); ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_gender_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo $this->User()->getStringGender(); ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_dob_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo $this->User()->getBirthday(); ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_phone_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo $this->User()->getPhone(); ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_email_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo $this->User()->getUserName(); ?>
		            						</td>
		            					</tr>
		            				</table>
		            			</div>
		            			<a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile/edit" class="btn-edit-profile-use" >
		            				<i class="fa fa-pencil" aria-hidden="true"></i>
		            				<?php echo $this->translate('txt_edit_infomation'); ?>
		            			</a>
		            		</div>
		            	</div>

		            	<div class="col-md-4" >
		            		<div class="item-sumad" >
		            			<h3 class="title-sumad" >
		            				<?php echo $this->translate('txt_shipping_address'); ?>
		            			</h3>
		            			<?php if( !empty($shipping) ){ ?>
		            			<div class="tb-info-profile" >
		            				<table class="tb-iprofile">
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_name_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo !empty($shipping->full_name) ? $shipping->full_name : ''; ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_phone_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo !empty($shipping->phone) ? $shipping->phone : ''; ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_address_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo !empty($shipping->address) ? $shipping->address : ''; ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>&nbsp;</th>
		            						<td>&nbsp;</td>
		            					</tr>
		            					<tr>
		            						<th>&nbsp;</th>
		            						<td>&nbsp;</td>
		            					</tr>
		            				</table>
		            			</div>
		            			<a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile/edit-shipping" class="btn-edit-profile-use" >
		            				<i class="fa fa-pencil" aria-hidden="true"></i>
		            				<?php echo $this->translate('txt_edit_address'); ?>
		            			</a>
		            			<?php }else{ ?>
		            			<p>
		            				<?php echo $this->translate('txt_chua_co_shipping_address'); ?>
		            			</p>
		            			<?php } ?>
		            		</div>
		            	</div>

		            	<div class="col-md-4" >
		            		<div class="item-sumad last" >
		            			<h3 class="title-sumad" >
		            				<?php echo $this->translate('txt_billing_address'); ?>
		            			</h3>
		            			<?php if( !empty($billing) ){ ?>
		            			<div class="tb-info-profile" >
		            				<table class="tb-iprofile">
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_name_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo !empty($billing->full_name) ? $billing->full_name : ''; ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_phone_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo !empty($billing->phone) ? $billing->phone : ''; ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>
		            							<?php echo $this->translate('txt_address_user_profile'); ?>
		            						</th>
		            						<td>
		            							<?php echo !empty($billing->address) ? $billing->address : ''; ?>
		            						</td>
		            					</tr>
		            					<tr>
		            						<th>&nbsp;</th>
		            						<td>&nbsp;</td>
		            					</tr>
		            					<tr>
		            						<th>&nbsp;</th>
		            						<td>&nbsp;</td>
		            					</tr>
		            				</table>
		            			</div>
		            			<a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile/edit-billing" class="btn-edit-profile-use" >
		            				<i class="fa fa-pencil" aria-hidden="true"></i>
		            				<?php echo $this->translate('txt_edit_address'); ?>
		            			</a>
		            			<?php }else{ ?>
		            			<p>
		            				<?php echo $this->translate('txt_chua_co_billing_address'); ?>
		            			</p>
		            			<?php } ?>
		            		</div>
		            	</div>
		            </div>
		        </div>

		        <div class="quist-info-use" >
		        	<span class="it-quist-info-use" >
		        		<?php echo $this->translate('txt_register_date'); ?>
		        		<b><?php echo $this->User()->getDateCreate(); ?></b>
		        	</span>
		        	<span class="it-quist-info-use" >
		        		<?php echo $this->translate('txt_puchase'); ?>
		        		<b>
		        			<?php echo $total_invoice ?> order -
		        			<?php echo $total_product ?> items</b>
		        	</span>
		        </div>
			</div>
		</div>
	</div>
</div>