<div class="menu-bar-profile clearfix" >
	<div class="current-profile">
	    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile" class="name-profile" >
	    	<?php echo $this->User()->getFullName(); ?>
	    </a>
	</div>

	<div class="profile-menu">
		<ul class="nav">
			<li <?php echo $active == 'index' ? 'class="active"' : '' ?> >
				<a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile" title="<?php echo $this->translate('txt_overflow') ?>" >
					<?php echo $this->translate('txt_profile_overflow') ?> 
				</a>
			</li>

			<li <?php echo $active == 'history' ? 'class="active"' : '' ?> >
				<a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile/history" title="<?php echo $this->translate('txt_profile_history') ?>" >
					<?php echo $this->translate('txt_profile_history') ?>
				</a>
			</li>
		</ul>
	</div>
</div>