<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
                <li class="active">
                    Danh sách commission của đại lý
                    <i><?php echo $merchant->merchant_name ?></i>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Commission của đại lý <i><?php echo $merchant->merchant_name ?></i> :: Quản lý
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/merchant', array('action' => 'commission')) ?>" method="post">
                <div class="coz-search-bar clearfix" data-form="searchAjax" >
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/merchant', array('action' => 'commission')) ?>" method="post" class="clearfix" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/merchant', array('action' => 'addCommission')) ?>"
                   class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm commission" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($commissions) ){ ?>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/merchant', array('action' => 'publishCommission')) ?>')" data-toggle="tooltip" data-placement="top" title="Hiện commission" >
                            <i class="fa fa-toggle-on" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/merchant', array('action' => 'unpublishCommission')) ?>')" data-toggle="tooltip" data-placement="top" title="Ẩn commission" >
                            <i class="fa fa-toggle-off" aria-hidden="true"></i>
                        </button>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/merchant', array('action' => 'deleteCommission')) ?>')" data-toggle="tooltip" data-placement="top" title="Xoá commission" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
        
        <?php if( !empty($commissions) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" >ID</th>
                        <th class="text-right" >Rate</th>
                        <th class="col-lim text-right" >Start</th>
                        <th class="col-lim text-right" >End</th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($commissions as $commission) { ?>
                    <tr>
                        <td class="text-center col-lim" >
                            <?php echo $commission['commission_id'] ?>
                        </td>
                        <td class="text-right" >
                            <?php echo $commission['rate'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $commission['start_date'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $commission['end_date'] ?>
                        </td>
                        <td class="col-lim text-right" >    
                            <?php if( !empty($commission['is_published']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Đang hiển thị" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Đang ẩn" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="text-right col-lim" >
                            <a href="<?php echo $this->url('cms/merchant', array('action' => 'editCommission', 'id' => $commission['commission_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Sửa commission" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/merchant', array('action' => 'deleteCommission', 'id' => $commission['commission_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá commission"  data-confirm="Bạn có muốn xoá ?" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                            <?php if( !empty($commission['is_published']) ){ ?>
                                <a href="<?php echo $this->url('cms/merchant', array('action' => 'unpublishCommission', 'id' => $commission['commission_id'])) ?>" class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Ẩn commission" >
                                    <i class="fa fa-toggle-on" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <a href="<?php echo $this->url('cms/merchant', array('action' => 'publishCommission', 'id' => $commission['commission_id'])) ?>" class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Hiện commission" >
                                    <i class="fa fa-toggle-off" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $commission['commission_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có commission
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>