<?php foreach ($users as $user) : ?>
    <tr>
        <td style="text-align: center"><?php echo $user['users_id'] ?></td>
        <td>
            <a href="<?php echo $this->url('cms/user', array('action' => 'edit', 'id' => $user['users_id'])) ?>"><?php echo $user['full_name'] ?></a>
        </td>
        <td>
            <?php echo $user['user_name'] ?>
        </td>
        <td><?php echo date('d/m/Y', strtotime($user['date_create'])) ?></td>
        <td style="text-align: center">
            <?php echo $user['is_published'] == 1 ? 'Hiển thị' : '-' ?>
        </td>
        <td>
            <input type="checkbox" name="cid[]"
                   value="<?php echo $user['users_id'] ?>"/>
        </td>
    </tr>
<?php endforeach; ?>