<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ngân hàng :: Cập nhật
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/banks') ?>">Ngân hàng</a></li>
        <li class="active">Cập nhật thông tin</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/banks', array('action' => 'edit','id' => $id)));
        $form->setAttribute('enctype', 'multipart/form-data');
        $form->setAttribute('id', 'form-banks');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('banks_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <button class="btn btn-primary">Lưu lại</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
                </div>
            </div>
        </div>
        <div class="col-xs-8">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="banks_title">Tên ngân hàng</label>
                        <?php echo $this->formRow($form->get('banks_title')); ?>
                    </div>
                    <div class="form-group">
                        <label for="banks_description">Mô tả</label>
                        <?php echo $this->formRow($form->get('banks_description')); ?>
                    </div>
                    <div class="form-group">
                        <label for="file_image">Hình đại diện (Size: 500x300)</label>
                        <input type="file" name="file_image" id="file_image"/>
                    </div>
                    <div class="form-group">
                        <img src="<?php echo $bank->thumb_image ?>" alt="" width="100"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_published">
                                <?php echo $this->formRow($form->get('is_published')); ?>
                                Hiển thị
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <button class="btn btn-primary">Lưu lại</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>