<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ngân hàng :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Ngân hàng</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <form action="<?php echo $this->url('cms/banks', array('action' => 'add-config')) ?>" method="post">
                        <div class="row">
                            <div class="col-xs-4">
                                <select name="banks_id" class="form-control">
                                    <?php $banks = $banks->toArray() ?>
                                    <?php foreach ($banks as $bank) : ?>
                                        <option <?php echo isset($_SESSION['current_bank_add']) && $_SESSION['current_bank_add'] == $bank['banks_id'] ? 'selected' : '' ?>
                                            value="<?php echo $bank['banks_id'] ?>"><?php echo $bank['banks_title'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <?php
                            if (isset($_SESSION['current_bank_add'])) {
                                unset($_SESSION['current_bank_add']);
                            }
                            ?>
                            <div class="col-xs-2">
                                <input class="numberInput form-control" type="text" name="total_month"
                                       placeholder="Số tháng"/>
                                <!--                            <select name="total_month" id="" class="form-control">-->
                                <!--                                <option value="1">3 tháng</option>-->
                                <!--                                <option value="1">6 tháng</option>-->
                                <!--                                <option value="1">12 tháng</option>-->
                                <!--                            </select>-->
                            </div>
                            <div class="col-xs-2">
                                <input class="numberInput form-control" type="text" name="percent_interest_rate" id=""
                                       placeholder="Lãi suất"/>
                            </div>
                            <div class="col-xs-2">
                                <input class="numberInput form-control" type="text" name="percent_must_pay" id=""
                                       placeholder="% trả trước"/>
                            </div>
                            <div class="col-xs-2">
                                <button class="btn btn-primary form-control">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <form action="<?php echo $this->url('cms/banks', array('action' => 'filter')) ?>" method="post"
                                            class="filter_form form-inline">
                        <div class="form-group">
                            <label for="filter-banks-id">Chọn ngân hàng</label>
                            <select name="banks_id" class="form-control" id="filter-banks-id">
                                <?php foreach ($banks as $bank) : ?>
                                    <option
                                        value="<?php echo $bank['banks_id'] ?>"><?php echo $bank['banks_title'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">
                                <i class="fa fa-filter"></i>
                                Lọc
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/banks', array('action' => 'delete-bank')) ?>')">
                                Xóa
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <form action="<?php echo $this->url('cms/banks') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/banks', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm ngân hàng mới</a>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/banks', array('action' => 'delete-config')) ?>')">
                                Xóa
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php //echo $paging ?>
                            </ul>
                        </div>
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="50" style="text-align: center">ID</th>
                                <th>Tên ngân hàng</th>
                                <th>Lãi suất toàn phần</th>
                                <th>% trả trước</th>
                                <th>% số tháng</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($data as $row) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $row['banks_id'] ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/banks', array('action' => 'edit', 'id' => $row['banks_id'])) ?>"><?php echo $row['banks_title'] ?></a>
                                    </td>
                                    <td>
                                        <?php echo $row['percent_interest_rate'] ?>%
                                    </td>
                                    <td>
                                        <?php echo $row['percent_must_pay'] ?>%
                                    </td>
                                    <td>
                                        <?php echo $row['total_month'] ?> tháng
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $row['banks_config_id'] ?>"/>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="50" style="text-align: center">ID</th>
                                <th>Tên ngân hàng</th>
                                <th>Lãi suất toàn phần</th>
                                <th>% trả trước</th>
                                <th>% số tháng</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php //echo $paging ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/banks', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm ngân hàng mới</a>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/banks', array('action' => 'delete-config')) ?>')">
                                Xóa
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->