<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Phí mở rộng :: Thêm mới
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/extension') ?>">Phí mở rộng</a></li>
        <li class="active">Thêm phí mới</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/extension', array('action' => 'add')));
        $form->setAttribute('id', 'form-extension');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('ext_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="parent_id">Tên loại phí</label>
                        <?php echo $this->formRow($form->get('ext_name')); ?>
                    </div>
                    <div class="form-group">
                        <label for="ordering">Mô tả</label>
                        <?php echo $this->formRow($form->get('ext_description')); ?>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_published">
                                <?php echo $this->formRow($form->get('is_published')); ?>
                                Kích hoạt
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <button class="btn btn-primary">Lưu lại</button>
            <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>