<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Phí mở rộng :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Phí mở rộng</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/extension') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/extension', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm loại phí</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/extension', array('action' => 'publish')) ?>')">
                                Hiển thị
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/extension', array('action' => 'unpublish')) ?>')">
                                Ẩn
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="100">ID</th>
                                <th>Tên loại phí</th>
                                <th width="150">Ngày tạo</th>
                                <th width="100" style="text-align: center">Hiển thị</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($extensions as $row) : ?>
                                <tr>
                                    <td><?php echo $row['ext_id'] ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/extension', array('action' => 'edit', 'id' => $row['ext_id'])) ?>" data-toggle='tooltip' title='<?php echo $row['ext_description'] ?>' data-original-title='<?php echo $row['ext_description'] ?>'><?php echo $row['ext_name'] ?></a>
                                    </td>
                                    <td><?php echo date('d/m/Y', strtotime($row['date_create'])) ?></td>
                                    <td style="text-align: center">
                                        <?php if($row['is_published'] == 1) : ?>
                                            <?php $href = $this->url('cms/extension', array('action' => 'singleunpublish', 'id' => $row['ext_id'])) ?>
                                        <?php else: ?>
                                            <?php $href = $this->url('cms/extension', array('action' => 'singlepublish', 'id' => $row['ext_id'])) ?>
                                        <?php endif; ?>
                                        <?php echo $row['is_published'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Đang hiển thị' data-original-title='Đang hiển thị'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Bị ẩn'><i class='fa fa-circle-o'></i></a>" ?>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $row['ext_id'] ?>"/>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="100">ID</th>
                                <th>Tên loại phí</th>
                                <th width="150">Ngày tạo</th>
                                <th width="100" style="text-align: center">Hiển thị</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/extension', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm loại phí</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/extension', array('action' => 'publish')) ?>')">
                                Hiển thị
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/extension', array('action' => 'unpublish')) ?>')">
                                Ẩn
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>

</section><!-- /.content -->