<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        Trang chủ
                    </a>
                </li>
                <li class="active">Assign</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Assign :: Quản lý
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/assign') ?>" method="get">
                <div class="coz-search-bar clearfix" data-form="searchAjax" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="Search..." value="<?php echo $q ?>" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo tên assign
                                    </option>
                                    <option value="1" <?php echo $type == 1 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo mã assign
                                    </option>
                                    <option value="2" <?php echo $type == 2 ? 'selected="selected"' : '' ?> >
                                        Kiểu tìm kiếm : theo mã hoá đơn
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/assign') ?>" method="post" class="clearfix" >
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" >
                    <div class="text-right" >
                        <a href="<?php echo $this->url('cms/assign', array('action' => 'add')) ?>"
                   class="btn btn-link" data-toggle="tooltip" data-placement="top" title="Thêm assign" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                        <?php if( !empty($assigns) ){ ?>
                        <button class="btn btn-link" type="button"
                                onclick="doSubmit(this.form, '<?php echo $this->url('cms/assign', array('action' => 'delete')) ?>')" data-toggle="tooltip" data-placement="top" title="Xoá assign" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
        
        <?php if( !empty($assigns) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th class="text-center col-lim" >Id</th>
                        <th class="col-lim" >Code</th>
                        <th >Tên</th>
                        <th class="col-lim" >Invoice</th>
                        <th class="col-lim text-right"  >Giá assign</th>
                        <th class="col-lim text-right"  >Giá gốc</th>
                        <th class="col-lim text-right" >Trạng thái</th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($assigns as $row) { ?>
                    <tr>
                        <td class="text-center col-lim" >
                            <?php echo $row['assign_id'] ?>
                        </td>

                        <td class="col-lim" >
                            <?php echo $row['assign_code'] ?>
                        </td>

                        <td >
                            <a href="<?php echo $this->url('cms/assign', array('action' => 'edit', 'id'=> $row['assign_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xem assign" >
                                <?php echo $row['assign_name'] ?>
                            </a>
                        </td>

                        <td class="col-lim" >
                            <?php echo $row['invoice_title'] ?>
                        </td>

                        <td class="col-lim text-right" >
                            <span class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($row['assign_total_tax'] + $row['assign_extention_total_tax'] + $row['assign_shipping']) ?>
                            </span>
                        </td>

                        <td class="col-lim text-right" >
                            <span class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($row['total_tax']+$row['shipping_fee']) ?>
                            </span>
                        </td>

                        <td class="col-lim text-right" >
                            <?php if( !empty($row['invoice_id']) ){ ?>
                            <a href="<?php echo $this->url('cms/invoice', array('action' => 'edit', 'id' => $row['invoice_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xem hóa đơn" >
                                <i class="fa fa-link" aria-hidden="true"></i>
                            </a>
                            <?php } ?>

                            <span class="round-order-status round-order-<?php echo $row['assign_status'] ?>" >
                                <?php echo $row['assign_status'] ?>
                            </span>
                        </td>

                        <td class="text-right col-lim" >
                            <a href="<?php echo $this->url('cms/assign', array('action' => 'edit', 'id' => $row['assign_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xem assign" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>

                            <a href="<?php echo $this->url('cms/assign', array('action' => 'delete', 'id' => $row['assign_id'])) ?>" data-toggle="tooltip" data-placement="top" title="Xoá assign"  data-confirm="Bạn có muốn xoá ?" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>

                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['assign_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            Chưa có assign
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>