<!-- Header -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>404</h1>
        <h2><?php echo $this->translate('txt_page_not_found') ?></h2>
        <p><?php echo $this->translate('txt_des_page_not_found') ?></p>
      </div>
    </div>
  </div>
</section>
<!-- end Header -->

<!-- Illustration -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="illustration">
          <div class="laptop"></div>
          <div class="hand"></div>
          <div class="caveman"></div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end Header -->

<!-- Button -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" >
          <span class="btn btn-action">
            <?php echo $this->translate('txt_take_me_out_off_here') ?>
          </span>
        </a>
      </div>
    </div>
  </div>
</section>
<!-- end Button -->