<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Khu vực :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Khu vực</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="<?php echo $this->url('cms/cities') ?>" method="GET" >
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <div class="row" >
                            <div class="col-sm-6" >
                                <div class="form-inline">
                                    <div class="form-group">
                                        <label >
                                            Quốc gia
                                        </label>
                                        <select class="form-control reload-form-change-contry" name="country_id" >
                                            <?php foreach ($contries as $key => $contry) { ?>
                                            <option value="<?php echo $contry['id']; ?>" <?php echo ($contry['id'] == $country_id ? 'selected="selected"' : ''); ?> >
                                                <?php echo $contry['title']; ?>
                                            </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6" >
                                <div class="pull-right">
                                    <ul class="pagination">
                                        <?php echo $paging ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                                <tr>
                                    <th width="50" style="text-align: center">ID</th>
                                    <th style="width:200px">Tên khu vực</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($cities as $row) : ?>
                                <tr>
                                    <td style="text-align: center">
                                        <?php echo $row['cities_id'] ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/cities', array('action' => 'shipping', 'id' => $row['cities_id'])) ?>">
                                            <?php echo $row['cities_title'] ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th width="50" style="text-align: center">ID</th>
                                    <th style="width:200px">Tên khu vực</th>
                                </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section><!-- /.content -->