<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Shipping :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Shipping</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-sm-12" >
            <h2>
                Shipping của thành phố <?php echo $city->cities_title ?>
            </h2>
        </div>
        <form action="<?php echo $this->url('cms/cities') ?>" method="post">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                                <tr>
                                    <th width="50" style="text-align: center">ID</th>
                                    <th style="width:200px">Tên</th>
                                    <th width="10"><input type="checkbox" class="checkall"/></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($shippings as $row) : ?>
                                <tr>
                                    <td style="text-align: center">
                                        <?php echo $row['shipping_id'] ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/shipping', array('action' => 'edit', 'id' => $row['shipping_id'])) ?>">
                                            <?php echo $row['shipping_title'] ?>
                                        </a>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $row['shipping_id'] ?>" />
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th width="50" style="text-align: center">ID</th>
                                    <th style="width:200px">Tên</th>
                                    <th width="10"><input type="checkbox" class="checkall"/></th>
                                </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <ul class="pagination">
                                <?php echo $paging ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section><!-- /.content -->