<?php
$news = $this->Articles()->getTopArticles(0, 5);
$categoryArticles = $this->Articles()->getAllCategoriesArticlesSort();
$list_bcum = $this->CategoriesArticles()->getAllParentsOfCategory($article->categories_articles_id, true);
?>
<div class="wrap-breadcrumbs clearfix" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem"  >
                        <a href='<?php echo $this->Websites()->getUrlPrefixLang() ?>/articles' data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_news'); ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="2" />
                    </li>

                    <?php 
                    $pbc = 2;
                    if(!empty($list_bcum)){ 
                        for($i = count($list_bcum)-1;$i>=0;$i-- ){
                            $item_cum = $list_bcum[$i];
                            $pbc ++;
                    ?>
                    <li itemprop="itemListElement" itemtype="http://schema.org/ListItem"  >
                        <a href="<?php echo $this->CategoriesArticles()->getCategoriesUrl($item_cum); ?>" title='<?php echo $this->CategoriesArticles()->getTitle($item_cum); ?>' data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->CategoriesArticles()->getTitle($item_cum); ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="<?php echo $pbc ?>" />
                    </li>
                    <?php }
                    } ?>

                    <li itemprop="itemListElement" itemtype="http://schema.org/ListItem"  >
                            <span itemprop="item name" >
                            <?php echo $this->Articles()->getTitle($article) ?>
                        </span>
                        <meta itemprop="position" content="<?php echo ($pbc+1) ?>" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="blog-template" class="blog-template" >
    <div class="container">
        <div class="row">
            
            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12"> 
                <h1>
                    <?php echo $this->Articles()->getTitle($article) ?>
                </h1>
                <div class="info-description-article clearfix" >
                    <?php echo $this->Articles()->getContent($article) ?>
                </div>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 pd5">
                <div class="general-box" >
                    <h2 class="title-general" >
                        <?php echo $this->translate('txt_category_article'); ?>
                    </h2>
                    <div class="ds-general clearfix" >
                        <?php echo $this->partial('app/categories-articles-left', array('categories' => $categoryArticles) ); ?>
                    </div>
                </div>

                <?php if(!empty($news)){ ?>
                <div class="general-box" >
                    <h2 class="title-general" >
                        <?php echo $this->translate('txt_bai_viet_moi_nhat'); ?>
                    </h2>
                    <div class="ds-general clearfix" >
                        <div class="blog-list-articles" >
                            <?php foreach ($news as $k => $new) { ?>
                            <div class="clearfix">
                                <?php echo $this->partial('app/item-sm-articles', array('article' => $new) ); ?>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php } ?>

                <?php echo $this->partial('app/contact-sm', array() ); ?>
                
            </div>
    

        </div>
    </div>
</div>

