<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Danh mục :: Cập nhật
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/carticles') ?>">Danh mục sản phẩm</a></li>
        <li class="active">Cập nhật danh mục</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/carticles', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('id', 'form-category-articles');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('categories_articles_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="parent_id">Danh mục cha</label>
                        <?php echo $this->formRow($form->get('parent_id')); ?>
                    </div>

                    <?php if(!empty($languages)){ ?>
                    <div class="form-group">
                        <label for="parent_id">Tên danh mục</label>
                        <div class="row" >
                            <div class="col-sm-12" >
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                    <?php foreach ($languages as $key => $language) { ?>
                                    <li role="presentation" class="<?php echo $key == 0 ? 'active' : '' ?>" >
                                        <a href="#categories_articles_title_<?php echo $language['languages_id']; ?>" aria-controls="categories_articles_title_<?php echo $language['languages_id']; ?>" role="tab" data-toggle="tab" >
                                            <?php echo $language['languages_name']; ?>
                                        </a>
                                    </li>
                                    <?php } ?>
                                </ul>

                                <div class="tab-content" >
                                    <?php foreach ($languages as $key => $language) { ?>
                                    <div class="tab-pane <?php echo $key == 0 ? 'active' : '' ?>" id="categories_articles_title_<?php echo $language['languages_id']; ?>" >
                                        <div style="padding: 20px 10px;border: 1px solid #ddd;border-top: none;" >
                                            <input type="text" name="categories_articles_title[<?php echo $language['languages_id']; ?>]" class="form-control bulid-alias" data-alias=".categories_articles_alias_<?php echo $language['languages_id']; ?>" value="<?php echo empty($category_languages[$language['languages_id']]) ? '' : $category_languages[$language['languages_id']]['categories_articles_title'];  ?>" >
                                        </div>
                                    </div>
                                    <?php } ?>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <?php } ?>

                    <?php if(!empty($languages)){ ?>
                    <div class="form-group">
                        <label for="categories_articles_alias" >Đường dẫn</label>
                        <div class="row" >
                            <div class="col-sm-12" >
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                    <?php foreach ($languages as $key => $language) { ?>
                                    <li role="presentation" class="<?php echo $key == 0 ? 'active' : '' ?>" >
                                        <a href="#categories_articles_alias_<?php echo $language['languages_id']; ?>" aria-controls="categories_articles_alias_<?php echo $language['languages_id']; ?>" role="tab" data-toggle="tab" >
                                            <?php echo $language['languages_name']; ?>
                                        </a>
                                    </li>
                                    <?php } ?>
                                </ul>

                                <div class="tab-content" >
                                    <?php foreach ($languages as $key => $language) { ?>
                                    <div class="tab-pane <?php echo $key == 0 ? 'active' : '' ?>" id="categories_articles_alias_<?php echo $language['languages_id']; ?>" >
                                        <div style="padding: 20px 10px;border: 1px solid #ddd;border-top: none;" >
                                            <input type="text" name="categories_articles_alias[<?php echo $language['languages_id']; ?>]" class="form-control categories_articles_alias_<?php echo $language['languages_id']; ?>" value="<?php echo empty($category_languages[$language['languages_id']]) ? '' : $category_languages[$language['languages_id']]['categories_articles_alias'];  ?>" >
                                        </div>
                                    </div>
                                    <?php } ?>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <?php } ?>

                    <?php if(!empty($languages)){ ?>
                    <div class="form-group">
                        <label for="seo_keywords" >SEO Keywords</label>
                        <div class="row" >
                            <div class="col-sm-12" >
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                    <?php foreach ($languages as $key => $language) { ?>
                                    <li role="presentation" class="<?php echo $key == 0 ? 'active' : '' ?>" >
                                        <a href="#seo_keywords_<?php echo $language['languages_id']; ?>" aria-controls="seo_keywords_<?php echo $language['languages_id']; ?>" role="tab" data-toggle="tab" >
                                            <?php echo $language['languages_name']; ?>
                                        </a>
                                    </li>
                                    <?php } ?>
                                </ul>

                                <div class="tab-content" >
                                    <?php foreach ($languages as $key => $language) { ?>
                                    <div class="tab-pane <?php echo $key == 0 ? 'active' : '' ?>" id="seo_keywords_<?php echo $language['languages_id']; ?>" >
                                        <div style="padding: 20px 10px;border: 1px solid #ddd;border-top: none;" >
                                            <input type="text" name="seo_keywords[<?php echo $language['languages_id']; ?>]" class="form-control" value="<?php echo empty($category_languages[$language['languages_id']]) ? '' : $category_languages[$language['languages_id']]['seo_keywords'];  ?>" >
                                        </div>
                                    </div>
                                    <?php } ?>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <?php } ?>

                    <?php if(!empty($languages)){ ?>
                    <div class="form-group">
                        <label for="seo_keywords" >SEO Description</label>
                        <div class="row" >
                            <div class="col-sm-12" >
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                    <?php foreach ($languages as $key => $language) { ?>
                                    <li role="presentation" class="<?php echo $key == 0 ? 'active' : '' ?>" >
                                        <a href="#seo_description_<?php echo $language['languages_id']; ?>" aria-controls="seo_description_<?php echo $language['languages_id']; ?>" role="tab" data-toggle="tab" >
                                            <?php echo $language['languages_name']; ?>
                                        </a>
                                    </li>
                                    <?php } ?>
                                </ul>

                                <div class="tab-content" >
                                    <?php foreach ($languages as $key => $language) { ?>
                                    <div class="tab-pane <?php echo $key == 0 ? 'active' : '' ?>" id="seo_description_<?php echo $language['languages_id']; ?>" >
                                        <div style="padding: 20px 10px;border: 1px solid #ddd;border-top: none;" >
                                            <input type="text" name="seo_description[<?php echo $language['languages_id']; ?>]" class="form-control" value="<?php echo empty($category_languages[$language['languages_id']]) ? '' : $category_languages[$language['languages_id']]['seo_description'];  ?>" >
                                        </div>
                                    </div>
                                    <?php } ?>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <?php } ?>
                    
                    <div class="form-group">
                        <label for="ordering">Thứ tự
                            <?php echo $this->formRow($form->get('ordering')); ?>
                        </label>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_published">
                                <?php echo $this->formRow($form->get('is_published')); ?>
                                Kích hoạt
                            </label>
                        </div>
                    </div>
                    <div class="form-group"  style="display:none">
                        <div class="checkbox">
                            <label for="is_faq">
                                <?php echo $this->formRow($form->get('is_faq')); ?>
                                Mục hỏi đáp
                            </label>
                        </div>
                    </div>
                    <div class="form-group"  style="display:none">
                        <div class="checkbox">
                            <label for="is_technical_category">
                                <?php echo $this->formRow($form->get('is_technical_category')); ?>
                                Là danh mục tin công nghệ
                            </label>
                        </div>
                    </div>
					<div class="form-group">
                        <div class="checkbox">
                            <label for="is_static">
                                <?php echo $this->formRow($form->get('is_static')); ?>
                                Chuyên mục tĩnh
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <button class="btn btn-primary">Lưu lại</button>
            <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>