<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Danh mục bài viết :: Quản lý
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active">Danh mục bài viết</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <form action="<?php echo $this->url('cms/carticles', array('action' => 'filter')) ?>" method="post"
                          class="filter_form form-inline" role="form">
                        <div class="form-group">
                            <label class="sr-only" for="title"></label>
                            <input type="text" class="form-control" id="title" name="categories_title" placeholder="Tên danh mục">
                        </div>
                        <!--                        <div class="form-group">-->
                        <!--                            <label class="sr-only" for="parentid">Danh mục cha</label>-->
                        <!--                            <select name="parent_id" id="parentid" class="form-control">-->
                        <!--                                --><?php //foreach($cats as $cat) : ?>
                        <!--                                    <option value="--><?php //echo $cat['categories_id'] ?><!--">--><?php //echo $cat['treename'] ?><!--</option>-->
                        <!--                                --><?php //endforeach; ?>
                        <!--                            </select>-->
                        <!--                        </div>-->
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="is_published" value="1" checked/>
                                Hiển thị
                            </label>

                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="is_delete" value="1"/>
                                Đã xóa
                            </label>
                        </div>
                        <button type="submit" class="btn btn-default">
                            <i class="fa fa-filter"></i>
                            Lọc
                        </button>

                    </form>
                </div>
            </div>
        </div>
        <form action="<?php echo $this->url('cms/carticles') ?>" method="post">
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/carticles', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm danh mục mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'publish')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'unpublish')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'updateorder')) ?>')">
                                Cập nhật thứ tự
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'delete')) ?>')">
                                Xóa danh mục
                            </button>
                            <button class="btn btn-info" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'undelete')) ?>')">
                                Khôi phục
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive">
                        <table class="table table-bordered table-hover table-data-bind">
                            <thead>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Danh mục</th>
                                <th width="100" style="text-align: center">Thứ tự</th>
                                <th width="150">Ngày tạo</th>
                                <th width="100" style="text-align: center">Hiển thị</th>
								 <th width="100" style="text-align: center">Danh mục tĩnh</th>
                                <th width="100" style="text-align: center">Đã xóa</th>
                                <th width="10"><input type="checkbox" class="checkall" /></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($cats as $cat) : ?>
                                <tr>
                                    <td style="text-align: center"><?php echo $cat['categories_articles_id'] ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('cms/carticles', array('action' => 'edit', 'id' => $cat['categories_articles_id'])) ?>"><?php echo $cat['treename'] ?></a>
                                    </td>
                                    <td style="text-align: center">
                                        <input type="text" style="width: 50px;text-align: center"
                                               name="order[<?php echo $cat['categories_articles_id'] ?>]"
                                               value="<?php echo $cat['ordering'] ?>" class="numberInput"/>
                                    </td>
                                    <td><?php echo date('d/m/Y', strtotime($cat['date_create'])) ?></td>
                                    <td style="text-align: center">
                                        <?php if($cat['is_published'] == 1) : ?>
                                            <?php $href = $this->url('cms/carticles', array('action' => 'singleunpublish', 'id' => $cat['categories_articles_id'])) ?>
                                        <?php else: ?>
                                            <?php $href = $this->url('cms/carticles', array('action' => 'singlepublish', 'id' => $cat['categories_articles_id'])) ?>
                                        <?php endif; ?>
                                        <?php echo $cat['is_published'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Đang hiển thị' data-original-title='Đang hiển thị'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Bị ẩn'><i class='fa fa-circle-o'></i></a>" ?>
                                    </td>
									 <td style="text-align: center">
                                        <?php if($cat['is_static'] == 1) : ?>
                                            <?php $href = $this->url('cms/carticles', array('action' => 'singleunstatic', 'id' => $cat['categories_articles_id'])) ?>
                                        <?php else: ?>
                                            <?php $href = $this->url('cms/carticles', array('action' => 'singlestatic', 'id' => $cat['categories_articles_id'])) ?>
                                        <?php endif; ?>
                                        <?php echo $cat['is_static'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Chuyên mục tĩnh' data-original-title='Chuyên mục tĩnh'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Chuyên mục hiển thị'><i class='fa fa-circle-o'></i></a>" ?>
                                    </td>
                                    <td style="text-align: center">
                                        <?php echo $cat['is_delete'] == 1 ? 'Đã xóa' : '-' ?>
                                    </td>
                                    <td>
                                        <input type="checkbox" name="cid[]"
                                               value="<?php echo $cat['categories_articles_id'] ?>"/>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="20" style="text-align: center">ID</th>
                                <th>Danh mục</th>
                                <th width="100" style="text-align: center">Thứ tự</th>
                                <th width="150">Ngày tạo</th>
                                <th width="100" style="text-align: center">Hiển thị</th>
								<th width="100" style="text-align: center">Danh mục tĩnh</th>
                                <th width="100" style="text-align: center">Đã Xóa</th>
                                <th width="10"><input type="checkbox" class="checkall"/></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/carticles', array('action' => 'add')) ?>"
                               class="btn btn-primary">Thêm danh mục mới</a>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'publish')) ?>')">
                                Kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'unpublish')) ?>')">
                                Bỏ kích hoạt
                            </button>
                            <button class="btn btn-primary" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'updateorder')) ?>')">
                                Cập nhật thứ tự
                            </button>
                            <button class="btn btn-danger" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'delete')) ?>')">
                                Xóa danh mục
                            </button>
                            <button class="btn btn-info" type="button"
                                    onclick="doSubmit(this.form, '<?php echo $this->url('cms/carticles', array('action' => 'undelete')) ?>')">
                                Khôi phục
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</section><!-- /.content -->