<?php if($this->datas && count($datas)) : ?>
<?php foreach ($datas as $row) : ?>
	<tr>
		<td style="text-align: center"><?php echo $row['id'] ?></td>
		<td>
			<?php if($row['email']) : ?>
				<?php echo $row['email'] ?>
			<?php else: ?>
				<?php echo $row['full_name'] ?>
			<?php endif; ?>
		</td>
		<td>
			<?php echo $row['tieu_de'] ?>
		</td>
		<td>
			<a href="<?php echo $this->Common()->getProductsUrl($row) ?>" target="_blank"><?php echo $row['products_title'] ?></a>
		</td>
		<td>
			<a href="<?php echo $this->url('cms/fqa', array('action' => 'answer','id' => $row['id'])) ?>"  data-toggle='tooltip' title='Vào trả lời' data-original-title='Vào trả lời'><?php echo !$row['total_answer'] ? 'Chưa trả lời' : "Có <strong>{$row['total_answer']}</strong> câu trả lời"  ?></a>
		</td>
		<td style="text-align:center">
			<?php
			if($row['is_published']){
				$href = $this->url('cms/fqa', array('action' => 'unpublished','id' => $row['id']));
			}else{
				$href = $this->url('cms/fqa', array('action' => 'published','id' => $row['id']));
			}
			?>
			<?php echo $row['is_published'] == 1 ? "<a href='{$href}' data-toggle='tooltip' title='Đang hiển thị' data-original-title='Đang hiển thị'><i class='fa fa-circle'></i></a>" : "<a href='{$href}' data-toggle='tooltip' title='Bị ẩn' data-original-title='Bị ẩn'><i class='fa fa-circle-o'></i></a>" ?>
		</td>
		<td>
			<?php echo date('d-m-Y H:i:s', strtotime($row['date_create'])) ?>
		</td>
		<td>
			<input type="checkbox" name="cid[]"
				   value="<?php echo $row['id'] ?>"/>
		</td>
	</tr>
<?php endforeach; ?>
<?php else: ?>
	<tr>
		<td style="text-align:center" colspan="8">Không có kết quả</td>
	</tr>
<?php endif; ?>