<?php
//txt_id_aboutus
$num = 3;
$productHots = $this->Products()->getHotProduct(0, 6);
if( empty($productHots) ){
    $num -= 1;
}
$productNews = $this->Products()->getNewProduct(0, 6);
if( empty($productNews) ){
    $num -= 1;
}
$productDeals = $this->Products()->getDealProduct(0, 6);
if( empty($productDeals) ){
    $num -= 1;
}
$sliders = $this->Banners()->getBannerWithPositionAlias('HOME');
?>
<h1 class="hidden-xs-up" ><?php echo $this->translate('txt_h1_product') ?></h1>
<?php echo $this->partial('app/slider', array('sliders' => $sliders) ); ?>

<?php if( !empty($num) ){ ?>
<div class="case-product" >
    <div class="container" >
        <div class="row text-xs-center hidden-sm-down" >
            <div class="col-lg-6 col-lg-offset-3 col-md-10 col-md-offset-1 col-sm-12" >
                <ul class="nav nav-inline tcase-product row" role="tablist">
                    <?php if( !empty($productHots) ){ ?>
                    <li class="nav-item col-xs-<?php echo 12/$num ?>" >
                        <a class="nav-link active" data-toggle="tab" href="#featured_products" role="tab">
                            <?php echo $this->translate('txt_featured_products') ?>                             
                        </a>
                    </li>
                    <?php } ?>

                    <?php if( !empty($productNews) ){ ?>
                    <li class="nav-item col-xs-<?php echo 12/$num ?>">
                        <a class="nav-link" data-toggle="tab" href="#new_arrivals" role="tab">
                            <?php echo $this->translate('txt_new_arrivals') ?>                            
                        </a>
                    </li>
                    <?php } ?>

                    <?php if( !empty($productDeals) ){ ?>
                    <li class="nav-item col-xs-<?php echo 12/$num ?>">
                        <a class="nav-link" data-toggle="tab" href="#hot_deals" role="tab">
                            <?php echo $this->translate('txt_hot_deals') ?>                        
                        </a>
                    </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div class="tab-content" >
            <?php if( !empty($productHots) ){ ?>
            <div class="tab-pane fade in active" role="tabpanel" id="featured_products" >
                <div class="hidden-md-up" >
                    <ul class="nav nav-inline tcase-product tcase-product-mm" >
                        <li class="nav-item" >
                            <a class="nav-link text-xs-center" href="#featured_products" >
                                <?php echo $this->translate('txt_featured_products') ?>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="list-product col-padd-empty" >
                    <div class="row lsProductsHots" >
                        <?php foreach ($productHots as $key => $p) { ?>
                            <div class="col-lg-4 col-md-4 col-sm-6" >
                                <?php echo $this->partial('app/item-product', array('product' => $p) ); ?>
                            </div>
                            <?php if( $key%3 == 0 ){ ?>
                            <div class="col-sm-12 hidden-sm-up" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php }else if( $key%3 == 1 ){ ?>
                            <div class="col-sm-12 hidden-md-up" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php }else if( $key%3 == 2 ){ ?>
                            <div class="col-sm-12 hidden-sm-down" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>

                <div class="text-xs-center" >
                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/category/hots" title="<?php echo $this->translate('txt_view_all') ?>" class="btn btn-style btn-view-more-ajax" data-btn="ajackProducts" data-page="1" data-page_size="6" data-el=".lsProductsHots" >
                        <?php echo $this->translate('txt_view_all') ?>
                    </a>
                </div>
            </div>
            <?php } ?>

            <?php if( !empty($productNews) ){ ?>
            <div class="tab-pane fade in <?php echo empty($productHots) ? 'active' : '' ?>" role="tabpanel" id="new_arrivals" >
                <div class="hidden-md-up" >
                    <ul class="nav nav-inline tcase-product tcase-product-mm" >
                        <li class="nav-item" >
                            <a class="nav-link text-xs-center" href="#new_arrivals" >
                                <?php echo $this->translate('txt_new_arrivals') ?>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="list-product col-padd-empty" >
                    <div class="row lsProductsNews" data-place="lsProducts" >
                        <?php foreach ($productNews as $key => $p) { ?>
                            <div class="col-lg-4 col-md-4 col-sm-6" >
                                <?php echo $this->partial('app/item-product', array('product' => $p) ); ?>
                            </div>
                            <?php if( $key%3 == 0 ){ ?>
                            <div class="col-sm-12 hidden-sm-up" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php }else if( $key%3 == 1 ){ ?>
                            <div class="col-sm-12 hidden-md-up" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php }else if( $key%3 == 2 ){ ?>
                            <div class="col-sm-12 hidden-sm-down" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>

                <div class="text-xs-center" >
                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/category/news" title="<?php echo $this->translate('txt_view_all') ?>" class="btn btn-style btn-view-more-ajax" data-btn="ajackProducts" data-page="1" data-page_size="6" data-el=".lsProductsNews" >
                        <?php echo $this->translate('txt_view_all') ?>
                    </a>
                </div>
            </div>
            <?php } ?>

            <?php if( !empty($productDeals) ){ ?>
            <div class="tab-pane fade in <?php echo (empty($productHots) && empty($productNews)) ? 'active' : '' ?>" role="tabpanel" id="hot_deals" >
                <div class="hidden-md-up" >
                    <ul class="nav nav-inline tcase-product tcase-product-mm" >
                        <li class="nav-item" >
                            <a class="nav-link text-xs-center" href="#hot_deals" >
                                <?php echo $this->translate('txt_hot_deals') ?>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="list-product col-padd-empty" >
                    <div class="row lsProductsDeals" data-place="lsProducts" >
                        <?php foreach ($productDeals as $key => $p) { ?>
                            <div class="col-lg-4 col-md-4 col-sm-6" >
                                <?php echo $this->partial('app/item-product', array('product' => $p) ); ?>
                            </div>
                            <?php if( $key%3 == 0 ){ ?>
                            <div class="col-sm-12 hidden-sm-up" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php }else if( $key%3 == 1 ){ ?>
                            <div class="col-sm-12 hidden-md-up" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php }else if( $key%3 == 2 ){ ?>
                            <div class="col-sm-12 hidden-sm-down" >
                                <div class="line-grid" ></div>
                            </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>
                <div class="text-xs-center" >
                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/category/deals" title="<?php echo $this->translate('txt_view_all') ?>" class="btn btn-style btn-view-more-ajax" data-btn="ajackProducts" data-page="1" data-page_size="6" data-el=".lsProductsDeals" >
                        <?php echo $this->translate('txt_view_all') ?>
                    </a>
                </div>
            </div>
            <?php } ?>

        </div>
    </div>
</div>
<?php } ?>

<?php echo $this->partial('app/case-quote', array() ); ?>

<?php echo $this->partial('app/case-feature', array() ); ?>

<?php echo $this->partial('app/case-supplier', array() ); ?>

<?php echo $this->partial('app/case-upgrate', array() ); ?>