<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/invoice') ?>">
                        <?php echo $this->translate('txt_hoa_don'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_chi_tiet_hoa_don'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_hoa_don'); ?> :: 
                <?php echo $this->translate('txt_chi_tiet_hoa_don'); ?>
            </h1>
        </div>
    </div>
</section>

<section class="content" >
    <div class="clearfix">
        <div class="row" >
            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>
                        <?php echo $this->translate('txt_khach_hang'); ?>
                    </h5>
                    <div class="m-info-invoice" >
                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    <?php echo $this->translate('txt_ho_va_ten'); ?>
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->full_name ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    <?php echo $this->translate('txt_so_dien_thoai'); ?>
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->phone ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    <?php echo $this->translate('txt_email'); ?>
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->email ?></b>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>
                        <?php echo $this->translate('txt_dia_chi_giao_hang'); ?>
                    </h5>
                    <div class="m-info-invoice" >
                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    <?php echo $this->translate('txt_ho_va_ten'); ?>
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_full_name ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    <?php echo $this->translate('txt_so_dien_thoai'); ?>
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_phone ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    <?php echo $this->translate('txt_email'); ?>
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_email ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    <?php echo $this->translate('txt_dia_chi'); ?>
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $this->Invoice()->getAddress($invoice, 1); ?></b>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>
                        <?php echo $this->translate('txt_thong_tin_thanh_toan'); ?>
                    </h5>
                    <div class="m-info-invoice" >
                        <div class="form-group">
                            <b><?php echo $this->Invoice()->getAddress($invoice); ?></b>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5>
                        <?php echo $this->translate('txt_danh_sach_san_pham'); ?>
                    </h5>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-data-bind table-bordered" >
                <thead>
                    <tr>
                        <th class="text-left col-lim" >
                            <?php echo $this->translate('txt_ma'); ?>
                        </th>
                        <th class="text-center" width="100" >
                            <?php echo $this->translate('txt_hinh'); ?>
                        </th>
                        <th colspan="5" >
                            <?php echo $this->translate('txt_san_pham'); ?>
                        </th>
                        <th class="text-right col-lim" colspan="2" >
                            <?php echo $this->translate('txt_don_gia'); ?>
                        </th>
                        <th class="text-right col-lim" >
                            <?php echo $this->translate('txt_so_luong'); ?>
                        </th>
                        <th class="text-right col-lim" >
                            <?php echo $this->translate('txt_thanh_tien'); ?>
                        </th>
                        <th class="text-right col-lim" >
                            <?php echo $this->translate('txt_tong_tien'); ?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                <?php 
                foreach($products as $key => $product){
                    foreach($product['product_type'] as $product_type_id => $row){
                        $extentions = array_merge($row['extensions'], $row['extensions_require']);
                ?>
                    <tr>
                        <td <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> class="text-left col-lim" >
                            <?php echo $product['products_code'] ?>
                        </td>

                        <td>
                            <a href="<?php echo $this->Products()->getLink($row); ?>" target="_blank">
                                <img src="<?php echo $this->Images()->getUrlImage($this->Products()->getImage($row),100); ?>" class="img-reponsive" width="100" >
                            </a>
                        </td>

                        <td colspan="5" >
                            <a href="<?php echo $this->Products()->getLink($row); ?>" target="_blank">
                                <?php echo $this->Products()->getName($row); ?>
                            </a>
                        </td>

                        <td class="text-right col-lim" <?php echo empty($row['extensions_require']) ? 'colspan="2"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSaleSimple($row)) ?>
                        </td>

                        <?php if( !empty($row['extensions_require']) ){ ?>
                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)) ?>
                        </td>
                        <?php } ?>

                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Cart()->getProductsQuantity($row) ?>
                        </td>

                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)*$this->Cart()->getProductsQuantity($row)) ?>
                        </td>
                        <td class="text-right col-lim" <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($row['price_total']) ?>
                            <input type='hidden' name='pdetail[<?php echo $product['products_id'] ?>][price_total]' value='<?php echo $row['price_total'] ?>' />
                        </td>
                    </tr>

                    <?php 
                    $k_ex = 0;
                    if(!empty($row['extensions_require'])){
                        foreach ($row['extensions_require'] as $k_ => $ext) {
                            $quality = $ext['quantity'];
                    ?>
                    <tr>
                        <?php if($k_ex == 0){ ?>
                        <td rowspan="<?php echo count($extentions); ?>" class="col-lim text-center" >
                            <?php echo $this->translate('txt_sp_dinh_kem');?>
                        </td>
                        <?php } ?>
                        <td class="col-lim text-right">
                            <?php echo ($k_ex+1); ?>
                        </td>
                        <td colspan="2" >
                            <?php echo $ext['ext_name'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $quality; ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                        </td>
                    </tr>
                    <?php 
                            $k_ex++;
                        }
                    } ?>

                    <?php 
                        if( !empty($row['extensions']) ){
                            foreach ($row['extensions'] as $k_ => $ext) {
                                $quality = $ext['quantity'];
                        ?>
                        <tr>
                            <td class="col-lim" >
                                <?php echo ($k_ex+1); ?>
                            </td>
                            <td colspan="5" >
                                <?php echo $ext['ext_name'] ?>
                            </td>
                            <td class="col-lim text-right" >
                                <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                            </td>
                            <td class="col-lim text-right" >
                                <?php echo $quality; ?>
                            </td>
                            <td class="col-lim text-right" >
                                <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                            </td>
                        </tr>
                        <?php $k_ex++; 
                            }
                        } ?>

                <?php }
                } ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_tam_tinh'); ?>
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($total_orig) ?>
                            </strong>
                        </td>
                    </tr>

                    <?php if ( !empty($coupon) ) { ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_giam_gia'); ?>
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($coupon['coupon_price']) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php } ?>

                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_phi_van_chuyen'); ?>
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($fee, 'txt_mien_phi_ship') ?>
                            </strong>
                        </td>
                    </tr>

                    <?php if( $total < $total_tax ){ ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_tong_cong_truoc'); ?>
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency($total + $fee) ?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_tien_thue'); ?>
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency(($total_tax - $total)) ?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_tien_sau_thue'); ?>
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($total_tax + $fee) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php }else{ ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_tong_cong'); ?>
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency($total + $fee) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php } ?>

                </tbody>
            </table>
        </div>

        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5>
                        <?php echo $this->translate('txt_thong_tin_hoa_don'); ?>
                    </h5>
                </div>
            </div>
        </div>
        <div class="table-responsive" >
            <table class="table table-data-bind table-no-border" >
                <tbody>
                    <tr>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_so_hoa_don'); ?>
                        </th>
                        <td>
                            <b><?php echo $invoice->invoice_title ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_ngay_dat_hang'); ?>
                        </th>
                        <td>
                            <b><?php echo $invoice->date_create ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_phuong_thuc_thanh_toan'); ?>
                        </th>
                        <td>
                            <b><?php echo $invoice->payment_code ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_dau_ten_voi_nguoi_nhan'); ?>
                        </th>
                        <td>
                            <?php if( !empty($invoice->is_incognito) ){ ?>
                            <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Dấu tên với người nhận" >
                                <i class="fa fa-check" aria-hidden="true"></i>
                            </span>
                            <?php }else{ ?>
                            <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Không dấu tên với người nhận" >
                                <i class="fa fa-check" aria-hidden="true"></i>
                            </span>
                            <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_so_dien_thoai_nguoi_nhan'); ?>
                        </th>
                        <td>
                            <b><?php echo $invoice->ships_phone ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_thong_tin_giao_hang'); ?>
                        </th>
                        <td>
                            <b><?php echo $invoice->date_delivery ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_thong_diep'); ?>
                        </th>
                        <td>
                            <b><?php echo $invoice->invoice_description ?></b>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>


        <?php if( !empty($logs) ){ ?>
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5>
                        <?php echo $this->translate('txt_lich_su_trang_thai_don_hang'); ?>
                    </h5>
                </div>
            </div>
        </div>
        <div class="table-responsive" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th  class="col-lim" >
                            <?php echo $this->translate('txt_ngay_add'); ?>
                        </th>
                        <th class="col-lim  text-center" >
                            <?php echo $this->translate('txt_thong_bao_cho_khach_hang'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_trang_thai'); ?>
                        </th>
                        <th >
                            <?php echo $this->translate('txt_y_kien_binh_luan'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_nhan_vien_cap_nhat'); ?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($logs as $key => $log) { ?>
                    <tr>
                        <td class="col-lim" >
                            <?php echo $log['date_create'] ?>
                        </td>
                        <td class="col-lim text-center" >
                            <?php if( !empty($log['has_feedback']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_co_thong_bao'); ?>" >
                                    <i class="fa fa-bell" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_khong_co_thong_bao'); ?>" >
                                    <i class="fa fa-bell" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="col-lim" >
                            <?php echo $log['invoice_status'] ?>
                        </td>
                        <td >
                            <?php echo $log['comment'] ?>
                        </td>
                        <td class="col-lim" >
                            <?php echo $log['first_name'].' '.$log['last_name'] ?>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php } ?>


        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/invoice', array('action' => 'updateInvoice', 'id' => $id)));
        $form->setAttribute('id', 'form-invoice');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('invoice_id'));
        ?>
        <div class="row" >
            <div class="col-sm-6" >
                <div class="form-group" >
                    <label for="comment">
                        <?php echo $this->translate('txt_y_kien_binh_luan'); ?>
                    </label>
                    <textarea class="form-control input-sm" name="comment" id="comment" ></textarea>
                </div>
                <div class="form-group" >
                    <label for="delivery">
                        <?php echo $this->translate('txt_trang_thai_don_hang'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('delivery')); ?>
                </div>
            </div>
        </div>
        <div class="form-group" >
            <?php echo $this->translate('txt_thong_bao_cho_khach_hang'); ?> : 
            [
                <label>
                    <input type="radio" name="has_feedback" value="1" checked="checked" >
                    - Email
                </label>
                <label>
                    <input type="radio" name="has_feedback" value="0" >
                    - No Email
                </label>
                <label>
                    <input type="radio" name="has_feedback" value="0" >
                    - Hide
                </label>
            ]

            <label>
                <?php echo $this->translate('txt_kem_loi_binh'); ?> : 
                <input type="checkbox" name="has_comment" value="1" checked="checked" >
            </label>
        </div>
        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                <?php echo $this->translate('txt_cap_nhat_don_hang'); ?>
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                <?php echo $this->translate('txt_quay_lai'); ?>
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12 text-right" > 
                    <a href="javascript:void(0);" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_in_hoa_don'); ?>"  >
                        <i class="fa fa-print" aria-hidden="true"></i>
                    </a>
                    <a href="javascript:void(0);" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_in_phan_hoi'); ?>"  >
                        <i class="fa fa-address-card-o" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>