<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        Trang chủ
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/invoice') ?>">
                        Hóa đơn
                    </a>
                </li>
                <li class="active">Chi tiết hóa đơn</li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                Hóa đơn :: Chi tiết hóa đơn
            </h1>
        </div>
    </div>
</section>

<section class="content" >
    <div class="clearfix">
        <div class="row" >
            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>Khách hàng</h5>
                    <div class="m-info-invoice" >
                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Họ và tên
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->full_name ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Số điện thoại
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->phone ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Email
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->email ?></b>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>
                        Địa chỉ giao hàng
                    </h5>
                    <div class="m-info-invoice" >
                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Họ và tên
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_full_name ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Số điện thoại
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_phone ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Email
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_email ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Địa chỉ
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $this->Invoice()->getAddress($invoice, 1); ?></b>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>
                        Thông tin thanh toán
                    </h5>
                    <div class="m-info-invoice" >
                        <div class="form-group">
                            <b><?php echo $this->Invoice()->getAddress($invoice); ?></b>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5>
                        Danh sách sản phẩm
                    </h5>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-data-bind table-bordered" >
                <thead>
                    <tr>
                        <th class="text-left col-lim" >Mã</th>
                        <th class="text-center" width="100" >Hình</th>
                        <th colspan="5" >Sản phẩm</th>
                        <th class="text-right col-lim" colspan="2" >Đơn giá</th>
                        <th class="text-right col-lim" >Số lượng</th>
                        <th class="text-right col-lim" >Thành tiền</th>
                        <th class="text-right col-lim" >Tổng tiền</th>
                    </tr>
                </thead>
                <tbody>
                <?php 
                foreach($products as $key => $product){
                    foreach($product['product_type'] as $product_type_id => $row){
                        $extentions = array_merge($row['extensions'], $row['extensions_require']);
                ?>
                    <tr>
                        <td <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> class="text-left col-lim" >
                            <?php echo $product['products_code'] ?>
                        </td>

                        <td>
                            <a href="<?php echo $this->Products()->getLink($row); ?>" target="_blank">
                                <img src="<?php echo $this->Images()->getUrlImage($this->Products()->getImage($row),100); ?>" class="img-reponsive" width="100" >
                            </a>
                        </td>

                        <td colspan="5" >
                            <a href="<?php echo $this->Products()->getLink($row); ?>" target="_blank">
                                <?php echo $this->Products()->getName($row); ?>
                            </a>
                        </td>

                        <td class="text-right col-lim" <?php echo empty($row['extensions_require']) ? 'colspan="2"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSaleSimple($row)) ?>
                        </td>

                        <?php if( !empty($row['extensions_require']) ){ ?>
                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)) ?>
                        </td>
                        <?php } ?>

                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Cart()->getProductsQuantity($row) ?>
                        </td>

                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)*$this->Cart()->getProductsQuantity($row)) ?>
                        </td>
                        <td class="text-right col-lim" <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($row['price_total']) ?>
                            <input type='hidden' name='pdetail[<?php echo $product['products_id'] ?>][price_total]' value='<?php echo $row['price_total'] ?>' />
                        </td>
                    </tr>

                    <?php 
                    $k_ex = 0;
                    if(!empty($row['extensions_require'])){
                        foreach ($row['extensions_require'] as $k_ => $ext) {
                            $quality = $ext['quantity'];
                    ?>
                    <tr>
                        <?php if($k_ex == 0){ ?>
                        <td rowspan="<?php echo count($extentions); ?>" class="col-lim text-center" >
                            <?php echo $this->translate('txt_sp_dinh_kem');?>
                        </td>
                        <?php } ?>
                        <td class="col-lim text-right">
                            <?php echo ($k_ex+1); ?>
                        </td>
                        <td colspan="2" >
                            <?php echo $ext['ext_name'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $quality; ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                        </td>
                    </tr>
                    <?php 
                            $k_ex++;
                        }
                    } ?>

                    <?php 
                        if( !empty($row['extensions']) ){
                            foreach ($row['extensions'] as $k_ => $ext) {
                                $quality = $ext['quantity'];
                        ?>
                        <tr>
                            <td class="col-lim" >
                                <?php echo ($k_ex+1); ?>
                            </td>
                            <td colspan="5" >
                                <?php echo $ext['ext_name'] ?>
                            </td>
                            <td class="col-lim text-right" >
                                <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                            </td>
                            <td class="col-lim text-right" >
                                <?php echo $quality; ?>
                            </td>
                            <td class="col-lim text-right" >
                                <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                            </td>
                        </tr>
                        <?php $k_ex++; 
                            }
                        } ?>

                <?php }
                } ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tạm tính
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($total_orig) ?>
                            </strong>
                        </td>
                    </tr>

                    <?php if ( !empty($coupon) ) { ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Giảm giá
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($coupon['coupon_price']) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php } ?>

                    <tr>
                        <td colspan="10" class="text-right" >
                            Phí vận chuyển
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($fee, 'txt_mien_phi_ship') ?>
                            </strong>
                        </td>
                    </tr>

                    <?php if( $total < $total_tax ){ ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tổng cộng trước
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency($total + $fee) ?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tiền thuế
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency(($total_tax - $total)) ?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tổng sau thuế
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($total_tax + $fee) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php }else{ ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tổng cộng
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency($total + $fee) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php } ?>

                </tbody>
            </table>
        </div>

        <?php if(   !empty($assign) 
                    && !empty($assign->merchant_name) 
                    && in_array($assign->assign_status, array('accept', 'finish')) ){ ?>
        <h4>
            Đại lý thực hiện đơn hàng(<i><?php echo $assign->merchant_name ?></i>)
        </h4>
        <div class="row" >
            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>Người thực hiện</h5>
                    <div class="m-info-invoice" >
                        <?php if( !empty($user) ){ ?>
                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Họ và tên
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $user->full_name ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Số điện thoại
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $user->phone ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Email
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $user->user_name ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Địa chỉ
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $this->Invoice()->getAddress($user); ?></b>
                                </div>
                            </div>
                        </div>
                        <?php }else{ ?>
                        <div class="text-center" >
                            <i class="fa fa-user-secret" aria-hidden="true"></i>
                        </div>
                        <?php } ?>
                    </div>
                </div>

            </div>

            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>
                        Địa chỉ giao hàng
                    </h5>
                    <div class="m-info-invoice" >
                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Họ và tên
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_full_name ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Số điện thoại
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_phone ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Email
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $invoice->ships_email ?></b>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" >
                                <div class="col-xs-4" >
                                    Địa chỉ
                                </div>
                                <div class="col-xs-8" >
                                    <b><?php echo $this->Invoice()->getAddress($invoice, 1); ?></b>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-4 col-xs-12" >
                <div class="box-info-invoice" >
                    <h5>
                        Thông tin thanh toán
                    </h5>
                    <div class="m-info-invoice" >
                        <?php if( !empty($merchant) ){ ?>
                        <div class="form-group">
                            <b>Đại lý : <?php echo $merchant['merchant_name'] ?></b><br />
                            <b>Địa chỉ : <?php echo $this->Invoice()->getAddress($merchant); ?></b>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </div>

        </div>
        <?php }else{ ?>
        <h4>
            Chưa có đại lý nhận đơn hàng
        </h4>
        <?php } ?>

        <?php if( !empty($assign_products) ) { ?>
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5>
                        Danh sách sản phẩm assign
                    </h5>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-data-bind table-bordered" >
                <thead>
                    <tr>
                        <th class="text-left col-lim" >Mã</th>
                        <th class="text-center" width="100" >Hình</th>
                        <th colspan="5" >Sản phẩm</th>
                        <th class="text-right col-lim" colspan="2" >Đơn giá</th>
                        <th class="text-right col-lim" >Số lượng</th>
                        <th class="text-right col-lim" >Thành tiền</th>
                        <th class="text-right col-lim" >Tổng tiền</th>
                    </tr>
                </thead>
                <tbody>
                <?php 
                foreach($assign_products as $key => $product){
                    foreach($product['product_type'] as $product_type_id => $row){
                        $extentions = array_merge($row['extensions'], $row['extensions_require']);
                ?>
                    <tr>
                        <td <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> class="text-left col-lim" >
                            <?php echo $product['products_code'] ?>
                        </td>

                        <td>
                            <a href="<?php echo $this->Products()->getLink($row); ?>" target="_blank">
                                <img src="<?php echo $this->Images()->getUrlImage($this->Products()->getImage($row),100); ?>" class="img-reponsive" width="100" >
                            </a>
                        </td>

                        <td colspan="5" >
                            <a href="<?php echo $this->Products()->getLink($row); ?>" target="_blank">
                                <?php echo $this->Products()->getName($row); ?>
                            </a>
                        </td>

                        <td class="text-right col-lim" <?php echo empty($row['extensions_require']) ? 'colspan="2"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSaleSimple($row)) ?>
                        </td>

                        <?php if( !empty($row['extensions_require']) ){ ?>
                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)) ?>
                        </td>
                        <?php } ?>

                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Cart()->getProductsQuantity($row) ?>
                        </td>

                        <td class="text-right col-lim" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)*$this->Cart()->getProductsQuantity($row)) ?>
                        </td>
                        <td class="text-right col-lim" <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> >
                            <?php echo $this->Currency()->fomatCurrency($row['price_total']) ?>
                            <input type='hidden' name='pdetail[<?php echo $product['products_id'] ?>][price_total]' value='<?php echo $row['price_total'] ?>' />
                        </td>
                    </tr>

                    <?php 
                    $k_ex = 0;
                    if(!empty($row['extensions_require'])){
                        foreach ($row['extensions_require'] as $k_ => $ext) {
                            $quality = $ext['quantity'];
                    ?>
                    <tr>
                        <?php if($k_ex == 0){ ?>
                        <td rowspan="<?php echo count($extentions); ?>" class="col-lim text-center" >
                            <?php echo $this->translate('txt_sp_dinh_kem');?>
                        </td>
                        <?php } ?>
                        <td class="col-lim text-right">
                            <?php echo ($k_ex+1); ?>
                        </td>
                        <td colspan="2" >
                            <?php echo $ext['ext_name'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $quality; ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                        </td>
                    </tr>
                    <?php 
                            $k_ex++;
                        }
                    } ?>

                    <?php 
                    if( !empty($row['extensions']) ){
                        foreach ($row['extensions'] as $k_ => $ext) {
                            $quality = $ext['quantity'];
                    ?>
                    <tr>
                        <td class="col-lim" >
                            <?php echo ($k_ex+1); ?>
                        </td>
                        <td colspan="5" >
                            <?php echo $ext['ext_name'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $quality; ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                        </td>
                    </tr>
                    <?php $k_ex++; 
                        }
                    } ?>

                <?php }
                } ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tạm tính
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($assign_total_orig) ?>
                            </strong>
                        </td>
                    </tr>

                    <?php if ( !empty($coupon) ) { ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Giảm giá
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($coupon['coupon_price']) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php } ?>

                    <tr>
                        <td colspan="10" class="text-right" >
                            Phí vận chuyển
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($assign->assign_shipping, 'txt_mien_phi_ship') ?>
                            </strong>
                        </td>
                    </tr>

                    <?php if( $total < $total_tax ){ ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tổng cộng trước
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency($assign_total + $assign->assign_shipping) ?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tiền thuế
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency(($assign_total_tax - $total)) ?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tổng sau thuế
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($assign_total_tax + $assign->assign_shipping) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php }else{ ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            Tổng cộng
                        </td>
                        <td colspan="2" class="text-right" >
                            <strong class="coz-color-important"  >
                                <?php echo $this->Currency()->fomatCurrency($assign_total + $assign->assign_shipping) ?>
                            </strong>
                        </td>
                    </tr>
                    <?php } ?>

                </tbody>
            </table>
        </div>
        <?php } ?>

        <?php if( !empty($merchants) ) { ?>
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5>
                        Danh sách đại lý đã assign 
                        <a href="<?php echo $this->url('cms/assign', array('action' => 'edit', 'id'=> $invoice->assign_id)) ?>" data-toggle="tooltip" data-placement="top" title="Xem merchant" >
                            Xem assign <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </a>
                    </h5>
                </div>
            </div>
        </div>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th>Tên</th>
                        <th class="col-lim" >Địa chỉ</th>
                        <th class="col-lim text-right" >Số ĐT</th>
                        <th class="col-lim text-right" >Fax</th>
                        <th class="col-lim text-right" >Email</th>
                        <th class="col-lim text-right" >Trạng thái</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($merchants as $key=>$merchant ) { ?>
                    <tr>
                        <td>
                            <?php echo $merchant['merchant_name'] ?>
                        </td>
                        <td class="col-lim" >
                            <?php echo $merchant['address'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $merchant['merchant_phone'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $merchant['merchant_fax'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <?php echo $merchant['merchant_email'] ?>
                        </td>
                        <td class="col-lim text-right" >
                            <span class="round-order-status round-order-<?php echo $merchant['assign_merchant_status'] ?>" >
                                <?php echo $merchant['assign_merchant_status'] ?>
                            </span>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5 class="text-center" >
                        Chưa có assign <br />
                        Thêm assign 
                        <a href="<?php echo $this->url('cms/assign', array('action' => 'add', 'id'=> $invoice->invoice_id)) ?>" data-toggle="tooltip" data-placement="top" title="Xem merchant" >
                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </a> 
                    </h5>
                </div>
            </div>
        </div>
        <?php } ?>

        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5>
                        Thông tin hoá đơn
                    </h5>
                </div>
            </div>
        </div>
        <div class="table-responsive" >
            <table class="table table-data-bind table-no-border" >
                <tbody>
                    <tr>
                        <th class="col-lim" >
                            Số hóa đơn
                        </th>
                        <td>
                            <b><?php echo $invoice->invoice_title ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            Ngày đặt hàng
                        </th>
                        <td>
                            <b><?php echo $invoice->date_create ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            Phương thức thanh toán
                        </th>
                        <td>
                            <b><?php echo $invoice->payment_code ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            Dấu tên với người nhận
                        </th>
                        <td>
                            <?php if( !empty($invoice->is_incognito) ){ ?>
                            <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Dấu tên với người nhận" >
                                <i class="fa fa-check" aria-hidden="true"></i>
                            </span>
                            <?php }else{ ?>
                            <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Không dấu tên với người nhận" >
                                <i class="fa fa-check" aria-hidden="true"></i>
                            </span>
                            <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            Số đt người nhận
                        </th>
                        <td>
                            <b><?php echo $invoice->ships_phone ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            Thông tin giao hàng
                        </th>
                        <td>
                            <b><?php echo $invoice->date_delivery ?></b>
                        </td>
                    </tr>
                    <tr>
                        <th class="col-lim" >
                            Thông điệp
                        </th>
                        <td>
                            <b><?php echo $invoice->invoice_description ?></b>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>


        <?php if( !empty($logs) ){ ?>
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12" > 
                    <h5>
                        Lịch sử trạng thái đơn hàng
                    </h5>
                </div>
            </div>
        </div>
        <div class="table-responsive" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th  class="col-lim" >Date Added</th>
                        <th class="col-lim  text-center" >Thông báo cho khách hàng</th>
                        <th class="col-lim" >Trạng thái</th>
                        <th >Ý kiến/Bình luận</th>
                        <th class="col-lim" >Nhân Viên Cập Nhật</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($logs as $key => $log) { ?>
                    <tr>
                        <td class="col-lim" >
                            <?php echo $log['date_create'] ?>
                        </td>
                        <td class="col-lim text-center" >
                            <?php if( !empty($log['has_feedback']) ){ ?>
                                <span class="coz-color-ative" data-toggle="tooltip" data-placement="top" title="Có thông báo" >
                                    <i class="fa fa-bell" aria-hidden="true"></i>
                                </span>
                            <?php }else{ ?>
                                <span class="coz-color-disable" data-toggle="tooltip" data-placement="top" title="Không thông báo" >
                                    <i class="fa fa-bell" aria-hidden="true"></i>
                                </span>
                            <?php } ?>
                        </td>
                        <td class="col-lim" >
                            <?php echo $log['invoice_status'] ?>
                        </td>
                        <td >
                            <?php echo $log['comment'] ?>
                        </td>
                        <td class="col-lim" >
                            <?php echo $log['first_name'].' '.$log['last_name'] ?>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php } ?>


        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/invoice', array('action' => 'updateInvoice', 'id' => $id)));
        $form->setAttribute('id', 'form-invoice');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('invoice_id'));
        ?>
        <div class="row" >
            <div class="col-sm-6" >
                <div class="form-group" >
                    <label for="comment">
                        Ý kiến/Bình luận
                    </label>
                    <textarea class="form-control input-sm" name="comment" id="comment" ></textarea>
                </div>
                <div class="form-group" >
                    <label for="delivery">
                        Status đơn hàng
                    </label>
                    <?php echo $this->formRow($form->get('delivery')); ?>
                </div>
            </div>
        </div>
        <div class="form-group" >
            Thông báo cho khách hàng : 
            [
                <label>
                    <input type="radio" name="has_feedback" value="1" checked="checked" >
                    - Email
                </label>
                <label>
                    <input type="radio" name="has_feedback" value="0" >
                    - No Email
                </label>
                <label>
                    <input type="radio" name="has_feedback" value="0" >
                    - Hide
                </label>
            ]

            <label>
                Kèm lời bình : <input type="checkbox" name="has_comment" value="1" checked="checked" >
            </label>
        </div>
        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                Cập nhật đơn hàng
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                Quay lại
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        <div class="toolbar clearfix" >
            <div class="row" >
                <div class="col-sm-12 text-right" > 
                    <a href="javascript:void(0);" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="In hoá đơn"  >
                        <i class="fa fa-print" aria-hidden="true"></i>
                    </a>
                    <a href="javascript:void(0);" class="btn btn-link" data-toggle="tooltip" data-placement="top" title="In phản hồi"  >
                        <i class="fa fa-address-card-o" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>