<?php foreach ($invoices as $row) : ?>
	<tr>
		<td><?php echo $row['invoice_id'] ?></td>
		<td>
			<a href="<?php echo $this->url('cms/invoice', array('action' => 'edit', 'id' => $row['invoice_id'])) ?>"><?php echo $row['invoice_title'] ?></a>
		</td>
		<td style="text-align: center">
			<?php echo $row['total_products'] ?>
		</td>
		<td style="text-align: right">
			<?php echo number_format($row['total']) ?>
		</td>
		<td style="text-align: center">
			<select name="data[delivery][<?php echo $row['invoice_id'] ?>]" item-name="delivery" item-id="<?php echo $row['invoice_id'] ?>" onchange="javascript:invoice_change(this);" class="invoice_update form-control">
				<option value="no_delivery" <?php echo $row['delivery'] == 'no_delivery' ? 'selected' : '' ?>>Chưa giao hàng</option>
				<option value="delivered" <?php echo $row['delivery'] == 'delivered' ? 'selected' : '' ?>>Đã giao hàng</option>
				<option value="delivering" <?php echo $row['delivery'] == 'delivering' ? 'selected' : '' ?>>Đang giao hàng</option>
			</select>
		</td>
		<td style="text-align: center">
			<select name="data[payment][<?php echo $row['invoice_id'] ?>]" item-name="payment" item-id="<?php echo $row['invoice_id'] ?>" onchange="javascript:invoice_change(this);" class="invoice_update form-control">
				<option value="unpaid" <?php echo $row['payment'] == 'unpaid' ? 'selected' : '' ?>>Chưa thanh toán</option>
				<option value="paid" <?php echo $row['payment'] == 'paid' ? 'selected' : '' ?>>Đã thanh toán</option>
			</select>
		</td>
		<td style="text-align: left">
			<?php echo $row['date_create'] ?>
		</td>
		<td style="text-align: center">
			<input type="checkbox" name="cid[]"
				   value="<?php echo $row['invoice_id'] ?>"/>
		</td>
	</tr>
<?php endforeach; ?>