<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/invoice') ?>">
                        <?php echo $this->translate('txt_hoa_don'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_report'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_hoa_don'); ?> :: 
                <?php echo $this->translate('txt_report'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
            <form action="<?php echo $this->url('cms/invoice', array('action' => 'report')) ?>" method="get">
                <div class="coz-search-bar clearfix" data-form="searchAjax" >
                    <div class="input-group">
                        <div class="row row-coz-search" >
                            <div class="col-xs-7 col-coz-search" >
                                <input type="text" name="q" class="form-control" placeholder="<?php echo $this->translate('txt_holder_search'); ?>" value="<?php echo $q ?>" >
                            </div>
                            <div class="col-xs-5 col-coz-search" >
                                <select name="type" class="form-control" >
                                    <option value="0" <?php echo $type == 0 ? 'selected="selected"' : '' ?> >
                                        <?php echo $this->translate('txt_kieu_tim_kiem'); ?> : 
                                        <?php echo $this->translate('txt_theo_ma_hoa_don'); ?>
                                    </option>
                                    <option value="1" <?php echo $type == 1 ? 'selected="selected"' : '' ?> >
                                        <?php echo $this->translate('txt_kieu_tim_kiem'); ?> : 
                                        <?php echo $this->translate('txt_theo_ten_khach_hang'); ?>
                                    </option>
                                </select>
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" name="seach" id="search-btn" class="btn btn-flat"  data-btn="searchAjax" >
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/invoice', array('action' => 'report')) ?>" method="post" class="clearfix" >
        
        <?php if( !empty($invoices) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-invoice-report table-bordered" >
                <thead>
                    <tr>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_ma_don_hang'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_ngay_dat_hang'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_nguoi_dat_hang'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_dai_ly_giao'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_loai_giao_dich'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_so_luong'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_gia_hoa'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_gia_van_chuyen'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_tong_tien'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_muc_hoa_hong'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_hoa_hong_tra_dai_ly'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_tong_tien_thu_chi'); ?>
                        </th>
                        <th class="col-lim" >
                            <?php echo $this->translate('txt_loi_nhuan'); ?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($invoices as $key => $row) { ?>
                    <tr>
                        <td class="col-lim" valign="middle" >
                            <?php echo $row['invoice_id'] ?>            
                        </td>
                        <td class="col-lim" valign="middle" >
                            <?php echo $row['date_create'] ?>           
                        </td>
                        <td class="col-lim" valign="middle" >
                            <?php echo $row['first_name'].' '.$row['last_name'] ?>            
                        </td>
                        <td class="col-lim" valign="middle" >
                            <?php echo $this->Invoice()->getAddress($row); ?>            
                        </td>
                        <td class="col-lim" valign="middle" >
                            Bán(+)            
                        </td>
                        <td class="col-lim text-right" valign="middle" >
                            <?php echo $row['total_products'] ?>            
                        </td>
                        <td class="col-lim text-right" valign="middle" >
                            <?php echo $this->Currency()->fomatCurrency($row['total']) ?>            
                        </td>
                        <td class="col-lim text-right" valign="middle" >
                            <?php echo $this->Currency()->fomatCurrency($row['shipping_fee']) ?>            
                        </td>
                        <td class="col-lim text-right"  valign="middle" >
                            <?php echo $this->Currency()->fomatCurrency($row['total'] + $row['shipping_fee']) ?>          
                        </td>
                        <td class="col-lim text-right"  valign="middle" >
                            <?php echo $row['commission'] ?>%
                        </td>
                        <td class="col-lim text-right"  valign="middle" >
                            <?php echo $this->Currency()->fomatCurrency(($row['total'] + $row['shipping_fee'])*($row['commission']/100)) ?>           
                        </td>
                        <td class="col-lim text-right" valign="middle" >
                            <?php echo $this->Currency()->fomatCurrency((($row['total'] + $row['shipping_fee'])-($row['total'] + $row['shipping_fee'])*($row['commission']/100))) ?>           
                        </td>
                        <td class="col-lim text-right" valign="middle" >
                            <?php echo $this->Currency()->fomatCurrency( max(((($row['total'] + $row['shipping_fee'])-($row['total'] + $row['shipping_fee'])*($row['commission']/100)) - ($row['assign_total'] + $row['assign_shipping'])), 0) ) ?>            
                        </td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_tong_doanh_thu'); ?>
                        </td>
                        <td colspan="3" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($total_revenue) ?>
                            </strong>
                        </td>
                    </tr>

                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_tong_chi_phi_dat_dai_ly'); ?>
                        </td>
                        <td colspan="3" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($total_cost) ?>
                            </strong>
                        </td>
                    </tr>

                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_hoa_hong_tra_dai_ly'); ?>
                        </td>
                        <td colspan="3" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency($total_commission) ?>
                            </strong>
                        </td>
                    </tr>

                    <tr>
                        <td colspan="10" class="text-right" >
                            <?php echo $this->translate('txt_loi_nhuan'); ?>
                        </td>
                        <td colspan="3" class="text-right" >
                            <strong class="coz-color-important" >
                                <?php echo $this->Currency()->fomatCurrency(max(0, ($total_revenue-$total_cost-$total_commission) )) ?>
                            </strong>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            <?php echo $this->translate('txt_chua_co_ho_don'); ?>
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>