
<div id="pop-extention" >
    <div class="inner-my-cart">
        <div class="modal-content">
            <?php if (!empty($products)) {
            ?>
            <div class="modal-header">
                <h4 class="modal-title" >
                    <?php echo $products['title'] ?>
                </h4>
                <div>
                    <?php echo $this->translate('lb_danh_sach_ex') ?>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <a aria-hidden="true"></a>
                </button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table style="width:100%;" id="cart-table">
                        <tbody>
                            <tr>
                                <th><?php echo $this->translate('lb_stt') ?></th>
                                <th><?php echo $this->translate('lb_ten_ex') ?></th>
                                <th><?php echo $this->translate('lb_gia_tien') ?></th>
                                <th></th>
                            </tr>
                            <?php 
                            $extensions = array_merge($products['product_type'][$product_type_id]['extensions'], $products['product_type'][$product_type_id]['extensions_require']);
                            foreach ($extensions as $index => $extension) {
                            ?>
                            <tr class="line-item">
                                <td >
                                    <?php echo ($index+1); ?>
                                </td>
                                <td class="item-title">
                                    <?php echo $extension['ext_name']; ?>
                                </td>
                                <td class="item-price">
                                    <?php echo $this->Currency()->fomatCurrency($extension['price']) ?>
                                </td>
                                <td class="item-delete text-center">
                                    <?php if($extension['is_always'] == 0){ ?>
                                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/cart/removeExtension?products_id=<?php echo $products['id'] ?>&product_type=<?php echo $product_type_id ?>&extension_id=<?php echo $extension['id'] ?>" data-id="<?php echo $products['id'] ?>" data-type="<?php echo $product_type_id ?>" data-iex="<?php echo $extension['id'] ?>" data-neo="ajax" >
                                        <span class="svg-icon-trash svg-icon-inline" >
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </span>
                                    </a>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
            
            <?php }else{ ?>
            <p><?php echo $this->translate('txt_co_loi_xay_ra') ?></p>
            <?php } ?>
        </div>
    </div>
</div>