
<div class="popup-cart-fast clearfix" id="cart" >
    <?php 
    $carts = $this->Cart()->getCart();
    if (!empty($carts)) {
        $index = 0;
        $price_total =0;
    ?>
    <!-- Begin empty cart -->
    <h1 class="p25 title-page">
        <i class="icon-aothun"></i>
        <?php echo $this->translate('txt_gio_hang_cua_ban') ?>
    </h1>
    <form action="<?php echo $this->url('cart', array('action' => 'update-cart')) ?>" method="post" id="cartform" >
        <div id="table-cart">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td></td>
                        <td id="p-name"><?php echo $this->translate('lb_ten_san_pham') ?></td>
                        <td id="p-cosst" class="hidden-xs"><?php echo $this->translate('lb_gia_tien') ?></td>
                        <td id="p-quality"><?php echo $this->translate('lb_so_luong') ?></td>
                        <td id="p-total"><?php echo $this->translate('lb_tong_cong') ?></td>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach ($carts as $id => $product) {
                        foreach ($product['product_type'] as $product_type_id => $p) {
                            $price_total +=$p['price_total'];
                            if($product['id'] == $products_id ){
                                $product_add = $p;
                            }
                    ?>
                    <tr>
                        <td class="cir-cancel">
                            <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/cart/remove?products_id=<?php echo $product['id'] ?>&product_type=<?php echo $p['products_type_id'] ?>" data-neo="ajax" ><i class="fa fa-times-circle-o"></i></a>
                        </td>
                        <td class="product-name">
                            <ul>
                                <li>
                                    <img src="<?php echo $this->Images()->getUrlImage($product['thumb'], 100, 100); ?>" alt="<?php echo $product['title']; ?>" class="img-responsive">
                                </li>
                                <li class="des">
                                    <p>
                                        <?php echo $product['title']; ?>
                                        <?php if(!empty($product['id']) 
                                            && !empty($p['products_type_id']) ){ ?>
                                        <span>(<?php echo $p['type_name'] ?>)</span>
                                        <?php } ?>

                                        <?php if(!empty($product['title_extention_always'])){ ?>
                                        <span class="tllf-plug" >
                                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                            <?php echo $product['title_extention_always']; ?>
                                        </span>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <?php if(!empty($p['extensions']) || !empty($p['extensions_require']) ){ ?>
                                            <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/cart/getExtention?products_id=<?php echo $product['id'] ?>&product_type=<?php echo $p['products_type_id'] ?>" data-neo="popup" data-id="<?php echo $product['id'] ?>" data-type="<?php echo $p['products_type_id'] ?>" >
                                                <?php echo $this->translate('txt_view_extention_product_on_cart'); ?>
                                            </a>
                                        <?php } ?>
                                    </p>
                                </li>
                            </ul>                                       
                        </td>
                        <td class="product-price hidden-xs"><?php echo $this->Currency()->fomatCurrency($p['price_sale']+$product['total_price_extention']) ?></td>
                        <td class="product-quality">
                            <input type="number" size="4" name="quantity[<?php echo $product['id'] ?>][<?php echo $p['products_type_id'] ?>]" value="<?php echo $p['quantity'] ?>" class="qty" min="1"/>
                            <div class="clearfix"></div>
                        </td>
                        <td class="total-product">
                            <p><?php echo $this->Currency()->fomatCurrency($p['price_total']) ?></p>
                        </td>
                    </tr>
                    <?php }
                    } ?>
                </tbody>
            </table>

            <div id="under-table">
                <div class="pull-right">
                    <input type="submit" id="update-cart" class="btn btn-lg btn-info" name="update" value="<?php echo $this->translate('lb_cap_nhat') ?>" />
                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/cart/payment" id="checkout" class="btn" >
                        <span class="btn-icons"><i class="fa fa-shopping-cart"></i> 
                        <span class="text-buy">Mình muốn mua</span><br><small>(Xem hàng tại nhà, không thích có thể trả lại ngay! )</small></span>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div><!-- #under-table -->

            <div id="order-infor" class="pull-right">
                <h4><?php echo $this->translate('lb_tong_cong') ?> <span style="color:#e81c25"> <b><?php echo $this->Currency()->fomatCurrency($price_total) ?></b></span></h4>
                <div class="clearfix"></div>
            </div><!-- #order-infor-->
            <div class="clearfix"></div>
        </div>
        
    </form>
    <!-- End cart -->
    <?php }else{ ?>
    <p><?php echo $this->translate('txt_co_loi_xay_ra') ?></p>
    <?php } ?>
</div> 