<div class="header-cart clearfix" >
    <div class="container" >
        <div class="row" >
            <div class="col-lg-4 col-md-3 col-sm-7 col-xs-7" >
                <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('title_site') ?>" class="logo-navi" >
                    <img src="<?php echo $this->Images()->getUrlImage($this->Websites()->getLogo(), 250); ?>" alt="<?php echo $this->translate('title_site') ?>" class="img-fluid" >
                </a>
            </div>
            <div class="col-lg-8 col-md-9 col-sm-5 col-xs-5" >
                <div class="mini-step pull-xs-right" >
                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/checkout/address" title="<?php echo $this->translate('txt_step_number_01') ?>" class="item-mini-step" >
                        <span class="stus-step" >
                            <i class="fa fa-check-circle" aria-hidden="true"></i>
                        </span>
                        <span class="riin-step" >
                            <span class="iriin-step" >
                                <span class="name-step" >
                                    <?php echo $this->translate('txt_step_number_01') ?>
                                </span>
                                <span class="des-step" >
                                    <?php echo $this->translate('txt_des_step_number_01') ?>
                                </span>
                            </span>
                        </span>
                    </a>

                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/checkout/payment" title="<?php echo $this->translate('txt_step_number_02') ?>" class="item-mini-step  prev-active" >
                        <span class="stus-step" >
                            <i class="fa fa-check-circle" aria-hidden="true"></i>
                        </span>
                        <span class="riin-step" >
                            <span class="iriin-step" >
                                <span class="name-step" >
                                    <?php echo $this->translate('txt_step_number_02') ?>
                                </span>
                                <span class="des-step" >
                                    <?php echo $this->translate('txt_des_step_number_02') ?>
                                </span>
                            </span>
                        </span>
                    </a>

                    <a href="javascript:void(0);" title="<?php echo $this->translate('txt_step_finish') ?>" class="item-mini-step last active" >
                        <span class="stus-step" >
                            <i class="fa fa-check-circle" aria-hidden="true"></i>
                        </span>
                        <span class="riin-step" >
                            <span class="iriin-step" >
                                <span class="name-step" >
                                    <?php echo $this->translate('txt_step_finish') ?>
                                </span>
                            </span>
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
if( !empty($cart) ){ 
    $caculator = $this->Cart()->sumSubTotalPriceFromArray($cart);
    $numberProduct = $this->Cart()->getNumberProductInArray($cart);
?>
<div class="coz-wrap-cart-thanks coz-wrap-payment clearfix" >
    <div class="clearfix" >
        <div class="container" >
            <div class="row">
                <div class="clearfix" >

                    <div class="col-md-8" >
                        <div class="collap-address " >
                            <div class="hcollap-address clearfix" >
                                <?php echo $this->translate('txt_order_confirmation') ?>
                            </div>
                            <div class="bcollap-address clearfix" >
                                <?php echo $this->Html()->mapMacroTranslate('txt_thank_for_shooping_'.strtolower($invoice->payment_code), array('{FULL_NAME}'=> $invoice->full_name) ); ?>
                            </div>
                        </div>

                        <div class="row" style="margin-top: 20px" >
                            <div class="col-sm-6 col-sm-offset-3" >
                                <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" class="coz-btn-flat coz-btn-flat-active coz-btn-flat-block coz-mgb" >
                                    <span><?php echo $this->translate('txt_continue_shopping') ?></span>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4" >
                        <table class="tb-order-detail" >
                            <tr class="tr-h tr-title" >
                                <th colspan="3">
                                    <?php echo $this->translate('txt_order_detail') ?> 
                                    <span class="small" >
                                        <?php echo $numberProduct ?> 
                                        <?php echo $this->translate('txt_item') ?>
                                    </span>
                                </th>
                            </tr>
                            <tr class="tr-line"><td colspan="3" ></td></tr>
                            <tr>
                                <td class="text-xs-center" >
                                    <b>
                                        <?php echo $this->translate('txt_san_pham') ?>
                                    </b>
                                </td>
                                <td>
                                    <b>
                                        <?php echo $this->translate('txt_so_luong') ?>
                                    </b>
                                </td>
                                <td>
                                    <b>
                                        <?php echo $this->translate('txt_gia') ?>
                                    </b>
                                </td>
                            </tr>
                            <tr class="tr-line"><td colspan="3" ></td></tr>
                            <?php
                            foreach ($cart as $id => $product) {
                                if($id == 'coupon'  || $id == 'shipping'  ) continue;
                                foreach ($product['product_type'] as $product_type_id => $p) {
                            ?>
                            <tr>
                                <td>
                                    <a class="pname" data-place="linkProduct"  href="<?php echo $this->Products()->getLink($p) ?>" <?php echo $this->Products()->getTypeView($p) ?> title="<?php echo $this->Products()->getTitle($p) ?>" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                        <span data-place="nameProduct" data-cartid="<?php echo $id.'-'.$product_type_id ?>" data-product_id="<?php echo $id ?>" data-product_type_id="<?php echo $product_type_id ?>" >
                                            <?php echo $this->Products()->getName($p) ?>
                                        </span>
                                    </a>
                                </td>
                                <td>
                                    <span class="pqualyti">
                                        <?php echo $this->Cart()->getProductsQuantity($p) ?>
                                    </span>
                                </td>
                                <td>
                                    <span class="price">
                                        <?php echo $this->Currency()->fomatCurrency($p['price_total']) ?>
                                    </span>
                                </td>
                            </tr>
                            <?php }
                            } ?>
                            <tr class="tr-line"><td colspan="3" ></td></tr>
                            <tr class="tr-title" >
                                <th colspan="2" >
                                    <?php echo $this->translate('txt_subtotal') ?>
                                    <span class="nte" >
                                        <?php echo $this->translate('txt_vat_include');?>
                                    </span>
                                </th>
                                <td>
                                    <span class="price">
                                        <?php echo $this->Currency()->fomatCurrency($caculator['price_total_orig']) ?>
                                    </span>
                                </td>
                            </tr>

                            <tr class="tr-title" >
                                <th colspan="2" >
                                    <?php echo $this->translate('txt_lb_ship_payment') ?> :
                                </th>
                                <td>
                                    <span neo-place="valueFeeTransitions" >
                                        <?php echo $this->Currency()->fomatCurrency($fee) ?>
                                    </span>
                                </td>
                            </tr>

                            <tr class="tr-title" <?php echo ( empty($coupon) ? 'style="display:none"' : '') ?> id="coz-tr-coupon-payment" data-place="hasCoupon" >
                                <th colspan="2" >
                                    <?php echo $this->translate('txt_giam_gia_payment') ?>
                                </th>
                                <td class="text-xs-right">
                                    <span class="price" data-place="valueCoupon" >
                                        <?php echo $this->Coupons()->getPriceWithCurrency() ?>
                                    </span>
                                </td>
                            </tr>

                            <tr class="tr-line"><td colspan="3" ></td></tr>
                            <tr class="tr-title" >
                                <th colspan="2" >
                                    <b>
                                        <?php echo $this->translate('txt_lb_total_tax_payment') ?>
                                    </b>
                                </th>
                                <td>
                                    <b>
                                        <?php echo $this->Currency()->fomatCurrency($caculator['price_total_tax']+$fee) ?>
                                    </b>
                                </td>
                            </tr>
                            <tr class="tr-line"><td colspan="3" ></td></tr>
                            <tr>
                                <td colspan="3" >
                                    <div class="summary-buyer-pay" >
                                        <h2 class="title-summary-buyer-pay" >
                                            <?php echo $this->translate('txt_shipping_address') ?>
                                        </h2>
                                        <div class="mi-summary-buyer-pay" >
                                            <?php if( empty($invoice->has_ship) ){ ?>
                                                <?php echo $this->translate('txt_shipping_at_office') ?><br />
                                            <?php }else{ ?>
                                                <?php echo $this->translate('txt_no_shipping_at_office') ?><br />
                                            <?php } ?>

                                            <?php echo $this->translate('txt_name_buyer') ?>
                                            <?php echo $invoice->full_name ?><br />

                                            <?php echo $this->translate('txt_phone_buyer') ?>
                                            <?php echo $invoice->phone ?><br />

                                            <?php echo $this->translate('txt_email_buyer') ?>
                                            <?php echo $invoice->email ?>
                                        </div>
                                    </div>
                                    <div class="summary-buyer-pay" >
                                        <h2 class="title-summary-buyer-pay" >
                                            <?php echo $this->translate('txt_billing_address') ?>
                                        </h2>
                                        <div class="mi-summary-buyer-pay" >
                                            <?php echo $this->translate('txt_name_shipper') ?>
                                            <?php echo $invoice->ships_full_name ?><br />
                                            
                                            <?php echo $this->translate('txt_address_shipper') ?>
                                            <?php echo $this->Invoice()->getAddress($invoice, 1); ?><br />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
<?php } ?>