<div class="coz-wrap-sucess" >
    <div class="container" >
        <div class="wrap-cart-page clearfix" >
            <div class="row" >
                <div class="col-sm-12" >
                    <h1 class="coz-title-sucess" >
                        <?php echo $this->translate('cam_on_da_mua_sam');?>
                        <b><?php echo $this->invoice_code ?></b>
                    </h1>
                    <div class="coz-content-sucess">
                        <div class="coz-inner-title-sucess" >
                            <p>
                                <?php echo $this->translate('don_hang_se_duoc_xu_ly'); ?>
                            </p>
                            <p>
                                <?php echo $this->translate('luu_y_de_dam_bao_cmnd'); ?>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12" >
                    <h2 class="coz-title-invoice-summary" >
                        <?php echo $this->translate('don_hang_ban_da_mua'); ?>
                    </h2>
                    <div class="clearfix" >
                        <table style="width: 100%;border-collapse: collapse;border: 1px solid #f5f5f5;" border="1" >
                            <tr>
                                <th style="width:10px;padding: 10px;">
                                    #
                                </th>
                                <th style="width:10px;padding: 10px;white-space: nowrap;" >
                                    <?php echo $this->translate('ma_hang');?>
                                </th>
                                <th colspan="6" style="padding: 10px;" >
                                    <?php echo $this->translate('ten_hang'); ?>
                                </th>
                                <th style="width:10px;padding: 10px;text-align: right;" colspan="2" >
                                    <?php echo $this->translate('don_gia');?>
                                </th>
                                <th style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;" >
                                    <?php echo $this->translate('so_luong');?>
                                </th>
                                <th style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;">
                                    <?php echo $this->translate('thanh_tien');?>
                                </th>
                                <th style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;">
                                    <?php echo $this->translate('txt_tong_tien');?>
                                </th>
                            </tr>
                            <?php 
                            $index = 1;
                            $total_products = 0;
                            foreach ($cart as $key => $products) {
                                if($key == 'coupon'  || $key == 'shipping'  ) continue; 
                                foreach($products['product_type'] as $product_type_id => $row){
                                    $total_products += $row['price_total'];
                                    $extentions = array_merge($row['extensions'], $row['extensions_require']);
                            ?>
                            <tr>
                                <td style="padding: 10px;" <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?>  >
                                    <?php echo $index++ ?>
                                </td>

                                <td <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> style="padding: 10px;white-space: nowrap;" >
                                    <?php echo $row['code'] ?>
                                </td>

                                <td colspan="6" style="padding: 10px;" >
                                    <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/<?php echo $row['alias'] ?>-<?php echo $row['id'] ?>" title="<?php echo $row['title']; ?>">
                                        <?php echo $row['title'] ?>
                                    </a>
                                </td>

                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" <?php echo empty($row['extensions_require']) ? 'colspan="2"' : '' ?> >
                                    <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSaleSimple($row)) ?>
                                </td>

                                <?php if( !empty($row['extensions_require']) ){ ?>
                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                                    <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)) ?>
                                </td>
                                <?php } ?>

                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                                    <?php echo $this->Cart()->getProductsQuantity($row) ?>
                                </td>

                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" <?php echo !empty($row['extensions_require']) ? 'rowspan="'.(count($row['extensions_require'])+1).'"' : '' ?> >
                                    <?php echo $this->Currency()->fomatCurrency($this->Products()->getPriceSale($row)*$this->Cart()->getProductsQuantity($row)) ?>
                                </td>

                                <td <?php echo !empty($extentions) ? 'rowspan="'.(count($extentions)+1).'"' : '' ?> style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                    <?php echo $this->Currency()->fomatCurrency($row['price_total']) ?>
                                </td>

                            </tr>

                            <?php
                            $k_ex = 0; 
                            if( !empty($row['extensions_require']) ){
                                foreach ($row['extensions_require'] as $k_ => $ext) {
                                    $quality = $ext['quantity'];
                            ?>
                            <tr>
                                <?php if($k_ex == 0){ ?>
                                <td style="padding: 10px;width: 10px;white-space: nowrap;" rowspan="<?php echo count($extentions); ?>" style="padding: 10px" >
                                    <?php echo $this->translate('txt_sp_dinh_kem');?>
                                </td>
                                <?php } ?>
                                <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                    <?php echo ($k_ex+1); ?>
                                </td>
                                <td style="padding: 10px;" colspan="2" >
                                    <?php echo $ext['ext_name'] ?>
                                </td>
                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                    <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                                </td>
                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;"><?php echo $quality; ?></td>
                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                    <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                                </td>
                            </tr>
                            <?php $k_ex++; 
                                }
                            } ?>

                            <?php 
                            if( !empty($row['extensions']) ){
                                foreach ($row['extensions'] as $k_ => $ext) {
                                    $quality = $ext['quantity'];
                            ?>
                            <tr>
                                <td style="text-align:center;padding: 10px;" >
                                    <?php echo ($k_ex+1); ?>
                                </td>
                                <td style="padding: 10px;" colspan="5" >
                                    <?php echo $ext['ext_name'] ?>
                                </td>
                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                    <?php echo $this->Currency()->fomatCurrency($ext['price']) ?>
                                </td>
                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;" ><?php echo $quality; ?></td>
                                <td style="width: 10px;padding: 10px;text-align: right;white-space: nowrap;color: #e10000;" >
                                    <?php echo $this->Currency()->fomatCurrency($ext['price']*$quality) ?>
                                </td>
                            </tr>
                            <?php $k_ex++; 
                                }
                            } ?>

                            <?php }
                            } ?>

                            <tr>
                                <td colspan="12" style="text-align:right;padding: 10px;" >
                                    <strong><?php echo $this->translate('txt_tong_phu');?></strong>
                                </td>
                                <td style="padding: 10px;text-align: right;color: #e10000;" >
                                    <strong><?php echo $this->Currency()->fomatCurrency($total_orig) ?></strong>
                                </td>
                            </tr>

                            <?php if ( !empty($cart['coupon']) ) { ?>
                            <tr>
                                <td colspan="12" style="text-align:right;padding: 10px;" >
                                    <strong><?php echo $this->translate('txt_gia_tri_giam_gia'); ?></strong>
                                </td>
                                <td style="padding: 10px;text-align: right;color: #e10000;" >
                                    <strong>
                                        <?php echo $this->Currency()->fomatCurrency($cart['coupon']['coupon_price']) ?>
                                    </strong>
                                </td>
                            </tr>
                            <?php } ?>

                            <tr>
                                <td colspan="12" style="text-align:right;padding: 10px;" >
                                    <strong><?php echo $this->translate('txt_phi_van_chuyen'); ?></strong>
                                </td>
                                <td style="padding: 10px;text-align: right;color: #e10000;" >
                                    <strong>
                                        <?php echo $this->Currency()->fomatCurrency($fee, 'txt_mien_phi_ship') ?>
                                    </strong>
                                </td>
                            </tr>

                            <tr>
                                <td colspan="12" style="text-align:right;padding: 10px;" >
                                    <strong><?php echo $this->translate('tong_cong'); ?></strong>
                                </td>
                                <td style="padding: 10px;text-align: right;color: #e10000;" >
                                    <strong>
                                        <?php echo $this->Currency()->fomatCurrency($total + $fee) ?>
                                    </strong>
                                </td>
                            </tr>

                            <tr>
                                <td colspan="12" style="text-align:right;padding: 10px;" >
                                    <strong><?php echo $this->translate('tong_cong_tax'); ?></strong>
                                </td>
                                <td style="padding: 10px;text-align: right;color: #e10000;" >
                                    <strong>
                                        <?php echo $this->Currency()->fomatCurrency($total_tax + $fee) ?>
                                    </strong>
                                </td>
                            </tr>

                        </table>
                    </div>

                    <h3 class="coz-title-subinvoice-summary" >
                        <?php echo $this->translate('txt_thong_tin_nguoi_mua'); ?>
                    </h3>
                    <table style="width: 100%;border-collapse: collapse;border: 1px solid #f5f5f5;" border="1"  >
                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >    
                                <?php echo $this->translate('khach_hang');?>
                            </td>
                            <td style="padding: 10px;" >
                                <strong><?php echo $invoice->full_name ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                <?php echo $this->translate('so_dien_thoai');?>
                            </td>
                            <td style="padding: 10px;" >
                                <strong></strong><?php echo $invoice->phone ?></strong>
                            </td>
                        </tr>

                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                <?php echo $this->translate('txt_email');?>
                            </td>
                            <td style="padding: 10px;" >
                                <strong></strong><?php echo $invoice->email ?></strong>
                            </td>
                        </tr>

                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                <?php echo $this->translate('txt_dia_chi');?> 
                            </td>
                            <td style="padding: 10px;" >
                                <strong>
                                    <?php echo $this->Invoice()->getAddress($invoice); ?>
                                </strong>
                            </td>
                        </tr>

                    </table>

                    <h3 class="coz-title-subinvoice-summary" >
                        <?php echo $this->translate('txt_thong_tin_van_chuyen'); ?>
                    </h3>
                    <table style="width: 100%;border-collapse: collapse;border: 1px solid #f5f5f5;" border="1" >
                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                <?php echo $this->translate('khach_hang');?>
                            </td>
                            <td style="padding: 10px;" >
                                <strong><?php echo $invoice->ships_full_name ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                <?php echo $this->translate('so_dien_thoai');?>
                            </td>
                            <td style="padding: 10px;" >
                                <strong></strong><?php echo $invoice->ships_phone ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                <?php echo $this->translate('txt_email');?>
                            </td>
                            <td style="padding: 10px;" >
                                <strong><?php echo $invoice->ships_email ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                <?php echo $this->translate('txt_dia_chi');?>
                            </td>
                            <td style="padding: 10px;" >
                                <strong>
                                    <?php echo $this->Invoice()->getAddress($invoice, 1); ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td style="padding: 10px;width: 10px;white-space: nowrap;" >
                                <?php echo $this->translate('txt_kieu_van_chuyen');?> 
                            </td>
                            <td style="padding: 10px;" >
                                <strong>
                                    <?php echo ( $transport_type == 0 ? $this->translate('txt_shipping_normal') : $this->translate('txt_shipping_fast')); ?>
                                </strong>
                            </td>
                        </tr>

                    </table>

                </div>
            </div>
        </div>
    </div>
</div>