<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Dịch vụ vận chuyển :: Thêm mới
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/trans') ?>">Dịch vụ vận chuyển</a></li>
        <li class="active">Thêm hình thức mới</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/trans', array('action' => 'add')));
        $form->setAttribute('id', 'form-transportation');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('transportation_id'));
        ?>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <button class="btn btn-primary">Lưu lại</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="form-group">
                        <label for="articles_title">Tiêu đề</label>
                        <?php echo $this->formRow($form->get('transportation_title')); ?>
                    </div>
                    <div class="form-group">
                        <label for="articles_title">Kiểu vận chuyển</label>
                        <?php echo $this->formRow($form->get('transportation_type')); ?>
                    </div>
                    <div class="form-group">
                        <label for="articles_title">Lớp vận chuyển</label>
                        <?php echo $this->formRow($form->get('shipping_class')); ?>
                    </div>
                    <div class="form-group">
                        <label for="articles_title">Mô tả</label>
                        <?php echo $this->formRow($form->get('transportation_description')); ?>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label for="is_published">
                                <?php echo $this->formRow($form->get('is_published')); ?>
                                Hiển thị
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <button class="btn btn-primary">Lưu lại</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>