<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/banners') ?>">
                        <?php echo $this->translate('txt_vi_tri_banner'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_cap_nhat'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_vi_tri_banner'); ?> :: 
                <?php echo $this->translate('txt_cap_nhat'); ?>
            </h1>
        </div>
    </div>
</section>

<section class="content" >
    <div class="clearfix">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('cms/BannerPosition', array('action' => 'edit', 'id' => $id)));
        $form->setAttribute('id', 'form-banner-positions');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('position_id'));
        ?>
        <div class="row" >
            <div class="col-sm-6 col-xs-6" >
                <div class="form-group">
                    <label for="position_name">
                        <?php echo $this->translate('txt_ten_vi_tri'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('position_name')); ?>
                </div>

                <div class="form-group">
                    <label for="position_alias">
                        <?php echo $this->translate('txt_alias'); ?>
                    </label>
                    <?php echo $this->formRow($form->get('position_alias')); ?>
                </div>
            </div>
        </div>

        <div class="form-group" >
            <div class="result-list-img clearfix" >
                <div class="list-img-upload clearfix" >
                    <?php if(!empty($position->image_preview)){ ?>
                    <div class="img-prevew-upload" data-place="prevewImage" >
                        <a href="javascript:void(0)" class="action-upload" data-btn="removePrevewImage" >
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </a>
                        <img src="<?php echo $position->image_preview; ?>" class="img-responsive" >
                    </div>
                    <?php } ?>
                </div>
                <div class="img-prevew-upload btn-upload btn-upload-banner-position" >
                    <a href="javascript:void(0)" class="action-upload" >
                        <i class="fa fa-plus" aria-hidden="true"></i>
                    </a>
                    <a href="javascript:void(0)" class="img-responsive"  >
                        <i class="fa fa-picture-o" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>

        <div class="form-group" >
            <button class="btn btn-primary btn-sm">
                <?php echo $this->translate('txt_cap_nhat_vi_tri'); ?>
            </button>
            <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">
                <?php echo $this->translate('txt_quay_lai'); ?>
            </button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>