<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/user') ?>" >
                        <?php echo $this->translate('txt_thanh_vien'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_doi_mat_khau'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_thanh_vien'); ?> :: 
                <?php echo $this->translate('txt_doi_mat_khau'); ?>
            </h1>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <form action="/cms/user/edit-password" method="post" role="form" id="form-password">
            <input type="hidden" name="users_id" value="<?php echo $id ?>" >
            <div class="col-xs-12">
                <div class="row">   
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label for="password">
                                <?php echo $this->translate('txt_mat_khau_cu'); ?>
                            </label>
                            <input type="password" name="password" id="password" placeholder="<?php echo $this->translate('txt_mat_khau_cu'); ?>" class="form-control input-sm" >
                        </div>
                        <div class="form-group">
                            <label for="newpassword">
                                <?php echo $this->translate('txt_mat_khau_moi'); ?>
                            </label>
                            <input type="password" name="newpassword" id="newpassword" placeholder="<?php echo $this->translate('txt_mat_khau_moi'); ?>" class="form-control input-sm" >
                        </div>
                        <div class="form-group">
                            <label for="re_newpassword">
                                <?php echo $this->translate('txt_xac_nhan_mat_khau_moi'); ?>
                            </label>
                            <input type="password" name="re_newpassword" id="re_newpassword" placeholder="<?php echo $this->translate('txt_xac_nhan_mat_khau_moi'); ?>" class="form-control input-sm" >
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <div class="form-group" >
                    <button class="btn btn-primary btn-sm">
                        <?php echo $this->translate('txt_doi_mat_khau'); ?>
                    </button>
                    <button type="button" class="btn btn-danger btn-sm" onclick="javascript:history.back(-1);">     <?php echo $this->translate('txt_quay_lai'); ?>
                    </button>
                </div>
            </div>
        </form>
    </div>
</section>