<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Thành viên :: Cập nhật
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('cms') ?>"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li><a href="<?php echo $this->url('cms/user') ?>">Danh sách thành viên</a></li>
        <li class="active">Cập nhật thành viên</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <form action="/cms/user/edit-password" method="post" role="form" id="form-password">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="password">Mật khẩu cũ</label>
                            <input type="password" name="password" id="password" placeholder="Mật khẩu cũ" class="form-control" >
                        </div>
                        <div class="form-group">
                            <label for="newpassword">Mật khẩu mới</label>
                            <input type="password" name="newpassword" id="newpassword" placeholder="Mật khẩu mới" class="form-control" >
                        </div>
                        <div class="form-group">
                            <label for="re_newpassword">Xác nhận mật khẩu</label>
                            <input type="password" name="re_newpassword" id="re_newpassword" placeholder="Xác nhận mật khẩu" class="form-control" >
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <button class="btn btn-primary">Lưu lại</button>
                <button type="button" class="btn btn-danger" onclick="javascript:history.back(-1);">Hủy</button>
            </div>
        </form>
    </div>
</section>