<header class="header clearfix" >
    <nav class="navbar navbar-static-top clearfix" role="navigation">
        <div class="pull-left" >
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo $this->url('cms') ?>">
                        <i class="fa fa-dashboard"></i> 
                        <?php echo $this->translate('txt_trang_chu'); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cms/user') ?>" >
                        <?php echo $this->translate('txt_thanh_vien'); ?>
                    </a>
                </li>
                <li class="active">
                    <?php echo $this->translate('txt_hoat_dong'); ?>
                </li>
            </ol>
        </div>
        <div class="navbar-right" >
            <?php echo $this->partial('layout/mini-navbar', array()) ?>
        </div>
    </nav>
</header>

<section class="content-header">
    <div class="row" >
        <div class="col-sm-6 col-xs-12" >
            <h1>
                <?php echo $this->translate('txt_thanh_vien'); ?> :: 
                <?php echo $this->translate('txt_hoat_dong'); ?>
            </h1>
        </div>
        <div class="col-sm-6 col-xs-12 pull-right" >
        </div>
    </div>
</section>

<section class="content clearfix" >
    <form action="<?php echo $this->url('cms/user', array('action' => 'logs', 'id' => $id)) ?>" method="post" class="clearfix" >
        <?php if( !empty($logs) ){ ?>
        <div class="table-responsive" data-table="searchAjax" >
            <table class="table table-data-bind table-no-border" >
                <thead>
                    <tr>
                        <th>
                            <?php echo $this->translate('txt_hoat_dong'); ?>
                        </th>
                        <th class="col-lim" ></th>
                        <th class="text-center col-lim" >
                            <input type="checkbox" class="checkall" />
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($logs as $row) { ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('cms/user', array('action' => 'log')).'?id='.$row['session_id'] ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xem_chi_tiet_hoat_dong'); ?>" >
                                <?php echo $row['step'] ?>
                            </a>
                        </td>
                        <td class="text-right col-lim" >
                            <a href="<?php echo $this->url('cms/user', array('action' => 'deleteLog')).'?id='.$row['session_id'] ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('txt_xoa_hoat_dong'); ?>"  data-confirm="<?php echo $this->translate('txt_ban_muon_xoa'); ?>" >
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            <input type="checkbox" name="cid[]" value="<?php echo $row['session_id'] ?>" />
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?php }else{ ?>
        <p class="empty" >
            <?php echo $this->translate('txt_chua_co_hoat_dong_nao'); ?>
        </p>
        <?php } ?>

        <?php if( !empty($paging) ){ ?>
        <div class="toolbar clearfix" >
            <div class="pull-right" >
                <?php echo $paging ?>
            </div>
        </div>
        <?php } ?>
    </form>
</section>