<!-- End Main Breadcrumb -->
<div class="wrap-breadcrumbs clearfix" >
    <div class="container" >
        <div class="row">
            <div class="col-xs-12" >
                <ul class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList" >
                    <li class="home" itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>" title="<?php echo $this->translate('txt_trang_chu') ?>"  data-pjax="true" data-container="Main" itemprop="item name" >
                            <?php echo $this->translate('txt_trang_chu') ?>
                        </a>
                        <span class="bc-dr" >
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </span>
                        <meta itemprop="position" content="1" />
                    </li>
                    <li itemprop="itemListElement" itemscope
      itemtype="http://schema.org/ListItem" >
                        <span itemprop="item name" >
                            <?php echo $this->translate('txt_dang_nhap'); ?>
                        </span>
                        <meta itemprop="position" content="2" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Main Content -->
<div class="login-content">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3" >
                <div class="form-style form-login">
                    <form accept-charset='UTF-8' accept-charset='UTF-8' action='<?php echo $this->Websites()->getUrlPrefixLang() ?>/login' id='loginform' method='post' data-form="signin" >
                        <h3 class="form-heading">
                            <?php echo $this->translate('txt_dang_nhap') ?>
                        </h3>

                        <p class="form-description">
                            <?php echo $this->translate('txt_thong_tin_dang_nhap') ?>
                        </p>

                        <div class="form-group" >
                            <div class="row">
                                <div class="col-md-2">
                                    <label>Email*</label>
                                </div>
                                <div class="col-md-10">
                                    <input type="email" value="" name="email" class="form-control user_name" name="user_name" placeholder="<?php echo $this->translate('txt_dia_chi_email') ?>" id="user_name" data-input="email" />
                                </div>
                            </div>
                        </div>

                        <div class="form-group" >
                            <div class="row">
                                <div class="col-md-2">
                                    <label>Password*</label>
                                </div>
                                <div class="col-md-10">
                                    <input type="password" value="" class="form-control password" name="password" placeholder="<?php echo $this->translate('txt_mat_khau') ?>" id="password" data-input="password"  />
                                </div>
                            </div>
                        </div>

                        <div class="form-group clearfix" >
                            <div class="pull-xs-left" >
                                <a href="javascript:void(0);" data-neo="silling" data-from="#loginform" data-to="#recover_customer_password" >
                                    <?php echo $this->translate('txt_ban_quyen_mat_khau') ?>
                                </a>
                            </div>
                            <div class="pull-xs-right" >
                                <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/sign-up">
                                    <?php echo $this->translate('txt_tao_tai_khoan') ?>
                                </a>
                            </div>
                        </div>

                        <div class="form-group" >
                            <div class="row">
                                <div class="col-md-12">
                                    <button class="btn btn-style-b" type="submit" >
                                        <?php echo $this->translate('txt_login')?>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-6 col-md-offset-3" >
                <div class="form-style form-login">
                    <form accept-charset='UTF-8' action='<?php echo $this->Websites()->getUrlPrefixLang() ?>/profile/recover' id='recover_customer_password' method='post' data-form="recoverPassword" style="display: none;"  >
                        <h3 class="form-heading">
                            <?php echo $this->translate('txt_quyen_mat_khau')?>
                        </h3>

                        <p class="form-description">
                            <?php echo $this->translate('txt_des_khoi_phuc_mat_khau')?>
                        </p>

                        <p>
                            <?php echo $this->translate('txt_nhap_thong_tin') ?>
                        </p>

                        <div class="form-group" >
                            <label>Email*</label>
                            <input type="email" name="email" class="form-control" placeholder="<?php echo $this->translate('txt_dia_chi_email')?>" data-input="email" />
                        </div>

                        <div class="form-group clearfix" >
                            <div class="pull-xs-left" >
                                <a href="javascript:void(0);" data-neo="silling" data-from="#recover_customer_password" data-to="#loginform" >
                                    <?php echo $this->translate('txt_ban_muon_dang_nhap') ?>
                                </a>
                            </div>
                            <div class="pull-xs-right" >
                                <a href="<?php echo $this->Websites()->getUrlPrefixLang() ?>/sign-up">
                                    <?php echo $this->translate('txt_tao_tai_khoan') ?>
                                </a>
                            </div>
                        </div>

                        <div class="form-group" >
                            <button class="btn btn-style-b" type="submit" >
                                <?php echo $this->translate('txt_gui_thuong_tin')?>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Main Content -->